#!/bin/bash

# This file is documentation for how to get started with DeepSeek v3.

# This file runs Step 1 on CPU.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16): 
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check, pre-training, fine-tuning, and decoding.

set -ex

export MODEL_NAME='qwen3-next-80b-a3b'
export TOKENIZER_PATH='Qwen/Qwen3-Next-80B-A3B-Instruct'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

# Ensure HF_TOKEN is set
if [ -z "${HF_TOKEN}" ]; then
  echo "Error: HF_TOKEN environment variable is not set. Please export your Hugging Face token."
  echo "Example: export HF_TOKEN=hf_..."
  exit 1
fi

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# 1.1 Convert checkpoint to `scanned` format, more suitable for training 
JAX_PLATFORMS=cpu python3 -m MaxText.utils.ckpt_conversion.to_maxtext src/MaxText/configs/base.yml \
    model_name=qwen3-next-80b-a3b \
    base_output_directory=<GCS_PATH_FOR_SCANNED_OUTPUT> \
    hf_access_token=${HF_TOKEN} \
    scan_layers=true \
    use_multimodal=false

# 1.2 Convert checkpoint to `unscanned` format, more suitable for decoding
JAX_PLATFORMS=cpu python3 -m MaxText.utils.ckpt_conversion.to_maxtext src/MaxText/configs/base.yml \
    model_name=qwen3-next-80b-a3b \
    base_output_directory=<GCS_PATH_FOR_UNSCANNED_OUTPUT> \
    hf_access_token=${HF_TOKEN} \
    scan_layers=false \
    use_multimodal=false
