# Copyright 2023–2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# MaxText Codecov Configuration
#
# We use a two-flag scheme ('regular' and 'scheduled') to handle our tiered test suite.
# 'carryforward' is enabled because each flag is only updated by its respective run type.
#
# Scheme:
# - 'regular': Updated ONLY by PRs (subset of tests, excluding 'scheduled_only'). Used for 'patch' coverage.
# - 'scheduled': Updated ONLY by scheduled runs (all tests including 'scheduled_only'). Used for 'project' coverage.
# During PRs, the 'scheduled' flag is carried forward from the last full run on 'main' to keep the score stable.
# During scheduled runs, the 'regular' flag is carried forward from the last PR.

# Exclude non-source code, deprecated and experimental folders from coverage tracking
codecov: 
 token: 35742a22-fb1f-4839-97ff-b54da5588689
# By default file names in the coverage report will have their path in the file system, which in our
# runners would be /__w/maxtext/maxtext/src/MaxText/* but Codecov expects src/MaxText/* so we need to fix the path
fixes:
  # - ".*/maxtext/src/::src/"
  - "/github/workspace/::"
ignore:
  - "src/MaxText/assets"
  - "src/MaxText/configs"
  - "src/MaxText/examples"
  - "src/MaxText/experimental"
  - "src/MaxText/inference"
  - "src/MaxText/inference_mlperf"
  - "src/MaxText/scratch_code"
  - "src/MaxText/distillation" # code moved to src/maxtext/trainers/post_train/distillation


flags:
  # Updated ONLY by PRs (contains subset of tests, excluding scheduled_only).
  regular:
    carryforward: true
  # Updated ONLY by scheduled runs (contains all tests including scheduled_only).
  scheduled:
    carryforward: true

coverage:
  status:
    # Project score remains stable at the 'Full Suite' level.
    # It carries forward the last 'scheduled' results during PRs.
    project:
      default:
        target: auto
        threshold: 5% # fail on 5+ percent degradation
        flags:
          - scheduled

    # Patch score provides feedback on the code changed in a PR.
    patch:
      default:
        target: auto
        threshold: 5% # fail on 5+ percent degradation
        flags:
          - regular

