base_config: "base.yml"

hardware: "gpu"
attention: "dot_product"
base_emb_dim: 8
base_emb_dim: 8
base_num_query_heads: 4
base_num_kv_heads: 4
base_mlp_dim: 32
base_num_decoder_layers: 8
head_dim: 16
per_device_batch_size: 2
max_target_length: 1024
dataset_type: "synthetic"
steps: 10
