base_config: "base.yml"

logical_axis_rules: [
                      ['activation_batch', ['data', 'fsdp', 'fsdp_transpose']],
                      ['activation_batch_no_exp', ['data', 'fsdp', 'fsdp_transpose']],
                      ['activation_embed_and_logits_batch', ['data', 'stage', 'fsdp', 'fsdp_transpose', 'expert']],
                      ['activation_heads', ['tensor', 'tensor_transpose', 'sequence','tensor_sequence', 'expert']],
                      ['activation_kv_heads', ['tensor', 'tensor_transpose', 'sequence','tensor_sequence', 'expert']],
                      ['activation_length', ['context', 'sequence']],
                      ['activation_length_q', ['context']],
                      ['activation_kv_length', ['context']],
                      ['activation_norm_length', ['tensor_sequence', 'sequence']],
                      ['activation_embed', ['tensor', 'tensor_transpose']],
                      ['activation_mlp', []],
                      ['activation_kv', ['tensor', 'tensor_transpose', 'tensor_sequence']],
                      ['activation_prefill_kv_batch', ['data', 'fsdp', 'fsdp_transpose', 'expert']],
                      ['activation_kv_batch', ['data', 'fsdp', 'fsdp_transpose', 'context']],
                      ['activation_kv_head_dim', ['tensor', 'tensor_transpose', 'tensor_sequence']],
                      ['activation_vocab', ['tensor', 'tensor_transpose', 'sequence', 'tensor_sequence']],
                      ['activation_stage', 'stage'],
                      ['activation_exp', ['expert', 'context']],
                      ['mlp', ['fsdp_transpose', 'tensor_sequence', 'autoregressive']],
                      ['vocab', ['tensor', 'tensor_transpose', 'tensor_sequence', 'autoregressive','context']],
                      ['heads', ['tensor', 'tensor_transpose', 'tensor_sequence', 'autoregressive', 'expert']],
                      ['q_heads', ['tensor', 'tensor_transpose', 'tensor_sequence', 'autoregressive', 'expert']],
                      ['kv_heads', ['tensor', 'tensor_transpose', 'tensor_sequence', 'autoregressive', 'expert']],
                      ['embed', ['fsdp', 'fsdp_transpose', 'sequence', 'tensor_transpose']],
                      ['embed_no_exp', ['fsdp', 'fsdp_transpose', 'sequence', 'context', 'tensor_transpose']],
                      ['embed_no_exp', ['fsdp', 'sequence', 'context', 'tensor_transpose']],
                      ['embed_no_exp', ['fsdp', 'fsdp_transpose', 'sequence', 'context']],
                      ['embed_no_exp', ['fsdp', 'sequence', 'context']],
                      [q_lora,[fsdp,sequence]],
                      [kv_lora,[fsdp,sequence]],
                      ['norm', ['tensor', 'tensor_transpose', 'tensor_sequence']],
                      ['layers', 'stage'],
                      ['kv', []],
                      ['kv_head_dim', []],
                      ['cache_batch_prefill', []],
                      ['cache_batch', ['context']],
                      ['cache_heads', ['autoregressive', 'tensor', 'tensor_transpose', 'tensor_sequence', 'expert']],
                      ['cache_kv', []],
                      ['cache_sequence', ['context']],
                      ['cache_scale_sequence', ['context']],
                      [cache_scale_heads,['autoregressive', 'tensor' ,'tensor_sequence', 'expert']],
                      ['exp', ['expert', 'context']],
                      ['paged_kv_heads', []],
                      ['num_pages', ['tensor', 'expert']],
                      ['tokens_per_page', []],
                      ['paged_kv_head_dim_size', []],
                    ]
kv_quant_axis: dkv