adam_b1: 0.9
adam_b2: 0.95
adam_eps: 1.0e-08
adam_eps_root: 0.0
adam_weight_decay: 0.1
aqt_rng_type: jax.uniform
aqt_use_dummy_static_bound: false
aqt_use_fwd_quant: false
async_checkpointing: true
base_emb_dim: 2560
base_mlp_dim: 8192
base_num_decoder_layers: 16
base_num_heads: 8
base_output_directory: gs://maxtext-experiments-multipod/
clip_by_block_rms: 0.0
clip_by_global_norm: 0.1
clip_by_ucb: 0.0
collect_stack_trace: false
data_sharding:
- - data
  - fsdp
  - tensor
data_shuffle_seed: 0
dataset_name: c4/en:3.0.1
dataset_path: gs://max-datasets-rogue-useast/
dataset_type: c4
dcn_data_parallelism: -1
dcn_fsdp_parallelism: 1
dcn_tensor_parallelism: 1
dlhs_int8: true
dlhs_int8_logits: false
dlhs_int8_pv: true
dlhs_int8_qk: false
drhs_int8: false
drhs_int8_logits: false
drhs_int8_pv: false
drhs_int8_qk: false
dropout_rate: 0
dtype: bfloat16
enable_checkpointing: true
enable_data_shuffling: true
enable_dropout: false
enable_flash_attention: false
enable_profiler: true
eos_id: 2
eval_dataset_name: c4/en:3.0.1
eval_per_device_batch_size: 0
eval_split: validation
fill_ratio: 0.8
fwd_int8: true
fwd_int8_logits: false
fwd_int8_pv: true
fwd_int8_qk: false
gcs_metrics: false
global_parameter_scale: 1
global_parameter_scale_mlp_bonus: 0
head_dim: 256
ici_data_parallelism: 1
ici_fsdp_parallelism: -1
ici_tensor_parallelism: 1
init_weights_seed: 0
int8_training: false
learning_rate: 0.0005
learning_rate_schedule_steps: 1600
load_from_other_directory: ''
load_from_other_directory_step: -1
load_parameters_path: ''
log_period: 100
logical_axis_rules:
- - activation_batch
  - - data
    - fsdp
- - activation_length
  - - data
    - fsdp
- - activation_embed
  - tensor
- - activation_mlp
  - tensor
- - activation_heads
  - tensor
- - activation_kv
  - tensor
- - activation_vocab
  - tensor
- - mlp
  - tensor
- - vocab
  - tensor
- - embed
  - fsdp
- - heads
  - tensor
logits_via_embedding: true
max_corpus_chars: 10000000
max_eval_target_length: 512
max_predict_length: 50
max_target_length: 2048
mesh_axes:
- data
- fsdp
- tensor
metrics_file: ''
mlp_activations:
- relu
num_slice: 8
param_scan_axis: 1
per_device_batch_size: 4
prompt: 'I love to '
quantize_logits: true
record_internal_nn_metrics: 0
remat_policy: full
reuse_example_batch: 0
run_name: int8-s35-a1-q_FFF_s1_ns8
sampling_temperature: 0.6
sampling_top_k: 20
save_period: 500
scan_layers: true
stack_trace_interval_seconds: 600
stack_trace_to_cloud: false
steps: -1
use_dqdg: false
use_iota_embed: false
vocab_relative_path: vocabs
vocab_size: 32768
