# SPDX-License-Identifier: Apache-2.0

base_config: "base.yml"

use_sft: True
use_multimodal: True
# For vision, the prompt contains image, we only train on completion tokens
sft_train_on_completion_only: True
packing: False  # packing is not supported yet
freeze_vision_encoder_params: True
learning_rate: 2.e-5

# -------------- HF pipeline --------------
dataset_type: hf
hf_path: 'HuggingFaceM4/ChartQA'
train_split: 'train'
hf_eval_split: 'val'
train_data_columns: ['query', 'label']  # the first column is prompt, second column is completion
eval_data_columns: ['query', 'label']  # the first column is prompt, second column is completion
