# SPDX-License-Identifier: Apache-2.0

base_config: "base.yml"

use_sft: True
# sft_train_on_completion_only=False trains on both prompt and completion tokens; trains only on completion tokens otherwise
sft_train_on_completion_only: True
packing: True
learning_rate: 2.e-5

# -------------- HF pipeline --------------
dataset_type: hf
hf_path: 'HuggingFaceH4/ultrachat_200k'
train_split: 'train_sft'
hf_eval_split: 'test_sft'
train_data_columns: ['messages']
eval_data_columns: ['messages']
