#!/bin/bash

# This file is documentation for how to get started with DeepSeek v4.

# This file runs Step 2 on v5p-128 on a daily basis.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16):
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check and pre-training.

set -ex
set -o pipefail

export MODEL_NAME=${MODEL_NAME:-deepseek4-1600b}

export TOKENIZER_PATH=${TOKENIZER_PATH:-deepseek-ai/DeepSeek-V4-Pro}

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -c "import torch" >/dev/null 2>&1 || python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

# Pin transformers version as requested by the user
python3 -c "import transformers" >/dev/null 2>&1 || python3 -m pip install transformers==4.57.3
# Exact pins keep the run hermetic. tpu-requirements.txt only declares `>=`
# floors for these, so an unbounded install can silently drift.
python3 -c "import pathwaysutils" >/dev/null 2>&1 || python3 -m pip install "pathwaysutils==0.1.11"
python3 -c "import qwix" >/dev/null 2>&1 || python3 -m pip install "qwix==0.1.8"
# train_utils imports orbax.checkpoint.pathways, which only exists in 0.12.x.
python3 -c "import orbax.checkpoint" >/dev/null 2>&1 || python3 -m pip install "orbax-checkpoint==0.12.4"

cat << 'EOPY' > /tmp/patch_orbax.py
import orbax.checkpoint, pathlib
base = pathlib.Path(orbax.checkpoint.__file__).parent
for f in base.glob('**/*.py'):
    try:
        content = f.read_text()
    except Exception:
        continue
    changed = False
    for old, new in [
        ('timeout_secs: int = 600', 'timeout_secs: int = 3600'),
        ('timeout=600', 'timeout=3600'),
        ('timeout_secs=600', 'timeout_secs=3600'),
        ('_DEFAULT_BARRIER_TIMEOUT = 300', '_DEFAULT_BARRIER_TIMEOUT = 3600'),
        ('_DEFAULT_BARRIER_TIMEOUT = 600', '_DEFAULT_BARRIER_TIMEOUT = 3600'),
    ]:
        if old in content:
            content = content.replace(old, new)
            changed = True
    if changed:
        f.write_text(content)
EOPY
python3 /tmp/patch_orbax.py

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH="gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)"
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH="${BASE_OUTPUT_PATH%/}"
echo "using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}"

# Dated public conversion verified by the v5p-128 end-to-end run. Override these
# to test a fresh conversion from 1_test_deepseek.sh, which writes
# ${BASE_OUTPUT_PATH}/{scanned,unscanned}/0/items.
SCANNED_CKPT_PATH="${SCANNED_CKPT_PATH:-gs://maxtext-deepseek/deepseek4-284b/2026-09-17/scanned/0/items}"
UNSCANNED_CKPT_PATH="${UNSCANNED_CKPT_PATH:-gs://maxtext-deepseek/deepseek4-284b/2026-09-17/unscanned/0/items}"

# Test whether the forward pass logits match the golden logits
# default golden_logits_path=/deps/tests/assets/golden_logits/golden_data_{MODEL_NAME}.jsonl, copied from gs://maxtext-test-assets/golden_data_${MODEL_NAME}.jsonl
if [ "${RUN_LOGIT:-true}" = "true" ]; then
  GOLDEN_LOGITS_DISK_LOCATION="/deps/tests/assets/golden_logits/golden_data_${MODEL_NAME}.jsonl"
  if [ ! -f "${GOLDEN_LOGITS_DISK_LOCATION}" ]; then
    GOLDEN_LOGITS_PATH="${GOLDEN_LOGITS_PATH:-gs://maxtext-test-assets/golden_data_${MODEL_NAME}.jsonl}"
    GOLDEN_LOGITS_DISK_LOCATION="/tmp/golden_data.jsonl"
    gcloud storage cp "${GOLDEN_LOGITS_PATH}" "${GOLDEN_LOGITS_DISK_LOCATION}"
  fi

  echo "=== STAGE: logit check ==="
  # Run logit test (using UNSCANNED_CKPT_PATH and scan_layers=False as per user commands)
  # Using indexer_topk=4 for DeepSeek v4 parity checking
  # We set ici_fsdp_parallelism=1 and ici_expert_parallelism=-1 as per the user's workload configuration.
  # shellcheck disable=SC2086
  python3 -m tests.utils.forward_pass_logit_checker \
    "${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml" \
    base_output_directory="${BASE_OUTPUT_PATH}" \
    run_name=ds4-parity \
    load_parameters_path="${UNSCANNED_CKPT_PATH}" \
    scan_layers=False \
    attention=dot_product \
    per_device_batch_size="${LOGIT_PER_DEVICE_BATCH_SIZE:-1}" \
    model_name=deepseek4-1600b \
    override_model_config=True \
    indexer_topk="${INDEXER_TOPK:-4}" \
    max_target_length=512 \
    max_prefill_predict_length=512 \
    activations_in_float32=true \
    matmul_precision=highest \
    float32_logits=true \
    float32_qk_product=true \
        sparse_matmul="${LOGIT_SPARSE_MATMUL:-True}" \
    megablox="${LOGIT_MEGABLOX:-False}" \
    ici_fsdp_parallelism=-1 \
    dcn_fsdp_parallelism="${DCN_FSDP_PARALLELISM:--1}" \
    ici_expert_parallelism="${ICI_EXPERT_PARALLELISM:-8}" \
    ici_tensor_parallelism="${LOGIT_ICI_TP:-1}" \
    ici_context_parallelism="${LOGIT_ICI_CP:-1}" \
    weight_dtype=bfloat16 \
    dtype=bfloat16 \
    ${LOGIT_EXTRA_FLAGS:-} \
    --golden_logits_path="${GOLDEN_LOGITS_DISK_LOCATION}" \
    --max_kl_div="${MAX_KL_DIV:-0.42}" \
    --clip_logits_epsilon=1e-6
fi

if [ "${RUN_PRETRAIN:-true}" = "true" ]; then
  echo "=== STAGE: pre-train ==="
  # An empty load_parameters_path parses to None and fails schema validation,
  # so drop the flag rather than passing a blank value.
  PRETRAIN_LOAD_PARAMS="${PRETRAIN_LOAD_PARAMS-${SCANNED_CKPT_PATH}}"
  PRETRAIN_LOAD_FLAG=""
  if [ -n "${PRETRAIN_LOAD_PARAMS}" ]; then
    PRETRAIN_LOAD_FLAG="load_parameters_path=${PRETRAIN_LOAD_PARAMS}"
  fi
  # Without indexer sparse training, use_indexer=true defaults to indexer warm-up (LM loss zeroed).
  # Stage 3 needs indexer_topk < max_target_length/4; deepseek4-284b pins indexer_topk=512, so
  # 2048 makes topk equal the block count and the indexer selects everything. 4096 keeps it sparse.
  # shellcheck disable=SC2086
  python3 -m maxtext.trainers.pre_train.train \
    "${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml" \
    base_output_directory="${BASE_OUTPUT_PATH}" \
    run_name=pre_training \
    model_name=deepseek4-1600b \
    tokenizer_type=huggingface \
    tokenizer_path="${TOKENIZER_PATH}" \
    dataset_type=synthetic \
    enable_checkpointing="${PRETRAIN_ENABLE_CKPT:-True}" \
    attention="${PRETRAIN_ATTENTION:-dot_product}" \
    use_tokamax_splash="${PRETRAIN_USE_TOKAMAX_SPLASH:-False}" \
    sparse_matmul="${PRETRAIN_SPARSE_MATMUL:-True}" \
    use_tokamax_gmm="${PRETRAIN_USE_TOKAMAX_GMM:-False}" \
    dtype=bfloat16 \
    weight_dtype=bfloat16 \
    per_device_batch_size=1 \
    steps="${STEPS:-5}" \
    max_target_length="${MAX_TARGET_LENGTH:-1024}" \
    override_model_config=True \
    ici_fsdp_parallelism=-1 \
    dcn_fsdp_parallelism="${DCN_FSDP_PARALLELISM:--1}" \
    ici_expert_parallelism="${ICI_EXPERT_PARALLELISM:-8}" \
    dcn_data_parallelism="${PRETRAIN_DCN_DP:--1}" \
    dcn_expert_parallelism="${PRETRAIN_DCN_EP:-1}" \
    opt_type=sgd \
    save_checkpoint_on_completion=false \
    indexer_sparse_training="${PRETRAIN_INDEXER_SPARSE_TRAINING:-True}" \
    indexer_loss_scaling_factor="${PRETRAIN_INDEXER_LOSS_SCALING:-1.0}" \
    indexer_topk="${PRETRAIN_INDEXER_TOPK:-64}" \
    ${PRETRAIN_LOAD_FLAG} \
    ${PRETRAIN_EXTRA_FLAGS:-} 2>&1 | tee /tmp/pretrain_output.log

  total_loss=$(awk -F"loss: " '/completed step:/ {print $2}' /tmp/pretrain_output.log | awk -F"," '{print $1}' | tail -n 1 | tr -d ' ' | tr '[:upper:]' '[:lower:]')
  if [ -z "$total_loss" ] || [ "$total_loss" = "nan" ] || [ "$total_loss" = "inf" ] || [ "$(awk -v v="$total_loss" 'BEGIN { print (v > 0) ? 1 : 0 }')" != "1" ]; then
    echo "ERROR: Total training loss is not strictly positive: ${total_loss}"
    exit 1
  fi

  if [ "$(echo "${PRETRAIN_INDEXER_SPARSE_TRAINING:-True}" | tr '[:upper:]' '[:lower:]')" = "true" ]; then
    lm_loss=$(awk -F"lm_loss: " '/completed step:/ {print $2}' /tmp/pretrain_output.log | awk -F"," '{print $1}' | tail -n 1 | tr -d ' ' | tr '[:upper:]' '[:lower:]')
    if [ -z "$lm_loss" ] || [ "$lm_loss" = "nan" ] || [ "$lm_loss" = "inf" ]; then
      echo "ERROR: Invalid or missing lm_loss: ${lm_loss}"
      exit 1
    fi
    is_positive=$(awk -v v="$lm_loss" 'BEGIN { print (v > 0) ? 1 : 0 }')
    if [ "$is_positive" != "1" ]; then
      echo "ERROR: lm_loss is not strictly positive: ${lm_loss}"
      exit 1
    fi
  fi
fi

if [ "${RUN_DECODE:-true}" = "true" ]; then
  echo "=== STAGE: decode ==="
  # shellcheck disable=SC2086
  python3 -m maxtext.inference.decode \
    "${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml" \
    base_output_directory="${BASE_OUTPUT_PATH}" \
    run_name=decode \
    model_name=deepseek4-1600b \
    tokenizer_type=huggingface \
    tokenizer_path="${TOKENIZER_PATH}" \
    hf_access_token="${HF_TOKEN:-}" \
    load_parameters_path="${UNSCANNED_CKPT_PATH}" \
    scan_layers=False \
    attention=dot_product \
    sparse_matmul="${DECODE_SPARSE_MATMUL:-True}" \
    use_tokamax_gmm="${DECODE_USE_TOKAMAX_GMM:-False}" \
    dtype=bfloat16 \
    weight_dtype=bfloat16 \
    per_device_batch_size=1 \
    max_prefill_predict_length=512 \
    activations_in_float32=true \
    matmul_precision=highest \
    float32_logits=true \
    float32_qk_product=true \
    max_target_length="${DECODE_MAX_TARGET:-512}" \
    override_model_config=True \
    ici_fsdp_parallelism=-1 \
    dcn_fsdp_parallelism="${DCN_FSDP_PARALLELISM:--1}" \
    ici_tensor_parallelism="${DECODE_ICI_TP:-1}" \
    ici_expert_parallelism="${ICI_EXPERT_PARALLELISM:-8}" \
    checkpoint_storage_concurrent_gb=1024 \
    mla_naive_kvcache=false \
    prompt="An attention function can be described as..." \
    autoregressive_decode_assert="${DECODE_ASSERT:- mapping a query and a set of key-value pairs to an output}" \
    ${DECODE_EXTRA_FLAGS:-}
fi

echo "DeepSeek V4 end-to-end tests completed successfully!"
