"""Script to upload Validation Agent JSON results to BigQuery."""

import json
import logging
from google.cloud import bigquery

# set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# # update this to specific project and dataset later
# PROJECT_ID = "tpu-prod-env-multipod"
# DATASET_ID = "maxtext_validation_agent_metrics"
# TABLE_ID = "nightly_runs"

def upload_results_to_bq(json_file_path: str, project_id: str, dataset_id: str, table_id: str):
  """Reads a JSON report and uploads the result to BigQuery."""

  client = bigquery.Client(project=project_id)
  table_ref = f"{project_id}.{dataset_id}.{table_id}"

  # read the local JSON file generated by validation agent
  try:
    with open(json_file_path, "r", encoding="utf-8") as file:
      report_data = json.load(file)
      logger.info("Successfully loaded JSON from %s", json_file_path)
  except FileNotFoundError:
    logger.error("Error: Could not find report file at %s", json_file_path)
    return
  except json.JSONDecodeError:
    logger.error("Error: The file is not a valid JSON.")
    return

  # format the data for big query (must be an array of dictionaries)
  # keys here should match the column names in the big query table
  rows_to_insert = [
      {
          "run_name": report_data.get("run_name", "unknown_run"),
          "model_name": report_data.get("model", "unknown_model"),
          "success": report_data.get("success", False),
          "stderr_output": report_data.get("stderr", ""),
          "checkpoint_gcs_path": report_data.get("checkpoint_used", ""),
          # timestamp to know exactly when the run happened
          "timestamp": "AUTO",  # if big query has a default timestamp or use datetime.now().isoformat()
      }
  ]

  # stream data into the table
  logger.info("Attempting to insert 1 row into %s...", table_ref)
  errors = client.insert_rows_json(table_ref, rows_to_insert)

  if not errors:
    logger.info("Success: New validation result added to BigQuery")
  else:
    logger.error("Failed to insert row. BigQuery Errors: %s", errors)


if __name__ == "__main__":
  import argparse

  parser = argparse.ArgumentParser(description="Upload Agent JSON to BQ")
  parser.add_argument("--report", type=str, required=True, help="Path to JSON report")
  parser.add_argument("--project", type=str, default="tpu-prod-env-multipod", help="GCP Project")
  parser.add_argument("--dataset", type=str, required=True, help="BigQuery Dataset ID")
  parser.add_argument("--table", type=str, default="nightly_runs", help="BigQuery Table ID")
  args = parser.parse_args()

  upload_results_to_bq(args.report, args.project, args.dataset, args.table)
