#!/bin/bash

# This file is documentation for how to get started with DeepSeek v4.

# This file runs Step 1 on CPU.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16): 
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check and pre-training.

set -ex

export MODEL_NAME='deepseek4-284b'
export TOKENIZER_PATH='deepseek-ai/DeepSeek-V4-Flash'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# Step 1: Checkpoint conversion
# You can use the HuggingFace checkpoint at https://huggingface.co/deepseek-ai/DeepSeek-V4-Flash (bf16)
# Non-Googlers please remember to point `BF16_HF_PATH` to GCS buckets that you own
# Copying the HF checkpoint into a local directory `/tmp` -- you are free to use a different directory
BF16_HF_PATH=gs://maxtext-deepseek/deepseek4/hf-bf16
if [ -z "${CKPT_DISK_LOCATION}" ]; then
  export BF16_HF_BUCKET=${BF16_HF_PATH}
  gcloud storage cp -r ${BF16_HF_BUCKET} /tmp
  export BF16_LOCAL_PATH=/tmp/hf-bf16
else
  export BF16_LOCAL_PATH=${CKPT_DISK_LOCATION}
fi

# scanned
# Note: The following command uses XLA_FLAGS and --simulated_cpu_devices_count to simulate
# 16 CPU devices and --lazy_load_tensors=False to eagerly load weights. These flags are not
# mandatory but can drastically speed up the conversion if you have a large CPU machine.
XLA_FLAGS="--xla_force_host_platform_device_count=16" python3 -m maxtext.checkpoint_conversion.to_maxtext src/maxtext/configs/base.yml \
  model_name=${MODEL_NAME} scan_layers=true \
  base_output_directory=${BASE_OUTPUT_PATH}/scanned hf_access_token=$HF_TOKEN \
  hardware=cpu skip_jax_distributed_system=True \
  --hf_model_path=$BF16_LOCAL_PATH \
  --lazy_load_tensors=False \
  --simulated_cpu_devices_count=16 \
  --save_dtype=bfloat16

# unscanned
# Note: Simulating CPU devices and disabling lazy load here also optimizes conversion performance.
XLA_FLAGS="--xla_force_host_platform_device_count=16" python3 -m maxtext.checkpoint_conversion.to_maxtext src/maxtext/configs/base.yml \
  model_name=${MODEL_NAME} scan_layers=false attention=dot_product \
  base_output_directory=${BASE_OUTPUT_PATH}/unscanned hf_access_token=$HF_TOKEN \
  hardware=cpu skip_jax_distributed_system=True \
  --hf_model_path=$BF16_LOCAL_PATH \
  --lazy_load_tensors=False \
  --simulated_cpu_devices_count=16 \
  --save_dtype=bfloat16
