#!/bin/bash

# This file is documentation for how to get started with DeepSeek v4.

# This file runs Step 2 on v5p-128 on a daily basis.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16):
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check and pre-training.

set -ex

export MODEL_NAME='deepseek4-284b'
export TOKENIZER_PATH='deepseek-ai/DeepSeek-V4-Flash'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

# Pin transformers version as requested by the user
python3 -m pip install transformers==4.57.3

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# Step 2:
# We define the checkpoint paths. This way it is easier to use these paths in the `train.py` command
# export SCANNED_CKPT_PATH=${BASE_OUTPUT_PATH}/scanned/0/items
# export UNSCANNED_CKPT_PATH=${BASE_OUTPUT_PATH}/unscanned/0/items
# Use a hard-coded golden checkpoint, rather than checkpoints generated by Step 1 as it is not in daily test.
SCANNED_CKPT_PATH=gs://maxtext-deepseek/deepseek4-284b/scanned/0/items
UNSCANNED_CKPT_PATH=gs://maxtext-deepseek/deepseek4-284b/unscanned/0/items

# Test whether the forward pass logits match the golden logits
# default golden_logits_path=/deps/tests/assets/golden_logits/golden_data_{MODEL_NAME}.jsonl, copied from gs://maxtext-test-assets/golden_data_${MODEL_NAME}.jsonl
GOLDEN_LOGITS_DISK_LOCATION="/deps/tests/assets/golden_logits/golden_data_${MODEL_NAME}.jsonl"
if [ ! -f "${GOLDEN_LOGITS_DISK_LOCATION}" ]; then
  GOLDEN_LOGITS_PATH="gs://snehalv-data/golden-logits-topk4/deepseek-ai/DeepSeek-V4-Flash/golden_data_deepseek4-284b_proper_512.jsonl"
  GOLDEN_LOGITS_DISK_LOCATION=/tmp/golden_data.jsonl
  gcloud storage cp ${GOLDEN_LOGITS_PATH} ${GOLDEN_LOGITS_DISK_LOCATION}
fi

# Run logit test (using UNSCANNED_CKPT_PATH and scan_layers=False as per user commands)
# Using indexer_topk=4 for DeepSeek v4 parity checking
# We set ici_fsdp_parallelism=1 and ici_expert_parallelism=-1 as per the user's workload configuration.
python3 -m tests.utils.forward_pass_logit_checker \
  ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml \
  base_output_directory=${BASE_OUTPUT_PATH} \
  run_name=ds4-parity \
  load_parameters_path=${UNSCANNED_CKPT_PATH} \
  scan_layers=False \
  attention=dot_product \
  per_device_batch_size=1 \
  model_name=${MODEL_NAME} \
  max_target_length=1024 \
  ici_fsdp_parallelism=1 \
  ici_expert_parallelism=-1 \
  weight_dtype=bfloat16 \
  dtype=bfloat16 \
  activations_in_float32=false \
  matmul_precision=highest \
  float32_logits=false \
  float32_qk_product=false \
  override_model_config=True \
  indexer_topk=4 \
  enable_nnx=false \
  pure_nnx=false \
  pure_nnx_decoder=false \
  --golden_logits_path=${GOLDEN_LOGITS_DISK_LOCATION} \
  --max_kl_div=0.3

# Run pre-training with synthetic dataset
python3 -m maxtext.trainers.pre_train.train \
  ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml \
  base_output_directory=${BASE_OUTPUT_PATH} \
  run_name=pre_training \
  model_name=${MODEL_NAME} \
  tokenizer_type=huggingface \
  tokenizer_path=${TOKENIZER_PATH} \
  dataset_type=synthetic \
  enable_checkpointing=false \
  attention=dot_product \
  dtype=bfloat16 \
  weight_dtype=bfloat16 \
  per_device_batch_size=1 \
  steps=20 \
  max_target_length=2048 \
  ici_fsdp_parallelism=-1 \
  opt_type=sgd \
  load_parameters_path=${SCANNED_CKPT_PATH}
