costs { name: "all-gather-start" cost_us: 10944.695 }
costs { name: "all-gather-start.1" cost_us: 11001.527 }
costs { name: "all-gather-start.2" cost_us: 11165.975 }
costs { name: "all-gather-start.4" cost_us: 14607.783 }
costs { name: "all-gather-start.5" cost_us: 12799.278 }
costs { name: "all-gather-start.6" cost_us: 11430.099 }
costs { name: "all-gather-start.7" cost_us: 11198.356 }
costs { name: "all-reduce-start" cost_us: 1822.937 }
costs { name: "all-reduce-start.13" cost_us: 2281.495 }
costs { name: "all-reduce-start.6" cost_us: 1260.763 }
costs { name: "all-reduce-start.9" cost_us: 2393.687 }
costs { name: "input_slice_fusion" cost_us: 1.728 }
costs { name: "input_transpose_fusion.21" cost_us: 9.313 }
costs { name: "input_transpose_fusion.22" cost_us: 14.016 }
costs { name: "loop_broadcast_fusion" cost_us: 1.568 }
costs { name: "loop_broadcast_fusion.10" cost_us: 7543.459 }
costs { name: "loop_broadcast_fusion.2" cost_us: 368.575 }
costs { name: "loop_broadcast_fusion.3" cost_us: 193.823 }
costs { name: "loop_broadcast_fusion.4" cost_us: 2.912 }
costs { name: "loop_broadcast_fusion.5" cost_us: 14.72 }
costs { name: "loop_broadcast_fusion.6" cost_us: 53.888 }
costs { name: "loop_broadcast_fusion.7" cost_us: 53.312 }
costs { name: "loop_broadcast_fusion.8" cost_us: 1682.554 }
costs { name: "loop_broadcast_fusion.9" cost_us: 7543.331 }
costs { name: "loop_compare_fusion.1" cost_us: 1.472 }
costs { name: "reduce-scatter-start" cost_us: 15619.044 }
costs { name: "reduce-scatter-start.1" cost_us: 17066.016 }
costs { name: "reduce-scatter-start.2" cost_us: 16165.729 }
costs { name: "reduce-scatter-start.3" cost_us: 8415.457 }
costs { name: "wrapped_concatenate" cost_us: 10.56 }
costs { name: "wrapped_concatenate.1" cost_us: 2.112 }
costs { name: "wrapped_concatenate.10" cost_us: 10.528 }
costs { name: "wrapped_concatenate.11" cost_us: 1.888 }
costs { name: "wrapped_concatenate.12" cost_us: 1.855 }
costs { name: "wrapped_concatenate.13" cost_us: 1.632 }
costs { name: "wrapped_concatenate.14" cost_us: 2.24 }
costs { name: "wrapped_concatenate.2" cost_us: 1.728 }
costs { name: "wrapped_concatenate.3" cost_us: 10.4 }
costs { name: "wrapped_concatenate.4" cost_us: 1.44 }
costs { name: "wrapped_concatenate.5" cost_us: 1.952 }
costs { name: "wrapped_concatenate.6" cost_us: 1.504 }
costs { name: "wrapped_concatenate.7" cost_us: 2.24 }
costs { name: "wrapped_concatenate.8" cost_us: 1.6 }
costs { name: "wrapped_concatenate.9" cost_us: 14.945 }
costs { name: "wrapped_convert.10" cost_us: 1.76 }
costs { name: "wrapped_convert.11" cost_us: 1.824 }
costs { name: "wrapped_convert.12" cost_us: 1.536 }
costs { name: "wrapped_convert.13" cost_us: 1.6 }
costs { name: "wrapped_convert.14" cost_us: 1.568 }
costs { name: "wrapped_convert.15" cost_us: 1.6 }
costs { name: "wrapped_convert.16" cost_us: 1.536 }
costs { name: "wrapped_convert.17" cost_us: 1.536 }
costs { name: "wrapped_convert.18" cost_us: 1.536 }
costs { name: "wrapped_convert.19" cost_us: 1.664 }
costs { name: "wrapped_convert.2" cost_us: 1.696 }
costs { name: "wrapped_convert.20" cost_us: 1.535 }
costs { name: "wrapped_convert.21" cost_us: 1.375 }
costs { name: "wrapped_convert.22" cost_us: 1.376 }
costs { name: "wrapped_convert.23" cost_us: 1.568 }
costs { name: "wrapped_convert.24" cost_us: 1.727 }
costs { name: "wrapped_convert.25" cost_us: 1.727 }
costs { name: "wrapped_convert.26" cost_us: 1.375 }
costs { name: "wrapped_convert.27" cost_us: 1.696 }
costs { name: "wrapped_convert.28" cost_us: 1.376 }
costs { name: "wrapped_convert.29" cost_us: 1.6 }
costs { name: "wrapped_convert.3" cost_us: 1.728 }
costs { name: "wrapped_convert.30" cost_us: 1.376 }
costs { name: "wrapped_convert.31" cost_us: 1.247 }
costs { name: "wrapped_convert.32" cost_us: 1.376 }
costs { name: "wrapped_convert.33" cost_us: 1.376 }
costs { name: "wrapped_convert.34" cost_us: 1.247 }
costs { name: "wrapped_convert.35" cost_us: 1.215 }
costs { name: "wrapped_convert.36" cost_us: 1.215 }
costs { name: "wrapped_convert.37" cost_us: 1.216 }
costs { name: "wrapped_convert.38" cost_us: 1.728 }
costs { name: "wrapped_convert.39" cost_us: 1.568 }
costs { name: "wrapped_convert.4" cost_us: 1.728 }
costs { name: "wrapped_convert.40" cost_us: 1.664 }
costs { name: "wrapped_convert.41" cost_us: 1.408 }
costs { name: "wrapped_convert.42" cost_us: 1.6 }
costs { name: "wrapped_convert.43" cost_us: 1.791 }
costs { name: "wrapped_convert.44" cost_us: 1.44 }
costs { name: "wrapped_convert.45" cost_us: 1.792 }
costs { name: "wrapped_convert.46" cost_us: 1.696 }
costs { name: "wrapped_convert.47" cost_us: 1.792 }
costs { name: "wrapped_convert.48" cost_us: 1.44 }
costs { name: "wrapped_convert.49" cost_us: 1.248 }
costs { name: "wrapped_convert.5" cost_us: 1.504 }
costs { name: "wrapped_convert.50" cost_us: 1.247 }
costs { name: "wrapped_convert.51" cost_us: 1.248 }
costs { name: "wrapped_convert.52" cost_us: 1.216 }
costs { name: "wrapped_convert.53" cost_us: 1.248 }
costs { name: "wrapped_convert.54" cost_us: 1.247 }
costs { name: "wrapped_convert.55" cost_us: 1.28 }
costs { name: "wrapped_convert.6" cost_us: 1.76 }
costs { name: "wrapped_convert.7" cost_us: 1.856 }
costs { name: "wrapped_convert.8" cost_us: 1.472 }
costs { name: "wrapped_convert.9" cost_us: 1.856 }
costs { name: "wrapped_slice" cost_us: 3.68 }
costs { name: "wrapped_slice.1" cost_us: 2.848 }
costs { name: "wrapped_slice.10" cost_us: 1.376 }
costs { name: "wrapped_slice.100" cost_us: 1.28 }
costs { name: "wrapped_slice.101" cost_us: 1.28 }
costs { name: "wrapped_slice.102" cost_us: 1.248 }
costs { name: "wrapped_slice.103" cost_us: 1.28 }
costs { name: "wrapped_slice.104" cost_us: 1.28 }
costs { name: "wrapped_slice.105" cost_us: 1.28 }
costs { name: "wrapped_slice.106" cost_us: 1.248 }
costs { name: "wrapped_slice.107" cost_us: 1.28 }
costs { name: "wrapped_slice.108" cost_us: 1.28 }
costs { name: "wrapped_slice.109" cost_us: 1.28 }
costs { name: "wrapped_slice.11" cost_us: 1.376 }
costs { name: "wrapped_slice.110" cost_us: 1.248 }
costs { name: "wrapped_slice.12" cost_us: 1.376 }
costs { name: "wrapped_slice.13" cost_us: 1.376 }
costs { name: "wrapped_slice.14" cost_us: 1.376 }
costs { name: "wrapped_slice.15" cost_us: 1.344 }
costs { name: "wrapped_slice.16" cost_us: 1.344 }
costs { name: "wrapped_slice.17" cost_us: 1.376 }
costs { name: "wrapped_slice.18" cost_us: 1.344 }
costs { name: "wrapped_slice.19" cost_us: 1.344 }
costs { name: "wrapped_slice.2" cost_us: 1.536 }
costs { name: "wrapped_slice.20" cost_us: 3.616 }
costs { name: "wrapped_slice.21" cost_us: 3.487 }
costs { name: "wrapped_slice.22" cost_us: 3.488 }
costs { name: "wrapped_slice.25" cost_us: 1.727 }
costs { name: "wrapped_slice.26" cost_us: 2.08 }
costs { name: "wrapped_slice.27" cost_us: 2.08 }
costs { name: "wrapped_slice.28" cost_us: 1.759 }
costs { name: "wrapped_slice.29" cost_us: 1.247 }
costs { name: "wrapped_slice.3" cost_us: 1.376 }
costs { name: "wrapped_slice.30" cost_us: 1.247 }
costs { name: "wrapped_slice.31" cost_us: 1.247 }
costs { name: "wrapped_slice.32" cost_us: 1.247 }
costs { name: "wrapped_slice.33" cost_us: 1.248 }
costs { name: "wrapped_slice.34" cost_us: 1.248 }
costs { name: "wrapped_slice.35" cost_us: 1.247 }
costs { name: "wrapped_slice.36" cost_us: 1.248 }
costs { name: "wrapped_slice.37" cost_us: 1.247 }
costs { name: "wrapped_slice.38" cost_us: 1.216 }
costs { name: "wrapped_slice.39" cost_us: 1.247 }
costs { name: "wrapped_slice.4" cost_us: 1.696 }
costs { name: "wrapped_slice.40" cost_us: 1.407 }
costs { name: "wrapped_slice.41" cost_us: 1.216 }
costs { name: "wrapped_slice.42" cost_us: 1.407 }
costs { name: "wrapped_slice.43" cost_us: 1.247 }
costs { name: "wrapped_slice.44" cost_us: 1.407 }
costs { name: "wrapped_slice.45" cost_us: 1.248 }
costs { name: "wrapped_slice.46" cost_us: 1.407 }
costs { name: "wrapped_slice.47" cost_us: 1.473 }
costs { name: "wrapped_slice.48" cost_us: 1.248 }
costs { name: "wrapped_slice.49" cost_us: 1.504 }
costs { name: "wrapped_slice.5" cost_us: 1.344 }
costs { name: "wrapped_slice.50" cost_us: 1.28 }
costs { name: "wrapped_slice.51" cost_us: 1.472 }
costs { name: "wrapped_slice.52" cost_us: 1.44 }
costs { name: "wrapped_slice.53" cost_us: 1.248 }
costs { name: "wrapped_slice.54" cost_us: 1.44 }
costs { name: "wrapped_slice.55" cost_us: 1.312 }
costs { name: "wrapped_slice.56" cost_us: 1.248 }
costs { name: "wrapped_slice.57" cost_us: 1.344 }
costs { name: "wrapped_slice.58" cost_us: 1.312 }
costs { name: "wrapped_slice.59" cost_us: 1.28 }
costs { name: "wrapped_slice.6" cost_us: 1.504 }
costs { name: "wrapped_slice.60" cost_us: 1.312 }
costs { name: "wrapped_slice.61" cost_us: 1.248 }
costs { name: "wrapped_slice.62" cost_us: 1.312 }
costs { name: "wrapped_slice.63" cost_us: 1.248 }
costs { name: "wrapped_slice.64" cost_us: 1.312 }
costs { name: "wrapped_slice.65" cost_us: 4.096 }
costs { name: "wrapped_slice.66" cost_us: 4.096 }
costs { name: "wrapped_slice.67" cost_us: 1.984 }
costs { name: "wrapped_slice.68" cost_us: 1.92 }
costs { name: "wrapped_slice.69" cost_us: 2.304 }
costs { name: "wrapped_slice.7" cost_us: 1.503 }
costs { name: "wrapped_slice.70" cost_us: 2.304 }
costs { name: "wrapped_slice.71" cost_us: 2.337 }
costs { name: "wrapped_slice.72" cost_us: 1.984 }
costs { name: "wrapped_slice.73" cost_us: 2.016 }
costs { name: "wrapped_slice.74" cost_us: 3.84 }
costs { name: "wrapped_slice.75" cost_us: 3.84 }
costs { name: "wrapped_slice.76" cost_us: 3.872 }
costs { name: "wrapped_slice.77" cost_us: 3.648 }
costs { name: "wrapped_slice.78" cost_us: 3.712 }
costs { name: "wrapped_slice.79" cost_us: 1.247 }
costs { name: "wrapped_slice.8" cost_us: 1.376 }
costs { name: "wrapped_slice.80" cost_us: 1.248 }
costs { name: "wrapped_slice.81" cost_us: 1.312 }
costs { name: "wrapped_slice.82" cost_us: 1.28 }
costs { name: "wrapped_slice.83" cost_us: 1.28 }
costs { name: "wrapped_slice.84" cost_us: 1.28 }
costs { name: "wrapped_slice.89" cost_us: 1.28 }
costs { name: "wrapped_slice.9" cost_us: 1.536 }
costs { name: "wrapped_slice.90" cost_us: 1.28 }
costs { name: "wrapped_slice.92" cost_us: 1.248 }
costs { name: "wrapped_slice.93" cost_us: 1.44 }
costs { name: "wrapped_slice.94" cost_us: 1.408 }
costs { name: "wrapped_slice.95" cost_us: 1.248 }
costs { name: "wrapped_slice.96" cost_us: 1.312 }
costs { name: "wrapped_slice.97" cost_us: 1.248 }
costs { name: "wrapped_slice.98" cost_us: 1.28 }
costs { name: "wrapped_slice.99" cost_us: 1.249 }
costs { name: "wrapped_transpose.23" cost_us: 6.047 }
costs { name: "wrapped_transpose.24" cost_us: 6.08 }
costs { name: "wrapped_transpose.25" cost_us: 6.399 }
costs { name: "wrapped_select" cost_us: 1.504 }
costs { name: "loop_add_fusion" cost_us: 1.377 }
costs { name: "wrapped_add" cost_us: 1.44 }
costs { name: "loop_minimum_fusion" cost_us: 1.6 }
costs { name: "wrapped_cosine" cost_us: 1.408 }
costs { name: "input_reduce_fusion" cost_us: 1.696 }
costs { name: "loop_xor_fusion" cost_us: 1.888 }
costs { name: "wrapped_multiply" cost_us: 1.343 }
costs { name: "loop_subtract_fusion" cost_us: 1.344 }
costs { name: "input_add_reduce_fusion.10" cost_us: 759.325 }
costs { name: "input_add_reduce_fusion.11" cost_us: 759.421 }
costs { name: "input_add_reduce_fusion.12" cost_us: 278.143 }
costs { name: "input_add_reduce_fusion.13" cost_us: 1171.931 }
costs { name: "input_add_reduce_fusion.14" cost_us: 1168.924 }
costs { name: "input_add_reduce_fusion.19" cost_us: 329.566 }
costs { name: "input_add_reduce_fusion.2" cost_us: 40.224 }
costs { name: "input_add_reduce_fusion.20" cost_us: 46.72 }
costs { name: "input_add_reduce_fusion.21" cost_us: 45.183 }
costs { name: "input_add_reduce_fusion.22" cost_us: 6.272 }
costs { name: "input_add_reduce_fusion.3" cost_us: 31.296 }
costs { name: "input_add_reduce_fusion.4" cost_us: 221.088 }
costs { name: "input_add_reduce_fusion.5" cost_us: 221.439 }
costs { name: "input_add_reduce_fusion.6" cost_us: 31.456 }
costs { name: "input_add_reduce_fusion.7" cost_us: 10.208 }
costs { name: "input_add_reduce_fusion.8" cost_us: 10.048 }
costs { name: "input_add_reduce_fusion.9" cost_us: 1375.131 }
costs { name: "input_compare_reduce_fusion" cost_us: 2.848 }
costs { name: "input_convert_reduce_fusion.7" cost_us: 2114.04 }
costs { name: "input_convert_reduce_fusion.8" cost_us: 477.214 }
costs { name: "input_dynamic_slice_reduce_fusion" cost_us: 176.095 }
costs { name: "input_dynamic_slice_reduce_fusion.1" cost_us: 177.247 }
costs { name: "input_dynamic_slice_reduce_fusion.2" cost_us: 174.495 }
costs { name: "input_reduce_fusion" cost_us: 2.784 }
costs { name: "input_reduce_fusion.1" cost_us: 2.304 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 2.4 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 1.984 }
costs { name: "input_reduce_fusion.10" cost_us: 2.815 }
costs { name: "input_reduce_fusion.10.double_buffer_clone" cost_us: 2.688 }
costs { name: "input_reduce_fusion.10.peeled_double_buffer" cost_us: 2.816 }
costs { name: "input_reduce_fusion.11" cost_us: 2.207 }
costs { name: "input_reduce_fusion.11.double_buffer_clone" cost_us: 2.208 }
costs { name: "input_reduce_fusion.11.peeled_double_buffer" cost_us: 1.952 }
costs { name: "input_reduce_fusion.117" cost_us: 3.167 }
costs { name: "input_reduce_fusion.118" cost_us: 3.808 }
costs { name: "input_reduce_fusion.119" cost_us: 2.048 }
costs { name: "input_reduce_fusion.12" cost_us: 2.816 }
costs { name: "input_reduce_fusion.12.double_buffer_clone" cost_us: 2.848 }
costs { name: "input_reduce_fusion.12.peeled_double_buffer" cost_us: 2.944 }
costs { name: "input_reduce_fusion.120" cost_us: 2.112 }
costs { name: "input_reduce_fusion.121" cost_us: 1.984 }
costs { name: "input_reduce_fusion.122" cost_us: 1.984 }
costs { name: "input_reduce_fusion.123" cost_us: 2.016 }
costs { name: "input_reduce_fusion.124" cost_us: 1.984 }
costs { name: "input_reduce_fusion.125" cost_us: 1.984 }
costs { name: "input_reduce_fusion.126" cost_us: 1.952 }
costs { name: "input_reduce_fusion.127" cost_us: 1.984 }
costs { name: "input_reduce_fusion.128" cost_us: 2.112 }
costs { name: "input_reduce_fusion.129" cost_us: 1.984 }
costs { name: "input_reduce_fusion.13" cost_us: 1.984 }
costs { name: "input_reduce_fusion.13.double_buffer_clone" cost_us: 1.92 }
costs { name: "input_reduce_fusion.13.peeled_double_buffer" cost_us: 1.76 }
costs { name: "input_reduce_fusion.130" cost_us: 1.984 }
costs { name: "input_reduce_fusion.131" cost_us: 2.08 }
costs { name: "input_reduce_fusion.132" cost_us: 1.984 }
costs { name: "input_reduce_fusion.133" cost_us: 1.984 }
costs { name: "input_reduce_fusion.134" cost_us: 1.984 }
costs { name: "input_reduce_fusion.135" cost_us: 2.08 }
costs { name: "input_reduce_fusion.136" cost_us: 2.111 }
costs { name: "input_reduce_fusion.137" cost_us: 2.016 }
costs { name: "input_reduce_fusion.138" cost_us: 2.016 }
costs { name: "input_reduce_fusion.139" cost_us: 2.048 }
costs { name: "input_reduce_fusion.140" cost_us: 3.136 }
costs { name: "input_reduce_fusion.141" cost_us: 3.104 }
costs { name: "input_reduce_fusion.142" cost_us: 10.08 }
costs { name: "input_reduce_fusion.143" cost_us: 64.32 }
costs { name: "input_reduce_fusion.144" cost_us: 60.927 }
costs { name: "input_reduce_fusion.145" cost_us: 9.92 }
costs { name: "input_reduce_fusion.146" cost_us: 2.24 }
costs { name: "input_reduce_fusion.147" cost_us: 2.272 }
costs { name: "input_reduce_fusion.148" cost_us: 192.992 }
costs { name: "input_reduce_fusion.149" cost_us: 189.887 }
costs { name: "input_reduce_fusion.150" cost_us: 195.391 }
costs { name: "input_reduce_fusion.151" cost_us: 1.92 }
costs { name: "input_reduce_fusion.152" cost_us: 2.208 }
costs { name: "input_reduce_fusion.153" cost_us: 2.336 }
costs { name: "input_reduce_fusion.154" cost_us: 2.24 }
costs { name: "input_reduce_fusion.155" cost_us: 1.984 }
costs { name: "input_reduce_fusion.156" cost_us: 2.08 }
costs { name: "input_reduce_fusion.157" cost_us: 2.208 }
costs { name: "input_reduce_fusion.158" cost_us: 2.144 }
costs { name: "input_reduce_fusion.159" cost_us: 2.272 }
costs { name: "input_reduce_fusion.160" cost_us: 513.342 }
costs { name: "input_reduce_fusion.161" cost_us: 2.017 }
costs { name: "input_reduce_fusion.162" cost_us: 2.208 }
costs { name: "input_reduce_fusion.163" cost_us: 1.76 }
costs { name: "input_reduce_fusion.164" cost_us: 1.792 }
costs { name: "input_reduce_fusion.165" cost_us: 374.463 }
costs { name: "input_reduce_fusion.169" cost_us: 169.407 }
costs { name: "input_reduce_fusion.170" cost_us: 259.999 }
costs { name: "input_reduce_fusion.171" cost_us: 169.727 }
costs { name: "input_reduce_fusion.172" cost_us: 89.12 }
costs { name: "input_reduce_fusion.173" cost_us: 259.327 }
costs { name: "input_reduce_fusion.174" cost_us: 168.255 }
costs { name: "input_reduce_fusion.175" cost_us: 87.68 }
costs { name: "input_reduce_fusion.195" cost_us: 1.728 }
costs { name: "input_reduce_fusion.196" cost_us: 1.729 }
costs { name: "input_reduce_fusion.197" cost_us: 5.888 }
costs { name: "input_reduce_fusion.2" cost_us: 2.847 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 2.848 }
costs { name: "input_reduce_fusion.2.peeled_double_buffer" cost_us: 2.849 }
costs { name: "input_reduce_fusion.202" cost_us: 1.664 }
costs { name: "input_reduce_fusion.203" cost_us: 1.632 }
costs { name: "input_reduce_fusion.204" cost_us: 1.696 }
costs { name: "input_reduce_fusion.205" cost_us: 2.272 }
costs { name: "input_reduce_fusion.206" cost_us: 1.92 }
costs { name: "input_reduce_fusion.207" cost_us: 1.92 }
costs { name: "input_reduce_fusion.208" cost_us: 1.984 }
costs { name: "input_reduce_fusion.209" cost_us: 1.729 }
costs { name: "input_reduce_fusion.210" cost_us: 1.727 }
costs { name: "input_reduce_fusion.211" cost_us: 5.024 }
costs { name: "input_reduce_fusion.212" cost_us: 1.696 }
costs { name: "input_reduce_fusion.213" cost_us: 1.92 }
costs { name: "input_reduce_fusion.214" cost_us: 2.176 }
costs { name: "input_reduce_fusion.215" cost_us: 2.24 }
costs { name: "input_reduce_fusion.216" cost_us: 1.92 }
costs { name: "input_reduce_fusion.217" cost_us: 1.6 }
costs { name: "input_reduce_fusion.218" cost_us: 1.6 }
costs { name: "input_reduce_fusion.219" cost_us: 1.632 }
costs { name: "input_reduce_fusion.220" cost_us: 1.632 }
costs { name: "input_reduce_fusion.221" cost_us: 1.536 }
costs { name: "input_reduce_fusion.222" cost_us: 1.568 }
costs { name: "input_reduce_fusion.223" cost_us: 1.728 }
costs { name: "input_reduce_fusion.224" cost_us: 2.272 }
costs { name: "input_reduce_fusion.225" cost_us: 2.368 }
costs { name: "input_reduce_fusion.226" cost_us: 1.76 }
costs { name: "input_reduce_fusion.227" cost_us: 1.696 }
costs { name: "input_reduce_fusion.228" cost_us: 1.632 }
costs { name: "input_reduce_fusion.229" cost_us: 1.632 }
costs { name: "input_reduce_fusion.230" cost_us: 1.504 }
costs { name: "input_reduce_fusion.231" cost_us: 1.984 }
costs { name: "input_reduce_fusion.232" cost_us: 1.664 }
costs { name: "input_reduce_fusion.233" cost_us: 1.696 }
costs { name: "input_reduce_fusion.234" cost_us: 1.696 }
costs { name: "input_reduce_fusion.235" cost_us: 1.503 }
costs { name: "input_reduce_fusion.3" cost_us: 2.144 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 2.208 }
costs { name: "input_reduce_fusion.3.peeled_double_buffer" cost_us: 2.176 }
costs { name: "input_reduce_fusion.37" cost_us: 258.88 }
costs { name: "input_reduce_fusion.38" cost_us: 167.84 }
costs { name: "input_reduce_fusion.39" cost_us: 87.135 }
costs { name: "input_reduce_fusion.4" cost_us: 2.848 }
costs { name: "input_reduce_fusion.4.double_buffer_clone" cost_us: 2.848 }
costs { name: "input_reduce_fusion.4.peeled_double_buffer" cost_us: 3.136 }
costs { name: "input_reduce_fusion.5" cost_us: 1.92 }
costs { name: "input_reduce_fusion.5.double_buffer_clone" cost_us: 2.047 }
costs { name: "input_reduce_fusion.5.peeled_double_buffer" cost_us: 2.24 }
costs { name: "input_reduce_fusion.6" cost_us: 2.848 }
costs { name: "input_reduce_fusion.6.double_buffer_clone" cost_us: 2.944 }
costs { name: "input_reduce_fusion.6.peeled_double_buffer" cost_us: 3.04 }
costs { name: "input_reduce_fusion.7" cost_us: 2.272 }
costs { name: "input_reduce_fusion.7.double_buffer_clone" cost_us: 2.368 }
costs { name: "input_reduce_fusion.7.peeled_double_buffer" cost_us: 2.368 }
costs { name: "input_reduce_fusion.75" cost_us: 2.433 }
costs { name: "input_reduce_fusion.76" cost_us: 2.464 }
costs { name: "input_reduce_fusion.77" cost_us: 2.529 }
costs { name: "input_reduce_fusion.78" cost_us: 2.177 }
costs { name: "input_reduce_fusion.79" cost_us: 2.113 }
costs { name: "input_reduce_fusion.8" cost_us: 2.656 }
costs { name: "input_reduce_fusion.8.double_buffer_clone" cost_us: 2.528 }
costs { name: "input_reduce_fusion.8.peeled_double_buffer" cost_us: 2.848 }
costs { name: "input_reduce_fusion.80" cost_us: 2.272 }
costs { name: "input_reduce_fusion.81" cost_us: 1.983 }
costs { name: "input_reduce_fusion.82" cost_us: 2.496 }
costs { name: "input_reduce_fusion.83" cost_us: 2.016 }
costs { name: "input_reduce_fusion.84" cost_us: 1.984 }
costs { name: "input_reduce_fusion.85" cost_us: 2.656 }
costs { name: "input_reduce_fusion.86" cost_us: 2.144 }
costs { name: "input_reduce_fusion.87" cost_us: 2.592 }
costs { name: "input_reduce_fusion.88" cost_us: 2.048 }
costs { name: "input_reduce_fusion.89" cost_us: 1.952 }
costs { name: "input_reduce_fusion.9" cost_us: 1.953 }
costs { name: "input_reduce_fusion.9.double_buffer_clone" cost_us: 2.049 }
costs { name: "input_reduce_fusion.9.peeled_double_buffer" cost_us: 1.664 }
costs { name: "input_reduce_fusion.90" cost_us: 1.92 }
costs { name: "input_reduce_fusion.91" cost_us: 1.92 }
costs { name: "input_reduce_fusion.92" cost_us: 2.08 }
costs { name: "input_reduce_fusion.93" cost_us: 2.112 }
costs { name: "input_reduce_fusion.94" cost_us: 1.92 }
costs { name: "input_reduce_fusion.95" cost_us: 2.048 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 2.816 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 2.848 }
costs { name: "input_transpose_fusion.18" cost_us: 417.663 }
costs { name: "input_transpose_fusion.19" cost_us: 420.19 }
costs { name: "input_transpose_fusion.20" cost_us: 420.574 }
costs { name: "loop_add_log_fusion" cost_us: 2.016 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.6 }
costs { name: "loop_divide_fusion" cost_us: 1.792 }
costs { name: "loop_multiply_fusion.10" cost_us: 1.6 }
costs { name: "loop_multiply_fusion.4" cost_us: 2.144 }
costs { name: "loop_select_fusion.1" cost_us: 2.08 }
costs { name: "loop_select_fusion.2" cost_us: 1.216 }
costs { name: "loop_select_fusion.5" cost_us: 1.504 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.504 }
costs { name: "loop_sqrt_fusion" cost_us: 2.976 }
costs { name: "loop_subtract_fusion" cost_us: 1.344 }
costs { name: "while.32.0" cost_us: 10944.695 }
costs { name: "while.32.0" cost_us: 196.319 }
costs { name: "while.32.0" cost_us: 5565.609 }
costs { name: "while.32.0" cost_us: 1452.442 }
costs { name: "while.32.0" cost_us: 1901.08 }
costs { name: "while.32.0" cost_us: 1751.097 }
costs { name: "while.32.0" cost_us: 1775.225 }
costs { name: "while.32.0" cost_us: 1140.187 }
costs { name: "while.32.0" cost_us: 1141.595 }
costs { name: "while.32.0" cost_us: 631.517 }
costs { name: "while.32.0" cost_us: 631.741 }
costs { name: "while.32.0" cost_us: 231.328 }
costs { name: "while.32.0" cost_us: 791.005 }
costs { name: "while.32.0" cost_us: 786.493 }
costs { name: "while.32.0" cost_us: 318.718 }
costs { name: "while.32.0" cost_us: 407.006 }
costs { name: "while.32.0" cost_us: 403.519 }
costs { name: "while.32.0" cost_us: 90.624 }
costs { name: "while.32.0" cost_us: 87.36 }
costs { name: "while.32.0" cost_us: 80.639 }
costs { name: "while.32.0" cost_us: 80.128 }
costs { name: "while.32.0" cost_us: 67.52 }
costs { name: "while.32.0" cost_us: 41.504 }
costs { name: "while.32.0" cost_us: 25.312 }
costs { name: "while.32.0" cost_us: 10.88 }
costs { name: "while.32.0" cost_us: 8.128 }
costs { name: "while.32.0" cost_us: 2.656 }
costs { name: "while.32.0" cost_us: 1.92 }
costs { name: "while.32.0" cost_us: 1.76 }
costs { name: "while.32.0" cost_us: 1.727 }
costs { name: "while.32.0" cost_us: 1.92 }
costs { name: "while.32.0" cost_us: 1.984 }
costs { name: "while.32.0" cost_us: 8.288 }
costs { name: "while.32.0" cost_us: 8.384 }
costs { name: "while.32.0" cost_us: 3.936 }
costs { name: "while.32.0" cost_us: 1.888 }
costs { name: "while.32.0" cost_us: 1.888 }
costs { name: "while.32.0" cost_us: 2.304 }
costs { name: "while.32.0" cost_us: 2.848 }
costs { name: "while.32.0" cost_us: 1.887 }
costs { name: "while.32.0" cost_us: 3.968 }
costs { name: "while.32.0" cost_us: 4.032 }
costs { name: "while.32.0" cost_us: 1.696 }
costs { name: "while.32.0" cost_us: 1.76 }
costs { name: "while.32.0" cost_us: 1.664 }
costs { name: "while.32.0" cost_us: 2.816 }
costs { name: "while.32.0" cost_us: 1.471 }
costs { name: "while.32.0" cost_us: 2.528 }
costs { name: "while.32.0" cost_us: 1.279 }
costs { name: "while.32.0" cost_us: 2.336 }
costs { name: "while.32.0" cost_us: 1.791 }
costs { name: "while.32.0" cost_us: 1.792 }
costs { name: "while.32.0" cost_us: 1.887 }
costs { name: "while.32.0" cost_us: 1.791 }
costs { name: "while.33.0" cost_us: 1359.355 }
costs { name: "while.33.0" cost_us: 15619.044 }
costs { name: "while.33.0" cost_us: 11165.975 }
costs { name: "while.33.0" cost_us: 5093.292 }
costs { name: "while.33.0" cost_us: 4703.599 }
costs { name: "while.33.0" cost_us: 261.694 }
costs { name: "while.33.0" cost_us: 3973.008 }
costs { name: "while.33.0" cost_us: 100.992 }
costs { name: "while.33.0" cost_us: 1822.937 }
costs { name: "while.33.0" cost_us: 2650.486 }
costs { name: "while.33.0" cost_us: 2235.063 }
costs { name: "while.33.0" cost_us: 1897.113 }
costs { name: "while.33.0" cost_us: 169.023 }
costs { name: "while.33.0" cost_us: 885.468 }
costs { name: "while.33.0" cost_us: 1515.13 }
costs { name: "while.33.0" cost_us: 1260.315 }
costs { name: "while.33.0" cost_us: 1188.155 }
costs { name: "while.33.0" cost_us: 812.285 }
costs { name: "while.33.0" cost_us: 734.43 }
costs { name: "while.33.0" cost_us: 613.566 }
costs { name: "while.33.0" cost_us: 252.831 }
costs { name: "while.33.0" cost_us: 233.887 }
costs { name: "while.33.0" cost_us: 415.518 }
costs { name: "while.33.0" cost_us: 394.046 }
costs { name: "while.33.0" cost_us: 324.319 }
costs { name: "while.33.0" cost_us: 258.88 }
costs { name: "while.33.0" cost_us: 245.279 }
costs { name: "while.33.0" cost_us: 234.879 }
costs { name: "while.33.0" cost_us: 98.56 }
costs { name: "while.33.0" cost_us: 188.511 }
costs { name: "while.33.0" cost_us: 177.983 }
costs { name: "while.33.0" cost_us: 176.095 }
costs { name: "while.33.0" cost_us: 167.84 }
costs { name: "while.33.0" cost_us: 90.688 }
costs { name: "while.33.0" cost_us: 89.567 }
costs { name: "while.33.0" cost_us: 87.135 }
costs { name: "while.33.0" cost_us: 80.512 }
costs { name: "while.33.0" cost_us: 66.784 }
costs { name: "while.33.0" cost_us: 49.759 }
costs { name: "while.33.0" cost_us: 24.48 }
costs { name: "while.33.0" cost_us: 33.696 }
costs { name: "while.33.0" cost_us: 1.567 }
costs { name: "while.33.0" cost_us: 10.848 }
costs { name: "while.33.0" cost_us: 1.727 }
costs { name: "while.33.0" cost_us: 10.016 }
costs { name: "while.33.0" cost_us: 1.215 }
costs { name: "while.33.0" cost_us: 7.136 }
costs { name: "while.33.0" cost_us: 1.536 }
costs { name: "while.33.0" cost_us: 12.512 }
costs { name: "while.33.0" cost_us: 1.567 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 10.4 }
costs { name: "while.33.0" cost_us: 10.08 }
costs { name: "while.33.0" cost_us: 2.272 }
costs { name: "while.33.0" cost_us: 10.015 }
costs { name: "while.33.0" cost_us: 9.12 }
costs { name: "while.33.0" cost_us: 9.12 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 7.616 }
costs { name: "while.33.0" cost_us: 2.271 }
costs { name: "while.33.0" cost_us: 1.375 }
costs { name: "while.33.0" cost_us: 6.624 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.6 }
costs { name: "while.33.0" cost_us: 1.631 }
costs { name: "while.33.0" cost_us: 1.92 }
costs { name: "while.33.0" cost_us: 1.76 }
costs { name: "while.33.0" cost_us: 4.0 }
costs { name: "while.33.0" cost_us: 3.936 }
costs { name: "while.33.0" cost_us: 1.823 }
costs { name: "while.33.0" cost_us: 1.6 }
costs { name: "while.33.0" cost_us: 3.616 }
costs { name: "while.33.0" cost_us: 1.631 }
costs { name: "while.33.0" cost_us: 1.663 }
costs { name: "while.33.0" cost_us: 3.488 }
costs { name: "while.33.0" cost_us: 3.487 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 2.016 }
costs { name: "while.33.0" cost_us: 2.016 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 1.952 }
costs { name: "while.33.0" cost_us: 1.76 }
costs { name: "while.33.0" cost_us: 1.759 }
costs { name: "while.33.0" cost_us: 1.504 }
costs { name: "while.33.0" cost_us: 1.632 }
costs { name: "while.33.0" cost_us: 1.664 }
costs { name: "while.33.0" cost_us: 1.727 }
costs { name: "while.33.0" cost_us: 1.472 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.471 }
costs { name: "while.33.0" cost_us: 1.44 }
costs { name: "while.33.0" cost_us: 1.44 }
costs { name: "while.33.0" cost_us: 1.44 }
costs { name: "while.33.0" cost_us: 1.44 }
costs { name: "while.33.0" cost_us: 1.44 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.311 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.183 }
costs { name: "while.33.0" cost_us: 1.119 }
costs { name: "while.33.0" cost_us: 1.024 }
costs { name: "loop_add_fusion.2" cost_us: 1.536 }
costs { name: "input_reduce_fusion.14" cost_us: 91.616 }
costs { name: "input_reduce_fusion.14.double_buffer_clone" cost_us: 90.624 }
costs { name: "input_reduce_fusion.14.peeled_double_buffer" cost_us: 86.4 }
costs { name: "input_reduce_fusion.15" cost_us: 87.487 }
costs { name: "input_reduce_fusion.15.double_buffer_clone" cost_us: 87.36 }
costs { name: "input_reduce_fusion.15.peeled_double_buffer" cost_us: 88.383 }
costs { name: "input_reduce_fusion.166" cost_us: 93.599 }
costs { name: "input_reduce_fusion.167" cost_us: 88.831 }
costs { name: "input_reduce_fusion.168" cost_us: 85.984 }
costs { name: "loop_multiply_fusion.3" cost_us: 190.207 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.24 }
costs { name: "wrapped_convert" cost_us: 1.952 }
costs { name: "wrapped_convert.1" cost_us: 6.592 }
costs { name: "custom-call.64.0" cost_us: 11978.352 }
costs { name: "loop_convert_fusion.112" cost_us: 618.141 }
costs { name: "input_transpose_fusion.23" cost_us: 7.392 }
costs { name: "all-gather-start.3" cost_us: 5161.133 }
costs { name: "custom-call.63.0" cost_us: 9103.068 }
costs { name: "loop_convert_fusion" cost_us: 1.887 }
costs { name: "loop_convert_fusion.1" cost_us: 1.888 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 1.92 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 1.92 }
costs { name: "loop_convert_fusion.10" cost_us: 1.76 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.10.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.11" cost_us: 1.824 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 1.856 }
costs { name: "loop_convert_fusion.11.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_convert_fusion.114" cost_us: 8.448 }
costs { name: "loop_convert_fusion.115" cost_us: 8.448 }
costs { name: "loop_convert_fusion.116" cost_us: 8.576 }
costs { name: "loop_convert_fusion.12" cost_us: 1.887 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 1.791 }
costs { name: "loop_convert_fusion.12.peeled_double_buffer" cost_us: 2.112 }
costs { name: "loop_convert_fusion.123" cost_us: 3.775 }
costs { name: "loop_convert_fusion.124" cost_us: 4.032 }
costs { name: "loop_convert_fusion.127" cost_us: 2.112 }
costs { name: "loop_convert_fusion.128" cost_us: 2.208 }
costs { name: "loop_convert_fusion.13" cost_us: 1.727 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_convert_fusion.13.peeled_double_buffer" cost_us: 1.664 }
costs { name: "loop_convert_fusion.133" cost_us: 2.272 }
costs { name: "loop_convert_fusion.134" cost_us: 2.144 }
costs { name: "loop_convert_fusion.137" cost_us: 1.472 }
costs { name: "loop_convert_fusion.138" cost_us: 1.696 }
costs { name: "loop_convert_fusion.139" cost_us: 1.728 }
costs { name: "loop_convert_fusion.19" cost_us: 8.384 }
costs { name: "loop_convert_fusion.19.double_buffer_clone" cost_us: 8.288 }
costs { name: "loop_convert_fusion.19.peeled_double_buffer" cost_us: 8.768 }
costs { name: "loop_convert_fusion.2" cost_us: 1.92 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 2.08 }
costs { name: "loop_convert_fusion.20" cost_us: 8.16 }
costs { name: "loop_convert_fusion.20.double_buffer_clone" cost_us: 8.128 }
costs { name: "loop_convert_fusion.20.peeled_double_buffer" cost_us: 8.64 }
costs { name: "loop_convert_fusion.21" cost_us: 8.479 }
costs { name: "loop_convert_fusion.21.double_buffer_clone" cost_us: 8.48 }
costs { name: "loop_convert_fusion.21.peeled_double_buffer" cost_us: 8.992 }
costs { name: "loop_convert_fusion.22" cost_us: 4.0 }
costs { name: "loop_convert_fusion.22.double_buffer_clone" cost_us: 3.936 }
costs { name: "loop_convert_fusion.22.peeled_double_buffer" cost_us: 4.288 }
costs { name: "loop_convert_fusion.23" cost_us: 3.968 }
costs { name: "loop_convert_fusion.23.double_buffer_clone" cost_us: 4.032 }
costs { name: "loop_convert_fusion.23.peeled_double_buffer" cost_us: 4.352 }
costs { name: "loop_convert_fusion.24" cost_us: 2.335 }
costs { name: "loop_convert_fusion.24.double_buffer_clone" cost_us: 2.336 }
costs { name: "loop_convert_fusion.24.peeled_double_buffer" cost_us: 2.464 }
costs { name: "loop_convert_fusion.25" cost_us: 2.304 }
costs { name: "loop_convert_fusion.25.double_buffer_clone" cost_us: 2.368 }
costs { name: "loop_convert_fusion.25.peeled_double_buffer" cost_us: 2.624 }
costs { name: "loop_convert_fusion.26" cost_us: 1.92 }
costs { name: "loop_convert_fusion.26.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_convert_fusion.26.peeled_double_buffer" cost_us: 1.696 }
costs { name: "loop_convert_fusion.27" cost_us: 1.952 }
costs { name: "loop_convert_fusion.27.double_buffer_clone" cost_us: 1.92 }
costs { name: "loop_convert_fusion.27.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.3" cost_us: 1.76 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 1.791 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 1.727 }
costs { name: "loop_convert_fusion.4" cost_us: 1.888 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 2.08 }
costs { name: "loop_convert_fusion.5" cost_us: 1.792 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 1.632 }
costs { name: "loop_convert_fusion.6" cost_us: 1.888 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.7" cost_us: 1.856 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 1.855 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.73" cost_us: 1.951 }
costs { name: "loop_convert_fusion.74" cost_us: 1.92 }
costs { name: "loop_convert_fusion.75" cost_us: 1.952 }
costs { name: "loop_convert_fusion.76" cost_us: 1.823 }
costs { name: "loop_convert_fusion.77" cost_us: 1.888 }
costs { name: "loop_convert_fusion.78" cost_us: 1.92 }
costs { name: "loop_convert_fusion.79" cost_us: 1.728 }
costs { name: "loop_convert_fusion.8" cost_us: 1.76 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 1.791 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.80" cost_us: 1.92 }
costs { name: "loop_convert_fusion.81" cost_us: 1.696 }
costs { name: "loop_convert_fusion.82" cost_us: 1.632 }
costs { name: "loop_convert_fusion.83" cost_us: 1.856 }
costs { name: "loop_convert_fusion.84" cost_us: 1.952 }
costs { name: "loop_convert_fusion.85" cost_us: 2.08 }
costs { name: "loop_convert_fusion.86" cost_us: 1.727 }
costs { name: "loop_convert_fusion.9" cost_us: 1.727 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_convert_fusion.9.peeled_double_buffer" cost_us: 1.44 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 2.048 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 631.517 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 80.671 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 80.639 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 80.767 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 80.128 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 80.287 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 80.672 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 631.805 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 631.741 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 631.806 }
costs { name: "loop_dynamic_update_slice_fusion.57" cost_us: 631.614 }
costs { name: "loop_dynamic_update_slice_fusion.58" cost_us: 81.247 }
costs { name: "loop_dynamic_update_slice_fusion.59" cost_us: 80.992 }
costs { name: "loop_dynamic_update_slice_fusion.60" cost_us: 632.318 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 631.741 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 631.838 }
costs { name: "loop_add_fusion" cost_us: 1.696 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_fusion.peeled_double_buffer" cost_us: 1.728 }
costs { name: "loop_convert_fusion.108" cost_us: 1864.408 }
costs { name: "loop_convert_fusion.109" cost_us: 828.957 }
costs { name: "loop_convert_fusion.110" cost_us: 1276.603 }
costs { name: "loop_convert_fusion.14" cost_us: 1751.097 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 1775.225 }
costs { name: "loop_convert_fusion.14.peeled_double_buffer" cost_us: 1762.265 }
costs { name: "loop_convert_fusion.15" cost_us: 791.005 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 786.493 }
costs { name: "loop_convert_fusion.15.peeled_double_buffer" cost_us: 779.165 }
costs { name: "loop_convert_fusion.16" cost_us: 1141.595 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 1140.187 }
costs { name: "loop_convert_fusion.16.peeled_double_buffer" cost_us: 1132.475 }
costs { name: "cublas-gemm.103.0" cost_us: 5099.532 }
costs { name: "cublas-gemm.96.0" cost_us: 5078.987 }
costs { name: "cublas-gemm.96.0.double_buffer_clone" cost_us: 5088.972 }
costs { name: "cublas-gemm.96.0.peeled_double_buffer" cost_us: 5106.956 }
costs { name: "wrapped_transpose.10" cost_us: 233.247 }
costs { name: "wrapped_transpose.12" cost_us: 234.303 }
costs { name: "wrapped_transpose.14" cost_us: 233.919 }
costs { name: "wrapped_transpose.16" cost_us: 241.375 }
costs { name: "cublas-gemm.104.0" cost_us: 5105.515 }
costs { name: "cublas-gemm.97.0" cost_us: 5084.363 }
costs { name: "cublas-gemm.97.0.double_buffer_clone" cost_us: 5098.091 }
costs { name: "cublas-gemm.97.0.peeled_double_buffer" cost_us: 5111.756 }
costs { name: "wrapped_transpose.11" cost_us: 231.328 }
costs { name: "wrapped_transpose.13" cost_us: 233.503 }
costs { name: "wrapped_transpose.15" cost_us: 240.031 }
costs { name: "wrapped_transpose.9" cost_us: 232.191 }
costs { name: "cublas-gemm.105.0" cost_us: 5617.354 }
costs { name: "cublas-gemm.98.0" cost_us: 5578.154 }
costs { name: "cublas-gemm.98.0.double_buffer_clone" cost_us: 5565.609 }
costs { name: "cublas-gemm.98.0.peeled_double_buffer" cost_us: 5601.835 }
costs { name: "loop_rsqrt_fusion" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.144 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 2.111 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 2.113 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.208 }
costs { name: "input_concatenate_fusion" cost_us: 318.751 }
costs { name: "input_concatenate_fusion.1" cost_us: 41.504 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 41.568 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 41.6 }
costs { name: "input_concatenate_fusion.2" cost_us: 318.91 }
costs { name: "input_concatenate_fusion.3" cost_us: 41.76 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 318.718 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 318.655 }
costs { name: "custom-call.72.0" cost_us: 1913.529 }
costs { name: "custom-call.72.0" cost_us: 1.664 }
costs { name: "custom-call.72.0.double_buffer_clone" cost_us: 1901.08 }
costs { name: "custom-call.72.0.double_buffer_clone" cost_us: 1.696 }
costs { name: "custom-call.72.0.peeled_double_buffer" cost_us: 1880.089 }
costs { name: "custom-call.72.0.peeled_double_buffer" cost_us: 1.824 }
costs { name: "custom-call.73.0" cost_us: 2013.144 }
costs { name: "custom-call.73.0" cost_us: 1.824 }
costs { name: "loop_broadcast_fusion" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.12" cost_us: 1.344 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.279 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.28 }
costs { name: "loop_multiply_fusion" cost_us: 1.472 }
costs { name: "loop_multiply_fusion.8" cost_us: 1.504 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 1.471 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 1.472 }
costs { name: "loop_convert_fusion.113" cost_us: 25.824 }
costs { name: "loop_convert_fusion.18" cost_us: 25.312 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 25.536 }
costs { name: "loop_convert_fusion.18.peeled_double_buffer" cost_us: 25.664 }
costs { name: "cublas-gemm.100.0" cost_us: 202.623 }
costs { name: "cublas-gemm.93.0" cost_us: 196.319 }
costs { name: "cublas-gemm.93.0.double_buffer_clone" cost_us: 196.511 }
costs { name: "cublas-gemm.93.0.peeled_double_buffer" cost_us: 198.111 }
costs { name: "input_transpose_fusion.1" cost_us: 10.88 }
costs { name: "input_transpose_fusion.1.double_buffer_clone" cost_us: 11.2 }
costs { name: "input_transpose_fusion.1.peeled_double_buffer" cost_us: 11.232 }
costs { name: "input_transpose_fusion.12" cost_us: 11.744 }
costs { name: "cublas-gemm.101.0" cost_us: 201.183 }
costs { name: "cublas-gemm.94.0" cost_us: 196.96 }
costs { name: "cublas-gemm.94.0.double_buffer_clone" cost_us: 197.983 }
costs { name: "cublas-gemm.94.0.peeled_double_buffer" cost_us: 197.631 }
costs { name: "input_transpose_fusion" cost_us: 11.039 }
costs { name: "input_transpose_fusion.11" cost_us: 12.48 }
costs { name: "input_transpose_fusion.double_buffer_clone" cost_us: 11.296 }
costs { name: "input_transpose_fusion.peeled_double_buffer" cost_us: 10.784 }
costs { name: "loop_convert_fusion.111" cost_us: 425.343 }
costs { name: "loop_convert_fusion.17" cost_us: 407.006 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 403.519 }
costs { name: "loop_convert_fusion.17.peeled_double_buffer" cost_us: 401.438 }
costs { name: "cublas-gemm.102.0" cost_us: 1539.93 }
costs { name: "cublas-gemm.95.0" cost_us: 1523.289 }
costs { name: "cublas-gemm.95.0.double_buffer_clone" cost_us: 1525.754 }
costs { name: "cublas-gemm.95.0.peeled_double_buffer" cost_us: 1529.881 }
costs { name: "cublas-gemm.92.0" cost_us: 1455.578 }
costs { name: "cublas-gemm.92.0.double_buffer_clone" cost_us: 1452.442 }
costs { name: "cublas-gemm.92.0.peeled_double_buffer" cost_us: 1472.282 }
costs { name: "cublas-gemm.99.0" cost_us: 1471.675 }
costs { name: "input_transpose_fusion.13" cost_us: 72.608 }
costs { name: "input_transpose_fusion.2" cost_us: 67.52 }
costs { name: "input_transpose_fusion.2.double_buffer_clone" cost_us: 67.68 }
costs { name: "input_transpose_fusion.2.peeled_double_buffer" cost_us: 69.119 }
costs { name: "loop_convert_fusion.120" cost_us: 6.88 }
costs { name: "loop_power_fusion.3" cost_us: 1.632 }
costs { name: "all-reduce-start.14" cost_us: 279.647 }
costs { name: "all-reduce-start.16" cost_us: 443.326 }
costs { name: "all-reduce-start.4" cost_us: 4038.96 }
costs { name: "all-reduce-start.5" cost_us: 4772.078 }
costs { name: "input_reduce_fusion.201" cost_us: 4.288 }
costs { name: "input_transpose_fusion.24" cost_us: 3.424 }
costs { name: "input_transpose_fusion.25" cost_us: 3.584 }
costs { name: "wrapped_slice.91" cost_us: 1.472 }
costs { name: "custom-call.65.0" cost_us: 11213.172 }
costs { name: "custom-call.66.0" cost_us: 10487.545 }
costs { name: "custom-call.67.0" cost_us: 8858.431 }
costs { name: "copy_fusion.1" cost_us: 13.984 }
costs { name: "copy_fusion.2" cost_us: 3.296 }
costs { name: "input_add_reduce_fusion.1" cost_us: 734.43 }
costs { name: "input_add_reduce_fusion.17" cost_us: 741.725 }
costs { name: "input_add_reduce_fusion.18" cost_us: 746.877 }
costs { name: "input_convert_reduce_fusion" cost_us: 11.392 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 10.848 }
costs { name: "input_convert_reduce_fusion.10" cost_us: 8.768 }
costs { name: "input_convert_reduce_fusion.11" cost_us: 9.024 }
costs { name: "input_convert_reduce_fusion.12" cost_us: 8.448 }
costs { name: "input_convert_reduce_fusion.13" cost_us: 8.352 }
costs { name: "input_convert_reduce_fusion.14" cost_us: 7.233 }
costs { name: "input_convert_reduce_fusion.15" cost_us: 7.393 }
costs { name: "input_convert_reduce_fusion.2" cost_us: 10.08 }
costs { name: "input_convert_reduce_fusion.3" cost_us: 9.12 }
costs { name: "input_convert_reduce_fusion.4" cost_us: 9.12 }
costs { name: "input_convert_reduce_fusion.5" cost_us: 7.167 }
costs { name: "input_convert_reduce_fusion.6" cost_us: 7.136 }
costs { name: "input_convert_reduce_fusion.9" cost_us: 9.024 }
costs { name: "input_reduce_fusion.100" cost_us: 2.048 }
costs { name: "input_reduce_fusion.101" cost_us: 2.528 }
costs { name: "input_reduce_fusion.102" cost_us: 1.888 }
costs { name: "input_reduce_fusion.103" cost_us: 2.496 }
costs { name: "input_reduce_fusion.104" cost_us: 2.176 }
costs { name: "input_reduce_fusion.105" cost_us: 2.656 }
costs { name: "input_reduce_fusion.106" cost_us: 2.56 }
costs { name: "input_reduce_fusion.107" cost_us: 2.528 }
costs { name: "input_reduce_fusion.108" cost_us: 2.208 }
costs { name: "input_reduce_fusion.109" cost_us: 2.08 }
costs { name: "input_reduce_fusion.110" cost_us: 2.753 }
costs { name: "input_reduce_fusion.111" cost_us: 2.08 }
costs { name: "input_reduce_fusion.112" cost_us: 2.496 }
costs { name: "input_reduce_fusion.113" cost_us: 2.047 }
costs { name: "input_reduce_fusion.114" cost_us: 2.368 }
costs { name: "input_reduce_fusion.115" cost_us: 2.624 }
costs { name: "input_reduce_fusion.116" cost_us: 2.528 }
costs { name: "input_reduce_fusion.16" cost_us: 1.76 }
costs { name: "input_reduce_fusion.17" cost_us: 1.792 }
costs { name: "input_reduce_fusion.177" cost_us: 95.775 }
costs { name: "input_reduce_fusion.18" cost_us: 1.76 }
costs { name: "input_reduce_fusion.180" cost_us: 91.103 }
costs { name: "input_reduce_fusion.188" cost_us: 6.208 }
costs { name: "input_reduce_fusion.189" cost_us: 6.272 }
costs { name: "input_reduce_fusion.19" cost_us: 1.728 }
costs { name: "input_reduce_fusion.190" cost_us: 6.112 }
costs { name: "input_reduce_fusion.191" cost_us: 3.487 }
costs { name: "input_reduce_fusion.192" cost_us: 3.712 }
costs { name: "input_reduce_fusion.193" cost_us: 2.592 }
costs { name: "input_reduce_fusion.194" cost_us: 2.592 }
costs { name: "input_reduce_fusion.20" cost_us: 2.272 }
costs { name: "input_reduce_fusion.21" cost_us: 1.76 }
costs { name: "input_reduce_fusion.22" cost_us: 2.272 }
costs { name: "input_reduce_fusion.23" cost_us: 1.76 }
costs { name: "input_reduce_fusion.24" cost_us: 2.335 }
costs { name: "input_reduce_fusion.25" cost_us: 1.727 }
costs { name: "input_reduce_fusion.26" cost_us: 1.76 }
costs { name: "input_reduce_fusion.27" cost_us: 1.76 }
costs { name: "input_reduce_fusion.28" cost_us: 1.76 }
costs { name: "input_reduce_fusion.29" cost_us: 2.271 }
costs { name: "input_reduce_fusion.30" cost_us: 1.76 }
costs { name: "input_reduce_fusion.31" cost_us: 2.336 }
costs { name: "input_reduce_fusion.32" cost_us: 1.76 }
costs { name: "input_reduce_fusion.33" cost_us: 2.303 }
costs { name: "input_reduce_fusion.34" cost_us: 1.728 }
costs { name: "input_reduce_fusion.35" cost_us: 2.272 }
costs { name: "input_reduce_fusion.36" cost_us: 1.76 }
costs { name: "input_reduce_fusion.40" cost_us: 89.567 }
costs { name: "input_reduce_fusion.47" cost_us: 2.112 }
costs { name: "input_reduce_fusion.48" cost_us: 2.08 }
costs { name: "input_reduce_fusion.49" cost_us: 2.143 }
costs { name: "input_reduce_fusion.50" cost_us: 2.08 }
costs { name: "input_reduce_fusion.51" cost_us: 1.952 }
costs { name: "input_reduce_fusion.52" cost_us: 1.856 }
costs { name: "input_reduce_fusion.53" cost_us: 1.855 }
costs { name: "input_reduce_fusion.54" cost_us: 2.08 }
costs { name: "input_reduce_fusion.55" cost_us: 1.888 }
costs { name: "input_reduce_fusion.56" cost_us: 1.856 }
costs { name: "input_reduce_fusion.57" cost_us: 1.856 }
costs { name: "input_reduce_fusion.58" cost_us: 2.016 }
costs { name: "input_reduce_fusion.59" cost_us: 1.92 }
costs { name: "input_reduce_fusion.60" cost_us: 2.08 }
costs { name: "input_reduce_fusion.61" cost_us: 1.856 }
costs { name: "input_reduce_fusion.62" cost_us: 1.889 }
costs { name: "input_reduce_fusion.63" cost_us: 1.856 }
costs { name: "input_reduce_fusion.64" cost_us: 1.856 }
costs { name: "input_reduce_fusion.65" cost_us: 1.856 }
costs { name: "input_reduce_fusion.66" cost_us: 2.08 }
costs { name: "input_reduce_fusion.67" cost_us: 1.856 }
costs { name: "input_reduce_fusion.68" cost_us: 2.08 }
costs { name: "input_reduce_fusion.69" cost_us: 1.887 }
costs { name: "input_reduce_fusion.70" cost_us: 1.888 }
costs { name: "input_reduce_fusion.71" cost_us: 1.92 }
costs { name: "input_reduce_fusion.72" cost_us: 1.888 }
costs { name: "input_reduce_fusion.73" cost_us: 1.92 }
costs { name: "input_reduce_fusion.74" cost_us: 1.887 }
costs { name: "input_reduce_fusion.96" cost_us: 1.76 }
costs { name: "input_reduce_fusion.97" cost_us: 1.792 }
costs { name: "input_reduce_fusion.98" cost_us: 1.76 }
costs { name: "input_reduce_fusion.99" cost_us: 2.336 }
costs { name: "input_transpose_fusion.14" cost_us: 1374.107 }
costs { name: "input_transpose_fusion.3" cost_us: 1188.155 }
costs { name: "input_transpose_fusion.7" cost_us: 1231.099 }
costs { name: "loop_convert_fusion.100" cost_us: 2.017 }
costs { name: "loop_convert_fusion.101" cost_us: 1.792 }
costs { name: "loop_convert_fusion.102" cost_us: 1.76 }
costs { name: "loop_convert_fusion.103" cost_us: 1.6 }
costs { name: "loop_convert_fusion.104" cost_us: 2.048 }
costs { name: "loop_convert_fusion.105" cost_us: 1.792 }
costs { name: "loop_convert_fusion.106" cost_us: 1.888 }
costs { name: "loop_convert_fusion.107" cost_us: 1.888 }
costs { name: "loop_convert_fusion.117" cost_us: 7.936 }
costs { name: "loop_convert_fusion.118" cost_us: 8.096 }
costs { name: "loop_convert_fusion.119" cost_us: 8.064 }
costs { name: "loop_convert_fusion.125" cost_us: 3.84 }
costs { name: "loop_convert_fusion.126" cost_us: 3.808 }
costs { name: "loop_convert_fusion.129" cost_us: 2.24 }
costs { name: "loop_convert_fusion.130" cost_us: 2.24 }
costs { name: "loop_convert_fusion.131" cost_us: 2.4 }
costs { name: "loop_convert_fusion.132" cost_us: 1.856 }
costs { name: "loop_convert_fusion.135" cost_us: 2.368 }
costs { name: "loop_convert_fusion.136" cost_us: 1.92 }
costs { name: "loop_convert_fusion.140" cost_us: 1.472 }
costs { name: "loop_convert_fusion.141" cost_us: 1.471 }
costs { name: "loop_convert_fusion.142" cost_us: 1.471 }
costs { name: "loop_convert_fusion.28" cost_us: 1.536 }
costs { name: "loop_convert_fusion.29" cost_us: 1.567 }
costs { name: "loop_convert_fusion.30" cost_us: 1.664 }
costs { name: "loop_convert_fusion.31" cost_us: 1.663 }
costs { name: "loop_convert_fusion.32" cost_us: 1.664 }
costs { name: "loop_convert_fusion.33" cost_us: 1.568 }
costs { name: "loop_convert_fusion.34" cost_us: 1.567 }
costs { name: "loop_convert_fusion.35" cost_us: 1.567 }
costs { name: "loop_convert_fusion.36" cost_us: 1.568 }
costs { name: "loop_convert_fusion.37" cost_us: 1.568 }
costs { name: "loop_convert_fusion.38" cost_us: 1.632 }
costs { name: "loop_convert_fusion.39" cost_us: 1.567 }
costs { name: "loop_convert_fusion.40" cost_us: 1.567 }
costs { name: "loop_convert_fusion.41" cost_us: 1.664 }
costs { name: "loop_convert_fusion.42" cost_us: 1.567 }
costs { name: "loop_convert_fusion.43" cost_us: 1.568 }
costs { name: "loop_convert_fusion.44" cost_us: 1.631 }
costs { name: "loop_convert_fusion.45" cost_us: 1.664 }
costs { name: "loop_convert_fusion.47" cost_us: 1.855 }
costs { name: "loop_convert_fusion.48" cost_us: 1.823 }
costs { name: "loop_convert_fusion.49" cost_us: 1.696 }
costs { name: "loop_convert_fusion.50" cost_us: 1.727 }
costs { name: "loop_convert_fusion.51" cost_us: 1.631 }
costs { name: "loop_convert_fusion.52" cost_us: 1.6 }
costs { name: "loop_convert_fusion.53" cost_us: 1.632 }
costs { name: "loop_convert_fusion.54" cost_us: 1.728 }
costs { name: "loop_convert_fusion.55" cost_us: 2.304 }
costs { name: "loop_convert_fusion.56" cost_us: 2.015 }
costs { name: "loop_convert_fusion.57" cost_us: 1.792 }
costs { name: "loop_convert_fusion.58" cost_us: 1.792 }
costs { name: "loop_convert_fusion.59" cost_us: 1.952 }
costs { name: "loop_convert_fusion.60" cost_us: 2.144 }
costs { name: "loop_convert_fusion.61" cost_us: 2.24 }
costs { name: "loop_convert_fusion.62" cost_us: 1.535 }
costs { name: "loop_convert_fusion.63" cost_us: 1.6 }
costs { name: "loop_convert_fusion.64" cost_us: 1.568 }
costs { name: "loop_convert_fusion.65" cost_us: 1.6 }
costs { name: "loop_convert_fusion.66" cost_us: 2.304 }
costs { name: "loop_convert_fusion.67" cost_us: 2.304 }
costs { name: "loop_convert_fusion.68" cost_us: 1.856 }
costs { name: "loop_convert_fusion.69" cost_us: 2.208 }
costs { name: "loop_convert_fusion.70" cost_us: 1.504 }
costs { name: "loop_convert_fusion.71" cost_us: 1.568 }
costs { name: "loop_convert_fusion.72" cost_us: 2.175 }
costs { name: "loop_convert_fusion.87" cost_us: 1.791 }
costs { name: "loop_convert_fusion.88" cost_us: 1.76 }
costs { name: "loop_convert_fusion.89" cost_us: 1.824 }
costs { name: "loop_convert_fusion.90" cost_us: 1.92 }
costs { name: "loop_convert_fusion.91" cost_us: 1.632 }
costs { name: "loop_convert_fusion.92" cost_us: 1.824 }
costs { name: "loop_convert_fusion.93" cost_us: 1.791 }
costs { name: "loop_convert_fusion.94" cost_us: 1.792 }
costs { name: "loop_convert_fusion.95" cost_us: 1.824 }
costs { name: "loop_convert_fusion.96" cost_us: 1.952 }
costs { name: "loop_convert_fusion.97" cost_us: 1.889 }
costs { name: "loop_convert_fusion.98" cost_us: 1.856 }
costs { name: "loop_convert_fusion.99" cost_us: 1.856 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.111" cost_us: 14.752 }
costs { name: "loop_dynamic_update_slice_fusion.112" cost_us: 3.424 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 1.471 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.17" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.18" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.19" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.20" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.21" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.22" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.23" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.24" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.25" cost_us: 4.0 }
costs { name: "loop_dynamic_update_slice_fusion.26" cost_us: 10.015 }
costs { name: "loop_dynamic_update_slice_fusion.34" cost_us: 1.632 }
costs { name: "loop_dynamic_update_slice_fusion.35" cost_us: 1.631 }
costs { name: "loop_dynamic_update_slice_fusion.36" cost_us: 1.728 }
costs { name: "loop_dynamic_update_slice_fusion.37" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.38" cost_us: 1.632 }
costs { name: "loop_dynamic_update_slice_fusion.39" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.40" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.41" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.42" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.43" cost_us: 1.792 }
costs { name: "loop_dynamic_update_slice_fusion.44" cost_us: 1.567 }
costs { name: "loop_dynamic_update_slice_fusion.45" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.46" cost_us: 1.791 }
costs { name: "loop_dynamic_update_slice_fusion.47" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.48" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.49" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.50" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.51" cost_us: 1.728 }
costs { name: "loop_dynamic_update_slice_fusion.52" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.53" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.54" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.55" cost_us: 106.207 }
costs { name: "loop_dynamic_update_slice_fusion.56" cost_us: 380.415 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.82" cost_us: 112.288 }
costs { name: "loop_dynamic_update_slice_fusion.83" cost_us: 387.742 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 1.407 }
costs { name: "loop_select_fusion" cost_us: 1.248 }
costs { name: "loop_select_fusion.3" cost_us: 1.44 }
costs { name: "loop_select_fusion.4" cost_us: 1.76 }
costs { name: "loop_add_fusion.1" cost_us: 1.247 }
costs { name: "loop_add_fusion.3" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.110" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.32" cost_us: 1.728 }
costs { name: "loop_dynamic_update_slice_fusion.33" cost_us: 1.663 }
costs { name: "loop_dynamic_update_slice_fusion.27" cost_us: 10.048 }
costs { name: "loop_dynamic_update_slice_fusion.28" cost_us: 10.016 }
costs { name: "loop_dynamic_update_slice_fusion.84" cost_us: 10.272 }
costs { name: "loop_dynamic_update_slice_fusion.85" cost_us: 10.24 }
costs { name: "loop_dynamic_update_slice_fusion.29" cost_us: 3.936 }
costs { name: "loop_dynamic_update_slice_fusion.86" cost_us: 4.064 }
costs { name: "loop_dynamic_update_slice_fusion.30" cost_us: 1.92 }
costs { name: "loop_dynamic_update_slice_fusion.31" cost_us: 1.952 }
costs { name: "loop_dynamic_update_slice_fusion.87" cost_us: 1.888 }
costs { name: "loop_dynamic_update_slice_fusion.88" cost_us: 1.92 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 2650.486 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 2675.254 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 2681.813 }
costs { name: "input_add_reduce_fusion" cost_us: 415.518 }
costs { name: "input_add_reduce_fusion.15" cost_us: 434.398 }
costs { name: "input_add_reduce_fusion.16" cost_us: 422.815 }
costs { name: "input_convert_transpose_fusion.14" cost_us: 823.773 }
costs { name: "input_convert_transpose_fusion.17" cost_us: 399.071 }
costs { name: "input_convert_transpose_fusion.23" cost_us: 829.693 }
costs { name: "input_convert_transpose_fusion.26" cost_us: 410.558 }
costs { name: "input_convert_transpose_fusion.5" cost_us: 812.285 }
costs { name: "input_convert_transpose_fusion.8" cost_us: 394.046 }
costs { name: "input_reduce_fusion.176" cost_us: 349.694 }
costs { name: "input_reduce_fusion.179" cost_us: 281.055 }
costs { name: "input_reduce_fusion.182" cost_us: 260.095 }
costs { name: "input_reduce_fusion.183" cost_us: 330.175 }
costs { name: "input_reduce_fusion.184" cost_us: 54.592 }
costs { name: "input_reduce_fusion.185" cost_us: 13.056 }
costs { name: "input_reduce_fusion.186" cost_us: 51.807 }
costs { name: "input_reduce_fusion.187" cost_us: 12.704 }
costs { name: "input_reduce_fusion.42" cost_us: 245.279 }
costs { name: "input_reduce_fusion.43" cost_us: 324.319 }
costs { name: "input_reduce_fusion.44" cost_us: 49.759 }
costs { name: "input_reduce_fusion.45" cost_us: 12.512 }
costs { name: "input_transpose_fusion.15" cost_us: 1342.971 }
costs { name: "input_transpose_fusion.4" cost_us: 1260.315 }
costs { name: "input_transpose_fusion.8" cost_us: 1291.162 }
costs { name: "loop_multiply_fusion.1" cost_us: 2.08 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.4 }
costs { name: "loop_multiply_fusion.6" cost_us: 2.271 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.08 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.304 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.273 }
costs { name: "input_convert_transpose_fusion.12" cost_us: 254.079 }
costs { name: "input_convert_transpose_fusion.21" cost_us: 279.583 }
costs { name: "input_convert_transpose_fusion.3" cost_us: 252.831 }
costs { name: "input_reduce_fusion.198" cost_us: 7.616 }
costs { name: "input_reduce_fusion.199" cost_us: 4.512 }
costs { name: "input_reduce_fusion.46" cost_us: 7.616 }
costs { name: "input_convert_transpose_fusion.13" cost_us: 890.493 }
costs { name: "input_convert_transpose_fusion.22" cost_us: 889.821 }
costs { name: "input_convert_transpose_fusion.4" cost_us: 885.468 }
costs { name: "cublas-gemm.110.0" cost_us: 4714.447 }
costs { name: "cublas-gemm.127.0" cost_us: 4749.839 }
costs { name: "cublas-gemm.62.0" cost_us: 5580.683 }
costs { name: "cublas-gemm.118.0" cost_us: 4735.213 }
costs { name: "cublas-gemm.135.0" cost_us: 4864.078 }
costs { name: "cublas-gemm.68.0" cost_us: 5159.565 }
costs { name: "input_convert_transpose_fusion.15" cost_us: 886.396 }
costs { name: "input_convert_transpose_fusion.24" cost_us: 969.884 }
costs { name: "input_convert_transpose_fusion.6" cost_us: 885.949 }
costs { name: "cublas-gemm.111.0" cost_us: 5070.892 }
costs { name: "cublas-gemm.128.0" cost_us: 5089.453 }
costs { name: "cublas-gemm.63.0" cost_us: 5766.217 }
costs { name: "cublas-gemm.119.0" cost_us: 4703.599 }
costs { name: "cublas-gemm.136.0" cost_us: 4988.525 }
costs { name: "cublas-gemm.69.0" cost_us: 5163.597 }
costs { name: "input_convert_transpose_fusion.16" cost_us: 254.4 }
costs { name: "input_convert_transpose_fusion.25" cost_us: 254.175 }
costs { name: "input_convert_transpose_fusion.7" cost_us: 254.975 }
costs { name: "cublas-gemm.108.0" cost_us: 4965.612 }
costs { name: "cublas-gemm.125.0" cost_us: 4977.966 }
costs { name: "cublas-gemm.60.0" cost_us: 4995.405 }
costs { name: "input_transpose_fusion.10" cost_us: 233.92 }
costs { name: "input_transpose_fusion.17" cost_us: 233.727 }
costs { name: "input_transpose_fusion.6" cost_us: 234.879 }
costs { name: "cublas-gemm.116.0" cost_us: 4701.518 }
costs { name: "cublas-gemm.133.0" cost_us: 4847.502 }
costs { name: "cublas-gemm.70.0" cost_us: 5103.404 }
costs { name: "all-reduce-start.1" cost_us: 100.992 }
costs { name: "all-reduce-start.10" cost_us: 863.453 }
costs { name: "input_reduce_fusion.200" cost_us: 4.544 }
costs { name: "wrapped_slice.23" cost_us: 1.471 }
costs { name: "wrapped_slice.85" cost_us: 1.536 }
costs { name: "wrapped_slice.88" cost_us: 1.152 }
costs { name: "all-reduce-start.15" cost_us: 3274.963 }
costs { name: "wrapped_slice.24" cost_us: 1.024 }
costs { name: "wrapped_slice.86" cost_us: 1.536 }
costs { name: "wrapped_slice.87" cost_us: 1.472 }
costs { name: "input_convert_transpose_fusion" cost_us: 613.566 }
costs { name: "input_convert_transpose_fusion.1" cost_us: 80.512 }
costs { name: "input_convert_transpose_fusion.10" cost_us: 85.184 }
costs { name: "input_convert_transpose_fusion.18" cost_us: 705.277 }
costs { name: "input_convert_transpose_fusion.19" cost_us: 92.736 }
costs { name: "input_convert_transpose_fusion.9" cost_us: 644.894 }
costs { name: "custom-call.69.0" cost_us: 4839.661 }
costs { name: "custom-call.69.0" cost_us: 2365.463 }
costs { name: "custom-call.69.0" cost_us: 99.551 }
costs { name: "custom-call.69.0" cost_us: 178.752 }
costs { name: "custom-call.75.0" cost_us: 3973.008 }
costs { name: "custom-call.75.0" cost_us: 2235.063 }
costs { name: "custom-call.75.0" cost_us: 98.56 }
costs { name: "custom-call.75.0" cost_us: 177.983 }
costs { name: "custom-call.77.0" cost_us: 4111.92 }
costs { name: "custom-call.77.0" cost_us: 2285.527 }
costs { name: "custom-call.77.0" cost_us: 99.68 }
costs { name: "custom-call.77.0" cost_us: 178.239 }
costs { name: "cublas-gemm.120.0" cost_us: 169.023 }
costs { name: "cublas-gemm.137.0" cost_us: 175.839 }
costs { name: "cublas-gemm.71.0" cost_us: 187.551 }
costs { name: "cublas-gemm.113.0" cost_us: 261.694 }
costs { name: "cublas-gemm.130.0" cost_us: 277.503 }
costs { name: "cublas-gemm.65.0" cost_us: 306.495 }
costs { name: "input_convert_transpose_fusion.11" cost_us: 37.152 }
costs { name: "input_convert_transpose_fusion.2" cost_us: 33.696 }
costs { name: "input_convert_transpose_fusion.20" cost_us: 39.616 }
costs { name: "cublas-gemm.122.0" cost_us: 170.431 }
costs { name: "cublas-gemm.139.0" cost_us: 180.671 }
costs { name: "cublas-gemm.74.0" cost_us: 197.503 }
costs { name: "cublas-gemm.114.0" cost_us: 288.798 }
costs { name: "cublas-gemm.131.0" cost_us: 307.55 }
costs { name: "cublas-gemm.66.0" cost_us: 338.591 }
costs { name: "cublas-gemm.117.0" cost_us: 1359.355 }
costs { name: "cublas-gemm.134.0" cost_us: 1408.635 }
costs { name: "cublas-gemm.72.0" cost_us: 1475.834 }
costs { name: "cublas-gemm.112.0" cost_us: 1375.675 }
costs { name: "cublas-gemm.129.0" cost_us: 1408.347 }
costs { name: "cublas-gemm.64.0" cost_us: 1622.297 }
costs { name: "input_transpose_fusion.16" cost_us: 76.128 }
costs { name: "input_transpose_fusion.5" cost_us: 66.784 }
costs { name: "input_transpose_fusion.9" cost_us: 67.935 }
costs { name: "cublas-gemm.121.0" cost_us: 1450.331 }
costs { name: "cublas-gemm.138.0" cost_us: 1460.347 }
costs { name: "cublas-gemm.73.0" cost_us: 1574.778 }
costs { name: "cublas-gemm.115.0" cost_us: 1365.659 }
costs { name: "cublas-gemm.132.0" cost_us: 1424.219 }
costs { name: "cublas-gemm.67.0" cost_us: 1557.818 }
costs { name: "input_reduce_fusion.178" cost_us: 85.247 }
costs { name: "input_reduce_fusion.181" cost_us: 83.936 }
costs { name: "input_reduce_fusion.41" cost_us: 90.688 }
costs { name: "cublas-gemm.107.0" cost_us: 5093.292 }
costs { name: "cublas-gemm.124.0" cost_us: 5110.892 }
costs { name: "cublas-gemm.59.0" cost_us: 5104.268 }
costs { name: "wrapped_transpose.17" cost_us: 236.543 }
costs { name: "wrapped_transpose.19" cost_us: 234.174 }
costs { name: "wrapped_transpose.21" cost_us: 233.375 }
costs { name: "all-reduce-start.12" cost_us: 111.327 }
costs { name: "all-reduce-start.3" cost_us: 638.27 }
costs { name: "all-reduce-start.8" cost_us: 3687.666 }
costs { name: "all-reduce-start.11" cost_us: 3343.059 }
costs { name: "all-reduce-start.2" cost_us: 638.75 }
costs { name: "all-reduce-start.7" cost_us: 3653.842 }
costs { name: "cublas-gemm.109.0" cost_us: 5100.363 }
costs { name: "cublas-gemm.126.0" cost_us: 5105.644 }
costs { name: "cublas-gemm.61.0" cost_us: 5096.236 }
costs { name: "wrapped_transpose.18" cost_us: 237.888 }
costs { name: "wrapped_transpose.20" cost_us: 233.887 }
costs { name: "wrapped_transpose.22" cost_us: 237.343 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.24 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.176 }
costs { name: "custom-call.68.0" cost_us: 2011.385 }
costs { name: "custom-call.68.0" cost_us: 1.728 }
costs { name: "custom-call.74.0" cost_us: 1897.113 }
costs { name: "custom-call.74.0" cost_us: 2.016 }
costs { name: "custom-call.76.0" cost_us: 1930.265 }
costs { name: "custom-call.76.0" cost_us: 1.824 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.119 }
costs { name: "loop_broadcast_fusion.11" cost_us: 1.312 }
costs { name: "loop_broadcast_fusion.13" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.2" cost_us: 1.311 }
costs { name: "loop_multiply_fusion.7" cost_us: 1.472 }
costs { name: "loop_multiply_fusion.9" cost_us: 1.6 }
costs { name: "loop_convert_fusion.121" cost_us: 6.944 }
costs { name: "loop_convert_fusion.122" cost_us: 6.816 }
costs { name: "loop_convert_fusion.46" cost_us: 6.624 }
costs { name: "loop_power_fusion" cost_us: 1.183 }
costs { name: "loop_power_fusion.1" cost_us: 1.536 }
costs { name: "loop_power_fusion.2" cost_us: 1.44 }
costs { name: "cublas-gemm.106.0" cost_us: 1515.13 }
costs { name: "cublas-gemm.123.0" cost_us: 1536.923 }
costs { name: "cublas-gemm.58.0" cost_us: 1533.146 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 188.511 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 188.512 }
costs { name: "loop_dynamic_slice_fusion.6" cost_us: 190.111 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 24.512 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 24.48 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 24.256 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 24.288 }
costs { name: "loop_dynamic_slice_fusion.7" cost_us: 25.056 }
costs { name: "loop_dynamic_slice_fusion.8" cost_us: 25.92 }
costs { name: "loop_transpose_fusion" cost_us: 124.095 }
costs { name: "loop_divide_fusion" cost_us: 1.536 }
costs { name: "wrapped_transpose.6" cost_us: 389.439 }
costs { name: "wrapped_transpose.7" cost_us: 388.575 }
costs { name: "wrapped_transpose.8" cost_us: 417.15 }
costs { name: "wrapped_transpose" cost_us: 3.328 }
costs { name: "wrapped_transpose.1" cost_us: 3.329 }
costs { name: "wrapped_transpose.3" cost_us: 14.304 }
costs { name: "wrapped_transpose.5" cost_us: 416.447 }
costs { name: "wrapped_transpose.2" cost_us: 113.152 }
costs { name: "wrapped_transpose.4" cost_us: 15.392 }
