costs { name: "all-gather-start" cost_us: 14558.088 }
costs { name: "all-gather-start.1" cost_us: 14672.264 }
costs { name: "all-gather-start.10" cost_us: 15119.463 }
costs { name: "all-gather-start.2" cost_us: 14731.718 }
costs { name: "all-gather-start.3" cost_us: 14558.438 }
costs { name: "all-gather-start.4" cost_us: 14990.086 }
costs { name: "all-gather-start.5" cost_us: 15656.998 }
costs { name: "all-gather-start.6" cost_us: 15357.798 }
costs { name: "all-gather-start.7" cost_us: 15427.237 }
costs { name: "all-gather-start.8" cost_us: 11153.22 }
costs { name: "all-gather-start.9" cost_us: 15244.901 }
costs { name: "input_transpose_fusion" cost_us: 422.848 }
costs { name: "input_transpose_fusion.1" cost_us: 8.8 }
costs { name: "input_transpose_fusion.2" cost_us: 13.984 }
costs { name: "loop_add_fusion.1" cost_us: 1.632 }
costs { name: "loop_add_fusion.1.double_buffer_clone" cost_us: 1.952 }
costs { name: "loop_add_fusion.5" cost_us: 1.536 }
costs { name: "loop_add_fusion.5.double_buffer_clone" cost_us: 1.536 }
costs { name: "loop_broadcast_fusion" cost_us: 1.504 }
costs { name: "loop_broadcast_fusion.1" cost_us: 423.2 }
costs { name: "loop_broadcast_fusion.2" cost_us: 3392.673 }
costs { name: "loop_broadcast_fusion.3" cost_us: 3387.458 }
costs { name: "loop_broadcast_fusion.4" cost_us: 52.768 }
costs { name: "loop_broadcast_fusion.5" cost_us: 1.472 }
costs { name: "loop_transpose_fusion" cost_us: 122.592 }
costs { name: "reduce-scatter.58.double_buffer_clone.1" cost_us: 14725.67 }
costs { name: "reduce-scatter.58.peeled_double_buffer.1" cost_us: 14590.917 }
costs { name: "reduce-scatter.61" cost_us: 14837.67 }
costs { name: "reduce-scatter.62" cost_us: 16211.142 }
costs { name: "reduce-scatter.63" cost_us: 38787.598 }
costs { name: "wrapped_concatenate" cost_us: 1.696 }
costs { name: "wrapped_concatenate.1" cost_us: 1.792 }
costs { name: "wrapped_concatenate.2" cost_us: 1.856 }
costs { name: "wrapped_concatenate.3" cost_us: 1.952 }
costs { name: "wrapped_concatenate.4" cost_us: 2.048 }
costs { name: "wrapped_concatenate.5" cost_us: 2.208 }
costs { name: "wrapped_concatenate.6" cost_us: 2.656 }
costs { name: "wrapped_slice.18" cost_us: 1.344 }
costs { name: "wrapped_slice.19" cost_us: 1.536 }
costs { name: "wrapped_slice.20" cost_us: 1.504 }
costs { name: "wrapped_slice.21" cost_us: 1.311 }
costs { name: "wrapped_slice.22" cost_us: 1.375 }
costs { name: "wrapped_slice.23" cost_us: 1.535 }
costs { name: "wrapped_slice.28" cost_us: 1.536 }
costs { name: "wrapped_slice.29" cost_us: 1.376 }
costs { name: "wrapped_slice.31" cost_us: 1.344 }
costs { name: "wrapped_slice.32" cost_us: 1.696 }
costs { name: "wrapped_slice.33" cost_us: 1.504 }
costs { name: "wrapped_slice.34" cost_us: 1.344 }
costs { name: "wrapped_slice.35" cost_us: 1.536 }
costs { name: "wrapped_slice.36" cost_us: 1.536 }
costs { name: "wrapped_slice.37" cost_us: 1.344 }
costs { name: "wrapped_slice.38" cost_us: 1.344 }
costs { name: "wrapped_slice.39" cost_us: 1.568 }
costs { name: "wrapped_slice.40" cost_us: 1.536 }
costs { name: "wrapped_slice.41" cost_us: 1.344 }
costs { name: "wrapped_slice.42" cost_us: 1.344 }
costs { name: "wrapped_slice.43" cost_us: 1.536 }
costs { name: "wrapped_slice.44" cost_us: 1.568 }
costs { name: "wrapped_slice.45" cost_us: 1.344 }
costs { name: "wrapped_slice.46" cost_us: 1.344 }
costs { name: "wrapped_slice.47" cost_us: 1.536 }
costs { name: "wrapped_slice.48" cost_us: 1.536 }
costs { name: "wrapped_slice.49" cost_us: 1.312 }
costs { name: "wrapped_slice.50" cost_us: 1.344 }
costs { name: "wrapped_slice.51" cost_us: 1.536 }
costs { name: "wrapped_slice.52" cost_us: 1.536 }
costs { name: "wrapped_slice.53" cost_us: 1.312 }
costs { name: "wrapped_slice.54" cost_us: 1.344 }
costs { name: "wrapped_slice.55" cost_us: 1.536 }
costs { name: "wrapped_slice.56" cost_us: 1.504 }
costs { name: "wrapped_slice.57" cost_us: 1.344 }
costs { name: "wrapped_slice.58" cost_us: 1.344 }
costs { name: "wrapped_slice.59" cost_us: 1.344 }
costs { name: "wrapped_transpose.10" cost_us: 13.44 }
costs { name: "wrapped_transpose.11" cost_us: 106.016 }
costs { name: "wrapped_transpose.12" cost_us: 12.96 }
costs { name: "wrapped_transpose.13" cost_us: 368.032 }
costs { name: "wrapped_transpose.14" cost_us: 14.367 }
costs { name: "wrapped_transpose.15" cost_us: 105.888 }
costs { name: "wrapped_transpose.16" cost_us: 15.072 }
costs { name: "wrapped_transpose.17" cost_us: 372.352 }
costs { name: "wrapped_transpose.18" cost_us: 15.2 }
costs { name: "wrapped_transpose.19" cost_us: 104.897 }
costs { name: "wrapped_transpose.20" cost_us: 14.592 }
costs { name: "wrapped_transpose.21" cost_us: 16.0 }
costs { name: "wrapped_transpose.22" cost_us: 109.024 }
costs { name: "wrapped_transpose.23" cost_us: 15.2 }
costs { name: "wrapped_transpose.24" cost_us: 381.184 }
costs { name: "wrapped_transpose.25" cost_us: 3.776 }
costs { name: "wrapped_transpose.26" cost_us: 4.032 }
costs { name: "wrapped_transpose.27" cost_us: 6.496 }
costs { name: "wrapped_transpose.28" cost_us: 7.104 }
costs { name: "wrapped_transpose.29" cost_us: 7.2 }
costs { name: "wrapped_transpose.9" cost_us: 376.864 }
costs { name: "wrapped_select" cost_us: 1.6 }
costs { name: "loop_add_fusion" cost_us: 1.632 }
costs { name: "wrapped_add" cost_us: 1.504 }
costs { name: "loop_minimum_fusion" cost_us: 1.632 }
costs { name: "wrapped_cosine" cost_us: 1.696 }
costs { name: "input_reduce_fusion" cost_us: 1.824 }
costs { name: "loop_xor_fusion" cost_us: 1.984 }
costs { name: "wrapped_multiply" cost_us: 1.376 }
costs { name: "loop_subtract_fusion" cost_us: 1.6 }
costs { name: "input_add_reduce_fusion.1" cost_us: 133.6 }
costs { name: "input_add_reduce_fusion.1.double_buffer_clone" cost_us: 133.152 }
costs { name: "input_add_reduce_fusion.1.peeled_double_buffer" cost_us: 129.28 }
costs { name: "input_add_reduce_fusion.10" cost_us: 1380.672 }
costs { name: "input_add_reduce_fusion.11" cost_us: 1691.041 }
costs { name: "input_add_reduce_fusion.12" cost_us: 1690.496 }
costs { name: "input_add_reduce_fusion.14" cost_us: 129.632 }
costs { name: "input_add_reduce_fusion.15" cost_us: 266.752 }
costs { name: "input_add_reduce_fusion.16" cost_us: 131.744 }
costs { name: "input_add_reduce_fusion.20" cost_us: 52.993 }
costs { name: "input_add_reduce_fusion.21" cost_us: 54.688 }
costs { name: "input_add_reduce_fusion.22" cost_us: 6.72 }
costs { name: "input_add_reduce_fusion.3" cost_us: 42.433 }
costs { name: "input_add_reduce_fusion.4" cost_us: 32.671 }
costs { name: "input_add_reduce_fusion.5" cost_us: 395.2 }
costs { name: "input_add_reduce_fusion.6" cost_us: 395.936 }
costs { name: "input_add_reduce_fusion.7" cost_us: 32.352 }
costs { name: "input_add_reduce_fusion.8" cost_us: 13.697 }
costs { name: "input_add_reduce_fusion.9" cost_us: 13.6 }
costs { name: "input_convert_reduce_fusion" cost_us: 1046.56 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 221.088 }
costs { name: "input_reduce_fusion.1" cost_us: 129.056 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 133.12 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 134.432 }
costs { name: "input_reduce_fusion.10" cost_us: 80.416 }
costs { name: "input_reduce_fusion.11" cost_us: 13.408 }
costs { name: "input_reduce_fusion.12" cost_us: 5.696 }
costs { name: "input_reduce_fusion.13" cost_us: 5.792 }
costs { name: "input_reduce_fusion.14" cost_us: 232.608 }
costs { name: "input_reduce_fusion.15" cost_us: 233.088 }
costs { name: "input_reduce_fusion.16" cost_us: 238.272 }
costs { name: "input_reduce_fusion.17" cost_us: 2.208 }
costs { name: "input_reduce_fusion.18" cost_us: 2.017 }
costs { name: "input_reduce_fusion.19" cost_us: 2.017 }
costs { name: "input_reduce_fusion.2" cost_us: 86.4 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 86.273 }
costs { name: "input_reduce_fusion.2.peeled_double_buffer" cost_us: 87.936 }
costs { name: "input_reduce_fusion.20" cost_us: 2.304 }
costs { name: "input_reduce_fusion.21" cost_us: 2.4 }
costs { name: "input_reduce_fusion.22" cost_us: 2.272 }
costs { name: "input_reduce_fusion.23" cost_us: 2.336 }
costs { name: "input_reduce_fusion.24" cost_us: 2.144 }
costs { name: "input_reduce_fusion.25" cost_us: 2.176 }
costs { name: "input_reduce_fusion.26" cost_us: 248.896 }
costs { name: "input_reduce_fusion.27" cost_us: 1.728 }
costs { name: "input_reduce_fusion.28" cost_us: 2.24 }
costs { name: "input_reduce_fusion.29" cost_us: 185.216 }
costs { name: "input_reduce_fusion.31" cost_us: 133.824 }
costs { name: "input_reduce_fusion.32" cost_us: 86.719 }
costs { name: "input_reduce_fusion.33" cost_us: 133.472 }
costs { name: "input_reduce_fusion.34" cost_us: 87.04 }
costs { name: "input_reduce_fusion.35" cost_us: 88.416 }
costs { name: "input_reduce_fusion.37" cost_us: 87.201 }
costs { name: "input_reduce_fusion.38" cost_us: 2.144 }
costs { name: "input_reduce_fusion.39" cost_us: 1.952 }
costs { name: "input_reduce_fusion.4" cost_us: 3.391 }
costs { name: "input_reduce_fusion.40" cost_us: 3.552 }
costs { name: "input_reduce_fusion.47" cost_us: 2.08 }
costs { name: "input_reduce_fusion.48" cost_us: 2.367 }
costs { name: "input_reduce_fusion.49" cost_us: 2.272 }
costs { name: "input_reduce_fusion.5" cost_us: 4.096 }
costs { name: "input_reduce_fusion.50" cost_us: 3.744 }
costs { name: "input_reduce_fusion.51" cost_us: 2.016 }
costs { name: "input_reduce_fusion.52" cost_us: 2.016 }
costs { name: "input_reduce_fusion.53" cost_us: 1.728 }
costs { name: "input_reduce_fusion.54" cost_us: 1.92 }
costs { name: "input_reduce_fusion.55" cost_us: 1.728 }
costs { name: "input_reduce_fusion.56" cost_us: 1.952 }
costs { name: "input_reduce_fusion.57" cost_us: 1.728 }
costs { name: "input_reduce_fusion.58" cost_us: 1.856 }
costs { name: "input_reduce_fusion.59" cost_us: 1.856 }
costs { name: "input_reduce_fusion.6" cost_us: 3.744 }
costs { name: "input_reduce_fusion.60" cost_us: 1.6 }
costs { name: "input_reduce_fusion.61" cost_us: 1.856 }
costs { name: "input_reduce_fusion.62" cost_us: 2.432 }
costs { name: "input_reduce_fusion.63" cost_us: 2.176 }
costs { name: "input_reduce_fusion.64" cost_us: 2.048 }
costs { name: "input_reduce_fusion.65" cost_us: 1.984 }
costs { name: "input_reduce_fusion.66" cost_us: 1.824 }
costs { name: "input_reduce_fusion.67" cost_us: 1.952 }
costs { name: "input_reduce_fusion.68" cost_us: 1.632 }
costs { name: "input_reduce_fusion.69" cost_us: 1.856 }
costs { name: "input_reduce_fusion.7" cost_us: 3.744 }
costs { name: "input_reduce_fusion.70" cost_us: 1.887 }
costs { name: "input_reduce_fusion.71" cost_us: 2.272 }
costs { name: "input_reduce_fusion.72" cost_us: 2.208 }
costs { name: "input_reduce_fusion.73" cost_us: 2.24 }
costs { name: "input_reduce_fusion.74" cost_us: 2.24 }
costs { name: "input_reduce_fusion.75" cost_us: 1.791 }
costs { name: "input_reduce_fusion.76" cost_us: 1.856 }
costs { name: "input_reduce_fusion.77" cost_us: 2.016 }
costs { name: "input_reduce_fusion.8" cost_us: 13.536 }
costs { name: "input_reduce_fusion.9" cost_us: 75.52 }
costs { name: "loop_add_fusion.12" cost_us: 7.584 }
costs { name: "loop_add_fusion.13" cost_us: 7.583 }
costs { name: "loop_add_log_fusion" cost_us: 2.08 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.952 }
costs { name: "loop_convert_fusion.32" cost_us: 5.024 }
costs { name: "loop_divide_fusion" cost_us: 1.76 }
costs { name: "loop_multiply_fusion.14" cost_us: 2.209 }
costs { name: "loop_multiply_fusion.18" cost_us: 1.664 }
costs { name: "loop_multiply_fusion.19" cost_us: 1.92 }
costs { name: "loop_select_fusion.1" cost_us: 912.897 }
costs { name: "loop_select_fusion.2" cost_us: 910.656 }
costs { name: "loop_select_fusion.3" cost_us: 894.112 }
costs { name: "loop_select_fusion.4" cost_us: 262.752 }
costs { name: "loop_select_fusion.5" cost_us: 259.168 }
costs { name: "loop_select_fusion.6" cost_us: 1.887 }
costs { name: "loop_select_fusion.7" cost_us: 1.472 }
costs { name: "loop_select_fusion.8" cost_us: 1.984 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.633 }
costs { name: "loop_slice_fusion" cost_us: 225.055 }
costs { name: "loop_sqrt_fusion" cost_us: 2.368 }
costs { name: "loop_subtract_fusion" cost_us: 1.408 }
costs { name: "while.7.0" cost_us: 202.048 }
costs { name: "while.7.0" cost_us: 14558.438 }
costs { name: "while.7.0" cost_us: 5088.834 }
costs { name: "while.7.0" cost_us: 14725.67 }
costs { name: "while.7.0" cost_us: 1389.12 }
costs { name: "while.7.0" cost_us: 2831.137 }
costs { name: "while.7.0" cost_us: 1378.336 }
costs { name: "while.7.0" cost_us: 924.545 }
costs { name: "while.7.0" cost_us: 259.552 }
costs { name: "while.7.0" cost_us: 509.536 }
costs { name: "while.7.0" cost_us: 188.704 }
costs { name: "while.7.0" cost_us: 409.056 }
costs { name: "while.7.0" cost_us: 368.032 }
costs { name: "while.7.0" cost_us: 281.344 }
costs { name: "while.7.0" cost_us: 248.064 }
costs { name: "while.7.0" cost_us: 92.832 }
costs { name: "while.7.0" cost_us: 135.167 }
costs { name: "while.7.0" cost_us: 133.152 }
costs { name: "while.7.0" cost_us: 129.056 }
costs { name: "while.7.0" cost_us: 116.576 }
costs { name: "while.7.0" cost_us: 50.848 }
costs { name: "while.7.0" cost_us: 104.897 }
costs { name: "while.7.0" cost_us: 97.952 }
costs { name: "while.7.0" cost_us: 97.312 }
costs { name: "while.7.0" cost_us: 86.273 }
costs { name: "while.7.0" cost_us: 33.12 }
costs { name: "while.7.0" cost_us: 14.367 }
costs { name: "while.7.0" cost_us: 13.728 }
costs { name: "while.7.0" cost_us: 11.424 }
costs { name: "while.7.0" cost_us: 6.144 }
costs { name: "while.7.0" cost_us: 6.144 }
costs { name: "while.7.0" cost_us: 6.016 }
costs { name: "while.7.0" cost_us: 2.272 }
costs { name: "while.7.0" cost_us: 4.64 }
costs { name: "while.7.0" cost_us: 4.352 }
costs { name: "while.7.0" cost_us: 2.048 }
costs { name: "while.7.0" cost_us: 2.047 }
costs { name: "while.7.0" cost_us: 3.392 }
costs { name: "while.7.0" cost_us: 1.632 }
costs { name: "while.7.0" cost_us: 3.168 }
costs { name: "while.7.0" cost_us: 3.136 }
costs { name: "while.7.0" cost_us: 2.144 }
costs { name: "while.7.0" cost_us: 2.144 }
costs { name: "while.7.0" cost_us: 2.048 }
costs { name: "while.7.0" cost_us: 2.08 }
costs { name: "while.7.0" cost_us: 1.856 }
costs { name: "while.7.0" cost_us: 1.536 }
costs { name: "while.7.0" cost_us: 1.536 }
costs { name: "while.7.0" cost_us: 1.632 }
costs { name: "while.7.0" cost_us: 1.536 }
costs { name: "while.7.0" cost_us: 1.536 }
costs { name: "while.7.0" cost_us: 1.376 }
costs { name: "while.7.0" cost_us: 1.28 }
costs { name: "loop_add_fusion.14" cost_us: 1.952 }
costs { name: "input_add_reduce_fusion" cost_us: 127.328 }
costs { name: "input_add_reduce_fusion.13" cost_us: 128.576 }
costs { name: "input_add_reduce_fusion.double_buffer_clone" cost_us: 130.88 }
costs { name: "input_add_reduce_fusion.peeled_double_buffer" cost_us: 127.616 }
costs { name: "input_reduce_fusion" cost_us: 49.824 }
costs { name: "input_reduce_fusion.30" cost_us: 53.504 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 49.696 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 46.144 }
costs { name: "while.5.0" cost_us: 14558.088 }
costs { name: "while.5.0" cost_us: 5095.842 }
costs { name: "while.5.0" cost_us: 1383.873 }
costs { name: "while.5.0" cost_us: 1351.841 }
costs { name: "while.5.0" cost_us: 952.0 }
costs { name: "while.5.0" cost_us: 344.64 }
costs { name: "while.5.0" cost_us: 447.808 }
costs { name: "while.5.0" cost_us: 344.384 }
costs { name: "while.5.0" cost_us: 344.448 }
costs { name: "while.5.0" cost_us: 169.599 }
costs { name: "while.5.0" cost_us: 95.744 }
costs { name: "while.5.0" cost_us: 173.856 }
costs { name: "while.5.0" cost_us: 127.328 }
costs { name: "while.5.0" cost_us: 107.264 }
costs { name: "while.5.0" cost_us: 49.696 }
costs { name: "while.5.0" cost_us: 44.8 }
costs { name: "while.5.0" cost_us: 44.544 }
costs { name: "while.5.0" cost_us: 23.52 }
costs { name: "while.5.0" cost_us: 5.952 }
costs { name: "while.5.0" cost_us: 5.888 }
costs { name: "while.5.0" cost_us: 2.272 }
costs { name: "while.5.0" cost_us: 2.048 }
costs { name: "while.5.0" cost_us: 3.232 }
costs { name: "while.5.0" cost_us: 3.264 }
costs { name: "while.5.0" cost_us: 2.176 }
costs { name: "while.5.0" cost_us: 2.017 }
costs { name: "while.5.0" cost_us: 1.983 }
costs { name: "while.5.0" cost_us: 1.632 }
costs { name: "while.5.0" cost_us: 1.792 }
costs { name: "while.5.0" cost_us: 1.632 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.535 }
costs { name: "input_reduce_fusion.36" cost_us: 45.312 }
costs { name: "loop_multiply_fusion.11" cost_us: 97.728 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.176 }
costs { name: "wrapped_convert.1" cost_us: 1.952 }
costs { name: "wrapped_convert" cost_us: 6.4 }
costs { name: "custom-call.152.0" cost_us: 5697.858 }
costs { name: "loop_convert_fusion.19" cost_us: 337.92 }
costs { name: "input_transpose_fusion.5" cost_us: 5.728 }
costs { name: "custom-call.145.0" cost_us: 4790.947 }
costs { name: "input_transpose_fusion.12" cost_us: 4.224 }
costs { name: "input_transpose_fusion.6" cost_us: 6.528 }
costs { name: "loop_convert_fusion" cost_us: 6.496 }
costs { name: "loop_convert_fusion.1" cost_us: 6.111 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 5.952 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 6.816 }
costs { name: "loop_convert_fusion.2" cost_us: 6.112 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 6.016 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 6.816 }
costs { name: "loop_convert_fusion.26" cost_us: 7.136 }
costs { name: "loop_convert_fusion.27" cost_us: 6.528 }
costs { name: "loop_convert_fusion.3" cost_us: 3.392 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 3.264 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 3.488 }
costs { name: "loop_convert_fusion.31" cost_us: 3.52 }
costs { name: "loop_convert_fusion.4" cost_us: 3.36 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 3.232 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 4.0 }
costs { name: "loop_convert_fusion.40" cost_us: 2.176 }
costs { name: "loop_convert_fusion.41" cost_us: 2.336 }
costs { name: "loop_convert_fusion.48" cost_us: 2.303 }
costs { name: "loop_convert_fusion.49" cost_us: 2.016 }
costs { name: "loop_convert_fusion.5" cost_us: 2.304 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 2.272 }
costs { name: "loop_convert_fusion.6" cost_us: 2.336 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 2.304 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 2.464 }
costs { name: "loop_convert_fusion.7" cost_us: 2.112 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 2.144 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 2.016 }
costs { name: "loop_convert_fusion.8" cost_us: 2.048 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 2.112 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 2.049 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 5.888 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 6.88 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 344.384 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 344.448 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 344.64 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 345.121 }
costs { name: "loop_dynamic_update_slice_fusion.17" cost_us: 358.656 }
costs { name: "loop_dynamic_update_slice_fusion.18" cost_us: 1.856 }
costs { name: "loop_dynamic_update_slice_fusion.19" cost_us: 111.904 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 344.8 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 344.704 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 345.376 }
costs { name: "loop_dynamic_update_slice_fusion.20" cost_us: 46.816 }
costs { name: "loop_dynamic_update_slice_fusion.21" cost_us: 46.592 }
costs { name: "loop_dynamic_update_slice_fusion.22" cost_us: 358.528 }
costs { name: "loop_dynamic_update_slice_fusion.23" cost_us: 366.304 }
costs { name: "loop_dynamic_update_slice_fusion.24" cost_us: 366.24 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 1.984 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 1.983 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 1.664 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 109.76 }
costs { name: "loop_dynamic_update_slice_fusion.4.double_buffer_clone" cost_us: 107.264 }
costs { name: "loop_dynamic_update_slice_fusion.4.peeled_double_buffer" cost_us: 113.632 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 44.544 }
costs { name: "loop_dynamic_update_slice_fusion.5.double_buffer_clone" cost_us: 44.608 }
costs { name: "loop_dynamic_update_slice_fusion.5.peeled_double_buffer" cost_us: 44.704 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 44.832 }
costs { name: "loop_dynamic_update_slice_fusion.6.double_buffer_clone" cost_us: 44.8 }
costs { name: "loop_dynamic_update_slice_fusion.6.peeled_double_buffer" cost_us: 44.704 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 345.12 }
costs { name: "loop_dynamic_update_slice_fusion.7.double_buffer_clone" cost_us: 344.64 }
costs { name: "loop_dynamic_update_slice_fusion.7.peeled_double_buffer" cost_us: 345.28 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 344.8 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 345.536 }
costs { name: "copy_fusion.2" cost_us: 1.664 }
costs { name: "loop_add_fusion" cost_us: 1.664 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_multiply_fusion" cost_us: 447.808 }
costs { name: "loop_multiply_fusion.7" cost_us: 448.16 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 447.872 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 453.696 }
costs { name: "custom-call.150.0" cost_us: 5129.794 }
costs { name: "custom-call.52.0" cost_us: 5095.842 }
costs { name: "custom-call.52.0.double_buffer_clone" cost_us: 5099.394 }
costs { name: "custom-call.52.0.peeled_double_buffer" cost_us: 5108.61 }
costs { name: "custom-call.151.0" cost_us: 5137.314 }
costs { name: "custom-call.53.0" cost_us: 5102.882 }
costs { name: "custom-call.53.0.double_buffer_clone" cost_us: 5097.538 }
costs { name: "custom-call.53.0.peeled_double_buffer" cost_us: 5128.865 }
costs { name: "cublas-gemm.2.0" cost_us: 4836.289 }
costs { name: "cublas-gemm.2.0.double_buffer_clone" cost_us: 4826.594 }
costs { name: "cublas-gemm.2.0.peeled_double_buffer" cost_us: 4846.946 }
costs { name: "cublas-gemm.23.0" cost_us: 4868.322 }
costs { name: "loop_multiply_fusion.1" cost_us: 96.8 }
costs { name: "loop_multiply_fusion.1.double_buffer_clone" cost_us: 97.92 }
costs { name: "loop_multiply_fusion.1.peeled_double_buffer" cost_us: 98.464 }
costs { name: "loop_multiply_fusion.12" cost_us: 98.24 }
costs { name: "loop_rsqrt_fusion" cost_us: 2.017 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.208 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 2.112 }
costs { name: "loop_multiply_fusion.13" cost_us: 96.96 }
costs { name: "loop_multiply_fusion.2" cost_us: 95.744 }
costs { name: "loop_multiply_fusion.2.double_buffer_clone" cost_us: 95.84 }
costs { name: "loop_multiply_fusion.2.peeled_double_buffer" cost_us: 95.808 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.176 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 2.176 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.8" cost_us: 2.208 }
costs { name: "custom-call.34.0" cost_us: 960.225 }
costs { name: "custom-call.34.0" cost_us: 1.792 }
costs { name: "custom-call.34.0.double_buffer_clone" cost_us: 952.0 }
costs { name: "custom-call.34.0.double_buffer_clone" cost_us: 1.792 }
costs { name: "custom-call.34.0.peeled_double_buffer" cost_us: 961.216 }
costs { name: "custom-call.34.0.peeled_double_buffer" cost_us: 1.856 }
costs { name: "custom-call.35.0" cost_us: 977.952 }
costs { name: "custom-call.35.0" cost_us: 1.888 }
costs { name: "loop_broadcast_fusion" cost_us: 1.535 }
costs { name: "loop_broadcast_fusion.6" cost_us: 1.344 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.536 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.376 }
costs { name: "loop_multiply_fusion.3" cost_us: 1.632 }
costs { name: "loop_multiply_fusion.3.double_buffer_clone" cost_us: 1.632 }
costs { name: "loop_multiply_fusion.3.peeled_double_buffer" cost_us: 1.664 }
costs { name: "input_concatenate_fusion" cost_us: 174.24 }
costs { name: "input_concatenate_fusion.2" cost_us: 175.808 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 173.856 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 174.047 }
costs { name: "input_concatenate_fusion.1" cost_us: 23.52 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 23.52 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 23.327 }
costs { name: "input_concatenate_fusion.3" cost_us: 23.936 }
costs { name: "custom-call.147.0" cost_us: 172.416 }
costs { name: "custom-call.48.0" cost_us: 173.024 }
costs { name: "custom-call.48.0.double_buffer_clone" cost_us: 171.904 }
costs { name: "custom-call.48.0.peeled_double_buffer" cost_us: 174.368 }
costs { name: "custom-call.148.0" cost_us: 175.585 }
costs { name: "custom-call.49.0" cost_us: 170.784 }
costs { name: "custom-call.49.0.double_buffer_clone" cost_us: 169.599 }
costs { name: "custom-call.49.0.peeled_double_buffer" cost_us: 174.528 }
costs { name: "custom-call.149.0" cost_us: 1387.808 }
costs { name: "custom-call.50.0" cost_us: 1385.281 }
costs { name: "custom-call.50.0.double_buffer_clone" cost_us: 1383.873 }
costs { name: "custom-call.50.0.peeled_double_buffer" cost_us: 1412.609 }
costs { name: "custom-call.146.0" cost_us: 1359.489 }
costs { name: "custom-call.47.0" cost_us: 1351.841 }
costs { name: "custom-call.47.0.double_buffer_clone" cost_us: 1352.672 }
costs { name: "custom-call.47.0.peeled_double_buffer" cost_us: 1356.545 }
costs { name: "loop_convert_fusion.33" cost_us: 4.608 }
costs { name: "loop_power_fusion.1" cost_us: 1.568 }
costs { name: "all-reduce-start.2" cost_us: 920.641 }
costs { name: "all-reduce-start.4" cost_us: 433.632 }
costs { name: "all-reduce-start.6" cost_us: 937.504 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 509.536 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 513.856 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 513.696 }
costs { name: "input_add_multiply_reduce_fusion.3" cost_us: 521.536 }
costs { name: "input_add_multiply_reduce_fusion.double_buffer_clone" cost_us: 512.0 }
costs { name: "input_add_multiply_reduce_fusion.peeled_double_buffer" cost_us: 519.937 }
costs { name: "input_add_reduce_fusion.17" cost_us: 282.848 }
costs { name: "input_add_reduce_fusion.18" cost_us: 279.296 }
costs { name: "input_add_reduce_fusion.19" cost_us: 287.776 }
costs { name: "input_add_reduce_fusion.2" cost_us: 281.344 }
costs { name: "input_add_reduce_fusion.2.double_buffer_clone" cost_us: 283.456 }
costs { name: "input_add_reduce_fusion.2.peeled_double_buffer" cost_us: 289.696 }
costs { name: "input_reduce_fusion.3" cost_us: 6.08 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 6.016 }
costs { name: "input_reduce_fusion.3.peeled_double_buffer" cost_us: 6.208 }
costs { name: "input_reduce_fusion.41" cost_us: 3.936 }
costs { name: "input_reduce_fusion.42" cost_us: 3.648 }
costs { name: "input_reduce_fusion.43" cost_us: 6.24 }
costs { name: "input_reduce_fusion.44" cost_us: 3.584 }
costs { name: "input_reduce_fusion.45" cost_us: 3.584 }
costs { name: "loop_multiply_fusion.15" cost_us: 2.272 }
costs { name: "loop_multiply_fusion.16" cost_us: 2.08 }
costs { name: "loop_multiply_fusion.17" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.464 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.3" cost_us: 2.207 }
costs { name: "input_reduce_fusion.46" cost_us: 3.776 }
costs { name: "wrapped_slice.30" cost_us: 1.824 }
costs { name: "custom-call.153.0" cost_us: 5413.186 }
costs { name: "custom-call.196.0" cost_us: 5619.106 }
costs { name: "custom-call.197.0" cost_us: 5940.162 }
costs { name: "input_transpose_fusion.13" cost_us: 3.808 }
costs { name: "input_transpose_fusion.14" cost_us: 3.584 }
costs { name: "input_transpose_fusion.15" cost_us: 3.52 }
costs { name: "input_transpose_fusion.7" cost_us: 6.208 }
costs { name: "input_transpose_fusion.8" cost_us: 6.304 }
costs { name: "input_transpose_fusion.9" cost_us: 6.208 }
costs { name: "loop_convert_fusion.10" cost_us: 6.4 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 6.144 }
costs { name: "loop_convert_fusion.10.peeled_double_buffer" cost_us: 6.24 }
costs { name: "loop_convert_fusion.11" cost_us: 6.176 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 6.177 }
costs { name: "loop_convert_fusion.11.peeled_double_buffer" cost_us: 6.432 }
costs { name: "loop_convert_fusion.12" cost_us: 3.168 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 3.232 }
costs { name: "loop_convert_fusion.12.peeled_double_buffer" cost_us: 3.712 }
costs { name: "loop_convert_fusion.13" cost_us: 3.168 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 3.136 }
costs { name: "loop_convert_fusion.13.peeled_double_buffer" cost_us: 3.616 }
costs { name: "loop_convert_fusion.15" cost_us: 2.272 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 2.528 }
costs { name: "loop_convert_fusion.15.peeled_double_buffer" cost_us: 2.465 }
costs { name: "loop_convert_fusion.16" cost_us: 2.368 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 2.368 }
costs { name: "loop_convert_fusion.16.peeled_double_buffer" cost_us: 2.495 }
costs { name: "loop_convert_fusion.17" cost_us: 2.048 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 2.047 }
costs { name: "loop_convert_fusion.17.peeled_double_buffer" cost_us: 2.496 }
costs { name: "loop_convert_fusion.18" cost_us: 2.08 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 2.144 }
costs { name: "loop_convert_fusion.18.peeled_double_buffer" cost_us: 2.368 }
costs { name: "loop_convert_fusion.20" cost_us: 5.92 }
costs { name: "loop_convert_fusion.21" cost_us: 6.4 }
costs { name: "loop_convert_fusion.22" cost_us: 6.56 }
costs { name: "loop_convert_fusion.23" cost_us: 6.176 }
costs { name: "loop_convert_fusion.24" cost_us: 6.528 }
costs { name: "loop_convert_fusion.25" cost_us: 6.24 }
costs { name: "loop_convert_fusion.28" cost_us: 3.36 }
costs { name: "loop_convert_fusion.29" cost_us: 3.232 }
costs { name: "loop_convert_fusion.30" cost_us: 3.264 }
costs { name: "loop_convert_fusion.34" cost_us: 2.336 }
costs { name: "loop_convert_fusion.35" cost_us: 2.24 }
costs { name: "loop_convert_fusion.36" cost_us: 2.496 }
costs { name: "loop_convert_fusion.37" cost_us: 2.368 }
costs { name: "loop_convert_fusion.38" cost_us: 2.272 }
costs { name: "loop_convert_fusion.39" cost_us: 2.304 }
costs { name: "loop_convert_fusion.42" cost_us: 2.624 }
costs { name: "loop_convert_fusion.43" cost_us: 2.624 }
costs { name: "loop_convert_fusion.44" cost_us: 2.592 }
costs { name: "loop_convert_fusion.45" cost_us: 2.209 }
costs { name: "loop_convert_fusion.46" cost_us: 2.432 }
costs { name: "loop_convert_fusion.47" cost_us: 2.56 }
costs { name: "loop_convert_fusion.9" cost_us: 6.368 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 6.144 }
costs { name: "loop_convert_fusion.9.peeled_double_buffer" cost_us: 6.048 }
costs { name: "loop_dynamic_slice_fusion.10" cost_us: 2.176 }
costs { name: "loop_dynamic_slice_fusion.11" cost_us: 94.784 }
costs { name: "loop_dynamic_slice_fusion.6" cost_us: 3.712 }
costs { name: "loop_dynamic_slice_fusion.7" cost_us: 95.168 }
costs { name: "loop_dynamic_slice_fusion.8" cost_us: 13.857 }
costs { name: "loop_dynamic_slice_fusion.9" cost_us: 14.016 }
costs { name: "loop_pad_fusion" cost_us: 434.913 }
costs { name: "loop_pad_fusion.1" cost_us: 434.785 }
costs { name: "loop_pad_fusion.2" cost_us: 436.577 }
costs { name: "loop_pad_fusion.3" cost_us: 112.193 }
costs { name: "loop_pad_fusion.4" cost_us: 112.095 }
costs { name: "loop_pad_fusion.5" cost_us: 16.64 }
costs { name: "loop_pad_fusion.6" cost_us: 16.704 }
costs { name: "loop_select_fusion" cost_us: 1.536 }
costs { name: "loop_select_fusion.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_select_fusion.peeled_double_buffer" cost_us: 2.048 }
costs { name: "copy_fusion" cost_us: 2.049 }
costs { name: "loop_add_fusion.4" cost_us: 1.856 }
costs { name: "loop_add_fusion.4.double_buffer_clone" cost_us: 1.536 }
costs { name: "input_transpose_fusion.3" cost_us: 4.736 }
costs { name: "input_transpose_fusion.4" cost_us: 4.736 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 409.056 }
costs { name: "loop_dynamic_update_slice_fusion.9.double_buffer_clone" cost_us: 409.761 }
costs { name: "loop_dynamic_update_slice_fusion.9.peeled_double_buffer" cost_us: 414.144 }
costs { name: "input_transpose_fusion.10" cost_us: 3.04 }
costs { name: "input_transpose_fusion.11" cost_us: 2.976 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 116.576 }
costs { name: "loop_dynamic_update_slice_fusion.8.double_buffer_clone" cost_us: 117.248 }
costs { name: "loop_dynamic_update_slice_fusion.8.peeled_double_buffer" cost_us: 122.752 }
costs { name: "copy_fusion.1" cost_us: 1.664 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 1.664 }
costs { name: "loop_dynamic_update_slice_fusion.15.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 1.632 }
costs { name: "loop_dynamic_update_slice_fusion.16.double_buffer_clone" cost_us: 1.633 }
costs { name: "loop_pad_fusion.7" cost_us: 5.856 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 11.84 }
costs { name: "loop_dynamic_update_slice_fusion.10.double_buffer_clone" cost_us: 11.712 }
costs { name: "loop_dynamic_update_slice_fusion.10.peeled_double_buffer" cost_us: 11.712 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 11.424 }
costs { name: "loop_dynamic_update_slice_fusion.11.double_buffer_clone" cost_us: 11.456 }
costs { name: "loop_dynamic_update_slice_fusion.11.peeled_double_buffer" cost_us: 11.776 }
costs { name: "reduce-scatter.45.1" cost_us: 5085.41 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 4.8 }
costs { name: "loop_dynamic_update_slice_fusion.12.double_buffer_clone" cost_us: 4.352 }
costs { name: "loop_dynamic_update_slice_fusion.12.peeled_double_buffer" cost_us: 4.928 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 2.24 }
costs { name: "loop_dynamic_update_slice_fusion.13.double_buffer_clone" cost_us: 2.304 }
costs { name: "loop_dynamic_update_slice_fusion.13.peeled_double_buffer" cost_us: 2.24 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 2.048 }
costs { name: "loop_dynamic_update_slice_fusion.14.double_buffer_clone" cost_us: 2.208 }
costs { name: "loop_dynamic_update_slice_fusion.14.peeled_double_buffer" cost_us: 2.24 }
costs { name: "loop_add_multiply_fusion" cost_us: 924.545 }
costs { name: "loop_add_multiply_fusion.1" cost_us: 926.752 }
costs { name: "loop_add_multiply_fusion.2" cost_us: 938.88 }
costs { name: "loop_add_multiply_fusion.3" cost_us: 938.048 }
costs { name: "loop_add_multiply_fusion.double_buffer_clone" cost_us: 925.089 }
costs { name: "loop_add_multiply_fusion.peeled_double_buffer" cost_us: 930.496 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.144 }
costs { name: "loop_multiply_fusion.5.double_buffer_clone" cost_us: 2.08 }
costs { name: "loop_multiply_fusion.5.peeled_double_buffer" cost_us: 2.336 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.208 }
costs { name: "loop_multiply_rsqrt_fusion.double_buffer_clone" cost_us: 2.144 }
costs { name: "loop_multiply_rsqrt_fusion.peeled_double_buffer" cost_us: 2.176 }
costs { name: "custom-call.157.0" cost_us: 4803.202 }
costs { name: "custom-call.164.0" cost_us: 4848.674 }
costs { name: "custom-call.188.0" cost_us: 4851.041 }
costs { name: "custom-call.74.0" cost_us: 4848.097 }
costs { name: "custom-call.74.0.double_buffer_clone" cost_us: 4845.346 }
costs { name: "custom-call.74.0.peeled_double_buffer" cost_us: 4847.394 }
costs { name: "custom-call.168.0" cost_us: 5089.186 }
costs { name: "custom-call.175.0" cost_us: 5401.506 }
costs { name: "custom-call.185.0" cost_us: 5284.738 }
costs { name: "custom-call.78.0" cost_us: 5129.73 }
costs { name: "custom-call.78.0.double_buffer_clone" cost_us: 5142.466 }
costs { name: "custom-call.78.0.peeled_double_buffer" cost_us: 5300.098 }
costs { name: "cublas-gemm.24.0" cost_us: 4866.37 }
costs { name: "cublas-gemm.26.0" cost_us: 4917.506 }
costs { name: "cublas-gemm.28.0" cost_us: 4905.698 }
costs { name: "cublas-gemm.7.0" cost_us: 4894.69 }
costs { name: "cublas-gemm.7.0.double_buffer_clone" cost_us: 4895.425 }
costs { name: "cublas-gemm.7.0.peeled_double_buffer" cost_us: 4933.09 }
costs { name: "custom-call.169.0" cost_us: 5061.474 }
costs { name: "custom-call.176.0" cost_us: 5358.626 }
costs { name: "custom-call.186.0" cost_us: 5273.986 }
costs { name: "custom-call.79.0" cost_us: 5123.618 }
costs { name: "custom-call.79.0.double_buffer_clone" cost_us: 5123.906 }
costs { name: "custom-call.79.0.peeled_double_buffer" cost_us: 5301.186 }
costs { name: "custom-call.155.0" cost_us: 5182.209 }
costs { name: "custom-call.162.0" cost_us: 5141.57 }
costs { name: "custom-call.183.0" cost_us: 5190.306 }
costs { name: "custom-call.72.0" cost_us: 5134.018 }
costs { name: "custom-call.72.0.double_buffer_clone" cost_us: 5120.258 }
costs { name: "custom-call.72.0.peeled_double_buffer" cost_us: 5141.09 }
costs { name: "custom-call.170.0" cost_us: 5087.779 }
costs { name: "custom-call.177.0" cost_us: 5354.403 }
costs { name: "custom-call.187.0" cost_us: 5157.731 }
costs { name: "custom-call.80.0" cost_us: 5083.01 }
costs { name: "custom-call.80.0.double_buffer_clone" cost_us: 5051.619 }
costs { name: "custom-call.80.0.peeled_double_buffer" cost_us: 5307.97 }
costs { name: "all-reduce-start" cost_us: 408.352 }
costs { name: "all-reduce-start.1" cost_us: 259.552 }
costs { name: "all-reduce-start.3" cost_us: 479.36 }
costs { name: "all-reduce-start.7" cost_us: 1007.073 }
costs { name: "wrapped_slice.10" cost_us: 1.696 }
costs { name: "wrapped_slice.12" cost_us: 1.44 }
costs { name: "wrapped_slice.15" cost_us: 1.632 }
costs { name: "wrapped_slice.16" cost_us: 1.952 }
costs { name: "wrapped_slice.26" cost_us: 1.248 }
costs { name: "wrapped_slice.27" cost_us: 1.888 }
costs { name: "all-reduce-start.5" cost_us: 2920.193 }
costs { name: "wrapped_slice.11" cost_us: 1.696 }
costs { name: "wrapped_slice.13" cost_us: 1.696 }
costs { name: "wrapped_slice.14" cost_us: 1.536 }
costs { name: "wrapped_slice.17" cost_us: 1.888 }
costs { name: "wrapped_slice.24" cost_us: 1.824 }
costs { name: "wrapped_slice.25" cost_us: 1.824 }
costs { name: "custom-call.32.0" cost_us: 2879.105 }
costs { name: "custom-call.32.0" cost_us: 134.976 }
costs { name: "custom-call.32.0" cost_us: 51.264 }
costs { name: "custom-call.32.0" cost_us: 97.984 }
costs { name: "custom-call.37.0" cost_us: 2953.249 }
costs { name: "custom-call.37.0" cost_us: 136.128 }
costs { name: "custom-call.37.0" cost_us: 51.647 }
costs { name: "custom-call.37.0" cost_us: 98.464 }
costs { name: "custom-call.38.0" cost_us: 2888.769 }
costs { name: "custom-call.38.0" cost_us: 135.488 }
costs { name: "custom-call.38.0" cost_us: 51.2 }
costs { name: "custom-call.38.0" cost_us: 99.392 }
costs { name: "custom-call.39.0" cost_us: 2856.417 }
costs { name: "custom-call.39.0" cost_us: 135.167 }
costs { name: "custom-call.39.0" cost_us: 50.977 }
costs { name: "custom-call.39.0" cost_us: 97.439 }
costs { name: "custom-call.39.0.double_buffer_clone" cost_us: 2831.137 }
costs { name: "custom-call.39.0.double_buffer_clone" cost_us: 135.168 }
costs { name: "custom-call.39.0.double_buffer_clone" cost_us: 50.848 }
costs { name: "custom-call.39.0.double_buffer_clone" cost_us: 97.312 }
costs { name: "custom-call.39.0.peeled_double_buffer" cost_us: 2981.121 }
costs { name: "custom-call.39.0.peeled_double_buffer" cost_us: 135.905 }
costs { name: "custom-call.39.0.peeled_double_buffer" cost_us: 51.232 }
costs { name: "custom-call.39.0.peeled_double_buffer" cost_us: 98.272 }
costs { name: "loop_multiply_fusion.6" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.6.double_buffer_clone" cost_us: 1.312 }
costs { name: "loop_multiply_fusion.6.peeled_double_buffer" cost_us: 1.696 }
costs { name: "loop_add_fusion.2" cost_us: 249.92 }
costs { name: "loop_add_fusion.2.double_buffer_clone" cost_us: 248.064 }
costs { name: "loop_add_fusion.2.peeled_double_buffer" cost_us: 260.128 }
costs { name: "loop_add_fusion.6" cost_us: 256.0 }
costs { name: "loop_add_fusion.7" cost_us: 258.464 }
costs { name: "loop_add_fusion.8" cost_us: 252.448 }
costs { name: "loop_add_fusion.10" cost_us: 34.72 }
costs { name: "loop_add_fusion.11" cost_us: 33.664 }
costs { name: "loop_add_fusion.3" cost_us: 33.44 }
costs { name: "loop_add_fusion.3.double_buffer_clone" cost_us: 33.12 }
costs { name: "loop_add_fusion.3.peeled_double_buffer" cost_us: 34.72 }
costs { name: "loop_add_fusion.9" cost_us: 34.24 }
costs { name: "custom-call.171.0" cost_us: 174.752 }
costs { name: "custom-call.178.0" cost_us: 218.464 }
costs { name: "custom-call.192.0" cost_us: 178.335 }
costs { name: "custom-call.81.0" cost_us: 202.048 }
costs { name: "custom-call.81.0.double_buffer_clone" cost_us: 202.753 }
costs { name: "custom-call.81.0.peeled_double_buffer" cost_us: 216.096 }
costs { name: "custom-call.159.0" cost_us: 189.248 }
costs { name: "custom-call.166.0" cost_us: 191.296 }
costs { name: "custom-call.190.0" cost_us: 190.913 }
costs { name: "custom-call.76.0" cost_us: 189.792 }
costs { name: "custom-call.76.0.double_buffer_clone" cost_us: 188.704 }
costs { name: "custom-call.76.0.peeled_double_buffer" cost_us: 193.888 }
costs { name: "custom-call.174.0" cost_us: 182.688 }
costs { name: "custom-call.181.0" cost_us: 215.904 }
costs { name: "custom-call.195.0" cost_us: 175.072 }
costs { name: "custom-call.84.0" cost_us: 204.096 }
costs { name: "custom-call.84.0.double_buffer_clone" cost_us: 205.792 }
costs { name: "custom-call.84.0.peeled_double_buffer" cost_us: 209.984 }
costs { name: "cublas-gemm.25.0" cost_us: 225.728 }
costs { name: "cublas-gemm.27.0" cost_us: 225.504 }
costs { name: "cublas-gemm.29.0" cost_us: 224.32 }
costs { name: "cublas-gemm.8.0" cost_us: 222.208 }
costs { name: "cublas-gemm.8.0.double_buffer_clone" cost_us: 222.273 }
costs { name: "cublas-gemm.8.0.peeled_double_buffer" cost_us: 226.208 }
costs { name: "custom-call.172.0" cost_us: 1467.073 }
costs { name: "custom-call.179.0" cost_us: 1553.217 }
costs { name: "custom-call.193.0" cost_us: 1460.673 }
costs { name: "custom-call.82.0" cost_us: 1450.688 }
costs { name: "custom-call.82.0.double_buffer_clone" cost_us: 1452.032 }
costs { name: "custom-call.82.0.peeled_double_buffer" cost_us: 1538.113 }
costs { name: "custom-call.158.0" cost_us: 1368.352 }
costs { name: "custom-call.165.0" cost_us: 1378.305 }
costs { name: "custom-call.189.0" cost_us: 1381.088 }
costs { name: "custom-call.75.0" cost_us: 1378.336 }
costs { name: "custom-call.75.0.double_buffer_clone" cost_us: 1378.625 }
costs { name: "custom-call.75.0.peeled_double_buffer" cost_us: 1380.257 }
costs { name: "custom-call.173.0" cost_us: 1459.488 }
costs { name: "custom-call.180.0" cost_us: 1552.449 }
costs { name: "custom-call.194.0" cost_us: 1457.185 }
costs { name: "custom-call.83.0" cost_us: 1406.561 }
costs { name: "custom-call.83.0.double_buffer_clone" cost_us: 1424.992 }
costs { name: "custom-call.83.0.peeled_double_buffer" cost_us: 1532.705 }
costs { name: "custom-call.160.0" cost_us: 1433.633 }
costs { name: "custom-call.167.0" cost_us: 1492.64 }
costs { name: "custom-call.191.0" cost_us: 1438.752 }
costs { name: "custom-call.77.0" cost_us: 1396.673 }
costs { name: "custom-call.77.0.double_buffer_clone" cost_us: 1389.12 }
costs { name: "custom-call.77.0.peeled_double_buffer" cost_us: 1479.809 }
costs { name: "custom-call.154.0" cost_us: 5123.362 }
costs { name: "custom-call.161.0" cost_us: 5116.131 }
costs { name: "custom-call.182.0" cost_us: 5134.21 }
costs { name: "custom-call.71.0" cost_us: 5097.154 }
costs { name: "custom-call.71.0.double_buffer_clone" cost_us: 5091.489 }
costs { name: "custom-call.71.0.peeled_double_buffer" cost_us: 5118.402 }
costs { name: "custom-call.156.0" cost_us: 5112.61 }
costs { name: "custom-call.163.0" cost_us: 5116.066 }
costs { name: "custom-call.184.0" cost_us: 5142.914 }
costs { name: "custom-call.73.0" cost_us: 5088.834 }
costs { name: "custom-call.73.0.double_buffer_clone" cost_us: 5097.506 }
costs { name: "custom-call.73.0.peeled_double_buffer" cost_us: 5127.714 }
costs { name: "loop_multiply_fusion.10" cost_us: 101.28 }
costs { name: "loop_multiply_fusion.4" cost_us: 98.592 }
costs { name: "loop_multiply_fusion.4.double_buffer_clone" cost_us: 97.952 }
costs { name: "loop_multiply_fusion.4.peeled_double_buffer" cost_us: 99.328 }
costs { name: "loop_multiply_fusion.8" cost_us: 100.288 }
costs { name: "loop_multiply_fusion.9" cost_us: 97.313 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.176 }
costs { name: "loop_rsqrt_fusion.2.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.2.peeled_double_buffer" cost_us: 2.176 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.336 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.113 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.272 }
costs { name: "loop_convert_fusion.14" cost_us: 4.64 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 4.672 }
costs { name: "loop_convert_fusion.14.peeled_double_buffer" cost_us: 4.833 }
costs { name: "loop_power_fusion" cost_us: 1.376 }
costs { name: "loop_power_fusion.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_power_fusion.peeled_double_buffer" cost_us: 1.889 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 2.144 }
costs { name: "loop_dynamic_slice_fusion.4.double_buffer_clone" cost_us: 2.24 }
costs { name: "loop_dynamic_slice_fusion.4.peeled_double_buffer" cost_us: 2.08 }
costs { name: "wrapped_slice.3" cost_us: 1.984 }
costs { name: "wrapped_slice.8" cost_us: 1.536 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 95.552 }
costs { name: "loop_dynamic_slice_fusion.1.double_buffer_clone" cost_us: 93.888 }
costs { name: "loop_dynamic_slice_fusion.1.peeled_double_buffer" cost_us: 95.776 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 94.784 }
costs { name: "loop_dynamic_slice_fusion.5.double_buffer_clone" cost_us: 92.832 }
costs { name: "loop_dynamic_slice_fusion.5.peeled_double_buffer" cost_us: 94.144 }
costs { name: "wrapped_slice" cost_us: 92.737 }
costs { name: "wrapped_slice.4" cost_us: 92.449 }
costs { name: "wrapped_slice.5" cost_us: 93.696 }
costs { name: "wrapped_slice.9" cost_us: 93.76 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 13.728 }
costs { name: "loop_dynamic_slice_fusion.2.double_buffer_clone" cost_us: 14.144 }
costs { name: "loop_dynamic_slice_fusion.2.peeled_double_buffer" cost_us: 14.208 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 13.792 }
costs { name: "loop_dynamic_slice_fusion.3.double_buffer_clone" cost_us: 14.016 }
costs { name: "loop_dynamic_slice_fusion.3.peeled_double_buffer" cost_us: 14.304 }
costs { name: "wrapped_slice.1" cost_us: 13.856 }
costs { name: "wrapped_slice.2" cost_us: 13.76 }
costs { name: "wrapped_slice.6" cost_us: 13.024 }
costs { name: "wrapped_slice.7" cost_us: 12.992 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 3.392 }
costs { name: "loop_dynamic_slice_fusion.double_buffer_clone" cost_us: 3.392 }
costs { name: "loop_dynamic_slice_fusion.peeled_double_buffer" cost_us: 3.072 }
costs { name: "loop_divide_fusion" cost_us: 1.568 }
costs { name: "wrapped_transpose.2" cost_us: 391.52 }
costs { name: "wrapped_transpose.3" cost_us: 391.264 }
costs { name: "wrapped_transpose.4" cost_us: 421.281 }
costs { name: "wrapped_transpose.1" cost_us: 4.256 }
costs { name: "wrapped_transpose" cost_us: 3.392 }
costs { name: "wrapped_transpose.5" cost_us: 16.096 }
costs { name: "wrapped_transpose.6" cost_us: 453.248 }
costs { name: "wrapped_transpose.7" cost_us: 114.72 }
costs { name: "wrapped_transpose.8" cost_us: 16.128 }
