costs { name: "all-gather-start" cost_us: 11496.912 }
costs { name: "all-gather-start.1" cost_us: 12168.657 }
costs { name: "all-gather-start.2" cost_us: 11463.604 }
costs { name: "all-gather-start.4" cost_us: 14782.504 }
costs { name: "all-gather-start.5" cost_us: 12922.156 }
costs { name: "all-gather-start.6" cost_us: 11400.562 }
costs { name: "all-gather-start.7" cost_us: 12288.013 }
costs { name: "all-reduce-start" cost_us: 2106.2 }
costs { name: "all-reduce-start.13" cost_us: 2703.125 }
costs { name: "all-reduce-start.6" cost_us: 3097.972 }
costs { name: "all-reduce-start.9" cost_us: 3163.572 }
costs { name: "input_slice_fusion" cost_us: 1.664 }
costs { name: "input_transpose_fusion.21" cost_us: 9.344 }
costs { name: "input_transpose_fusion.22" cost_us: 14.144 }
costs { name: "loop_broadcast_fusion" cost_us: 1.536 }
costs { name: "loop_broadcast_fusion.10" cost_us: 7526.019 }
costs { name: "loop_broadcast_fusion.2" cost_us: 367.838 }
costs { name: "loop_broadcast_fusion.3" cost_us: 194.879 }
costs { name: "loop_broadcast_fusion.4" cost_us: 2.848 }
costs { name: "loop_broadcast_fusion.5" cost_us: 14.24 }
costs { name: "loop_broadcast_fusion.6" cost_us: 53.248 }
costs { name: "loop_broadcast_fusion.7" cost_us: 52.8 }
costs { name: "loop_broadcast_fusion.8" cost_us: 1672.986 }
costs { name: "loop_broadcast_fusion.9" cost_us: 7530.179 }
costs { name: "loop_compare_fusion.1" cost_us: 1.504 }
costs { name: "reduce-scatter-start" cost_us: 15812.708 }
costs { name: "reduce-scatter-start.1" cost_us: 18047.607 }
costs { name: "reduce-scatter-start.2" cost_us: 15857.282 }
costs { name: "reduce-scatter-start.3" cost_us: 8321.889 }
costs { name: "wrapped_concatenate" cost_us: 10.496 }
costs { name: "wrapped_concatenate.1" cost_us: 2.112 }
costs { name: "wrapped_concatenate.10" cost_us: 10.528 }
costs { name: "wrapped_concatenate.11" cost_us: 1.856 }
costs { name: "wrapped_concatenate.12" cost_us: 1.856 }
costs { name: "wrapped_concatenate.13" cost_us: 1.664 }
costs { name: "wrapped_concatenate.14" cost_us: 2.208 }
costs { name: "wrapped_concatenate.2" cost_us: 1.632 }
costs { name: "wrapped_concatenate.3" cost_us: 10.4 }
costs { name: "wrapped_concatenate.4" cost_us: 1.471 }
costs { name: "wrapped_concatenate.5" cost_us: 1.855 }
costs { name: "wrapped_concatenate.6" cost_us: 1.632 }
costs { name: "wrapped_concatenate.7" cost_us: 2.24 }
costs { name: "wrapped_concatenate.8" cost_us: 1.632 }
costs { name: "wrapped_concatenate.9" cost_us: 14.72 }
costs { name: "wrapped_convert.10" cost_us: 1.632 }
costs { name: "wrapped_convert.11" cost_us: 1.76 }
costs { name: "wrapped_convert.12" cost_us: 1.472 }
costs { name: "wrapped_convert.13" cost_us: 1.568 }
costs { name: "wrapped_convert.14" cost_us: 1.568 }
costs { name: "wrapped_convert.15" cost_us: 1.536 }
costs { name: "wrapped_convert.16" cost_us: 1.44 }
costs { name: "wrapped_convert.17" cost_us: 1.44 }
costs { name: "wrapped_convert.18" cost_us: 1.44 }
costs { name: "wrapped_convert.19" cost_us: 1.6 }
costs { name: "wrapped_convert.2" cost_us: 1.664 }
costs { name: "wrapped_convert.20" cost_us: 1.535 }
costs { name: "wrapped_convert.21" cost_us: 1.375 }
costs { name: "wrapped_convert.22" cost_us: 1.376 }
costs { name: "wrapped_convert.23" cost_us: 1.568 }
costs { name: "wrapped_convert.24" cost_us: 1.727 }
costs { name: "wrapped_convert.25" cost_us: 1.568 }
costs { name: "wrapped_convert.26" cost_us: 1.376 }
costs { name: "wrapped_convert.27" cost_us: 1.727 }
costs { name: "wrapped_convert.28" cost_us: 1.375 }
costs { name: "wrapped_convert.29" cost_us: 1.6 }
costs { name: "wrapped_convert.3" cost_us: 1.632 }
costs { name: "wrapped_convert.30" cost_us: 1.376 }
costs { name: "wrapped_convert.31" cost_us: 1.216 }
costs { name: "wrapped_convert.32" cost_us: 1.375 }
costs { name: "wrapped_convert.33" cost_us: 1.376 }
costs { name: "wrapped_convert.34" cost_us: 1.247 }
costs { name: "wrapped_convert.35" cost_us: 1.216 }
costs { name: "wrapped_convert.36" cost_us: 1.215 }
costs { name: "wrapped_convert.37" cost_us: 1.216 }
costs { name: "wrapped_convert.38" cost_us: 1.728 }
costs { name: "wrapped_convert.39" cost_us: 1.76 }
costs { name: "wrapped_convert.4" cost_us: 1.728 }
costs { name: "wrapped_convert.40" cost_us: 1.696 }
costs { name: "wrapped_convert.41" cost_us: 1.44 }
costs { name: "wrapped_convert.42" cost_us: 1.664 }
costs { name: "wrapped_convert.43" cost_us: 1.792 }
costs { name: "wrapped_convert.44" cost_us: 1.664 }
costs { name: "wrapped_convert.45" cost_us: 1.76 }
costs { name: "wrapped_convert.46" cost_us: 1.696 }
costs { name: "wrapped_convert.47" cost_us: 1.76 }
costs { name: "wrapped_convert.48" cost_us: 1.472 }
costs { name: "wrapped_convert.49" cost_us: 1.216 }
costs { name: "wrapped_convert.5" cost_us: 1.6 }
costs { name: "wrapped_convert.50" cost_us: 1.216 }
costs { name: "wrapped_convert.51" cost_us: 1.216 }
costs { name: "wrapped_convert.52" cost_us: 1.216 }
costs { name: "wrapped_convert.53" cost_us: 1.217 }
costs { name: "wrapped_convert.54" cost_us: 1.248 }
costs { name: "wrapped_convert.55" cost_us: 1.247 }
costs { name: "wrapped_convert.6" cost_us: 1.632 }
costs { name: "wrapped_convert.7" cost_us: 1.824 }
costs { name: "wrapped_convert.8" cost_us: 1.663 }
costs { name: "wrapped_convert.9" cost_us: 1.824 }
costs { name: "wrapped_slice" cost_us: 3.68 }
costs { name: "wrapped_slice.1" cost_us: 2.944 }
costs { name: "wrapped_slice.10" cost_us: 1.344 }
costs { name: "wrapped_slice.100" cost_us: 1.248 }
costs { name: "wrapped_slice.101" cost_us: 1.248 }
costs { name: "wrapped_slice.102" cost_us: 1.28 }
costs { name: "wrapped_slice.103" cost_us: 1.248 }
costs { name: "wrapped_slice.104" cost_us: 1.248 }
costs { name: "wrapped_slice.105" cost_us: 1.28 }
costs { name: "wrapped_slice.106" cost_us: 1.28 }
costs { name: "wrapped_slice.107" cost_us: 1.28 }
costs { name: "wrapped_slice.108" cost_us: 1.248 }
costs { name: "wrapped_slice.109" cost_us: 1.248 }
costs { name: "wrapped_slice.11" cost_us: 1.28 }
costs { name: "wrapped_slice.110" cost_us: 1.28 }
costs { name: "wrapped_slice.12" cost_us: 1.28 }
costs { name: "wrapped_slice.13" cost_us: 1.28 }
costs { name: "wrapped_slice.14" cost_us: 1.312 }
costs { name: "wrapped_slice.15" cost_us: 1.312 }
costs { name: "wrapped_slice.16" cost_us: 1.28 }
costs { name: "wrapped_slice.17" cost_us: 1.344 }
costs { name: "wrapped_slice.18" cost_us: 1.28 }
costs { name: "wrapped_slice.19" cost_us: 1.28 }
costs { name: "wrapped_slice.2" cost_us: 1.473 }
costs { name: "wrapped_slice.20" cost_us: 3.487 }
costs { name: "wrapped_slice.21" cost_us: 3.487 }
costs { name: "wrapped_slice.22" cost_us: 3.487 }
costs { name: "wrapped_slice.25" cost_us: 1.727 }
costs { name: "wrapped_slice.26" cost_us: 2.08 }
costs { name: "wrapped_slice.27" cost_us: 2.08 }
costs { name: "wrapped_slice.28" cost_us: 1.727 }
costs { name: "wrapped_slice.29" cost_us: 1.216 }
costs { name: "wrapped_slice.3" cost_us: 1.344 }
costs { name: "wrapped_slice.30" cost_us: 1.247 }
costs { name: "wrapped_slice.31" cost_us: 1.247 }
costs { name: "wrapped_slice.32" cost_us: 1.247 }
costs { name: "wrapped_slice.33" cost_us: 1.248 }
costs { name: "wrapped_slice.34" cost_us: 1.247 }
costs { name: "wrapped_slice.35" cost_us: 1.216 }
costs { name: "wrapped_slice.36" cost_us: 1.247 }
costs { name: "wrapped_slice.37" cost_us: 1.247 }
costs { name: "wrapped_slice.38" cost_us: 1.216 }
costs { name: "wrapped_slice.39" cost_us: 1.247 }
costs { name: "wrapped_slice.4" cost_us: 1.472 }
costs { name: "wrapped_slice.40" cost_us: 1.376 }
costs { name: "wrapped_slice.41" cost_us: 1.216 }
costs { name: "wrapped_slice.42" cost_us: 1.407 }
costs { name: "wrapped_slice.43" cost_us: 1.216 }
costs { name: "wrapped_slice.44" cost_us: 1.407 }
costs { name: "wrapped_slice.45" cost_us: 1.28 }
costs { name: "wrapped_slice.46" cost_us: 1.408 }
costs { name: "wrapped_slice.47" cost_us: 1.472 }
costs { name: "wrapped_slice.48" cost_us: 1.28 }
costs { name: "wrapped_slice.49" cost_us: 1.664 }
costs { name: "wrapped_slice.5" cost_us: 1.311 }
costs { name: "wrapped_slice.50" cost_us: 1.249 }
costs { name: "wrapped_slice.51" cost_us: 1.504 }
costs { name: "wrapped_slice.52" cost_us: 1.472 }
costs { name: "wrapped_slice.53" cost_us: 1.247 }
costs { name: "wrapped_slice.54" cost_us: 1.472 }
costs { name: "wrapped_slice.55" cost_us: 1.312 }
costs { name: "wrapped_slice.56" cost_us: 1.248 }
costs { name: "wrapped_slice.57" cost_us: 1.344 }
costs { name: "wrapped_slice.58" cost_us: 1.312 }
costs { name: "wrapped_slice.59" cost_us: 1.248 }
costs { name: "wrapped_slice.6" cost_us: 1.44 }
costs { name: "wrapped_slice.60" cost_us: 1.312 }
costs { name: "wrapped_slice.61" cost_us: 1.28 }
costs { name: "wrapped_slice.62" cost_us: 1.312 }
costs { name: "wrapped_slice.63" cost_us: 1.249 }
costs { name: "wrapped_slice.64" cost_us: 1.312 }
costs { name: "wrapped_slice.65" cost_us: 4.096 }
costs { name: "wrapped_slice.66" cost_us: 4.032 }
costs { name: "wrapped_slice.67" cost_us: 1.92 }
costs { name: "wrapped_slice.68" cost_us: 1.888 }
costs { name: "wrapped_slice.69" cost_us: 2.272 }
costs { name: "wrapped_slice.7" cost_us: 1.44 }
costs { name: "wrapped_slice.70" cost_us: 2.368 }
costs { name: "wrapped_slice.71" cost_us: 2.304 }
costs { name: "wrapped_slice.72" cost_us: 1.984 }
costs { name: "wrapped_slice.73" cost_us: 1.983 }
costs { name: "wrapped_slice.74" cost_us: 3.84 }
costs { name: "wrapped_slice.75" cost_us: 3.808 }
costs { name: "wrapped_slice.76" cost_us: 3.872 }
costs { name: "wrapped_slice.77" cost_us: 3.648 }
costs { name: "wrapped_slice.78" cost_us: 3.649 }
costs { name: "wrapped_slice.79" cost_us: 1.247 }
costs { name: "wrapped_slice.8" cost_us: 1.28 }
costs { name: "wrapped_slice.80" cost_us: 1.249 }
costs { name: "wrapped_slice.81" cost_us: 1.28 }
costs { name: "wrapped_slice.82" cost_us: 1.28 }
costs { name: "wrapped_slice.83" cost_us: 1.28 }
costs { name: "wrapped_slice.84" cost_us: 1.248 }
costs { name: "wrapped_slice.89" cost_us: 1.311 }
costs { name: "wrapped_slice.9" cost_us: 1.471 }
costs { name: "wrapped_slice.90" cost_us: 1.248 }
costs { name: "wrapped_slice.92" cost_us: 1.249 }
costs { name: "wrapped_slice.93" cost_us: 1.407 }
costs { name: "wrapped_slice.94" cost_us: 1.408 }
costs { name: "wrapped_slice.95" cost_us: 1.28 }
costs { name: "wrapped_slice.96" cost_us: 1.248 }
costs { name: "wrapped_slice.97" cost_us: 1.28 }
costs { name: "wrapped_slice.98" cost_us: 1.28 }
costs { name: "wrapped_slice.99" cost_us: 1.28 }
costs { name: "wrapped_transpose.23" cost_us: 6.016 }
costs { name: "wrapped_transpose.24" cost_us: 6.112 }
costs { name: "wrapped_transpose.25" cost_us: 6.432 }
costs { name: "wrapped_select" cost_us: 1.504 }
costs { name: "loop_add_fusion" cost_us: 1.344 }
costs { name: "wrapped_add" cost_us: 1.408 }
costs { name: "loop_minimum_fusion" cost_us: 1.536 }
costs { name: "wrapped_cosine" cost_us: 1.408 }
costs { name: "input_reduce_fusion" cost_us: 1.695 }
costs { name: "loop_xor_fusion" cost_us: 1.856 }
costs { name: "wrapped_multiply" cost_us: 1.344 }
costs { name: "loop_subtract_fusion" cost_us: 1.344 }
costs { name: "input_add_reduce_fusion.10" cost_us: 759.005 }
costs { name: "input_add_reduce_fusion.11" cost_us: 760.253 }
costs { name: "input_add_reduce_fusion.12" cost_us: 278.175 }
costs { name: "input_add_reduce_fusion.13" cost_us: 1171.452 }
costs { name: "input_add_reduce_fusion.14" cost_us: 1168.699 }
costs { name: "input_add_reduce_fusion.19" cost_us: 329.983 }
costs { name: "input_add_reduce_fusion.2" cost_us: 40.256 }
costs { name: "input_add_reduce_fusion.20" cost_us: 47.104 }
costs { name: "input_add_reduce_fusion.21" cost_us: 45.088 }
costs { name: "input_add_reduce_fusion.22" cost_us: 6.176 }
costs { name: "input_add_reduce_fusion.3" cost_us: 31.456 }
costs { name: "input_add_reduce_fusion.4" cost_us: 220.671 }
costs { name: "input_add_reduce_fusion.5" cost_us: 221.567 }
costs { name: "input_add_reduce_fusion.6" cost_us: 31.199 }
costs { name: "input_add_reduce_fusion.7" cost_us: 10.112 }
costs { name: "input_add_reduce_fusion.8" cost_us: 10.016 }
costs { name: "input_add_reduce_fusion.9" cost_us: 1375.323 }
costs { name: "input_compare_reduce_fusion" cost_us: 2.752 }
costs { name: "input_convert_reduce_fusion.7" cost_us: 2018.712 }
costs { name: "input_convert_reduce_fusion.8" cost_us: 493.406 }
costs { name: "input_dynamic_slice_reduce_fusion" cost_us: 176.095 }
costs { name: "input_dynamic_slice_reduce_fusion.1" cost_us: 177.824 }
costs { name: "input_dynamic_slice_reduce_fusion.2" cost_us: 174.432 }
costs { name: "input_reduce_fusion" cost_us: 2.816 }
costs { name: "input_reduce_fusion.1" cost_us: 2.272 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 2.4 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 2.08 }
costs { name: "input_reduce_fusion.10" cost_us: 2.848 }
costs { name: "input_reduce_fusion.10.double_buffer_clone" cost_us: 2.688 }
costs { name: "input_reduce_fusion.10.peeled_double_buffer" cost_us: 3.009 }
costs { name: "input_reduce_fusion.11" cost_us: 2.176 }
costs { name: "input_reduce_fusion.11.double_buffer_clone" cost_us: 2.143 }
costs { name: "input_reduce_fusion.11.peeled_double_buffer" cost_us: 2.08 }
costs { name: "input_reduce_fusion.117" cost_us: 3.168 }
costs { name: "input_reduce_fusion.118" cost_us: 3.936 }
costs { name: "input_reduce_fusion.119" cost_us: 2.016 }
costs { name: "input_reduce_fusion.12" cost_us: 2.848 }
costs { name: "input_reduce_fusion.12.double_buffer_clone" cost_us: 2.816 }
costs { name: "input_reduce_fusion.12.peeled_double_buffer" cost_us: 3.072 }
costs { name: "input_reduce_fusion.120" cost_us: 1.984 }
costs { name: "input_reduce_fusion.121" cost_us: 1.984 }
costs { name: "input_reduce_fusion.122" cost_us: 2.016 }
costs { name: "input_reduce_fusion.123" cost_us: 2.048 }
costs { name: "input_reduce_fusion.124" cost_us: 2.112 }
costs { name: "input_reduce_fusion.125" cost_us: 2.016 }
costs { name: "input_reduce_fusion.126" cost_us: 2.112 }
costs { name: "input_reduce_fusion.127" cost_us: 2.08 }
costs { name: "input_reduce_fusion.128" cost_us: 1.983 }
costs { name: "input_reduce_fusion.129" cost_us: 2.111 }
costs { name: "input_reduce_fusion.13" cost_us: 2.016 }
costs { name: "input_reduce_fusion.13.double_buffer_clone" cost_us: 1.952 }
costs { name: "input_reduce_fusion.13.peeled_double_buffer" cost_us: 1.791 }
costs { name: "input_reduce_fusion.130" cost_us: 2.111 }
costs { name: "input_reduce_fusion.131" cost_us: 2.016 }
costs { name: "input_reduce_fusion.132" cost_us: 2.017 }
costs { name: "input_reduce_fusion.133" cost_us: 2.113 }
costs { name: "input_reduce_fusion.134" cost_us: 2.015 }
costs { name: "input_reduce_fusion.135" cost_us: 1.985 }
costs { name: "input_reduce_fusion.136" cost_us: 1.984 }
costs { name: "input_reduce_fusion.137" cost_us: 2.048 }
costs { name: "input_reduce_fusion.138" cost_us: 2.144 }
costs { name: "input_reduce_fusion.139" cost_us: 1.984 }
costs { name: "input_reduce_fusion.140" cost_us: 3.136 }
costs { name: "input_reduce_fusion.141" cost_us: 3.135 }
costs { name: "input_reduce_fusion.142" cost_us: 9.824 }
costs { name: "input_reduce_fusion.143" cost_us: 64.928 }
costs { name: "input_reduce_fusion.144" cost_us: 60.895 }
costs { name: "input_reduce_fusion.145" cost_us: 9.792 }
costs { name: "input_reduce_fusion.146" cost_us: 2.304 }
costs { name: "input_reduce_fusion.147" cost_us: 2.336 }
costs { name: "input_reduce_fusion.148" cost_us: 193.472 }
costs { name: "input_reduce_fusion.149" cost_us: 189.951 }
costs { name: "input_reduce_fusion.150" cost_us: 195.199 }
costs { name: "input_reduce_fusion.151" cost_us: 1.952 }
costs { name: "input_reduce_fusion.152" cost_us: 2.337 }
costs { name: "input_reduce_fusion.153" cost_us: 2.208 }
costs { name: "input_reduce_fusion.154" cost_us: 2.24 }
costs { name: "input_reduce_fusion.155" cost_us: 2.016 }
costs { name: "input_reduce_fusion.156" cost_us: 2.016 }
costs { name: "input_reduce_fusion.157" cost_us: 2.209 }
costs { name: "input_reduce_fusion.158" cost_us: 2.112 }
costs { name: "input_reduce_fusion.159" cost_us: 2.112 }
costs { name: "input_reduce_fusion.160" cost_us: 494.974 }
costs { name: "input_reduce_fusion.161" cost_us: 1.952 }
costs { name: "input_reduce_fusion.162" cost_us: 2.208 }
costs { name: "input_reduce_fusion.163" cost_us: 1.696 }
costs { name: "input_reduce_fusion.164" cost_us: 1.792 }
costs { name: "input_reduce_fusion.165" cost_us: 367.743 }
costs { name: "input_reduce_fusion.169" cost_us: 168.767 }
costs { name: "input_reduce_fusion.170" cost_us: 259.839 }
costs { name: "input_reduce_fusion.171" cost_us: 168.8 }
costs { name: "input_reduce_fusion.172" cost_us: 87.967 }
costs { name: "input_reduce_fusion.173" cost_us: 258.975 }
costs { name: "input_reduce_fusion.174" cost_us: 167.999 }
costs { name: "input_reduce_fusion.175" cost_us: 88.639 }
costs { name: "input_reduce_fusion.195" cost_us: 1.728 }
costs { name: "input_reduce_fusion.196" cost_us: 1.664 }
costs { name: "input_reduce_fusion.197" cost_us: 5.888 }
costs { name: "input_reduce_fusion.2" cost_us: 2.88 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 2.816 }
costs { name: "input_reduce_fusion.2.peeled_double_buffer" cost_us: 3.135 }
costs { name: "input_reduce_fusion.202" cost_us: 1.695 }
costs { name: "input_reduce_fusion.203" cost_us: 1.568 }
costs { name: "input_reduce_fusion.204" cost_us: 1.696 }
costs { name: "input_reduce_fusion.205" cost_us: 2.047 }
costs { name: "input_reduce_fusion.206" cost_us: 2.08 }
costs { name: "input_reduce_fusion.207" cost_us: 2.048 }
costs { name: "input_reduce_fusion.208" cost_us: 1.888 }
costs { name: "input_reduce_fusion.209" cost_us: 1.76 }
costs { name: "input_reduce_fusion.210" cost_us: 1.696 }
costs { name: "input_reduce_fusion.211" cost_us: 4.896 }
costs { name: "input_reduce_fusion.212" cost_us: 1.728 }
costs { name: "input_reduce_fusion.213" cost_us: 1.92 }
costs { name: "input_reduce_fusion.214" cost_us: 2.08 }
costs { name: "input_reduce_fusion.215" cost_us: 2.144 }
costs { name: "input_reduce_fusion.216" cost_us: 1.92 }
costs { name: "input_reduce_fusion.217" cost_us: 1.632 }
costs { name: "input_reduce_fusion.218" cost_us: 1.632 }
costs { name: "input_reduce_fusion.219" cost_us: 1.633 }
costs { name: "input_reduce_fusion.220" cost_us: 1.633 }
costs { name: "input_reduce_fusion.221" cost_us: 1.568 }
costs { name: "input_reduce_fusion.222" cost_us: 1.568 }
costs { name: "input_reduce_fusion.223" cost_us: 1.728 }
costs { name: "input_reduce_fusion.224" cost_us: 2.24 }
costs { name: "input_reduce_fusion.225" cost_us: 2.08 }
costs { name: "input_reduce_fusion.226" cost_us: 1.728 }
costs { name: "input_reduce_fusion.227" cost_us: 1.888 }
costs { name: "input_reduce_fusion.228" cost_us: 1.728 }
costs { name: "input_reduce_fusion.229" cost_us: 1.633 }
costs { name: "input_reduce_fusion.230" cost_us: 1.504 }
costs { name: "input_reduce_fusion.231" cost_us: 2.016 }
costs { name: "input_reduce_fusion.232" cost_us: 1.632 }
costs { name: "input_reduce_fusion.233" cost_us: 1.632 }
costs { name: "input_reduce_fusion.234" cost_us: 1.631 }
costs { name: "input_reduce_fusion.235" cost_us: 1.536 }
costs { name: "input_reduce_fusion.3" cost_us: 2.112 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 2.209 }
costs { name: "input_reduce_fusion.3.peeled_double_buffer" cost_us: 2.272 }
costs { name: "input_reduce_fusion.37" cost_us: 258.879 }
costs { name: "input_reduce_fusion.38" cost_us: 168.031 }
costs { name: "input_reduce_fusion.39" cost_us: 87.392 }
costs { name: "input_reduce_fusion.4" cost_us: 2.944 }
costs { name: "input_reduce_fusion.4.double_buffer_clone" cost_us: 2.912 }
costs { name: "input_reduce_fusion.4.peeled_double_buffer" cost_us: 3.008 }
costs { name: "input_reduce_fusion.5" cost_us: 1.952 }
costs { name: "input_reduce_fusion.5.double_buffer_clone" cost_us: 2.016 }
costs { name: "input_reduce_fusion.5.peeled_double_buffer" cost_us: 2.048 }
costs { name: "input_reduce_fusion.6" cost_us: 2.815 }
costs { name: "input_reduce_fusion.6.double_buffer_clone" cost_us: 2.944 }
costs { name: "input_reduce_fusion.6.peeled_double_buffer" cost_us: 2.913 }
costs { name: "input_reduce_fusion.7" cost_us: 2.304 }
costs { name: "input_reduce_fusion.7.double_buffer_clone" cost_us: 2.368 }
costs { name: "input_reduce_fusion.7.peeled_double_buffer" cost_us: 2.4 }
costs { name: "input_reduce_fusion.75" cost_us: 2.432 }
costs { name: "input_reduce_fusion.76" cost_us: 2.368 }
costs { name: "input_reduce_fusion.77" cost_us: 2.592 }
costs { name: "input_reduce_fusion.78" cost_us: 2.176 }
costs { name: "input_reduce_fusion.79" cost_us: 2.016 }
costs { name: "input_reduce_fusion.8" cost_us: 2.72 }
costs { name: "input_reduce_fusion.8.double_buffer_clone" cost_us: 2.56 }
costs { name: "input_reduce_fusion.8.peeled_double_buffer" cost_us: 3.071 }
costs { name: "input_reduce_fusion.80" cost_us: 2.24 }
costs { name: "input_reduce_fusion.81" cost_us: 1.92 }
costs { name: "input_reduce_fusion.82" cost_us: 2.624 }
costs { name: "input_reduce_fusion.83" cost_us: 2.017 }
costs { name: "input_reduce_fusion.84" cost_us: 2.112 }
costs { name: "input_reduce_fusion.85" cost_us: 2.592 }
costs { name: "input_reduce_fusion.86" cost_us: 2.368 }
costs { name: "input_reduce_fusion.87" cost_us: 2.656 }
costs { name: "input_reduce_fusion.88" cost_us: 1.92 }
costs { name: "input_reduce_fusion.89" cost_us: 1.952 }
costs { name: "input_reduce_fusion.9" cost_us: 1.952 }
costs { name: "input_reduce_fusion.9.double_buffer_clone" cost_us: 2.048 }
costs { name: "input_reduce_fusion.9.peeled_double_buffer" cost_us: 1.664 }
costs { name: "input_reduce_fusion.90" cost_us: 2.048 }
costs { name: "input_reduce_fusion.91" cost_us: 1.856 }
costs { name: "input_reduce_fusion.92" cost_us: 2.048 }
costs { name: "input_reduce_fusion.93" cost_us: 1.856 }
costs { name: "input_reduce_fusion.94" cost_us: 1.888 }
costs { name: "input_reduce_fusion.95" cost_us: 2.048 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 2.816 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 3.04 }
costs { name: "input_transpose_fusion.18" cost_us: 417.822 }
costs { name: "input_transpose_fusion.19" cost_us: 420.543 }
costs { name: "input_transpose_fusion.20" cost_us: 420.638 }
costs { name: "loop_add_log_fusion" cost_us: 2.047 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.6 }
costs { name: "loop_divide_fusion" cost_us: 1.696 }
costs { name: "loop_multiply_fusion.10" cost_us: 1.696 }
costs { name: "loop_multiply_fusion.4" cost_us: 2.303 }
costs { name: "loop_select_fusion.1" cost_us: 2.272 }
costs { name: "loop_select_fusion.2" cost_us: 1.215 }
costs { name: "loop_select_fusion.5" cost_us: 1.504 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.503 }
costs { name: "loop_sqrt_fusion" cost_us: 2.976 }
costs { name: "loop_subtract_fusion" cost_us: 1.312 }
costs { name: "while.32.0" cost_us: 4961.132 }
costs { name: "while.32.0" cost_us: 11496.912 }
costs { name: "while.32.0" cost_us: 1454.427 }
costs { name: "while.32.0" cost_us: 1886.169 }
costs { name: "while.32.0" cost_us: 1774.68 }
costs { name: "while.32.0" cost_us: 1774.361 }
costs { name: "while.32.0" cost_us: 1141.084 }
costs { name: "while.32.0" cost_us: 1139.899 }
costs { name: "while.32.0" cost_us: 631.485 }
costs { name: "while.32.0" cost_us: 631.678 }
costs { name: "while.32.0" cost_us: 232.096 }
costs { name: "while.32.0" cost_us: 784.957 }
costs { name: "while.32.0" cost_us: 786.077 }
costs { name: "while.32.0" cost_us: 195.231 }
costs { name: "while.32.0" cost_us: 318.686 }
costs { name: "while.32.0" cost_us: 403.998 }
costs { name: "while.32.0" cost_us: 403.614 }
costs { name: "while.32.0" cost_us: 90.592 }
costs { name: "while.32.0" cost_us: 87.616 }
costs { name: "while.32.0" cost_us: 80.607 }
costs { name: "while.32.0" cost_us: 80.287 }
costs { name: "while.32.0" cost_us: 66.976 }
costs { name: "while.32.0" cost_us: 41.536 }
costs { name: "while.32.0" cost_us: 25.312 }
costs { name: "while.32.0" cost_us: 10.976 }
costs { name: "while.32.0" cost_us: 8.064 }
costs { name: "while.32.0" cost_us: 2.688 }
costs { name: "while.32.0" cost_us: 1.952 }
costs { name: "while.32.0" cost_us: 1.728 }
costs { name: "while.32.0" cost_us: 1.727 }
costs { name: "while.32.0" cost_us: 1.952 }
costs { name: "while.32.0" cost_us: 1.952 }
costs { name: "while.32.0" cost_us: 8.32 }
costs { name: "while.32.0" cost_us: 8.256 }
costs { name: "while.32.0" cost_us: 3.904 }
costs { name: "while.32.0" cost_us: 1.887 }
costs { name: "while.32.0" cost_us: 1.887 }
costs { name: "while.32.0" cost_us: 2.336 }
costs { name: "while.32.0" cost_us: 2.816 }
costs { name: "while.32.0" cost_us: 1.856 }
costs { name: "while.32.0" cost_us: 4.064 }
costs { name: "while.32.0" cost_us: 4.032 }
costs { name: "while.32.0" cost_us: 1.727 }
costs { name: "while.32.0" cost_us: 1.728 }
costs { name: "while.32.0" cost_us: 1.696 }
costs { name: "while.32.0" cost_us: 2.848 }
costs { name: "while.32.0" cost_us: 1.504 }
costs { name: "while.32.0" cost_us: 2.56 }
costs { name: "while.32.0" cost_us: 1.248 }
costs { name: "while.32.0" cost_us: 2.368 }
costs { name: "while.32.0" cost_us: 1.792 }
costs { name: "while.32.0" cost_us: 1.792 }
costs { name: "while.32.0" cost_us: 1.887 }
costs { name: "while.32.0" cost_us: 1.792 }
costs { name: "while.33.0" cost_us: 1370.843 }
costs { name: "while.33.0" cost_us: 15812.708 }
costs { name: "while.33.0" cost_us: 11463.604 }
costs { name: "while.33.0" cost_us: 1364.155 }
costs { name: "while.33.0" cost_us: 4964.685 }
costs { name: "while.33.0" cost_us: 255.36 }
costs { name: "while.33.0" cost_us: 3946.129 }
costs { name: "while.33.0" cost_us: 186.687 }
costs { name: "while.33.0" cost_us: 2106.2 }
costs { name: "while.33.0" cost_us: 2641.238 }
costs { name: "while.33.0" cost_us: 2233.111 }
costs { name: "while.33.0" cost_us: 1868.345 }
costs { name: "while.33.0" cost_us: 879.773 }
costs { name: "while.33.0" cost_us: 1512.058 }
costs { name: "while.33.0" cost_us: 1240.091 }
costs { name: "while.33.0" cost_us: 1166.235 }
costs { name: "while.33.0" cost_us: 803.741 }
costs { name: "while.33.0" cost_us: 732.189 }
costs { name: "while.33.0" cost_us: 604.286 }
costs { name: "while.33.0" cost_us: 252.703 }
costs { name: "while.33.0" cost_us: 233.503 }
costs { name: "while.33.0" cost_us: 415.838 }
costs { name: "while.33.0" cost_us: 387.615 }
costs { name: "while.33.0" cost_us: 170.015 }
costs { name: "while.33.0" cost_us: 326.558 }
costs { name: "while.33.0" cost_us: 258.879 }
costs { name: "while.33.0" cost_us: 244.383 }
costs { name: "while.33.0" cost_us: 234.719 }
costs { name: "while.33.0" cost_us: 98.623 }
costs { name: "while.33.0" cost_us: 188.255 }
costs { name: "while.33.0" cost_us: 178.015 }
costs { name: "while.33.0" cost_us: 176.095 }
costs { name: "while.33.0" cost_us: 168.031 }
costs { name: "while.33.0" cost_us: 90.752 }
costs { name: "while.33.0" cost_us: 89.568 }
costs { name: "while.33.0" cost_us: 87.392 }
costs { name: "while.33.0" cost_us: 80.064 }
costs { name: "while.33.0" cost_us: 66.464 }
costs { name: "while.33.0" cost_us: 49.759 }
costs { name: "while.33.0" cost_us: 24.513 }
costs { name: "while.33.0" cost_us: 33.856 }
costs { name: "while.33.0" cost_us: 1.567 }
costs { name: "while.33.0" cost_us: 10.848 }
costs { name: "while.33.0" cost_us: 1.727 }
costs { name: "while.33.0" cost_us: 9.984 }
costs { name: "while.33.0" cost_us: 1.215 }
costs { name: "while.33.0" cost_us: 7.04 }
costs { name: "while.33.0" cost_us: 1.536 }
costs { name: "while.33.0" cost_us: 12.544 }
costs { name: "while.33.0" cost_us: 1.567 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 10.4 }
costs { name: "while.33.0" cost_us: 10.144 }
costs { name: "while.33.0" cost_us: 2.24 }
costs { name: "while.33.0" cost_us: 9.984 }
costs { name: "while.33.0" cost_us: 9.056 }
costs { name: "while.33.0" cost_us: 9.056 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 7.648 }
costs { name: "while.33.0" cost_us: 2.303 }
costs { name: "while.33.0" cost_us: 1.375 }
costs { name: "while.33.0" cost_us: 6.624 }
costs { name: "while.33.0" cost_us: 1.376 }
costs { name: "while.33.0" cost_us: 1.568 }
costs { name: "while.33.0" cost_us: 1.6 }
costs { name: "while.33.0" cost_us: 1.92 }
costs { name: "while.33.0" cost_us: 4.0 }
costs { name: "while.33.0" cost_us: 1.76 }
costs { name: "while.33.0" cost_us: 3.936 }
costs { name: "while.33.0" cost_us: 1.792 }
costs { name: "while.33.0" cost_us: 1.6 }
costs { name: "while.33.0" cost_us: 3.487 }
costs { name: "while.33.0" cost_us: 1.567 }
costs { name: "while.33.0" cost_us: 1.632 }
costs { name: "while.33.0" cost_us: 3.487 }
costs { name: "while.33.0" cost_us: 3.487 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 2.111 }
costs { name: "while.33.0" cost_us: 2.015 }
costs { name: "while.33.0" cost_us: 2.015 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 2.08 }
costs { name: "while.33.0" cost_us: 1.855 }
costs { name: "while.33.0" cost_us: 1.791 }
costs { name: "while.33.0" cost_us: 1.632 }
costs { name: "while.33.0" cost_us: 1.6 }
costs { name: "while.33.0" cost_us: 1.727 }
costs { name: "while.33.0" cost_us: 1.632 }
costs { name: "while.33.0" cost_us: 1.727 }
costs { name: "while.33.0" cost_us: 1.504 }
costs { name: "while.33.0" cost_us: 1.408 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.28 }
costs { name: "while.33.0" cost_us: 1.471 }
costs { name: "while.33.0" cost_us: 1.44 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.408 }
costs { name: "while.33.0" cost_us: 1.408 }
costs { name: "while.33.0" cost_us: 1.408 }
costs { name: "while.33.0" cost_us: 1.408 }
costs { name: "while.33.0" cost_us: 1.376 }
costs { name: "while.33.0" cost_us: 1.407 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.248 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.343 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.247 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.216 }
costs { name: "while.33.0" cost_us: 1.184 }
costs { name: "while.33.0" cost_us: 1.12 }
costs { name: "while.33.0" cost_us: 1.024 }
costs { name: "loop_add_fusion.2" cost_us: 1.536 }
costs { name: "input_reduce_fusion.14" cost_us: 90.656 }
costs { name: "input_reduce_fusion.14.double_buffer_clone" cost_us: 90.592 }
costs { name: "input_reduce_fusion.14.peeled_double_buffer" cost_us: 85.152 }
costs { name: "input_reduce_fusion.15" cost_us: 87.616 }
costs { name: "input_reduce_fusion.15.double_buffer_clone" cost_us: 87.648 }
costs { name: "input_reduce_fusion.15.peeled_double_buffer" cost_us: 87.552 }
costs { name: "input_reduce_fusion.166" cost_us: 94.816 }
costs { name: "input_reduce_fusion.167" cost_us: 87.872 }
costs { name: "input_reduce_fusion.168" cost_us: 87.647 }
costs { name: "loop_multiply_fusion.3" cost_us: 190.752 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.208 }
costs { name: "wrapped_convert" cost_us: 1.984 }
costs { name: "wrapped_convert.1" cost_us: 6.432 }
costs { name: "custom-call.64.0" cost_us: 11550.899 }
costs { name: "loop_convert_fusion.112" cost_us: 618.045 }
costs { name: "input_transpose_fusion.23" cost_us: 7.36 }
costs { name: "all-gather-start.3" cost_us: 5100.653 }
costs { name: "custom-call.63.0" cost_us: 9110.298 }
costs { name: "loop_convert_fusion" cost_us: 1.887 }
costs { name: "loop_convert_fusion.1" cost_us: 1.887 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 1.92 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 1.92 }
costs { name: "loop_convert_fusion.10" cost_us: 1.76 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.10.peeled_double_buffer" cost_us: 1.792 }
costs { name: "loop_convert_fusion.11" cost_us: 1.855 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 1.856 }
costs { name: "loop_convert_fusion.11.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.114" cost_us: 8.32 }
costs { name: "loop_convert_fusion.115" cost_us: 8.416 }
costs { name: "loop_convert_fusion.116" cost_us: 8.543 }
costs { name: "loop_convert_fusion.12" cost_us: 1.856 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.12.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.123" cost_us: 3.776 }
costs { name: "loop_convert_fusion.124" cost_us: 4.032 }
costs { name: "loop_convert_fusion.127" cost_us: 2.016 }
costs { name: "loop_convert_fusion.128" cost_us: 2.112 }
costs { name: "loop_convert_fusion.13" cost_us: 1.759 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_convert_fusion.13.peeled_double_buffer" cost_us: 1.696 }
costs { name: "loop_convert_fusion.133" cost_us: 2.336 }
costs { name: "loop_convert_fusion.134" cost_us: 2.208 }
costs { name: "loop_convert_fusion.137" cost_us: 1.472 }
costs { name: "loop_convert_fusion.138" cost_us: 1.664 }
costs { name: "loop_convert_fusion.139" cost_us: 1.792 }
costs { name: "loop_convert_fusion.19" cost_us: 8.32 }
costs { name: "loop_convert_fusion.19.double_buffer_clone" cost_us: 8.256 }
costs { name: "loop_convert_fusion.19.peeled_double_buffer" cost_us: 8.287 }
costs { name: "loop_convert_fusion.2" cost_us: 1.887 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 1.887 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.20" cost_us: 8.096 }
costs { name: "loop_convert_fusion.20.double_buffer_clone" cost_us: 8.064 }
costs { name: "loop_convert_fusion.20.peeled_double_buffer" cost_us: 8.096 }
costs { name: "loop_convert_fusion.21" cost_us: 8.352 }
costs { name: "loop_convert_fusion.21.double_buffer_clone" cost_us: 8.448 }
costs { name: "loop_convert_fusion.21.peeled_double_buffer" cost_us: 8.576 }
costs { name: "loop_convert_fusion.22" cost_us: 3.904 }
costs { name: "loop_convert_fusion.22.double_buffer_clone" cost_us: 3.968 }
costs { name: "loop_convert_fusion.22.peeled_double_buffer" cost_us: 4.192 }
costs { name: "loop_convert_fusion.23" cost_us: 4.032 }
costs { name: "loop_convert_fusion.23.double_buffer_clone" cost_us: 4.064 }
costs { name: "loop_convert_fusion.23.peeled_double_buffer" cost_us: 4.128 }
costs { name: "loop_convert_fusion.24" cost_us: 2.336 }
costs { name: "loop_convert_fusion.24.double_buffer_clone" cost_us: 2.368 }
costs { name: "loop_convert_fusion.24.peeled_double_buffer" cost_us: 2.432 }
costs { name: "loop_convert_fusion.25" cost_us: 2.336 }
costs { name: "loop_convert_fusion.25.double_buffer_clone" cost_us: 2.368 }
costs { name: "loop_convert_fusion.25.peeled_double_buffer" cost_us: 2.432 }
costs { name: "loop_convert_fusion.26" cost_us: 1.888 }
costs { name: "loop_convert_fusion.26.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_convert_fusion.26.peeled_double_buffer" cost_us: 1.664 }
costs { name: "loop_convert_fusion.27" cost_us: 1.92 }
costs { name: "loop_convert_fusion.27.double_buffer_clone" cost_us: 1.887 }
costs { name: "loop_convert_fusion.27.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.3" cost_us: 1.728 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 1.727 }
costs { name: "loop_convert_fusion.4" cost_us: 1.887 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 1.92 }
costs { name: "loop_convert_fusion.5" cost_us: 1.76 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 1.664 }
costs { name: "loop_convert_fusion.6" cost_us: 1.856 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 1.888 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 1.887 }
costs { name: "loop_convert_fusion.7" cost_us: 1.856 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 1.856 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.73" cost_us: 1.984 }
costs { name: "loop_convert_fusion.74" cost_us: 1.92 }
costs { name: "loop_convert_fusion.75" cost_us: 1.888 }
costs { name: "loop_convert_fusion.76" cost_us: 1.92 }
costs { name: "loop_convert_fusion.77" cost_us: 1.984 }
costs { name: "loop_convert_fusion.78" cost_us: 1.856 }
costs { name: "loop_convert_fusion.79" cost_us: 1.632 }
costs { name: "loop_convert_fusion.8" cost_us: 1.76 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 1.92 }
costs { name: "loop_convert_fusion.80" cost_us: 2.016 }
costs { name: "loop_convert_fusion.81" cost_us: 1.792 }
costs { name: "loop_convert_fusion.82" cost_us: 1.825 }
costs { name: "loop_convert_fusion.83" cost_us: 1.92 }
costs { name: "loop_convert_fusion.84" cost_us: 1.92 }
costs { name: "loop_convert_fusion.85" cost_us: 2.048 }
costs { name: "loop_convert_fusion.86" cost_us: 1.632 }
costs { name: "loop_convert_fusion.9" cost_us: 1.727 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 1.728 }
costs { name: "loop_convert_fusion.9.peeled_double_buffer" cost_us: 1.44 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 1.887 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 2.08 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 631.485 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 80.639 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 80.607 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 80.608 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 80.575 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 80.287 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 80.64 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 631.71 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 631.678 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 631.709 }
costs { name: "loop_dynamic_update_slice_fusion.57" cost_us: 631.517 }
costs { name: "loop_dynamic_update_slice_fusion.58" cost_us: 81.024 }
costs { name: "loop_dynamic_update_slice_fusion.59" cost_us: 80.832 }
costs { name: "loop_dynamic_update_slice_fusion.60" cost_us: 631.965 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 631.677 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 632.093 }
costs { name: "loop_add_fusion" cost_us: 1.727 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_fusion.peeled_double_buffer" cost_us: 1.76 }
costs { name: "loop_convert_fusion.108" cost_us: 1877.369 }
costs { name: "loop_convert_fusion.109" cost_us: 816.573 }
costs { name: "loop_convert_fusion.110" cost_us: 1185.692 }
costs { name: "loop_convert_fusion.14" cost_us: 1774.68 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 1774.361 }
costs { name: "loop_convert_fusion.14.peeled_double_buffer" cost_us: 1762.297 }
costs { name: "loop_convert_fusion.15" cost_us: 786.077 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 784.957 }
costs { name: "loop_convert_fusion.15.peeled_double_buffer" cost_us: 779.516 }
costs { name: "loop_convert_fusion.16" cost_us: 1141.084 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 1139.899 }
costs { name: "loop_convert_fusion.16.peeled_double_buffer" cost_us: 1132.027 }
costs { name: "cublas-gemm.103.0" cost_us: 4995.501 }
costs { name: "cublas-gemm.96.0" cost_us: 4961.132 }
costs { name: "cublas-gemm.96.0.double_buffer_clone" cost_us: 4961.932 }
costs { name: "cublas-gemm.96.0.peeled_double_buffer" cost_us: 4987.469 }
costs { name: "wrapped_transpose.10" cost_us: 233.726 }
costs { name: "wrapped_transpose.12" cost_us: 233.791 }
costs { name: "wrapped_transpose.14" cost_us: 234.239 }
costs { name: "wrapped_transpose.16" cost_us: 240.031 }
costs { name: "cublas-gemm.104.0" cost_us: 4985.26 }
costs { name: "cublas-gemm.97.0" cost_us: 4968.459 }
costs { name: "cublas-gemm.97.0.double_buffer_clone" cost_us: 4973.067 }
costs { name: "cublas-gemm.97.0.peeled_double_buffer" cost_us: 4993.484 }
costs { name: "wrapped_transpose.11" cost_us: 232.672 }
costs { name: "wrapped_transpose.13" cost_us: 232.096 }
costs { name: "wrapped_transpose.15" cost_us: 237.759 }
costs { name: "wrapped_transpose.9" cost_us: 232.639 }
costs { name: "cublas-gemm.105.0" cost_us: 5130.219 }
costs { name: "cublas-gemm.98.0" cost_us: 5086.731 }
costs { name: "cublas-gemm.98.0.double_buffer_clone" cost_us: 5095.466 }
costs { name: "cublas-gemm.98.0.peeled_double_buffer" cost_us: 5115.852 }
costs { name: "loop_rsqrt_fusion" cost_us: 1.952 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.144 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 2.112 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.176 }
costs { name: "input_concatenate_fusion" cost_us: 318.686 }
costs { name: "input_concatenate_fusion.1" cost_us: 41.536 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 41.536 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 41.568 }
costs { name: "input_concatenate_fusion.2" cost_us: 318.974 }
costs { name: "input_concatenate_fusion.3" cost_us: 41.504 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 318.846 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 318.59 }
costs { name: "custom-call.72.0" cost_us: 1900.089 }
costs { name: "custom-call.72.0" cost_us: 1.696 }
costs { name: "custom-call.72.0.double_buffer_clone" cost_us: 1886.169 }
costs { name: "custom-call.72.0.double_buffer_clone" cost_us: 1.696 }
costs { name: "custom-call.72.0.peeled_double_buffer" cost_us: 1881.4 }
costs { name: "custom-call.72.0.peeled_double_buffer" cost_us: 1.696 }
costs { name: "custom-call.73.0" cost_us: 1977.177 }
costs { name: "custom-call.73.0" cost_us: 1.985 }
costs { name: "loop_broadcast_fusion" cost_us: 1.248 }
costs { name: "loop_broadcast_fusion.12" cost_us: 1.313 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.28 }
costs { name: "loop_multiply_fusion" cost_us: 1.504 }
costs { name: "loop_multiply_fusion.8" cost_us: 1.568 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 1.504 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 1.504 }
costs { name: "loop_convert_fusion.113" cost_us: 25.44 }
costs { name: "loop_convert_fusion.18" cost_us: 25.312 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 25.472 }
costs { name: "loop_convert_fusion.18.peeled_double_buffer" cost_us: 25.696 }
costs { name: "cublas-gemm.100.0" cost_us: 199.519 }
costs { name: "cublas-gemm.93.0" cost_us: 196.095 }
costs { name: "cublas-gemm.93.0.double_buffer_clone" cost_us: 195.231 }
costs { name: "cublas-gemm.93.0.peeled_double_buffer" cost_us: 197.312 }
costs { name: "input_transpose_fusion.1" cost_us: 10.976 }
costs { name: "input_transpose_fusion.1.double_buffer_clone" cost_us: 11.295 }
costs { name: "input_transpose_fusion.1.peeled_double_buffer" cost_us: 11.04 }
costs { name: "input_transpose_fusion.12" cost_us: 11.424 }
costs { name: "cublas-gemm.101.0" cost_us: 199.071 }
costs { name: "cublas-gemm.94.0" cost_us: 196.447 }
costs { name: "cublas-gemm.94.0.double_buffer_clone" cost_us: 196.831 }
costs { name: "cublas-gemm.94.0.peeled_double_buffer" cost_us: 197.631 }
costs { name: "input_transpose_fusion" cost_us: 11.072 }
costs { name: "input_transpose_fusion.11" cost_us: 11.872 }
costs { name: "input_transpose_fusion.double_buffer_clone" cost_us: 11.264 }
costs { name: "input_transpose_fusion.peeled_double_buffer" cost_us: 10.72 }
costs { name: "loop_convert_fusion.111" cost_us: 420.414 }
costs { name: "loop_convert_fusion.17" cost_us: 403.998 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 403.614 }
costs { name: "loop_convert_fusion.17.peeled_double_buffer" cost_us: 402.655 }
costs { name: "cublas-gemm.102.0" cost_us: 1552.314 }
costs { name: "cublas-gemm.95.0" cost_us: 1524.794 }
costs { name: "cublas-gemm.95.0.double_buffer_clone" cost_us: 1523.162 }
costs { name: "cublas-gemm.95.0.peeled_double_buffer" cost_us: 1528.698 }
costs { name: "cublas-gemm.92.0" cost_us: 1454.427 }
costs { name: "cublas-gemm.92.0.double_buffer_clone" cost_us: 1462.778 }
costs { name: "cublas-gemm.92.0.peeled_double_buffer" cost_us: 1471.77 }
costs { name: "cublas-gemm.99.0" cost_us: 1479.546 }
costs { name: "input_transpose_fusion.13" cost_us: 69.024 }
costs { name: "input_transpose_fusion.2" cost_us: 67.872 }
costs { name: "input_transpose_fusion.2.double_buffer_clone" cost_us: 66.976 }
costs { name: "input_transpose_fusion.2.peeled_double_buffer" cost_us: 69.216 }
costs { name: "loop_convert_fusion.120" cost_us: 6.912 }
costs { name: "loop_power_fusion.3" cost_us: 1.6 }
costs { name: "all-reduce-start.14" cost_us: 265.183 }
costs { name: "all-reduce-start.16" cost_us: 434.655 }
costs { name: "all-reduce-start.4" cost_us: 4072.239 }
costs { name: "all-reduce-start.5" cost_us: 5848.713 }
costs { name: "input_reduce_fusion.201" cost_us: 4.288 }
costs { name: "input_transpose_fusion.24" cost_us: 3.456 }
costs { name: "input_transpose_fusion.25" cost_us: 3.68 }
costs { name: "wrapped_slice.91" cost_us: 1.504 }
costs { name: "custom-call.65.0" cost_us: 11297.49 }
costs { name: "custom-call.66.0" cost_us: 10485.336 }
costs { name: "custom-call.67.0" cost_us: 9079.262 }
costs { name: "copy_fusion.1" cost_us: 13.344 }
costs { name: "copy_fusion.2" cost_us: 3.36 }
costs { name: "input_add_reduce_fusion.1" cost_us: 732.189 }
costs { name: "input_add_reduce_fusion.17" cost_us: 746.876 }
costs { name: "input_add_reduce_fusion.18" cost_us: 753.053 }
costs { name: "input_convert_reduce_fusion" cost_us: 11.36 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 10.848 }
costs { name: "input_convert_reduce_fusion.10" cost_us: 8.672 }
costs { name: "input_convert_reduce_fusion.11" cost_us: 8.8 }
costs { name: "input_convert_reduce_fusion.12" cost_us: 8.032 }
costs { name: "input_convert_reduce_fusion.13" cost_us: 8.096 }
costs { name: "input_convert_reduce_fusion.14" cost_us: 6.944 }
costs { name: "input_convert_reduce_fusion.15" cost_us: 7.04 }
costs { name: "input_convert_reduce_fusion.2" cost_us: 10.144 }
costs { name: "input_convert_reduce_fusion.3" cost_us: 9.056 }
costs { name: "input_convert_reduce_fusion.4" cost_us: 9.056 }
costs { name: "input_convert_reduce_fusion.5" cost_us: 7.072 }
costs { name: "input_convert_reduce_fusion.6" cost_us: 7.04 }
costs { name: "input_convert_reduce_fusion.9" cost_us: 8.64 }
costs { name: "input_reduce_fusion.100" cost_us: 2.112 }
costs { name: "input_reduce_fusion.101" cost_us: 2.687 }
costs { name: "input_reduce_fusion.102" cost_us: 1.856 }
costs { name: "input_reduce_fusion.103" cost_us: 2.4 }
costs { name: "input_reduce_fusion.104" cost_us: 2.144 }
costs { name: "input_reduce_fusion.105" cost_us: 2.591 }
costs { name: "input_reduce_fusion.106" cost_us: 2.527 }
costs { name: "input_reduce_fusion.107" cost_us: 2.496 }
costs { name: "input_reduce_fusion.108" cost_us: 2.24 }
costs { name: "input_reduce_fusion.109" cost_us: 2.144 }
costs { name: "input_reduce_fusion.110" cost_us: 2.432 }
costs { name: "input_reduce_fusion.111" cost_us: 1.919 }
costs { name: "input_reduce_fusion.112" cost_us: 2.56 }
costs { name: "input_reduce_fusion.113" cost_us: 2.112 }
costs { name: "input_reduce_fusion.114" cost_us: 2.272 }
costs { name: "input_reduce_fusion.115" cost_us: 2.528 }
costs { name: "input_reduce_fusion.116" cost_us: 2.464 }
costs { name: "input_reduce_fusion.16" cost_us: 1.728 }
costs { name: "input_reduce_fusion.17" cost_us: 1.76 }
costs { name: "input_reduce_fusion.177" cost_us: 92.704 }
costs { name: "input_reduce_fusion.18" cost_us: 1.76 }
costs { name: "input_reduce_fusion.180" cost_us: 92.672 }
costs { name: "input_reduce_fusion.188" cost_us: 6.208 }
costs { name: "input_reduce_fusion.189" cost_us: 6.304 }
costs { name: "input_reduce_fusion.19" cost_us: 1.76 }
costs { name: "input_reduce_fusion.190" cost_us: 6.24 }
costs { name: "input_reduce_fusion.191" cost_us: 3.584 }
costs { name: "input_reduce_fusion.192" cost_us: 3.743 }
costs { name: "input_reduce_fusion.193" cost_us: 2.592 }
costs { name: "input_reduce_fusion.194" cost_us: 2.72 }
costs { name: "input_reduce_fusion.20" cost_us: 2.272 }
costs { name: "input_reduce_fusion.21" cost_us: 1.76 }
costs { name: "input_reduce_fusion.22" cost_us: 2.272 }
costs { name: "input_reduce_fusion.23" cost_us: 1.76 }
costs { name: "input_reduce_fusion.24" cost_us: 2.304 }
costs { name: "input_reduce_fusion.25" cost_us: 1.727 }
costs { name: "input_reduce_fusion.26" cost_us: 1.76 }
costs { name: "input_reduce_fusion.27" cost_us: 1.727 }
costs { name: "input_reduce_fusion.28" cost_us: 1.76 }
costs { name: "input_reduce_fusion.29" cost_us: 2.303 }
costs { name: "input_reduce_fusion.30" cost_us: 1.76 }
costs { name: "input_reduce_fusion.31" cost_us: 2.336 }
costs { name: "input_reduce_fusion.32" cost_us: 1.76 }
costs { name: "input_reduce_fusion.33" cost_us: 2.304 }
costs { name: "input_reduce_fusion.34" cost_us: 1.728 }
costs { name: "input_reduce_fusion.35" cost_us: 2.24 }
costs { name: "input_reduce_fusion.36" cost_us: 1.791 }
costs { name: "input_reduce_fusion.40" cost_us: 89.568 }
costs { name: "input_reduce_fusion.47" cost_us: 2.304 }
costs { name: "input_reduce_fusion.48" cost_us: 2.048 }
costs { name: "input_reduce_fusion.49" cost_us: 1.92 }
costs { name: "input_reduce_fusion.50" cost_us: 2.016 }
costs { name: "input_reduce_fusion.51" cost_us: 1.824 }
costs { name: "input_reduce_fusion.52" cost_us: 1.856 }
costs { name: "input_reduce_fusion.53" cost_us: 1.824 }
costs { name: "input_reduce_fusion.54" cost_us: 1.92 }
costs { name: "input_reduce_fusion.55" cost_us: 1.856 }
costs { name: "input_reduce_fusion.56" cost_us: 1.887 }
costs { name: "input_reduce_fusion.57" cost_us: 1.856 }
costs { name: "input_reduce_fusion.58" cost_us: 1.856 }
costs { name: "input_reduce_fusion.59" cost_us: 1.823 }
costs { name: "input_reduce_fusion.60" cost_us: 1.856 }
costs { name: "input_reduce_fusion.61" cost_us: 1.855 }
costs { name: "input_reduce_fusion.62" cost_us: 1.92 }
costs { name: "input_reduce_fusion.63" cost_us: 1.888 }
costs { name: "input_reduce_fusion.64" cost_us: 1.857 }
costs { name: "input_reduce_fusion.65" cost_us: 1.824 }
costs { name: "input_reduce_fusion.66" cost_us: 2.111 }
costs { name: "input_reduce_fusion.67" cost_us: 1.856 }
costs { name: "input_reduce_fusion.68" cost_us: 2.048 }
costs { name: "input_reduce_fusion.69" cost_us: 1.92 }
costs { name: "input_reduce_fusion.70" cost_us: 1.856 }
costs { name: "input_reduce_fusion.71" cost_us: 1.888 }
costs { name: "input_reduce_fusion.72" cost_us: 1.92 }
costs { name: "input_reduce_fusion.73" cost_us: 1.92 }
costs { name: "input_reduce_fusion.74" cost_us: 1.888 }
costs { name: "input_reduce_fusion.96" cost_us: 1.696 }
costs { name: "input_reduce_fusion.97" cost_us: 1.76 }
costs { name: "input_reduce_fusion.98" cost_us: 1.664 }
costs { name: "input_reduce_fusion.99" cost_us: 2.305 }
costs { name: "input_transpose_fusion.14" cost_us: 1251.483 }
costs { name: "input_transpose_fusion.3" cost_us: 1166.235 }
costs { name: "input_transpose_fusion.7" cost_us: 1273.339 }
costs { name: "loop_convert_fusion.100" cost_us: 1.951 }
costs { name: "loop_convert_fusion.101" cost_us: 1.824 }
costs { name: "loop_convert_fusion.102" cost_us: 1.728 }
costs { name: "loop_convert_fusion.103" cost_us: 1.76 }
costs { name: "loop_convert_fusion.104" cost_us: 1.952 }
costs { name: "loop_convert_fusion.105" cost_us: 1.76 }
costs { name: "loop_convert_fusion.106" cost_us: 1.76 }
costs { name: "loop_convert_fusion.107" cost_us: 1.888 }
costs { name: "loop_convert_fusion.117" cost_us: 8.0 }
costs { name: "loop_convert_fusion.118" cost_us: 8.096 }
costs { name: "loop_convert_fusion.119" cost_us: 8.064 }
costs { name: "loop_convert_fusion.125" cost_us: 3.904 }
costs { name: "loop_convert_fusion.126" cost_us: 3.776 }
costs { name: "loop_convert_fusion.129" cost_us: 2.208 }
costs { name: "loop_convert_fusion.130" cost_us: 2.208 }
costs { name: "loop_convert_fusion.131" cost_us: 2.368 }
costs { name: "loop_convert_fusion.132" cost_us: 1.952 }
costs { name: "loop_convert_fusion.135" cost_us: 2.272 }
costs { name: "loop_convert_fusion.136" cost_us: 2.016 }
costs { name: "loop_convert_fusion.140" cost_us: 1.472 }
costs { name: "loop_convert_fusion.141" cost_us: 1.472 }
costs { name: "loop_convert_fusion.142" cost_us: 1.472 }
costs { name: "loop_convert_fusion.28" cost_us: 1.536 }
costs { name: "loop_convert_fusion.29" cost_us: 1.567 }
costs { name: "loop_convert_fusion.30" cost_us: 1.664 }
costs { name: "loop_convert_fusion.31" cost_us: 1.663 }
costs { name: "loop_convert_fusion.32" cost_us: 1.664 }
costs { name: "loop_convert_fusion.33" cost_us: 1.6 }
costs { name: "loop_convert_fusion.34" cost_us: 1.567 }
costs { name: "loop_convert_fusion.35" cost_us: 1.567 }
costs { name: "loop_convert_fusion.36" cost_us: 1.567 }
costs { name: "loop_convert_fusion.37" cost_us: 1.567 }
costs { name: "loop_convert_fusion.38" cost_us: 1.663 }
costs { name: "loop_convert_fusion.39" cost_us: 1.567 }
costs { name: "loop_convert_fusion.40" cost_us: 1.536 }
costs { name: "loop_convert_fusion.41" cost_us: 1.664 }
costs { name: "loop_convert_fusion.42" cost_us: 1.567 }
costs { name: "loop_convert_fusion.43" cost_us: 1.568 }
costs { name: "loop_convert_fusion.44" cost_us: 1.567 }
costs { name: "loop_convert_fusion.45" cost_us: 1.632 }
costs { name: "loop_convert_fusion.47" cost_us: 1.824 }
costs { name: "loop_convert_fusion.48" cost_us: 1.792 }
costs { name: "loop_convert_fusion.49" cost_us: 1.697 }
costs { name: "loop_convert_fusion.50" cost_us: 1.727 }
costs { name: "loop_convert_fusion.51" cost_us: 1.6 }
costs { name: "loop_convert_fusion.52" cost_us: 1.6 }
costs { name: "loop_convert_fusion.53" cost_us: 1.632 }
costs { name: "loop_convert_fusion.54" cost_us: 1.728 }
costs { name: "loop_convert_fusion.55" cost_us: 2.304 }
costs { name: "loop_convert_fusion.56" cost_us: 2.08 }
costs { name: "loop_convert_fusion.57" cost_us: 1.824 }
costs { name: "loop_convert_fusion.58" cost_us: 1.824 }
costs { name: "loop_convert_fusion.59" cost_us: 2.016 }
costs { name: "loop_convert_fusion.60" cost_us: 2.144 }
costs { name: "loop_convert_fusion.61" cost_us: 2.208 }
costs { name: "loop_convert_fusion.62" cost_us: 1.472 }
costs { name: "loop_convert_fusion.63" cost_us: 1.44 }
costs { name: "loop_convert_fusion.64" cost_us: 1.44 }
costs { name: "loop_convert_fusion.65" cost_us: 1.728 }
costs { name: "loop_convert_fusion.66" cost_us: 2.336 }
costs { name: "loop_convert_fusion.67" cost_us: 2.272 }
costs { name: "loop_convert_fusion.68" cost_us: 1.792 }
costs { name: "loop_convert_fusion.69" cost_us: 2.303 }
costs { name: "loop_convert_fusion.70" cost_us: 1.6 }
costs { name: "loop_convert_fusion.71" cost_us: 1.567 }
costs { name: "loop_convert_fusion.72" cost_us: 2.176 }
costs { name: "loop_convert_fusion.87" cost_us: 1.632 }
costs { name: "loop_convert_fusion.88" cost_us: 1.664 }
costs { name: "loop_convert_fusion.89" cost_us: 1.76 }
costs { name: "loop_convert_fusion.90" cost_us: 1.887 }
costs { name: "loop_convert_fusion.91" cost_us: 1.6 }
costs { name: "loop_convert_fusion.92" cost_us: 1.792 }
costs { name: "loop_convert_fusion.93" cost_us: 1.664 }
costs { name: "loop_convert_fusion.94" cost_us: 1.728 }
costs { name: "loop_convert_fusion.95" cost_us: 1.696 }
costs { name: "loop_convert_fusion.96" cost_us: 1.824 }
costs { name: "loop_convert_fusion.97" cost_us: 1.76 }
costs { name: "loop_convert_fusion.98" cost_us: 1.856 }
costs { name: "loop_convert_fusion.99" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 1.376 }
costs { name: "loop_dynamic_update_slice_fusion.111" cost_us: 14.24 }
costs { name: "loop_dynamic_update_slice_fusion.112" cost_us: 3.424 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 1.471 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.17" cost_us: 1.439 }
costs { name: "loop_dynamic_update_slice_fusion.18" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.19" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.20" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.21" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.22" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.23" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.24" cost_us: 1.408 }
costs { name: "loop_dynamic_update_slice_fusion.25" cost_us: 4.0 }
costs { name: "loop_dynamic_update_slice_fusion.26" cost_us: 9.984 }
costs { name: "loop_dynamic_update_slice_fusion.34" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.35" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.36" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.37" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.38" cost_us: 1.631 }
costs { name: "loop_dynamic_update_slice_fusion.39" cost_us: 1.855 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.40" cost_us: 1.728 }
costs { name: "loop_dynamic_update_slice_fusion.41" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.42" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.43" cost_us: 1.633 }
costs { name: "loop_dynamic_update_slice_fusion.44" cost_us: 1.567 }
costs { name: "loop_dynamic_update_slice_fusion.45" cost_us: 1.823 }
costs { name: "loop_dynamic_update_slice_fusion.46" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.47" cost_us: 1.568 }
costs { name: "loop_dynamic_update_slice_fusion.48" cost_us: 1.727 }
costs { name: "loop_dynamic_update_slice_fusion.49" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.50" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.51" cost_us: 1.727 }
costs { name: "loop_dynamic_update_slice_fusion.52" cost_us: 1.632 }
costs { name: "loop_dynamic_update_slice_fusion.53" cost_us: 1.599 }
costs { name: "loop_dynamic_update_slice_fusion.54" cost_us: 1.823 }
costs { name: "loop_dynamic_update_slice_fusion.55" cost_us: 106.016 }
costs { name: "loop_dynamic_update_slice_fusion.56" cost_us: 380.99 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 1.44 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 1.439 }
costs { name: "loop_dynamic_update_slice_fusion.82" cost_us: 112.224 }
costs { name: "loop_dynamic_update_slice_fusion.83" cost_us: 387.742 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 1.407 }
costs { name: "loop_select_fusion" cost_us: 1.248 }
costs { name: "loop_select_fusion.3" cost_us: 1.408 }
costs { name: "loop_select_fusion.4" cost_us: 1.856 }
costs { name: "loop_add_fusion.1" cost_us: 1.247 }
costs { name: "loop_add_fusion.3" cost_us: 1.536 }
costs { name: "loop_dynamic_update_slice_fusion.110" cost_us: 1.6 }
costs { name: "loop_dynamic_update_slice_fusion.32" cost_us: 1.696 }
costs { name: "loop_dynamic_update_slice_fusion.33" cost_us: 1.632 }
costs { name: "loop_dynamic_update_slice_fusion.27" cost_us: 10.016 }
costs { name: "loop_dynamic_update_slice_fusion.28" cost_us: 9.984 }
costs { name: "loop_dynamic_update_slice_fusion.84" cost_us: 10.24 }
costs { name: "loop_dynamic_update_slice_fusion.85" cost_us: 10.24 }
costs { name: "loop_dynamic_update_slice_fusion.29" cost_us: 3.936 }
costs { name: "loop_dynamic_update_slice_fusion.86" cost_us: 4.064 }
costs { name: "loop_dynamic_update_slice_fusion.30" cost_us: 1.952 }
costs { name: "loop_dynamic_update_slice_fusion.31" cost_us: 1.92 }
costs { name: "loop_dynamic_update_slice_fusion.87" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.88" cost_us: 1.856 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 2641.238 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 2778.07 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 2686.869 }
costs { name: "input_add_reduce_fusion" cost_us: 415.838 }
costs { name: "input_add_reduce_fusion.15" cost_us: 423.167 }
costs { name: "input_add_reduce_fusion.16" cost_us: 429.758 }
costs { name: "input_convert_transpose_fusion.14" cost_us: 817.949 }
costs { name: "input_convert_transpose_fusion.17" cost_us: 398.559 }
costs { name: "input_convert_transpose_fusion.23" cost_us: 812.157 }
costs { name: "input_convert_transpose_fusion.26" cost_us: 396.222 }
costs { name: "input_convert_transpose_fusion.5" cost_us: 803.741 }
costs { name: "input_convert_transpose_fusion.8" cost_us: 387.615 }
costs { name: "input_reduce_fusion.176" cost_us: 336.543 }
costs { name: "input_reduce_fusion.179" cost_us: 265.151 }
costs { name: "input_reduce_fusion.182" cost_us: 264.415 }
costs { name: "input_reduce_fusion.183" cost_us: 333.246 }
costs { name: "input_reduce_fusion.184" cost_us: 53.311 }
costs { name: "input_reduce_fusion.185" cost_us: 12.864 }
costs { name: "input_reduce_fusion.186" cost_us: 52.48 }
costs { name: "input_reduce_fusion.187" cost_us: 12.704 }
costs { name: "input_reduce_fusion.42" cost_us: 244.383 }
costs { name: "input_reduce_fusion.43" cost_us: 326.558 }
costs { name: "input_reduce_fusion.44" cost_us: 49.759 }
costs { name: "input_reduce_fusion.45" cost_us: 12.544 }
costs { name: "input_transpose_fusion.15" cost_us: 1299.323 }
costs { name: "input_transpose_fusion.4" cost_us: 1240.091 }
costs { name: "input_transpose_fusion.8" cost_us: 1299.483 }
costs { name: "loop_multiply_fusion.1" cost_us: 2.111 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.24 }
costs { name: "loop_multiply_fusion.6" cost_us: 2.271 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.08 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.336 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.24 }
costs { name: "input_convert_transpose_fusion.12" cost_us: 264.479 }
costs { name: "input_convert_transpose_fusion.21" cost_us: 263.167 }
costs { name: "input_convert_transpose_fusion.3" cost_us: 252.703 }
costs { name: "input_reduce_fusion.198" cost_us: 7.775 }
costs { name: "input_reduce_fusion.199" cost_us: 4.48 }
costs { name: "input_reduce_fusion.46" cost_us: 7.648 }
costs { name: "input_convert_transpose_fusion.13" cost_us: 889.628 }
costs { name: "input_convert_transpose_fusion.22" cost_us: 920.157 }
costs { name: "input_convert_transpose_fusion.4" cost_us: 885.82 }
costs { name: "cublas-gemm.110.0" cost_us: 4707.822 }
costs { name: "cublas-gemm.127.0" cost_us: 4742.574 }
costs { name: "cublas-gemm.62.0" cost_us: 5126.893 }
costs { name: "cublas-gemm.118.0" cost_us: 4708.751 }
costs { name: "cublas-gemm.135.0" cost_us: 4907.054 }
costs { name: "cublas-gemm.68.0" cost_us: 5012.715 }
costs { name: "input_convert_transpose_fusion.15" cost_us: 887.325 }
costs { name: "input_convert_transpose_fusion.24" cost_us: 917.693 }
costs { name: "input_convert_transpose_fusion.6" cost_us: 879.773 }
costs { name: "cublas-gemm.111.0" cost_us: 4850.605 }
costs { name: "cublas-gemm.128.0" cost_us: 5171.084 }
costs { name: "cublas-gemm.63.0" cost_us: 5196.588 }
costs { name: "cublas-gemm.119.0" cost_us: 4662.126 }
costs { name: "cublas-gemm.136.0" cost_us: 4953.837 }
costs { name: "cublas-gemm.69.0" cost_us: 5085.228 }
costs { name: "input_convert_transpose_fusion.16" cost_us: 253.407 }
costs { name: "input_convert_transpose_fusion.25" cost_us: 263.999 }
costs { name: "input_convert_transpose_fusion.7" cost_us: 254.143 }
costs { name: "cublas-gemm.108.0" cost_us: 4955.692 }
costs { name: "cublas-gemm.125.0" cost_us: 5020.621 }
costs { name: "cublas-gemm.60.0" cost_us: 5511.212 }
costs { name: "input_transpose_fusion.10" cost_us: 234.655 }
costs { name: "input_transpose_fusion.17" cost_us: 247.999 }
costs { name: "input_transpose_fusion.6" cost_us: 234.719 }
costs { name: "cublas-gemm.116.0" cost_us: 4688.686 }
costs { name: "cublas-gemm.133.0" cost_us: 4906.093 }
costs { name: "cublas-gemm.70.0" cost_us: 4902.572 }
costs { name: "all-reduce-start.1" cost_us: 186.687 }
costs { name: "all-reduce-start.10" cost_us: 1026.62 }
costs { name: "input_reduce_fusion.200" cost_us: 4.353 }
costs { name: "wrapped_slice.23" cost_us: 1.44 }
costs { name: "wrapped_slice.85" cost_us: 1.568 }
costs { name: "wrapped_slice.88" cost_us: 1.12 }
costs { name: "all-reduce-start.15" cost_us: 3467.154 }
costs { name: "wrapped_slice.24" cost_us: 1.024 }
costs { name: "wrapped_slice.86" cost_us: 1.567 }
costs { name: "wrapped_slice.87" cost_us: 1.504 }
costs { name: "input_convert_transpose_fusion" cost_us: 604.286 }
costs { name: "input_convert_transpose_fusion.1" cost_us: 80.064 }
costs { name: "input_convert_transpose_fusion.10" cost_us: 86.912 }
costs { name: "input_convert_transpose_fusion.18" cost_us: 660.253 }
costs { name: "input_convert_transpose_fusion.19" cost_us: 86.976 }
costs { name: "input_convert_transpose_fusion.9" cost_us: 655.261 }
costs { name: "custom-call.69.0" cost_us: 4410.384 }
costs { name: "custom-call.69.0" cost_us: 2304.632 }
costs { name: "custom-call.69.0" cost_us: 99.647 }
costs { name: "custom-call.69.0" cost_us: 178.943 }
costs { name: "custom-call.75.0" cost_us: 3946.129 }
costs { name: "custom-call.75.0" cost_us: 2233.111 }
costs { name: "custom-call.75.0" cost_us: 98.623 }
costs { name: "custom-call.75.0" cost_us: 178.015 }
costs { name: "custom-call.77.0" cost_us: 4451.759 }
costs { name: "custom-call.77.0" cost_us: 2299.415 }
costs { name: "custom-call.77.0" cost_us: 99.68 }
costs { name: "custom-call.77.0" cost_us: 179.135 }
costs { name: "cublas-gemm.120.0" cost_us: 170.079 }
costs { name: "cublas-gemm.137.0" cost_us: 182.175 }
costs { name: "cublas-gemm.71.0" cost_us: 180.255 }
costs { name: "cublas-gemm.113.0" cost_us: 255.36 }
costs { name: "cublas-gemm.130.0" cost_us: 280.479 }
costs { name: "cublas-gemm.65.0" cost_us: 283.231 }
costs { name: "input_convert_transpose_fusion.11" cost_us: 37.504 }
costs { name: "input_convert_transpose_fusion.2" cost_us: 33.856 }
costs { name: "input_convert_transpose_fusion.20" cost_us: 37.759 }
costs { name: "cublas-gemm.122.0" cost_us: 170.015 }
costs { name: "cublas-gemm.139.0" cost_us: 184.575 }
costs { name: "cublas-gemm.74.0" cost_us: 180.128 }
costs { name: "cublas-gemm.114.0" cost_us: 281.246 }
costs { name: "cublas-gemm.131.0" cost_us: 311.167 }
costs { name: "cublas-gemm.66.0" cost_us: 315.743 }
costs { name: "cublas-gemm.117.0" cost_us: 1370.843 }
costs { name: "cublas-gemm.134.0" cost_us: 1423.355 }
costs { name: "cublas-gemm.72.0" cost_us: 1418.331 }
costs { name: "cublas-gemm.112.0" cost_us: 1377.723 }
costs { name: "cublas-gemm.129.0" cost_us: 1464.73 }
costs { name: "cublas-gemm.64.0" cost_us: 1455.803 }
costs { name: "input_transpose_fusion.16" cost_us: 71.487 }
costs { name: "input_transpose_fusion.5" cost_us: 66.464 }
costs { name: "input_transpose_fusion.9" cost_us: 71.36 }
costs { name: "cublas-gemm.121.0" cost_us: 1364.155 }
costs { name: "cublas-gemm.138.0" cost_us: 1494.747 }
costs { name: "cublas-gemm.73.0" cost_us: 1463.098 }
costs { name: "cublas-gemm.115.0" cost_us: 1371.995 }
costs { name: "cublas-gemm.132.0" cost_us: 1442.298 }
costs { name: "cublas-gemm.67.0" cost_us: 1449.051 }
costs { name: "input_reduce_fusion.178" cost_us: 84.511 }
costs { name: "input_reduce_fusion.181" cost_us: 83.968 }
costs { name: "input_reduce_fusion.41" cost_us: 90.752 }
costs { name: "cublas-gemm.107.0" cost_us: 4964.685 }
costs { name: "cublas-gemm.124.0" cost_us: 4988.396 }
costs { name: "cublas-gemm.59.0" cost_us: 4980.204 }
costs { name: "wrapped_transpose.17" cost_us: 232.415 }
costs { name: "wrapped_transpose.19" cost_us: 233.695 }
costs { name: "wrapped_transpose.21" cost_us: 234.24 }
costs { name: "all-reduce-start.12" cost_us: 97.344 }
costs { name: "all-reduce-start.3" cost_us: 697.245 }
costs { name: "all-reduce-start.8" cost_us: 3753.554 }
costs { name: "all-reduce-start.11" cost_us: 2734.229 }
costs { name: "all-reduce-start.2" cost_us: 1180.156 }
costs { name: "all-reduce-start.7" cost_us: 4923.788 }
costs { name: "cublas-gemm.109.0" cost_us: 4972.396 }
costs { name: "cublas-gemm.126.0" cost_us: 4986.189 }
costs { name: "cublas-gemm.61.0" cost_us: 4967.499 }
costs { name: "wrapped_transpose.18" cost_us: 234.623 }
costs { name: "wrapped_transpose.20" cost_us: 233.503 }
costs { name: "wrapped_transpose.22" cost_us: 235.071 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.015 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.208 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.176 }
costs { name: "custom-call.68.0" cost_us: 1911.833 }
costs { name: "custom-call.68.0" cost_us: 1.696 }
costs { name: "custom-call.74.0" cost_us: 1868.345 }
costs { name: "custom-call.74.0" cost_us: 2.015 }
costs { name: "custom-call.76.0" cost_us: 1934.456 }
costs { name: "custom-call.76.0" cost_us: 1.953 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.12 }
costs { name: "loop_broadcast_fusion.11" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.13" cost_us: 1.471 }
costs { name: "loop_multiply_fusion.2" cost_us: 1.343 }
costs { name: "loop_multiply_fusion.7" cost_us: 1.504 }
costs { name: "loop_multiply_fusion.9" cost_us: 1.504 }
costs { name: "loop_convert_fusion.121" cost_us: 6.849 }
costs { name: "loop_convert_fusion.122" cost_us: 6.816 }
costs { name: "loop_convert_fusion.46" cost_us: 6.624 }
costs { name: "loop_power_fusion" cost_us: 1.184 }
costs { name: "loop_power_fusion.1" cost_us: 1.569 }
costs { name: "loop_power_fusion.2" cost_us: 1.44 }
costs { name: "cublas-gemm.106.0" cost_us: 1512.058 }
costs { name: "cublas-gemm.123.0" cost_us: 1531.003 }
costs { name: "cublas-gemm.58.0" cost_us: 1530.489 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 188.255 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 188.735 }
costs { name: "loop_dynamic_slice_fusion.6" cost_us: 188.607 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 24.608 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 24.513 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 24.192 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 24.416 }
costs { name: "loop_dynamic_slice_fusion.7" cost_us: 25.056 }
costs { name: "loop_dynamic_slice_fusion.8" cost_us: 25.568 }
costs { name: "loop_transpose_fusion" cost_us: 124.415 }
costs { name: "loop_divide_fusion" cost_us: 1.44 }
costs { name: "wrapped_transpose.6" cost_us: 389.823 }
costs { name: "wrapped_transpose.7" cost_us: 389.023 }
costs { name: "wrapped_transpose.8" cost_us: 417.95 }
costs { name: "wrapped_transpose" cost_us: 3.296 }
costs { name: "wrapped_transpose.1" cost_us: 3.296 }
costs { name: "wrapped_transpose.3" cost_us: 14.272 }
costs { name: "wrapped_transpose.5" cost_us: 416.511 }
costs { name: "wrapped_transpose.2" cost_us: 112.896 }
costs { name: "wrapped_transpose.4" cost_us: 15.648 }
