costs { name: "all-gather-start" cost_us: 24171.405 }
costs { name: "all-gather-start.1" cost_us: 22819.181 }
costs { name: "all-gather-start.2" cost_us: 25945.424 }
costs { name: "all-gather-start.3" cost_us: 25269.359 }
costs { name: "all-gather-start.4" cost_us: 22607.119 }
costs { name: "all-gather-start.5" cost_us: 20980.588 }
costs { name: "all-gather-start.6" cost_us: 38299.42 }
costs { name: "all-gather-start.7" cost_us: 30227.51 }
costs { name: "all-gather-start.8" cost_us: 22748.845 }
costs { name: "all-gather-start.9" cost_us: 22969.612 }
costs { name: "input_transpose_fusion" cost_us: 204.352 }
costs { name: "input_transpose_fusion.1" cost_us: 4.864 }
costs { name: "input_transpose_fusion.2" cost_us: 6.88 }
costs { name: "loop_add_fusion.1" cost_us: 1.408 }
costs { name: "loop_add_fusion.1.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_fusion.5" cost_us: 1.44 }
costs { name: "loop_add_fusion.5.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_broadcast_fusion" cost_us: 1.536 }
costs { name: "loop_broadcast_fusion.2" cost_us: 842.721 }
costs { name: "loop_broadcast_fusion.3" cost_us: 6746.501 }
costs { name: "loop_broadcast_fusion.4" cost_us: 6741.38 }
costs { name: "loop_transpose_fusion" cost_us: 57.024 }
costs { name: "reduce-scatter.58.double_buffer_clone.1" cost_us: 22297.518 }
costs { name: "reduce-scatter.58.peeled_double_buffer.1" cost_us: 28506.608 }
costs { name: "reduce-scatter.61" cost_us: 22662.862 }
costs { name: "reduce-scatter.62" cost_us: 27555.153 }
costs { name: "reduce-scatter.63" cost_us: 55011.417 }
costs { name: "wrapped_concatenate" cost_us: 1.504 }
costs { name: "wrapped_concatenate.1" cost_us: 1.6 }
costs { name: "wrapped_concatenate.2" cost_us: 1.76 }
costs { name: "wrapped_concatenate.3" cost_us: 1.824 }
costs { name: "wrapped_concatenate.4" cost_us: 1.76 }
costs { name: "wrapped_concatenate.5" cost_us: 2.305 }
costs { name: "wrapped_concatenate.6" cost_us: 2.56 }
costs { name: "wrapped_slice.16" cost_us: 1.28 }
costs { name: "wrapped_slice.17" cost_us: 1.28 }
costs { name: "wrapped_slice.18" cost_us: 1.248 }
costs { name: "wrapped_slice.19" cost_us: 1.28 }
costs { name: "wrapped_slice.20" cost_us: 1.28 }
costs { name: "wrapped_slice.21" cost_us: 1.248 }
costs { name: "wrapped_slice.26" cost_us: 1.28 }
costs { name: "wrapped_slice.27" cost_us: 1.248 }
costs { name: "wrapped_slice.29" cost_us: 1.28 }
costs { name: "wrapped_slice.30" cost_us: 1.408 }
costs { name: "wrapped_slice.31" cost_us: 1.248 }
costs { name: "wrapped_slice.32" cost_us: 1.248 }
costs { name: "wrapped_slice.33" cost_us: 1.248 }
costs { name: "wrapped_slice.34" cost_us: 1.28 }
costs { name: "wrapped_slice.35" cost_us: 1.248 }
costs { name: "wrapped_slice.36" cost_us: 1.248 }
costs { name: "wrapped_slice.37" cost_us: 1.28 }
costs { name: "wrapped_slice.38" cost_us: 1.28 }
costs { name: "wrapped_slice.39" cost_us: 1.248 }
costs { name: "wrapped_slice.40" cost_us: 1.248 }
costs { name: "wrapped_slice.41" cost_us: 1.248 }
costs { name: "wrapped_slice.42" cost_us: 1.216 }
costs { name: "wrapped_slice.43" cost_us: 1.28 }
costs { name: "wrapped_slice.44" cost_us: 1.248 }
costs { name: "wrapped_slice.45" cost_us: 1.248 }
costs { name: "wrapped_slice.46" cost_us: 1.248 }
costs { name: "wrapped_slice.47" cost_us: 1.248 }
costs { name: "wrapped_slice.48" cost_us: 1.216 }
costs { name: "wrapped_slice.49" cost_us: 1.248 }
costs { name: "wrapped_slice.50" cost_us: 1.248 }
costs { name: "wrapped_slice.51" cost_us: 1.248 }
costs { name: "wrapped_slice.52" cost_us: 1.248 }
costs { name: "wrapped_slice.53" cost_us: 1.248 }
costs { name: "wrapped_slice.54" cost_us: 1.28 }
costs { name: "wrapped_slice.55" cost_us: 1.216 }
costs { name: "wrapped_slice.56" cost_us: 1.216 }
costs { name: "wrapped_slice.57" cost_us: 1.408 }
costs { name: "wrapped_transpose.10" cost_us: 11.264 }
costs { name: "wrapped_transpose.11" cost_us: 103.008 }
costs { name: "wrapped_transpose.12" cost_us: 11.008 }
costs { name: "wrapped_transpose.13" cost_us: 361.568 }
costs { name: "wrapped_transpose.14" cost_us: 14.112 }
costs { name: "wrapped_transpose.15" cost_us: 103.968 }
costs { name: "wrapped_transpose.16" cost_us: 15.52 }
costs { name: "wrapped_transpose.17" cost_us: 365.376 }
costs { name: "wrapped_transpose.18" cost_us: 14.976 }
costs { name: "wrapped_transpose.19" cost_us: 102.721 }
costs { name: "wrapped_transpose.20" cost_us: 14.272 }
costs { name: "wrapped_transpose.21" cost_us: 15.584 }
costs { name: "wrapped_transpose.22" cost_us: 106.144 }
costs { name: "wrapped_transpose.23" cost_us: 14.593 }
costs { name: "wrapped_transpose.24" cost_us: 370.08 }
costs { name: "wrapped_transpose.25" cost_us: 3.616 }
costs { name: "wrapped_transpose.26" cost_us: 3.872 }
costs { name: "wrapped_transpose.27" cost_us: 4.0 }
costs { name: "wrapped_transpose.28" cost_us: 4.448 }
costs { name: "wrapped_transpose.29" cost_us: 4.352 }
costs { name: "wrapped_transpose.9" cost_us: 367.136 }
costs { name: "wrapped_select" cost_us: 1.44 }
costs { name: "loop_add_fusion" cost_us: 1.248 }
costs { name: "wrapped_add" cost_us: 1.408 }
costs { name: "loop_minimum_fusion" cost_us: 1.472 }
costs { name: "wrapped_cosine" cost_us: 1.312 }
costs { name: "input_reduce_fusion" cost_us: 1.568 }
costs { name: "loop_xor_fusion" cost_us: 1.952 }
costs { name: "wrapped_multiply" cost_us: 1.216 }
costs { name: "loop_subtract_fusion" cost_us: 1.28 }
costs { name: "input_add_reduce_fusion.1" cost_us: 22.24 }
costs { name: "input_add_reduce_fusion.10" cost_us: 767.233 }
costs { name: "input_add_reduce_fusion.14" cost_us: 26.176 }
costs { name: "input_add_reduce_fusion.15" cost_us: 26.175 }
costs { name: "input_add_reduce_fusion.16" cost_us: 6.24 }
costs { name: "input_add_reduce_fusion.2" cost_us: 10.656 }
costs { name: "input_add_reduce_fusion.3" cost_us: 201.056 }
costs { name: "input_add_reduce_fusion.4" cost_us: 201.92 }
costs { name: "input_add_reduce_fusion.5" cost_us: 10.657 }
costs { name: "input_add_reduce_fusion.6" cost_us: 13.92 }
costs { name: "input_add_reduce_fusion.7" cost_us: 13.728 }
costs { name: "input_add_reduce_fusion.8" cost_us: 689.6 }
costs { name: "input_add_reduce_fusion.9" cost_us: 764.448 }
costs { name: "input_compare_reduce_fusion" cost_us: 2.655 }
costs { name: "input_convert_reduce_fusion" cost_us: 2079.169 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 428.224 }
costs { name: "input_dynamic_slice_reduce_fusion" cost_us: 178.176 }
costs { name: "input_dynamic_slice_reduce_fusion.1" cost_us: 174.112 }
costs { name: "input_dynamic_slice_reduce_fusion.double_buffer_clone" cost_us: 178.208 }
costs { name: "input_dynamic_slice_reduce_fusion.peeled_double_buffer" cost_us: 176.864 }
costs { name: "input_reduce_fusion.10" cost_us: 7.905 }
costs { name: "input_reduce_fusion.11" cost_us: 39.841 }
costs { name: "input_reduce_fusion.12" cost_us: 46.816 }
costs { name: "input_reduce_fusion.13" cost_us: 8.032 }
costs { name: "input_reduce_fusion.14" cost_us: 5.632 }
costs { name: "input_reduce_fusion.15" cost_us: 5.824 }
costs { name: "input_reduce_fusion.16" cost_us: 136.448 }
costs { name: "input_reduce_fusion.17" cost_us: 137.344 }
costs { name: "input_reduce_fusion.18" cost_us: 139.104 }
costs { name: "input_reduce_fusion.19" cost_us: 484.417 }
costs { name: "input_reduce_fusion.2" cost_us: 252.32 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 256.096 }
costs { name: "input_reduce_fusion.2.peeled_double_buffer" cost_us: 256.064 }
costs { name: "input_reduce_fusion.20" cost_us: 1.984 }
costs { name: "input_reduce_fusion.21" cost_us: 363.84 }
costs { name: "input_reduce_fusion.24" cost_us: 256.928 }
costs { name: "input_reduce_fusion.25" cost_us: 86.08 }
costs { name: "input_reduce_fusion.26" cost_us: 169.44 }
costs { name: "input_reduce_fusion.27" cost_us: 258.112 }
costs { name: "input_reduce_fusion.28" cost_us: 85.825 }
costs { name: "input_reduce_fusion.29" cost_us: 169.44 }
costs { name: "input_reduce_fusion.3" cost_us: 84.768 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 85.152 }
costs { name: "input_reduce_fusion.3.peeled_double_buffer" cost_us: 85.312 }
costs { name: "input_reduce_fusion.30" cost_us: 261.184 }
costs { name: "input_reduce_fusion.31" cost_us: 85.632 }
costs { name: "input_reduce_fusion.32" cost_us: 169.824 }
costs { name: "input_reduce_fusion.34" cost_us: 169.632 }
costs { name: "input_reduce_fusion.35" cost_us: 1.984 }
costs { name: "input_reduce_fusion.36" cost_us: 1.632 }
costs { name: "input_reduce_fusion.37" cost_us: 5.92 }
costs { name: "input_reduce_fusion.4" cost_us: 169.441 }
costs { name: "input_reduce_fusion.4.double_buffer_clone" cost_us: 169.377 }
costs { name: "input_reduce_fusion.4.peeled_double_buffer" cost_us: 169.056 }
costs { name: "input_reduce_fusion.44" cost_us: 2.016 }
costs { name: "input_reduce_fusion.45" cost_us: 4.927 }
costs { name: "input_reduce_fusion.46" cost_us: 1.728 }
costs { name: "input_reduce_fusion.47" cost_us: 2.112 }
costs { name: "input_reduce_fusion.48" cost_us: 1.727 }
costs { name: "input_reduce_fusion.49" cost_us: 2.144 }
costs { name: "input_reduce_fusion.50" cost_us: 2.016 }
costs { name: "input_reduce_fusion.51" cost_us: 2.368 }
costs { name: "input_reduce_fusion.52" cost_us: 2.144 }
costs { name: "input_reduce_fusion.53" cost_us: 2.145 }
costs { name: "input_reduce_fusion.54" cost_us: 1.664 }
costs { name: "input_reduce_fusion.55" cost_us: 1.664 }
costs { name: "input_reduce_fusion.56" cost_us: 1.76 }
costs { name: "input_reduce_fusion.57" cost_us: 2.271 }
costs { name: "input_reduce_fusion.58" cost_us: 2.08 }
costs { name: "input_reduce_fusion.59" cost_us: 1.728 }
costs { name: "input_reduce_fusion.6" cost_us: 2.592 }
costs { name: "input_reduce_fusion.60" cost_us: 1.695 }
costs { name: "input_reduce_fusion.61" cost_us: 1.696 }
costs { name: "input_reduce_fusion.62" cost_us: 2.432 }
costs { name: "input_reduce_fusion.63" cost_us: 2.208 }
costs { name: "input_reduce_fusion.64" cost_us: 2.208 }
costs { name: "input_reduce_fusion.65" cost_us: 1.536 }
costs { name: "input_reduce_fusion.66" cost_us: 1.696 }
costs { name: "input_reduce_fusion.67" cost_us: 2.24 }
costs { name: "input_reduce_fusion.68" cost_us: 2.24 }
costs { name: "input_reduce_fusion.69" cost_us: 1.728 }
costs { name: "input_reduce_fusion.7" cost_us: 2.688 }
costs { name: "input_reduce_fusion.70" cost_us: 1.664 }
costs { name: "input_reduce_fusion.71" cost_us: 1.536 }
costs { name: "input_reduce_fusion.72" cost_us: 2.112 }
costs { name: "input_reduce_fusion.73" cost_us: 1.504 }
costs { name: "input_reduce_fusion.74" cost_us: 1.536 }
costs { name: "input_reduce_fusion.8" cost_us: 2.88 }
costs { name: "input_reduce_fusion.9" cost_us: 2.88 }
costs { name: "loop_add_fusion.12" cost_us: 7.232 }
costs { name: "loop_add_fusion.13" cost_us: 7.104 }
costs { name: "loop_add_log_fusion" cost_us: 1.984 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.568 }
costs { name: "loop_convert_fusion.28" cost_us: 7.424 }
costs { name: "loop_divide_fusion" cost_us: 1.6 }
costs { name: "loop_multiply_fusion.14" cost_us: 2.24 }
costs { name: "loop_multiply_fusion.18" cost_us: 1.472 }
costs { name: "loop_multiply_fusion.19" cost_us: 1.504 }
costs { name: "loop_select_fusion.1" cost_us: 411.265 }
costs { name: "loop_select_fusion.2" cost_us: 411.52 }
costs { name: "loop_select_fusion.3" cost_us: 403.328 }
costs { name: "loop_select_fusion.4" cost_us: 119.072 }
costs { name: "loop_select_fusion.5" cost_us: 117.92 }
costs { name: "loop_select_fusion.6" cost_us: 2.048 }
costs { name: "loop_select_fusion.7" cost_us: 1.568 }
costs { name: "loop_select_fusion.8" cost_us: 1.44 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.472 }
costs { name: "loop_sqrt_fusion" cost_us: 2.304 }
costs { name: "loop_subtract_fusion" cost_us: 1.312 }
costs { name: "while.7.0" cost_us: 2674.753 }
costs { name: "while.7.0" cost_us: 10167.335 }
costs { name: "while.7.0" cost_us: 25269.359 }
costs { name: "while.7.0" cost_us: 22297.518 }
costs { name: "while.7.0" cost_us: 9679.815 }
costs { name: "while.7.0" cost_us: 6622.116 }
costs { name: "while.7.0" cost_us: 2989.506 }
costs { name: "while.7.0" cost_us: 2950.402 }
costs { name: "while.7.0" cost_us: 1866.624 }
costs { name: "while.7.0" cost_us: 1863.168 }
costs { name: "while.7.0" cost_us: 192.96 }
costs { name: "while.7.0" cost_us: 1037.536 }
costs { name: "while.7.0" cost_us: 398.304 }
costs { name: "while.7.0" cost_us: 368.864 }
costs { name: "while.7.0" cost_us: 578.656 }
costs { name: "while.7.0" cost_us: 556.577 }
costs { name: "while.7.0" cost_us: 361.568 }
costs { name: "while.7.0" cost_us: 273.697 }
costs { name: "while.7.0" cost_us: 252.32 }
costs { name: "while.7.0" cost_us: 100.8 }
costs { name: "while.7.0" cost_us: 198.336 }
costs { name: "while.7.0" cost_us: 193.856 }
costs { name: "while.7.0" cost_us: 191.168 }
costs { name: "while.7.0" cost_us: 185.056 }
costs { name: "while.7.0" cost_us: 178.176 }
costs { name: "while.7.0" cost_us: 169.377 }
costs { name: "while.7.0" cost_us: 102.721 }
costs { name: "while.7.0" cost_us: 84.768 }
costs { name: "while.7.0" cost_us: 74.4 }
costs { name: "while.7.0" cost_us: 56.32 }
costs { name: "while.7.0" cost_us: 24.64 }
costs { name: "while.7.0" cost_us: 14.112 }
costs { name: "while.7.0" cost_us: 5.92 }
costs { name: "while.7.0" cost_us: 3.903 }
costs { name: "while.7.0" cost_us: 6.752 }
costs { name: "while.7.0" cost_us: 6.656 }
costs { name: "while.7.0" cost_us: 2.047 }
costs { name: "while.7.0" cost_us: 1.856 }
costs { name: "while.7.0" cost_us: 4.064 }
costs { name: "while.7.0" cost_us: 1.824 }
costs { name: "while.7.0" cost_us: 1.504 }
costs { name: "while.7.0" cost_us: 3.007 }
costs { name: "while.7.0" cost_us: 2.944 }
costs { name: "while.7.0" cost_us: 2.72 }
costs { name: "while.7.0" cost_us: 2.24 }
costs { name: "while.7.0" cost_us: 2.176 }
costs { name: "while.7.0" cost_us: 2.048 }
costs { name: "while.7.0" cost_us: 2.048 }
costs { name: "while.7.0" cost_us: 1.76 }
costs { name: "while.7.0" cost_us: 1.44 }
costs { name: "while.7.0" cost_us: 1.44 }
costs { name: "while.7.0" cost_us: 1.44 }
costs { name: "while.7.0" cost_us: 1.44 }
costs { name: "while.7.0" cost_us: 1.024 }
costs { name: "while.7.0" cost_us: 1.312 }
costs { name: "while.7.0" cost_us: 1.248 }
costs { name: "while.7.0" cost_us: 1.088 }
costs { name: "loop_add_fusion.14" cost_us: 1.376 }
costs { name: "input_reduce_fusion" cost_us: 93.536 }
costs { name: "input_reduce_fusion.1" cost_us: 85.184 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 85.152 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 85.312 }
costs { name: "input_reduce_fusion.22" cost_us: 94.592 }
costs { name: "input_reduce_fusion.23" cost_us: 85.632 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 90.4 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 87.2 }
costs { name: "while.5.0" cost_us: 22819.181 }
costs { name: "while.5.0" cost_us: 366.4 }
costs { name: "while.5.0" cost_us: 9609.063 }
costs { name: "while.5.0" cost_us: 2997.794 }
costs { name: "while.5.0" cost_us: 2902.53 }
costs { name: "while.5.0" cost_us: 1862.049 }
costs { name: "while.5.0" cost_us: 901.217 }
costs { name: "while.5.0" cost_us: 632.64 }
costs { name: "while.5.0" cost_us: 632.225 }
costs { name: "while.5.0" cost_us: 318.144 }
costs { name: "while.5.0" cost_us: 191.2 }
costs { name: "while.5.0" cost_us: 191.488 }
costs { name: "while.5.0" cost_us: 90.4 }
costs { name: "while.5.0" cost_us: 85.152 }
costs { name: "while.5.0" cost_us: 80.704 }
costs { name: "while.5.0" cost_us: 80.704 }
costs { name: "while.5.0" cost_us: 41.407 }
costs { name: "while.5.0" cost_us: 3.488 }
costs { name: "while.5.0" cost_us: 2.017 }
costs { name: "while.5.0" cost_us: 1.983 }
costs { name: "while.5.0" cost_us: 2.016 }
costs { name: "while.5.0" cost_us: 3.52 }
costs { name: "while.5.0" cost_us: 3.04 }
costs { name: "while.5.0" cost_us: 3.04 }
costs { name: "while.5.0" cost_us: 1.696 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.28 }
costs { name: "while.5.0" cost_us: 1.76 }
costs { name: "while.5.0" cost_us: 1.408 }
costs { name: "input_reduce_fusion.33" cost_us: 86.208 }
costs { name: "loop_multiply_fusion.11" cost_us: 192.96 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.24 }
costs { name: "wrapped_convert.1" cost_us: 1.92 }
costs { name: "wrapped_convert" cost_us: 4.512 }
costs { name: "custom-call.162.0" cost_us: 11385.574 }
costs { name: "loop_convert_fusion.19" cost_us: 619.2 }
costs { name: "input_transpose_fusion.5" cost_us: 2.592 }
costs { name: "custom-call.156.0" cost_us: 9026.598 }
costs { name: "input_transpose_fusion.12" cost_us: 3.232 }
costs { name: "input_transpose_fusion.6" cost_us: 4.896 }
costs { name: "loop_convert_fusion" cost_us: 3.52 }
costs { name: "loop_convert_fusion.1" cost_us: 3.488 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 4.096 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 4.672 }
costs { name: "loop_convert_fusion.2" cost_us: 3.551 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 4.128 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 4.864 }
costs { name: "loop_convert_fusion.26" cost_us: 4.416 }
costs { name: "loop_convert_fusion.27" cost_us: 4.064 }
costs { name: "loop_convert_fusion.3" cost_us: 3.04 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 3.104 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 3.392 }
costs { name: "loop_convert_fusion.33" cost_us: 2.848 }
costs { name: "loop_convert_fusion.4" cost_us: 3.04 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 3.135 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 3.424 }
costs { name: "loop_convert_fusion.40" cost_us: 1.984 }
costs { name: "loop_convert_fusion.41" cost_us: 2.016 }
costs { name: "loop_convert_fusion.48" cost_us: 2.208 }
costs { name: "loop_convert_fusion.49" cost_us: 2.112 }
costs { name: "loop_convert_fusion.5" cost_us: 2.017 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 2.112 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 1.824 }
costs { name: "loop_convert_fusion.6" cost_us: 2.08 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 2.208 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.7" cost_us: 1.983 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 2.047 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.8" cost_us: 2.08 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 4.224 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 4.768 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 632.769 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 80.736 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 80.609 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 633.089 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 80.864 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 633.057 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 80.576 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 633.024 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 632.225 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 631.84 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 632.64 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 632.577 }
costs { name: "copy_fusion.2" cost_us: 1.76 }
costs { name: "loop_add_fusion" cost_us: 1.632 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_multiply_fusion" cost_us: 901.408 }
costs { name: "loop_multiply_fusion.7" cost_us: 902.592 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 901.217 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 897.345 }
costs { name: "custom-call.160.0" cost_us: 10234.406 }
costs { name: "custom-call.60.0" cost_us: 10174.503 }
costs { name: "custom-call.60.0.double_buffer_clone" cost_us: 10168.615 }
costs { name: "custom-call.60.0.peeled_double_buffer" cost_us: 10174.856 }
costs { name: "custom-call.161.0" cost_us: 10282.598 }
costs { name: "custom-call.61.0" cost_us: 10177.383 }
costs { name: "custom-call.61.0.double_buffer_clone" cost_us: 10173.736 }
costs { name: "custom-call.61.0.peeled_double_buffer" cost_us: 10187.175 }
costs { name: "cublas-gemm.38.0" cost_us: 9734.151 }
costs { name: "cublas-gemm.5.0" cost_us: 9619.366 }
costs { name: "cublas-gemm.5.0.double_buffer_clone" cost_us: 9609.063 }
costs { name: "cublas-gemm.5.0.peeled_double_buffer" cost_us: 9685.254 }
costs { name: "loop_multiply_fusion.1" cost_us: 191.552 }
costs { name: "loop_multiply_fusion.1.double_buffer_clone" cost_us: 191.488 }
costs { name: "loop_multiply_fusion.1.peeled_double_buffer" cost_us: 190.88 }
costs { name: "loop_multiply_fusion.12" cost_us: 193.248 }
costs { name: "loop_rsqrt_fusion" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.113 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_multiply_fusion.13" cost_us: 193.728 }
costs { name: "loop_multiply_fusion.2" cost_us: 191.2 }
costs { name: "loop_multiply_fusion.2.double_buffer_clone" cost_us: 191.328 }
costs { name: "loop_multiply_fusion.2.peeled_double_buffer" cost_us: 192.0 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 2.144 }
costs { name: "loop_rsqrt_fusion.8" cost_us: 2.24 }
costs { name: "custom-call.38.0" cost_us: 1862.049 }
costs { name: "custom-call.38.0" cost_us: 1.696 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1932.129 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1.728 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1864.897 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1.824 }
costs { name: "custom-call.39.0" cost_us: 2014.689 }
costs { name: "custom-call.39.0" cost_us: 2.048 }
costs { name: "loop_broadcast_fusion" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.5" cost_us: 1.312 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.311 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.3" cost_us: 1.44 }
costs { name: "loop_multiply_fusion.3.double_buffer_clone" cost_us: 1.471 }
costs { name: "loop_multiply_fusion.3.peeled_double_buffer" cost_us: 1.44 }
costs { name: "input_concatenate_fusion" cost_us: 318.144 }
costs { name: "input_concatenate_fusion.2" cost_us: 318.944 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 318.432 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 318.4 }
costs { name: "input_concatenate_fusion.1" cost_us: 41.407 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 41.44 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 41.504 }
costs { name: "input_concatenate_fusion.3" cost_us: 41.568 }
costs { name: "custom-call.158.0" cost_us: 376.96 }
costs { name: "custom-call.58.0" cost_us: 366.912 }
costs { name: "custom-call.58.0.double_buffer_clone" cost_us: 373.92 }
costs { name: "custom-call.58.0.peeled_double_buffer" cost_us: 370.465 }
costs { name: "custom-call.159.0" cost_us: 380.416 }
costs { name: "custom-call.59.0" cost_us: 366.4 }
costs { name: "custom-call.59.0.double_buffer_clone" cost_us: 373.696 }
costs { name: "custom-call.59.0.peeled_double_buffer" cost_us: 369.92 }
costs { name: "cublas-gemm.37.0" cost_us: 3032.386 }
costs { name: "cublas-gemm.4.0" cost_us: 2997.794 }
costs { name: "cublas-gemm.4.0.double_buffer_clone" cost_us: 3000.482 }
costs { name: "cublas-gemm.4.0.peeled_double_buffer" cost_us: 3013.122 }
costs { name: "custom-call.157.0" cost_us: 3010.85 }
costs { name: "custom-call.57.0" cost_us: 2902.53 }
costs { name: "custom-call.57.0.double_buffer_clone" cost_us: 2909.858 }
costs { name: "custom-call.57.0.peeled_double_buffer" cost_us: 2899.81 }
costs { name: "loop_convert_fusion.29" cost_us: 6.752 }
costs { name: "loop_power_fusion.1" cost_us: 1.536 }
costs { name: "all-reduce-start.2" cost_us: 1968.417 }
costs { name: "all-reduce-start.4" cost_us: 171.008 }
costs { name: "all-reduce-start.6" cost_us: 543.2 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 1037.536 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 1035.585 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 997.824 }
costs { name: "input_add_multiply_reduce_fusion.3" cost_us: 1074.688 }
costs { name: "input_add_multiply_reduce_fusion.double_buffer_clone" cost_us: 1039.745 }
costs { name: "input_add_multiply_reduce_fusion.peeled_double_buffer" cost_us: 1032.865 }
costs { name: "input_add_reduce_fusion" cost_us: 559.52 }
costs { name: "input_add_reduce_fusion.11" cost_us: 599.872 }
costs { name: "input_add_reduce_fusion.12" cost_us: 583.84 }
costs { name: "input_add_reduce_fusion.13" cost_us: 607.136 }
costs { name: "input_add_reduce_fusion.double_buffer_clone" cost_us: 556.577 }
costs { name: "input_add_reduce_fusion.peeled_double_buffer" cost_us: 599.585 }
costs { name: "input_reduce_fusion.38" cost_us: 4.928 }
costs { name: "input_reduce_fusion.39" cost_us: 4.864 }
costs { name: "input_reduce_fusion.40" cost_us: 8.064 }
costs { name: "input_reduce_fusion.41" cost_us: 4.704 }
costs { name: "input_reduce_fusion.42" cost_us: 4.896 }
costs { name: "input_reduce_fusion.5" cost_us: 8.224 }
costs { name: "input_reduce_fusion.5.double_buffer_clone" cost_us: 6.752 }
costs { name: "input_reduce_fusion.5.peeled_double_buffer" cost_us: 7.328 }
costs { name: "loop_multiply_fusion.15" cost_us: 2.368 }
costs { name: "loop_multiply_fusion.16" cost_us: 2.272 }
costs { name: "loop_multiply_fusion.17" cost_us: 2.208 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.367 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.271 }
costs { name: "loop_multiply_rsqrt_fusion.3" cost_us: 2.464 }
costs { name: "input_reduce_fusion.43" cost_us: 4.895 }
costs { name: "wrapped_slice.28" cost_us: 1.632 }
costs { name: "custom-call.163.0" cost_us: 10675.623 }
costs { name: "custom-call.207.0" cost_us: 11671.975 }
costs { name: "custom-call.208.0" cost_us: 11743.399 }
costs { name: "input_transpose_fusion.13" cost_us: 3.2 }
costs { name: "input_transpose_fusion.14" cost_us: 3.232 }
costs { name: "input_transpose_fusion.15" cost_us: 3.328 }
costs { name: "input_transpose_fusion.7" cost_us: 5.12 }
costs { name: "input_transpose_fusion.8" cost_us: 4.865 }
costs { name: "input_transpose_fusion.9" cost_us: 5.056 }
costs { name: "loop_convert_fusion.10" cost_us: 4.192 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 4.032 }
costs { name: "loop_convert_fusion.10.peeled_double_buffer" cost_us: 4.32 }
costs { name: "loop_convert_fusion.11" cost_us: 4.224 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 3.903 }
costs { name: "loop_convert_fusion.11.peeled_double_buffer" cost_us: 4.128 }
costs { name: "loop_convert_fusion.13" cost_us: 3.007 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 3.007 }
costs { name: "loop_convert_fusion.13.peeled_double_buffer" cost_us: 3.136 }
costs { name: "loop_convert_fusion.14" cost_us: 2.944 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 2.976 }
costs { name: "loop_convert_fusion.14.peeled_double_buffer" cost_us: 3.072 }
costs { name: "loop_convert_fusion.15" cost_us: 2.047 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 2.208 }
costs { name: "loop_convert_fusion.15.peeled_double_buffer" cost_us: 2.304 }
costs { name: "loop_convert_fusion.16" cost_us: 2.144 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 2.112 }
costs { name: "loop_convert_fusion.16.peeled_double_buffer" cost_us: 2.368 }
costs { name: "loop_convert_fusion.17" cost_us: 1.856 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 1.92 }
costs { name: "loop_convert_fusion.17.peeled_double_buffer" cost_us: 2.4 }
costs { name: "loop_convert_fusion.18" cost_us: 2.016 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_convert_fusion.18.peeled_double_buffer" cost_us: 2.175 }
costs { name: "loop_convert_fusion.20" cost_us: 4.768 }
costs { name: "loop_convert_fusion.21" cost_us: 4.511 }
costs { name: "loop_convert_fusion.22" cost_us: 4.416 }
costs { name: "loop_convert_fusion.23" cost_us: 4.48 }
costs { name: "loop_convert_fusion.24" cost_us: 4.352 }
costs { name: "loop_convert_fusion.25" cost_us: 4.352 }
costs { name: "loop_convert_fusion.30" cost_us: 3.04 }
costs { name: "loop_convert_fusion.31" cost_us: 3.04 }
costs { name: "loop_convert_fusion.32" cost_us: 3.008 }
costs { name: "loop_convert_fusion.34" cost_us: 2.176 }
costs { name: "loop_convert_fusion.35" cost_us: 2.144 }
costs { name: "loop_convert_fusion.36" cost_us: 2.08 }
costs { name: "loop_convert_fusion.37" cost_us: 2.144 }
costs { name: "loop_convert_fusion.38" cost_us: 2.08 }
costs { name: "loop_convert_fusion.39" cost_us: 2.176 }
costs { name: "loop_convert_fusion.42" cost_us: 2.496 }
costs { name: "loop_convert_fusion.43" cost_us: 2.016 }
costs { name: "loop_convert_fusion.44" cost_us: 2.432 }
costs { name: "loop_convert_fusion.45" cost_us: 2.176 }
costs { name: "loop_convert_fusion.46" cost_us: 2.432 }
costs { name: "loop_convert_fusion.47" cost_us: 2.176 }
costs { name: "loop_convert_fusion.9" cost_us: 4.064 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 4.128 }
costs { name: "loop_convert_fusion.9.peeled_double_buffer" cost_us: 3.904 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 186.432 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 25.344 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 26.432 }
costs { name: "loop_pad_fusion" cost_us: 201.44 }
costs { name: "loop_pad_fusion.1" cost_us: 201.888 }
costs { name: "loop_pad_fusion.2" cost_us: 185.249 }
costs { name: "loop_pad_fusion.3" cost_us: 60.288 }
costs { name: "loop_pad_fusion.4" cost_us: 59.904 }
costs { name: "loop_pad_fusion.5" cost_us: 9.728 }
costs { name: "loop_pad_fusion.6" cost_us: 9.6 }
costs { name: "loop_select_fusion" cost_us: 1.44 }
costs { name: "loop_select_fusion.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_select_fusion.peeled_double_buffer" cost_us: 1.792 }
costs { name: "copy_fusion" cost_us: 1.792 }
costs { name: "loop_add_fusion.4" cost_us: 1.76 }
costs { name: "loop_add_fusion.4.double_buffer_clone" cost_us: 1.44 }
costs { name: "input_transpose_fusion.3" cost_us: 3.04 }
costs { name: "input_transpose_fusion.4" cost_us: 2.976 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 198.752 }
costs { name: "loop_dynamic_update_slice_fusion.5.double_buffer_clone" cost_us: 198.336 }
costs { name: "loop_dynamic_update_slice_fusion.5.peeled_double_buffer" cost_us: 197.632 }
costs { name: "input_transpose_fusion.10" cost_us: 2.208 }
costs { name: "input_transpose_fusion.11" cost_us: 2.145 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 56.448 }
costs { name: "loop_dynamic_update_slice_fusion.4.double_buffer_clone" cost_us: 56.32 }
costs { name: "loop_dynamic_update_slice_fusion.4.peeled_double_buffer" cost_us: 60.608 }
costs { name: "copy_fusion.1" cost_us: 1.536 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 1.536 }
costs { name: "loop_dynamic_update_slice_fusion.11.double_buffer_clone" cost_us: 1.663 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 1.504 }
costs { name: "loop_dynamic_update_slice_fusion.12.double_buffer_clone" cost_us: 1.536 }
costs { name: "loop_pad_fusion.7" cost_us: 5.728 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 6.015 }
costs { name: "loop_dynamic_update_slice_fusion.6.double_buffer_clone" cost_us: 6.144 }
costs { name: "loop_dynamic_update_slice_fusion.6.peeled_double_buffer" cost_us: 6.24 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 5.983 }
costs { name: "loop_dynamic_update_slice_fusion.7.double_buffer_clone" cost_us: 5.92 }
costs { name: "loop_dynamic_update_slice_fusion.7.peeled_double_buffer" cost_us: 6.272 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 3.137 }
costs { name: "loop_dynamic_update_slice_fusion.8.double_buffer_clone" cost_us: 2.72 }
costs { name: "loop_dynamic_update_slice_fusion.8.peeled_double_buffer" cost_us: 3.232 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.824 }
costs { name: "loop_dynamic_update_slice_fusion.10.double_buffer_clone" cost_us: 2.016 }
costs { name: "loop_dynamic_update_slice_fusion.10.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 2.016 }
costs { name: "loop_dynamic_update_slice_fusion.9.double_buffer_clone" cost_us: 2.08 }
costs { name: "loop_dynamic_update_slice_fusion.9.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_add_multiply_fusion" cost_us: 1869.665 }
costs { name: "loop_add_multiply_fusion.1" cost_us: 1846.433 }
costs { name: "loop_add_multiply_fusion.2" cost_us: 1867.169 }
costs { name: "loop_add_multiply_fusion.3" cost_us: 1868.29 }
costs { name: "loop_add_multiply_fusion.double_buffer_clone" cost_us: 1863.168 }
costs { name: "loop_add_multiply_fusion.peeled_double_buffer" cost_us: 1868.961 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.176 }
costs { name: "loop_multiply_fusion.5.double_buffer_clone" cost_us: 2.176 }
costs { name: "loop_multiply_fusion.5.peeled_double_buffer" cost_us: 2.304 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.304 }
costs { name: "loop_multiply_rsqrt_fusion.double_buffer_clone" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.peeled_double_buffer" cost_us: 2.4 }
costs { name: "custom-call.167.0" cost_us: 9867.59 }
costs { name: "custom-call.174.0" cost_us: 9725.734 }
costs { name: "custom-call.198.0" cost_us: 9888.902 }
costs { name: "custom-call.82.0" cost_us: 9679.815 }
costs { name: "custom-call.82.0.double_buffer_clone" cost_us: 9696.549 }
costs { name: "custom-call.82.0.peeled_double_buffer" cost_us: 9868.006 }
costs { name: "custom-call.178.0" cost_us: 9489.639 }
costs { name: "custom-call.185.0" cost_us: 9943.975 }
costs { name: "custom-call.195.0" cost_us: 10066.118 }
costs { name: "custom-call.86.0" cost_us: 9379.077 }
costs { name: "custom-call.86.0.double_buffer_clone" cost_us: 9303.301 }
costs { name: "custom-call.86.0.peeled_double_buffer" cost_us: 10044.134 }
costs { name: "cublas-gemm.13.0" cost_us: 9779.015 }
costs { name: "cublas-gemm.13.0.double_buffer_clone" cost_us: 9705.894 }
costs { name: "cublas-gemm.13.0.peeled_double_buffer" cost_us: 9993.285 }
costs { name: "cublas-gemm.40.0" cost_us: 9988.325 }
costs { name: "cublas-gemm.43.0" cost_us: 9744.582 }
costs { name: "cublas-gemm.46.0" cost_us: 9958.119 }
costs { name: "custom-call.179.0" cost_us: 9412.391 }
costs { name: "custom-call.186.0" cost_us: 9890.726 }
costs { name: "custom-call.196.0" cost_us: 9745.511 }
costs { name: "custom-call.87.0" cost_us: 9549.35 }
costs { name: "custom-call.87.0.double_buffer_clone" cost_us: 9422.278 }
costs { name: "custom-call.87.0.peeled_double_buffer" cost_us: 10044.006 }
costs { name: "custom-call.165.0" cost_us: 10262.279 }
costs { name: "custom-call.172.0" cost_us: 11611.686 }
costs { name: "custom-call.193.0" cost_us: 10644.359 }
costs { name: "custom-call.80.0" cost_us: 10336.584 }
costs { name: "custom-call.80.0.double_buffer_clone" cost_us: 10307.335 }
costs { name: "custom-call.80.0.peeled_double_buffer" cost_us: 10342.76 }
costs { name: "custom-call.180.0" cost_us: 9413.735 }
costs { name: "custom-call.187.0" cost_us: 9838.31 }
costs { name: "custom-call.197.0" cost_us: 9390.886 }
costs { name: "custom-call.88.0" cost_us: 9395.335 }
costs { name: "custom-call.88.0.double_buffer_clone" cost_us: 9459.527 }
costs { name: "custom-call.88.0.peeled_double_buffer" cost_us: 10042.822 }
costs { name: "all-reduce-start" cost_us: 192.96 }
costs { name: "all-reduce-start.1" cost_us: 194.336 }
costs { name: "all-reduce-start.3" cost_us: 588.225 }
costs { name: "all-reduce-start.7" cost_us: 1224.033 }
costs { name: "wrapped_slice.10" cost_us: 1.056 }
costs { name: "wrapped_slice.13" cost_us: 1.44 }
costs { name: "wrapped_slice.14" cost_us: 1.792 }
costs { name: "wrapped_slice.24" cost_us: 1.184 }
costs { name: "wrapped_slice.25" cost_us: 1.728 }
costs { name: "wrapped_slice.8" cost_us: 1.504 }
costs { name: "all-reduce-start.5" cost_us: 4585.859 }
costs { name: "wrapped_slice.11" cost_us: 1.632 }
costs { name: "wrapped_slice.12" cost_us: 1.024 }
costs { name: "wrapped_slice.15" cost_us: 1.76 }
costs { name: "wrapped_slice.22" cost_us: 1.696 }
costs { name: "wrapped_slice.23" cost_us: 1.664 }
costs { name: "wrapped_slice.9" cost_us: 1.44 }
costs { name: "custom-call.35.0" cost_us: 6614.724 }
costs { name: "custom-call.35.0" cost_us: 277.281 }
costs { name: "custom-call.35.0" cost_us: 101.216 }
costs { name: "custom-call.35.0" cost_us: 197.569 }
costs { name: "custom-call.43.0" cost_us: 6959.78 }
costs { name: "custom-call.43.0" cost_us: 268.704 }
costs { name: "custom-call.43.0" cost_us: 101.472 }
costs { name: "custom-call.43.0" cost_us: 194.88 }
costs { name: "custom-call.45.0" cost_us: 6191.716 }
costs { name: "custom-call.45.0" cost_us: 275.68 }
costs { name: "custom-call.45.0" cost_us: 101.313 }
costs { name: "custom-call.45.0" cost_us: 197.568 }
costs { name: "custom-call.47.0" cost_us: 6622.948 }
costs { name: "custom-call.47.0" cost_us: 274.273 }
costs { name: "custom-call.47.0" cost_us: 101.056 }
costs { name: "custom-call.47.0" cost_us: 193.856 }
costs { name: "custom-call.47.0.double_buffer_clone" cost_us: 6622.116 }
costs { name: "custom-call.47.0.double_buffer_clone" cost_us: 273.697 }
costs { name: "custom-call.47.0.double_buffer_clone" cost_us: 100.8 }
costs { name: "custom-call.47.0.double_buffer_clone" cost_us: 198.944 }
costs { name: "custom-call.47.0.peeled_double_buffer" cost_us: 6556.035 }
costs { name: "custom-call.47.0.peeled_double_buffer" cost_us: 276.928 }
costs { name: "custom-call.47.0.peeled_double_buffer" cost_us: 101.024 }
costs { name: "custom-call.47.0.peeled_double_buffer" cost_us: 195.392 }
costs { name: "loop_add_fusion.2" cost_us: 578.72 }
costs { name: "loop_add_fusion.2.double_buffer_clone" cost_us: 578.656 }
costs { name: "loop_add_fusion.2.peeled_double_buffer" cost_us: 573.153 }
costs { name: "loop_add_fusion.6" cost_us: 635.872 }
costs { name: "loop_add_fusion.7" cost_us: 558.945 }
costs { name: "loop_add_fusion.8" cost_us: 589.345 }
costs { name: "loop_add_fusion.10" cost_us: 67.264 }
costs { name: "loop_add_fusion.11" cost_us: 76.8 }
costs { name: "loop_add_fusion.3" cost_us: 74.464 }
costs { name: "loop_add_fusion.3.double_buffer_clone" cost_us: 74.4 }
costs { name: "loop_add_fusion.3.peeled_double_buffer" cost_us: 73.824 }
costs { name: "loop_add_fusion.9" cost_us: 81.952 }
costs { name: "custom-call.181.0" cost_us: 322.209 }
costs { name: "custom-call.188.0" cost_us: 365.504 }
costs { name: "custom-call.203.0" cost_us: 354.912 }
costs { name: "custom-call.89.0" cost_us: 373.376 }
costs { name: "custom-call.89.0.double_buffer_clone" cost_us: 368.864 }
costs { name: "custom-call.89.0.peeled_double_buffer" cost_us: 362.496 }
costs { name: "custom-call.169.0" cost_us: 409.728 }
costs { name: "custom-call.176.0" cost_us: 367.968 }
costs { name: "custom-call.200.0" cost_us: 432.48 }
costs { name: "custom-call.84.0" cost_us: 398.304 }
costs { name: "custom-call.84.0.double_buffer_clone" cost_us: 402.912 }
costs { name: "custom-call.84.0.peeled_double_buffer" cost_us: 394.016 }
costs { name: "custom-call.184.0" cost_us: 339.649 }
costs { name: "custom-call.191.0" cost_us: 375.936 }
costs { name: "custom-call.206.0" cost_us: 391.329 }
costs { name: "custom-call.92.0" cost_us: 376.768 }
costs { name: "custom-call.92.0.double_buffer_clone" cost_us: 372.704 }
costs { name: "custom-call.92.0.peeled_double_buffer" cost_us: 365.888 }
costs { name: "cublas-gemm.14.0" cost_us: 431.745 }
costs { name: "cublas-gemm.14.0.double_buffer_clone" cost_us: 441.728 }
costs { name: "cublas-gemm.14.0.peeled_double_buffer" cost_us: 426.464 }
costs { name: "cublas-gemm.41.0" cost_us: 440.32 }
costs { name: "cublas-gemm.44.0" cost_us: 413.536 }
costs { name: "cublas-gemm.47.0" cost_us: 461.025 }
costs { name: "custom-call.182.0" cost_us: 2678.082 }
costs { name: "custom-call.189.0" cost_us: 2869.922 }
costs { name: "custom-call.204.0" cost_us: 2746.146 }
costs { name: "custom-call.90.0" cost_us: 2678.242 }
costs { name: "custom-call.90.0.double_buffer_clone" cost_us: 2674.753 }
costs { name: "custom-call.90.0.peeled_double_buffer" cost_us: 2842.529 }
costs { name: "custom-call.168.0" cost_us: 3240.513 }
costs { name: "custom-call.175.0" cost_us: 3077.922 }
costs { name: "custom-call.199.0" cost_us: 3331.331 }
costs { name: "custom-call.83.0" cost_us: 3175.458 }
costs { name: "custom-call.83.0.double_buffer_clone" cost_us: 2950.402 }
costs { name: "custom-call.83.0.peeled_double_buffer" cost_us: 3237.794 }
costs { name: "custom-call.183.0" cost_us: 2463.361 }
costs { name: "custom-call.190.0" cost_us: 2959.202 }
costs { name: "custom-call.205.0" cost_us: 2959.553 }
costs { name: "custom-call.91.0" cost_us: 2930.978 }
costs { name: "custom-call.91.0.double_buffer_clone" cost_us: 2922.626 }
costs { name: "custom-call.91.0.peeled_double_buffer" cost_us: 2841.601 }
costs { name: "custom-call.170.0" cost_us: 3362.498 }
costs { name: "custom-call.177.0" cost_us: 2945.282 }
costs { name: "custom-call.201.0" cost_us: 3520.034 }
costs { name: "custom-call.85.0" cost_us: 3267.459 }
costs { name: "custom-call.85.0.double_buffer_clone" cost_us: 3320.194 }
costs { name: "custom-call.85.0.peeled_double_buffer" cost_us: 3238.402 }
costs { name: "custom-call.164.0" cost_us: 11300.487 }
costs { name: "custom-call.171.0" cost_us: 11105.639 }
costs { name: "custom-call.192.0" cost_us: 10233.99 }
costs { name: "custom-call.79.0" cost_us: 10180.423 }
costs { name: "custom-call.79.0.double_buffer_clone" cost_us: 10189.319 }
costs { name: "custom-call.79.0.peeled_double_buffer" cost_us: 10215.143 }
costs { name: "custom-call.166.0" cost_us: 11298.534 }
costs { name: "custom-call.173.0" cost_us: 10920.935 }
costs { name: "custom-call.194.0" cost_us: 10276.26 }
costs { name: "custom-call.81.0" cost_us: 10167.335 }
costs { name: "custom-call.81.0.double_buffer_clone" cost_us: 10212.679 }
costs { name: "custom-call.81.0.peeled_double_buffer" cost_us: 10253.893 }
costs { name: "loop_multiply_fusion.10" cost_us: 192.608 }
costs { name: "loop_multiply_fusion.4" cost_us: 191.808 }
costs { name: "loop_multiply_fusion.4.double_buffer_clone" cost_us: 191.168 }
costs { name: "loop_multiply_fusion.4.peeled_double_buffer" cost_us: 191.616 }
costs { name: "loop_multiply_fusion.8" cost_us: 193.472 }
costs { name: "loop_multiply_fusion.9" cost_us: 193.951 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.111 }
costs { name: "loop_rsqrt_fusion.2.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.2.peeled_double_buffer" cost_us: 2.08 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.208 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.303 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.272 }
costs { name: "custom-call.34.0" cost_us: 1947.041 }
costs { name: "custom-call.34.0" cost_us: 2.176 }
costs { name: "custom-call.42.0" cost_us: 2012.993 }
costs { name: "custom-call.42.0" cost_us: 2.24 }
costs { name: "custom-call.44.0" cost_us: 2248.066 }
costs { name: "custom-call.44.0" cost_us: 2.24 }
costs { name: "custom-call.46.0" cost_us: 1937.153 }
costs { name: "custom-call.46.0" cost_us: 2.048 }
costs { name: "custom-call.46.0.double_buffer_clone" cost_us: 1866.624 }
costs { name: "custom-call.46.0.double_buffer_clone" cost_us: 2.048 }
costs { name: "custom-call.46.0.peeled_double_buffer" cost_us: 1912.929 }
costs { name: "custom-call.46.0.peeled_double_buffer" cost_us: 1.696 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.248 }
costs { name: "loop_broadcast_fusion.1.double_buffer_clone" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.1.peeled_double_buffer" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.6" cost_us: 1.088 }
costs { name: "loop_multiply_fusion.6.double_buffer_clone" cost_us: 1.152 }
costs { name: "loop_multiply_fusion.6.peeled_double_buffer" cost_us: 1.472 }
costs { name: "loop_convert_fusion.12" cost_us: 6.656 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 6.656 }
costs { name: "loop_convert_fusion.12.peeled_double_buffer" cost_us: 6.944 }
costs { name: "loop_power_fusion" cost_us: 1.312 }
costs { name: "loop_power_fusion.double_buffer_clone" cost_us: 1.375 }
costs { name: "loop_power_fusion.peeled_double_buffer" cost_us: 1.631 }
costs { name: "cublas-gemm.12.0" cost_us: 3001.505 }
costs { name: "cublas-gemm.12.0.double_buffer_clone" cost_us: 2989.506 }
costs { name: "cublas-gemm.12.0.peeled_double_buffer" cost_us: 3022.785 }
costs { name: "cublas-gemm.39.0" cost_us: 3272.099 }
costs { name: "cublas-gemm.42.0" cost_us: 3260.769 }
costs { name: "cublas-gemm.45.0" cost_us: 3049.409 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 186.144 }
costs { name: "loop_dynamic_slice_fusion.2.double_buffer_clone" cost_us: 185.056 }
costs { name: "loop_dynamic_slice_fusion.2.peeled_double_buffer" cost_us: 186.304 }
costs { name: "wrapped_slice" cost_us: 188.672 }
costs { name: "wrapped_slice.4" cost_us: 184.864 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 25.12 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 24.64 }
costs { name: "loop_dynamic_slice_fusion.1.double_buffer_clone" cost_us: 25.248 }
costs { name: "loop_dynamic_slice_fusion.1.peeled_double_buffer" cost_us: 22.816 }
costs { name: "loop_dynamic_slice_fusion.double_buffer_clone" cost_us: 25.088 }
costs { name: "loop_dynamic_slice_fusion.peeled_double_buffer" cost_us: 24.704 }
costs { name: "wrapped_slice.1" cost_us: 25.248 }
costs { name: "wrapped_slice.2" cost_us: 23.264 }
costs { name: "wrapped_slice.5" cost_us: 24.32 }
costs { name: "wrapped_slice.6" cost_us: 24.448 }
costs { name: "wrapped_slice.3" cost_us: 186.592 }
costs { name: "wrapped_slice.7" cost_us: 184.192 }
costs { name: "loop_divide_fusion" cost_us: 1.408 }
costs { name: "wrapped_transpose.2" cost_us: 197.728 }
costs { name: "wrapped_transpose.3" cost_us: 195.648 }
costs { name: "wrapped_transpose.4" cost_us: 208.864 }
costs { name: "wrapped_transpose.1" cost_us: 3.296 }
costs { name: "wrapped_transpose" cost_us: 3.264 }
costs { name: "wrapped_transpose.5" cost_us: 8.768 }
costs { name: "wrapped_transpose.6" cost_us: 211.04 }
costs { name: "wrapped_transpose.7" cost_us: 56.191 }
costs { name: "wrapped_transpose.8" cost_us: 8.993 }
