#!/bin/bash

# This file is documentation for how to get started with DeepSeek v3.

# This file runs Step 1 on CPU.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16): 
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check, pre-training, fine-tuning, and decoding.

set -ex

export MODEL_NAME='deepseek3-671b'
export TOKENIZER_PATH='deepseek-ai/DeepSeek-V3'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# Step 1: Checkpoint conversion
# You can use the HuggingFace checkpoint at https://huggingface.co/deepseek-ai/DeepSeek-V3 (fp8), and dequantize it to bf16
# Assume HF checkpoints are uploaded to GCS bucket at CKPT_BUCKET 
# Non-Googlers please remember to point `CKPT_BUCKET` to GCS buckets that you own
# Copying the HF checkpoint into a local directory `/tmp` -- you are free to use a different directory
if [ -z "${CKPT_DISK_LOCATION}" ]; then
  export CKPT_BUCKET=gs://maxtext-deepseek/deepseek3-671b/hf
  gcloud storage cp -r ${CKPT_BUCKET} /tmp
  export CKPT_DISK_LOCATION=/tmp/hf
fi

# Convert checkpoint to `scanned` format, more suitable for training
python3 -m maxtext.checkpoint_conversion.to_maxtext \
    model_name=${MODEL_NAME} \
    --hf_model_path=${CKPT_DISK_LOCATION} \
    base_output_directory=${BASE_OUTPUT_PATH}/scanned \
    scan_layers=true \
    hardware=cpu \
    skip_jax_distributed_system=True
export SCANNED_CKPT_PATH=${BASE_OUTPUT_PATH}/scanned/0/items
echo "Scanned checkpoint path: ${SCANNED_CKPT_PATH}"

# Convert checkpoint to `unscanned` format, more suitable for decoding
python3 -m maxtext.checkpoint_conversion.to_maxtext \
    model_name=${MODEL_NAME} \
    --hf_model_path=${CKPT_DISK_LOCATION} \
    base_output_directory=${BASE_OUTPUT_PATH}/unscanned \
    scan_layers=false \
    hardware=cpu \
    skip_jax_distributed_system=True
export UNSCANNED_CKPT_PATH=${BASE_OUTPUT_PATH}/unscanned/0/items
echo "Unscanned checkpoint path: ${UNSCANNED_CKPT_PATH}"

# Test whether the forward pass logits match the golden logits
# default golden_logits_path=/deps/tests/assets/golden_logits/golden_data_{MODEL_NAME}.jsonl, copied from gs://maxtext-test-assets/golden_data_${MODEL_NAME}.jsonl
GOLDEN_LOGITS_DISK_LOCATION="/deps/tests/assets/golden_logits/golden_data_${MODEL_NAME}.jsonl"
if [ ! -f "${GOLDEN_LOGITS_DISK_LOCATION}" ]; then
  GOLDEN_LOGITS_PATH="gs://maxtext-test-assets/golden_data_${MODEL_NAME}.jsonl"
  GOLDEN_LOGITS_DISK_LOCATION=/tmp/${MODEL_NAME}_golden_data.jsonl
  gcloud storage cp ${GOLDEN_LOGITS_PATH} ${GOLDEN_LOGITS_DISK_LOCATION}
fi

python3 -m tests.utils.forward_pass_logit_checker \
    load_parameters_path=${SCANNED_CKPT_PATH} \
    scan_layers=true \
    attention=dot_product \
    model_name=${MODEL_NAME} \
    hardware=cpu \
    skip_jax_distributed_system=True \
    --golden_logits_path=${GOLDEN_LOGITS_DISK_LOCATION} \
    --atol=1e-4 \
    --rtol=1e-4 \
    --max_kl_div=5e-6
