#!/bin/bash

# This file is documentation for how to get started with DeepSeek v3 MTP.

# This file runs Step 2 on v5p-128 on a daily basis.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16):
#    Scanned format is better for training.
# 2. Run short MTP fine-tuning.

set -ex

export MODEL_NAME='deepseek3-671b'
export TOKENIZER_PATH='deepseek-ai/DeepSeek-V3'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# Use a hard-coded golden checkpoint, rather than checkpoints generated by Step 1 as it is not in daily test.
SCANNED_CKPT_PATH=gs://maxtext-deepseek/deepseek3-671b-mtp/04-15-2026/scanned/0/items
# Non-Googlers please remember to point `DATASET_PATH` to the GCS bucket where you have your training data
export DATASET_PATH=gs://maxtext-dataset

# Run short fine-tuning to verify MTP training loop (10 steps)
python3 -m maxtext.trainers.pre_train.train "${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}"/base.yml \
    base_output_directory=${BASE_OUTPUT_PATH} \
    dataset_path=${DATASET_PATH} \
    load_parameters_path=${SCANNED_CKPT_PATH} \
    run_name=mtp_fine_tuning \
    per_device_batch_size=1 \
    model_name=${MODEL_NAME} \
    ici_expert_parallelism=16 \
    ici_fsdp_parallelism=4 \
    steps=10 \
    max_target_length=2048 \
    tokenizer_type=huggingface \
    tokenizer_path=${TOKENIZER_PATH} \
    attention=flash \
    dtype=bfloat16 \
    weight_dtype=bfloat16 \
    opt_type=sgd \
    enable_checkpointing=True \
    mtp_num_layers=1 \
    mtp_loss_scaling_factor=0.1 \
    checkpoint_storage_concurrent_gb=1024
