costs { name: "all-gather-start" cost_us: 26045.505699999998 }
costs { name: "all-gather-start.1" cost_us: 36280.6334 }
costs { name: "all-gather-start.10" cost_us: 19068.8417 }
costs { name: "all-gather-start.2" cost_us: 9188.9236 }
costs { name: "all-gather-start.3" cost_us: 10873.0354 }
costs { name: "all-gather-start.6" cost_us: 10636.894 }
costs { name: "all-gather-start.7" cost_us: 27738.535 }
costs { name: "all-gather-start.8" cost_us: 34889.987700000005 }
costs { name: "all-gather-start.9" cost_us: 36557.405 }
costs { name: "all-reduce-start" cost_us: 663.4318000000001 }
costs { name: "all-reduce-start.2" cost_us: 1046.8707 }
costs { name: "all-reduce-start.6" cost_us: 4314.9902999999995 }
costs { name: "input_scatter_fusion" cost_us: 2.6221 }
costs { name: "input_scatter_fusion.1" cost_us: 2.1801999999999997 }
costs { name: "input_scatter_fusion.1.double_buffer_clone" cost_us: 2.4286999999999996 }
costs { name: "input_scatter_fusion.1.peeled_double_buffer" cost_us: 1.984 }
costs { name: "input_scatter_fusion.2" cost_us: 4.2054 }
costs { name: "input_scatter_fusion.2.double_buffer_clone" cost_us: 4.2187 }
costs { name: "input_scatter_fusion.3" cost_us: 2.5622 }
costs { name: "input_scatter_fusion.3.double_buffer_clone" cost_us: 2.4369 }
costs { name: "input_scatter_fusion.4" cost_us: 4.4373000000000005 }
costs { name: "input_scatter_fusion.5" cost_us: 2.5703 }
costs { name: "input_scatter_fusion.6" cost_us: 2.4213 }
costs { name: "input_scatter_fusion.7" cost_us: 2.4743000000000004 }
costs { name: "input_scatter_fusion.8" cost_us: 2.624 }
costs { name: "input_scatter_fusion.9" cost_us: 2.4857 }
costs { name: "input_scatter_fusion.double_buffer_clone" cost_us: 2.0486 }
costs { name: "input_scatter_fusion.peeled_double_buffer" cost_us: 2.411 }
costs { name: "input_transpose_fusion" cost_us: 14.1848 }
costs { name: "input_transpose_fusion.1" cost_us: 73.39710000000001 }
costs { name: "input_transpose_fusion.1.double_buffer_clone" cost_us: 71.3245 }
costs { name: "input_transpose_fusion.11" cost_us: 326.5707 }
costs { name: "input_transpose_fusion.15" cost_us: 34.816300000000005 }
costs { name: "input_transpose_fusion.16" cost_us: 40.5653 }
costs { name: "input_transpose_fusion.2" cost_us: 15.4918 }
costs { name: "input_transpose_fusion.2.double_buffer_clone" cost_us: 13.803799999999999 }
costs { name: "input_transpose_fusion.3" cost_us: 13.792 }
costs { name: "input_transpose_fusion.4" cost_us: 76.05369999999999 }
costs { name: "input_transpose_fusion.7" cost_us: 94.134 }
costs { name: "input_transpose_fusion.8" cost_us: 13.0663 }
costs { name: "input_transpose_fusion.double_buffer_clone" cost_us: 12.8345 }
costs { name: "loop_add_fusion.2" cost_us: 2.1013 }
costs { name: "loop_add_fusion.2.double_buffer_clone" cost_us: 1.9988 }
costs { name: "loop_add_fusion.6" cost_us: 2.1201999999999996 }
costs { name: "loop_add_fusion.6.double_buffer_clone" cost_us: 2.0253 }
costs { name: "loop_broadcast_fusion.10" cost_us: 55.723 }
costs { name: "loop_broadcast_fusion.11" cost_us: 55.6163 }
costs { name: "loop_broadcast_fusion.5" cost_us: 25285.1047 }
costs { name: "loop_broadcast_fusion.6" cost_us: 328.12870000000004 }
costs { name: "loop_broadcast_fusion.7" cost_us: 196.982 }
costs { name: "loop_broadcast_fusion.8" cost_us: 3.1147 }
costs { name: "loop_broadcast_fusion.9" cost_us: 13.685 }
costs { name: "reduce-scatter.22.1" cost_us: 20839.3793 }
costs { name: "reduce-scatter.24.double_buffer_clone.1" cost_us: 18959.3 }
costs { name: "reduce-scatter.28" cost_us: 9668.9059 }
costs { name: "reduce-scatter.29" cost_us: 28879.3567 }
costs { name: "reduce-scatter.30" cost_us: 25713.888 }
costs { name: "reduce-scatter.31" cost_us: 18907.629699999998 }
costs { name: "while.12.0" cost_us: 29090.0121 }
costs { name: "while.13.0" cost_us: 26604.4316 }
costs { name: "wrapped_concatenate" cost_us: 10.934700000000001 }
costs { name: "wrapped_concatenate.1" cost_us: 1.8685999999999998 }
costs { name: "wrapped_concatenate.2" cost_us: 10.363100000000001 }
costs { name: "wrapped_concatenate.3" cost_us: 85.731 }
costs { name: "wrapped_concatenate.4" cost_us: 142.934 }
costs { name: "wrapped_concatenate.5" cost_us: 2.2293000000000003 }
costs { name: "wrapped_concatenate.6" cost_us: 2.656 }
costs { name: "wrapped_concatenate.7" cost_us: 2.3573000000000004 }
costs { name: "wrapped_slice" cost_us: 2.1989 }
costs { name: "wrapped_slice.1" cost_us: 2.9044 }
costs { name: "wrapped_slice.10" cost_us: 4.5973999999999995 }
costs { name: "wrapped_slice.11" cost_us: 4.3878 }
costs { name: "wrapped_slice.14" cost_us: 2.2444 }
costs { name: "wrapped_slice.15" cost_us: 2.4052 }
costs { name: "wrapped_slice.16" cost_us: 2.395 }
costs { name: "wrapped_slice.17" cost_us: 2.0198 }
costs { name: "wrapped_slice.18" cost_us: 11.5413 }
costs { name: "wrapped_slice.19" cost_us: 11.744 }
costs { name: "wrapped_slice.2" cost_us: 2.8062 }
costs { name: "wrapped_slice.20" cost_us: 1.9523 }
costs { name: "wrapped_slice.21" cost_us: 1.9623 }
costs { name: "wrapped_slice.22" cost_us: 2.464 }
costs { name: "wrapped_slice.23" cost_us: 2.208 }
costs { name: "wrapped_slice.24" cost_us: 2.3043 }
costs { name: "wrapped_slice.25" cost_us: 2.2503 }
costs { name: "wrapped_slice.26" cost_us: 2.1013 }
costs { name: "wrapped_slice.27" cost_us: 1.8987 }
costs { name: "wrapped_slice.28" cost_us: 3.872 }
costs { name: "wrapped_slice.29" cost_us: 4.1813 }
costs { name: "wrapped_slice.3" cost_us: 2.1889000000000003 }
costs { name: "wrapped_slice.30" cost_us: 4.192 }
costs { name: "wrapped_slice.31" cost_us: 3.9253 }
costs { name: "wrapped_slice.32" cost_us: 4.32 }
costs { name: "wrapped_slice.33" cost_us: 4.0217 }
costs { name: "wrapped_slice.34" cost_us: 1.2587000000000002 }
costs { name: "wrapped_slice.35" cost_us: 1.2692999999999999 }
costs { name: "wrapped_slice.36" cost_us: 1.2477 }
costs { name: "wrapped_slice.37" cost_us: 1.2697 }
costs { name: "wrapped_slice.38" cost_us: 1.2692999999999999 }
costs { name: "wrapped_slice.39" cost_us: 1.2692999999999999 }
costs { name: "wrapped_slice.44" cost_us: 1.2372999999999998 }
costs { name: "wrapped_slice.45" cost_us: 1.248 }
costs { name: "wrapped_slice.47" cost_us: 1.2692999999999999 }
costs { name: "wrapped_slice.48" cost_us: 1.5467 }
costs { name: "wrapped_slice.49" cost_us: 1.4617 }
costs { name: "wrapped_slice.50" cost_us: 1.2267000000000001 }
costs { name: "wrapped_slice.51" cost_us: 1.2377 }
costs { name: "wrapped_slice.52" cost_us: 1.248 }
costs { name: "wrapped_slice.53" cost_us: 1.248 }
costs { name: "wrapped_slice.54" cost_us: 1.216 }
costs { name: "wrapped_slice.55" cost_us: 1.5352999999999999 }
costs { name: "wrapped_slice.56" cost_us: 1.2587000000000002 }
costs { name: "wrapped_slice.57" cost_us: 1.333 }
costs { name: "wrapped_slice.58" cost_us: 1.2692999999999999 }
costs { name: "wrapped_slice.59" cost_us: 1.2053 }
costs { name: "wrapped_slice.6" cost_us: 4.4418 }
costs { name: "wrapped_slice.60" cost_us: 1.2477 }
costs { name: "wrapped_slice.61" cost_us: 1.2163 }
costs { name: "wrapped_slice.62" cost_us: 1.248 }
costs { name: "wrapped_slice.63" cost_us: 1.2372999999999998 }
costs { name: "wrapped_slice.64" cost_us: 1.205 }
costs { name: "wrapped_slice.65" cost_us: 1.216 }
costs { name: "wrapped_slice.66" cost_us: 1.2587000000000002 }
costs { name: "wrapped_slice.67" cost_us: 1.248 }
costs { name: "wrapped_slice.68" cost_us: 1.2483 }
costs { name: "wrapped_slice.69" cost_us: 1.2053 }
costs { name: "wrapped_slice.7" cost_us: 4.6941999999999995 }
costs { name: "wrapped_slice.70" cost_us: 1.2267000000000001 }
costs { name: "wrapped_slice.71" cost_us: 1.2267000000000001 }
costs { name: "wrapped_slice.72" cost_us: 1.2263 }
costs { name: "wrapped_slice.73" cost_us: 1.2263 }
costs { name: "wrapped_slice.74" cost_us: 1.2372999999999998 }
costs { name: "wrapped_slice.8" cost_us: 4.6253 }
costs { name: "wrapped_slice.9" cost_us: 4.4699 }
costs { name: "wrapped_transpose.10" cost_us: 14.272 }
costs { name: "wrapped_transpose.11" cost_us: 16.608 }
costs { name: "wrapped_transpose.12" cost_us: 19.0293 }
costs { name: "wrapped_transpose.5" cost_us: 253.07770000000002 }
costs { name: "wrapped_transpose.6" cost_us: 252.5735 }
costs { name: "wrapped_transpose.7" cost_us: 256.44829999999996 }
costs { name: "wrapped_transpose.8" cost_us: 3.2426999999999997 }
costs { name: "wrapped_transpose.9" cost_us: 3.4133 }
costs { name: "wrapped_select" cost_us: 1.408 }
costs { name: "loop_add_fusion" cost_us: 385.311 }
costs { name: "wrapped_add" cost_us: 1.4135 }
costs { name: "loop_minimum_fusion" cost_us: 1.579 }
costs { name: "wrapped_cosine" cost_us: 1.4932999999999998 }
costs { name: "input_reduce_fusion" cost_us: 108.6512 }
costs { name: "loop_xor_fusion" cost_us: 1.9093 }
costs { name: "wrapped_multiply" cost_us: 1.2747 }
costs { name: "loop_subtract_fusion" cost_us: 1.728 }
costs { name: "input_add_reduce_fusion.10" cost_us: 12.3303 }
costs { name: "input_add_reduce_fusion.11" cost_us: 541.7846999999999 }
costs { name: "input_add_reduce_fusion.12" cost_us: 544.63 }
costs { name: "input_add_reduce_fusion.13" cost_us: 544.4193 }
costs { name: "input_add_reduce_fusion.16" cost_us: 375.36 }
costs { name: "input_add_reduce_fusion.17" cost_us: 398.0383 }
costs { name: "input_add_reduce_fusion.18" cost_us: 548.33 }
costs { name: "input_add_reduce_fusion.19" cost_us: 483.7663 }
costs { name: "input_add_reduce_fusion.2" cost_us: 403.75559999999996 }
costs { name: "input_add_reduce_fusion.2.double_buffer_clone" cost_us: 375.00120000000004 }
costs { name: "input_add_reduce_fusion.20" cost_us: 698.9167 }
costs { name: "input_add_reduce_fusion.21" cost_us: 698.07 }
costs { name: "input_add_reduce_fusion.22" cost_us: 699.6596999999999 }
costs { name: "input_add_reduce_fusion.23" cost_us: 810.147 }
costs { name: "input_add_reduce_fusion.25" cost_us: 30.123 }
costs { name: "input_add_reduce_fusion.26" cost_us: 30.282700000000002 }
costs { name: "input_add_reduce_fusion.27" cost_us: 5.7493 }
costs { name: "input_add_reduce_fusion.3" cost_us: 487.92909999999995 }
costs { name: "input_add_reduce_fusion.3.double_buffer_clone" cost_us: 490.6083 }
costs { name: "input_add_reduce_fusion.4" cost_us: 67.41369999999999 }
costs { name: "input_add_reduce_fusion.5" cost_us: 25.3443 }
costs { name: "input_add_reduce_fusion.6" cost_us: 296.4373 }
costs { name: "input_add_reduce_fusion.7" cost_us: 296.533 }
costs { name: "input_add_reduce_fusion.8" cost_us: 25.2907 }
costs { name: "input_add_reduce_fusion.9" cost_us: 12.7363 }
costs { name: "input_convert_reduce_fusion" cost_us: 727.5533 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 7711.3197 }
costs { name: "input_exponential_reduce_fusion" cost_us: 6376.0003 }
costs { name: "input_not_reduce_fusion" cost_us: 266.25829999999996 }
costs { name: "input_not_reduce_fusion.1" cost_us: 264.1273 }
costs { name: "input_not_reduce_fusion.2" cost_us: 198.732 }
costs { name: "input_not_reduce_fusion.double_buffer_clone" cost_us: 265.6469 }
costs { name: "input_reduce_fusion.1" cost_us: 240.0192 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 239.5516 }
costs { name: "input_reduce_fusion.10" cost_us: 2.4537 }
costs { name: "input_reduce_fusion.11" cost_us: 2.1016999999999997 }
costs { name: "input_reduce_fusion.12" cost_us: 1.952 }
costs { name: "input_reduce_fusion.13" cost_us: 6.2397 }
costs { name: "input_reduce_fusion.14" cost_us: 6.176 }
costs { name: "input_reduce_fusion.15" cost_us: 10.9653 }
costs { name: "input_reduce_fusion.16" cost_us: 58.5073 }
costs { name: "input_reduce_fusion.17" cost_us: 79.4133 }
costs { name: "input_reduce_fusion.18" cost_us: 11.3597 }
costs { name: "input_reduce_fusion.19" cost_us: 6.1013 }
costs { name: "input_reduce_fusion.2" cost_us: 2.6660999999999997 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 2.6250999999999998 }
costs { name: "input_reduce_fusion.20" cost_us: 6.336 }
costs { name: "input_reduce_fusion.21" cost_us: 1.888 }
costs { name: "input_reduce_fusion.22" cost_us: 270.8807 }
costs { name: "input_reduce_fusion.23" cost_us: 1.8557000000000001 }
costs { name: "input_reduce_fusion.24" cost_us: 205.4617 }
costs { name: "input_reduce_fusion.25" cost_us: 1.92 }
costs { name: "input_reduce_fusion.26" cost_us: 212.87429999999998 }
costs { name: "input_reduce_fusion.27" cost_us: 2369.252 }
costs { name: "input_reduce_fusion.28" cost_us: 2.3573000000000004 }
costs { name: "input_reduce_fusion.29" cost_us: 107.6373 }
costs { name: "input_reduce_fusion.30" cost_us: 108.928 }
costs { name: "input_reduce_fusion.32" cost_us: 244.874 }
costs { name: "input_reduce_fusion.33" cost_us: 241.621 }
costs { name: "input_reduce_fusion.34" cost_us: 264.24629999999996 }
costs { name: "input_reduce_fusion.35" cost_us: 1.6747 }
costs { name: "input_reduce_fusion.36" cost_us: 1.888 }
costs { name: "input_reduce_fusion.37" cost_us: 2.5383 }
costs { name: "input_reduce_fusion.38" cost_us: 6.432 }
costs { name: "input_reduce_fusion.4" cost_us: 9.088299999999998 }
costs { name: "input_reduce_fusion.43" cost_us: 1.8023 }
costs { name: "input_reduce_fusion.44" cost_us: 2.1757 }
costs { name: "input_reduce_fusion.45" cost_us: 2.0373 }
costs { name: "input_reduce_fusion.46" cost_us: 23.637700000000002 }
costs { name: "input_reduce_fusion.47" cost_us: 1.5467 }
costs { name: "input_reduce_fusion.48" cost_us: 2.304 }
costs { name: "input_reduce_fusion.49" cost_us: 2.1653000000000002 }
costs { name: "input_reduce_fusion.5" cost_us: 2.2613000000000003 }
costs { name: "input_reduce_fusion.50" cost_us: 2.485 }
costs { name: "input_reduce_fusion.51" cost_us: 2.2293000000000003 }
costs { name: "input_reduce_fusion.52" cost_us: 2.347 }
costs { name: "input_reduce_fusion.53" cost_us: 2.336 }
costs { name: "input_reduce_fusion.54" cost_us: 1.952 }
costs { name: "input_reduce_fusion.55" cost_us: 1.9627000000000001 }
costs { name: "input_reduce_fusion.56" cost_us: 2.4747 }
costs { name: "input_reduce_fusion.57" cost_us: 1.5997000000000001 }
costs { name: "input_reduce_fusion.58" cost_us: 1.4827000000000001 }
costs { name: "input_reduce_fusion.59" cost_us: 1.632 }
costs { name: "input_reduce_fusion.6" cost_us: 1.9947000000000001 }
costs { name: "input_reduce_fusion.60" cost_us: 2.0907 }
costs { name: "input_reduce_fusion.61" cost_us: 24.928 }
costs { name: "input_reduce_fusion.62" cost_us: 1.9203 }
costs { name: "input_reduce_fusion.63" cost_us: 2.144 }
costs { name: "input_reduce_fusion.64" cost_us: 2.251 }
costs { name: "input_reduce_fusion.65" cost_us: 1.6322999999999999 }
costs { name: "input_reduce_fusion.66" cost_us: 1.568 }
costs { name: "input_reduce_fusion.67" cost_us: 1.5252999999999999 }
costs { name: "input_reduce_fusion.68" cost_us: 1.707 }
costs { name: "input_reduce_fusion.69" cost_us: 1.504 }
costs { name: "input_reduce_fusion.7" cost_us: 2.2506999999999997 }
costs { name: "input_reduce_fusion.70" cost_us: 1.483 }
costs { name: "input_reduce_fusion.71" cost_us: 1.802 }
costs { name: "input_reduce_fusion.72" cost_us: 2.2297 }
costs { name: "input_reduce_fusion.73" cost_us: 2.229 }
costs { name: "input_reduce_fusion.74" cost_us: 1.7492999999999999 }
costs { name: "input_reduce_fusion.75" cost_us: 1.7603 }
costs { name: "input_reduce_fusion.76" cost_us: 2.656 }
costs { name: "input_reduce_fusion.8" cost_us: 2.6773000000000002 }
costs { name: "input_reduce_fusion.9" cost_us: 9.1737 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 108.432 }
costs { name: "input_transpose_fusion.12" cost_us: 12.8107 }
costs { name: "input_transpose_fusion.13" cost_us: 5.973 }
costs { name: "loop_add_log_fusion" cost_us: 2.869 }
costs { name: "loop_add_select_fusion" cost_us: 1.578 }
costs { name: "loop_compare_select_fusion" cost_us: 44.405699999999996 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.6533 }
costs { name: "loop_convert_fusion.31" cost_us: 2.6776999999999997 }
costs { name: "loop_convert_fusion.32" cost_us: 2.4107 }
costs { name: "loop_convert_slice_fusion" cost_us: 11.5733 }
costs { name: "loop_convert_slice_fusion.1" cost_us: 11.776 }
costs { name: "loop_convert_slice_fusion.2" cost_us: 5.0877 }
costs { name: "loop_convert_slice_fusion.3" cost_us: 2.4963 }
costs { name: "loop_convert_slice_fusion.4" cost_us: 3.008 }
costs { name: "loop_cosine_sine_fusion.2" cost_us: 15.8613 }
costs { name: "loop_divide_sqrt_fusion" cost_us: 2.3787 }
costs { name: "loop_multiply_fusion.12" cost_us: 3.7443 }
costs { name: "loop_multiply_fusion.16" cost_us: 2.0157 }
costs { name: "loop_multiply_fusion.9" cost_us: 352.7143 }
costs { name: "loop_select_fusion.1" cost_us: 287.574 }
costs { name: "loop_select_fusion.2" cost_us: 288.47 }
costs { name: "loop_select_fusion.3" cost_us: 80.619 }
costs { name: "loop_select_fusion.4" cost_us: 2.4213 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.9093 }
costs { name: "fusion.50" cost_us: 327.2526 }
costs { name: "fusion.50.double_buffer_clone" cost_us: 288.0295 }
costs { name: "fusion.50.peeled_double_buffer" cost_us: 274.2397 }
costs { name: "fusion.51" cost_us: 287.2814 }
costs { name: "fusion.51.double_buffer_clone" cost_us: 284.0845 }
costs { name: "fusion.51.peeled_double_buffer" cost_us: 273.6953 }
costs { name: "fusion.693" cost_us: 290.7217 }
costs { name: "fusion.694" cost_us: 331.8723 }
costs { name: "input_reduce_fusion.31" cost_us: 128.7687 }
costs { name: "loop_multiply_fusion.10" cost_us: 357.1853 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.4853 }
costs { name: "wrapped_convert" cost_us: 2.24 }
costs { name: "wrapped_convert.1" cost_us: 15.648 }
costs { name: "all-gather-start.5" cost_us: 29372.549300000002 }
costs { name: "custom-call.154.0" cost_us: 103465.592 }
costs { name: "loop_convert_fusion.24" cost_us: 4958.213 }
costs { name: "input_transpose_fusion.17" cost_us: 16.736 }
costs { name: "all-gather-start.4" cost_us: 25840.368 }
costs { name: "custom-call.147.0" cost_us: 88726.4233 }
costs { name: "copy_fusion.2" cost_us: 3.115 }
costs { name: "copy_fusion.3" cost_us: 10.2507 }
costs { name: "loop_broadcast_fusion.4" cost_us: 1.6853 }
costs { name: "loop_convert_fusion.10" cost_us: 2.1949 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 2.418 }
costs { name: "loop_convert_fusion.10.peeled_double_buffer" cost_us: 1.7917 }
costs { name: "loop_convert_fusion.2" cost_us: 5.6101 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 5.458399999999999 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 5.8237 }
costs { name: "loop_convert_fusion.3" cost_us: 5.5092 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 5.3875 }
costs { name: "loop_convert_fusion.33" cost_us: 2.6986999999999997 }
costs { name: "loop_convert_fusion.34" cost_us: 2.4857 }
costs { name: "loop_convert_fusion.4" cost_us: 5.6706 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 5.5956 }
costs { name: "loop_convert_fusion.5" cost_us: 3.3663000000000003 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 3.2727 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 3.499 }
costs { name: "loop_convert_fusion.6" cost_us: 3.3531999999999997 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 3.2643 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 3.584 }
costs { name: "loop_convert_fusion.7" cost_us: 2.5051 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 2.78 }
costs { name: "loop_convert_fusion.8" cost_us: 2.551 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 2.5175 }
costs { name: "loop_convert_fusion.9" cost_us: 2.4903000000000004 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 2.4011 }
costs { name: "loop_convert_fusion.9.peeled_double_buffer" cost_us: 2.336 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 347.7471 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 346.57590000000005 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 338.83759999999995 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 330.52 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 364.235 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 364.216 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 339.43829999999997 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 332.641 }
costs { name: "copy_fusion.1" cost_us: 2.059 }
costs { name: "loop_add_fusion.1" cost_us: 2.0374 }
costs { name: "loop_add_fusion.1.double_buffer_clone" cost_us: 2.0514 }
costs { name: "loop_add_fusion.7" cost_us: 438.8487 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 383.3773 }
costs { name: "loop_add_fusion.peeled_double_buffer" cost_us: 372.4933 }
costs { name: "loop_multiply_fusion" cost_us: 1500.9617 }
costs { name: "loop_multiply_fusion.5" cost_us: 1501.7943 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 1680.3519 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 1449.2527 }
costs { name: "custom-call.152.0" cost_us: 25252.9293 }
costs { name: "custom-call.59.0" cost_us: 22117.6305 }
costs { name: "custom-call.59.0.double_buffer_clone" cost_us: 21843.3837 }
costs { name: "custom-call.59.0.peeled_double_buffer" cost_us: 21125.8737 }
costs { name: "custom-call.153.0" cost_us: 22713.5213 }
costs { name: "custom-call.60.0" cost_us: 22480.974100000003 }
costs { name: "custom-call.60.0.double_buffer_clone" cost_us: 23426.1277 }
costs { name: "custom-call.60.0.peeled_double_buffer" cost_us: 21552.3567 }
costs { name: "cublas-gemm.19.0" cost_us: 23556.6163 }
costs { name: "cublas-gemm.2.0" cost_us: 23246.6853 }
costs { name: "cublas-gemm.2.0.double_buffer_clone" cost_us: 25937.2137 }
costs { name: "cublas-gemm.2.0.peeled_double_buffer" cost_us: 22429.0667 }
costs { name: "custom-call.42.0" cost_us: 10468.785800000001 }
costs { name: "custom-call.42.0.double_buffer_clone" cost_us: 9350.8341 }
costs { name: "custom-call.42.0.peeled_double_buffer" cost_us: 9707.9777 }
costs { name: "custom-call.43.0" cost_us: 9465.392 }
costs { name: "loop_broadcast_fusion" cost_us: 1.4619000000000002 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.3744 }
costs { name: "loop_broadcast_fusion.1.double_buffer_clone" cost_us: 1.5917999999999999 }
costs { name: "loop_broadcast_fusion.1.peeled_double_buffer" cost_us: 1.2372999999999998 }
costs { name: "loop_broadcast_fusion.12" cost_us: 1.9733 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.5724 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 2.0903 }
costs { name: "loop_convert_fusion.1" cost_us: 77.5815 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 72.8064 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 80.331 }
costs { name: "loop_convert_fusion.30" cost_us: 73.4937 }
costs { name: "loop_convert_fusion" cost_us: 564.8892 }
costs { name: "loop_convert_fusion.25" cost_us: 519.7023 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 515.7626 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 577.783 }
costs { name: "custom-call.149.0" cost_us: 843.7453 }
costs { name: "custom-call.56.0" cost_us: 1054.7178999999999 }
costs { name: "custom-call.56.0.double_buffer_clone" cost_us: 840.8375 }
costs { name: "custom-call.56.0.peeled_double_buffer" cost_us: 980.4257 }
costs { name: "custom-call.150.0" cost_us: 844.3323 }
costs { name: "custom-call.57.0" cost_us: 1054.8659 }
costs { name: "custom-call.57.0.double_buffer_clone" cost_us: 840.6201 }
costs { name: "custom-call.57.0.peeled_double_buffer" cost_us: 980.511 }
costs { name: "custom-call.151.0" cost_us: 6823.4033 }
costs { name: "custom-call.58.0" cost_us: 6912.7563 }
costs { name: "custom-call.58.0.double_buffer_clone" cost_us: 6629.9267 }
costs { name: "custom-call.58.0.peeled_double_buffer" cost_us: 6354.5953 }
costs { name: "custom-call.148.0" cost_us: 6769.953 }
costs { name: "custom-call.55.0" cost_us: 7787.492200000001 }
costs { name: "custom-call.55.0.double_buffer_clone" cost_us: 6750.4992 }
costs { name: "custom-call.55.0.peeled_double_buffer" cost_us: 6976.445299999999 }
costs { name: "input_reduce_fusion.77" cost_us: 2.592 }
costs { name: "loop_slice_fusion" cost_us: 1.632 }
costs { name: "wrapped_broadcast.1" cost_us: 42.336 }
costs { name: "loop_convert_fusion.23" cost_us: 1.8023 }
costs { name: "loop_cosine_sine_fusion.1" cost_us: 15.424299999999999 }
costs { name: "loop_divide_fusion.1" cost_us: 24.4693 }
costs { name: "wrapped_broadcast" cost_us: 318.5943 }
costs { name: "input_reduce_fusion.78" cost_us: 18.848 }
costs { name: "all-reduce-start.4" cost_us: 22989.09 }
costs { name: "all-reduce-start.5" cost_us: 217.5463 }
costs { name: "all-reduce-start.7" cost_us: 581.091 }
costs { name: "all-reduce-start.9" cost_us: 257.495 }
costs { name: "input_add_reduce_fusion" cost_us: 665.1486 }
costs { name: "input_add_reduce_fusion.1" cost_us: 858.1265 }
costs { name: "input_add_reduce_fusion.1.double_buffer_clone" cost_us: 851.7129 }
costs { name: "input_add_reduce_fusion.14" cost_us: 520.5123 }
costs { name: "input_add_reduce_fusion.15" cost_us: 843.6387 }
costs { name: "input_add_reduce_fusion.24" cost_us: 836.5003 }
costs { name: "input_add_reduce_fusion.double_buffer_clone" cost_us: 615.9825 }
costs { name: "input_reduce_fusion.3" cost_us: 4.1417 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 3.8173000000000004 }
costs { name: "input_reduce_fusion.39" cost_us: 4.448 }
costs { name: "input_reduce_fusion.40" cost_us: 3.424 }
costs { name: "input_reduce_fusion.42" cost_us: 3.4133 }
costs { name: "loop_multiply_fusion.11" cost_us: 2.7517 }
costs { name: "loop_multiply_fusion.13" cost_us: 2.3676999999999997 }
costs { name: "loop_multiply_fusion.14" cost_us: 2.5063 }
costs { name: "loop_multiply_fusion.15" cost_us: 3.1363000000000003 }
costs { name: "input_reduce_fusion.41" cost_us: 3.403 }
costs { name: "wrapped_slice.46" cost_us: 1.632 }
costs { name: "custom-call.155.0" cost_us: 112424.5797 }
costs { name: "custom-call.190.0" cost_us: 105103.2643 }
costs { name: "custom-call.191.0" cost_us: 91031.151 }
costs { name: "loop_convert_fusion.14" cost_us: 4.64 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 5.3725 }
costs { name: "loop_convert_fusion.15" cost_us: 4.501399999999999 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 5.0536 }
costs { name: "loop_convert_fusion.16" cost_us: 4.889399999999999 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 5.57 }
costs { name: "loop_convert_fusion.17" cost_us: 2.9554 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 30.1265 }
costs { name: "loop_convert_fusion.18" cost_us: 2.9459 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 14.6585 }
costs { name: "loop_convert_fusion.19" cost_us: 2.3110999999999997 }
costs { name: "loop_convert_fusion.19.double_buffer_clone" cost_us: 2.4689 }
costs { name: "loop_convert_fusion.20" cost_us: 2.3595 }
costs { name: "loop_convert_fusion.20.double_buffer_clone" cost_us: 21.3688 }
costs { name: "loop_convert_fusion.21" cost_us: 2.3091999999999997 }
costs { name: "loop_convert_fusion.21.double_buffer_clone" cost_us: 2.3961 }
costs { name: "loop_convert_fusion.22" cost_us: 2.5573 }
costs { name: "loop_convert_fusion.22.double_buffer_clone" cost_us: 2.3448 }
costs { name: "loop_multiply_fusion.2" cost_us: 346.1165 }
costs { name: "loop_multiply_fusion.2.double_buffer_clone" cost_us: 346.0002 }
costs { name: "loop_multiply_fusion.7" cost_us: 347.55170000000004 }
costs { name: "loop_select_fusion" cost_us: 4.2333 }
costs { name: "loop_select_fusion.double_buffer_clone" cost_us: 1.882 }
costs { name: "loop_add_fusion.5" cost_us: 2.0694 }
costs { name: "loop_add_fusion.5.double_buffer_clone" cost_us: 2.0507 }
costs { name: "input_transpose_fusion.10" cost_us: 3.8933 }
costs { name: "input_transpose_fusion.5" cost_us: 2.6023 }
costs { name: "input_transpose_fusion.6" cost_us: 2.1227 }
costs { name: "input_transpose_fusion.9" cost_us: 3.8293000000000004 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.6428 }
costs { name: "loop_dynamic_update_slice_fusion.10.double_buffer_clone" cost_us: 1.6134000000000002 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 2.5863 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 2.4011 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 4.288600000000001 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 4.311 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 4.475899999999999 }
costs { name: "loop_dynamic_update_slice_fusion.4.double_buffer_clone" cost_us: 4.2818000000000005 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 4.4959 }
costs { name: "loop_dynamic_update_slice_fusion.5.double_buffer_clone" cost_us: 4.1846000000000005 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 2.3874 }
costs { name: "loop_dynamic_update_slice_fusion.6.double_buffer_clone" cost_us: 2.1779 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 1.9233 }
costs { name: "loop_dynamic_update_slice_fusion.7.double_buffer_clone" cost_us: 2.0057 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 1.8054000000000001 }
costs { name: "loop_dynamic_update_slice_fusion.8.double_buffer_clone" cost_us: 1.844 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 1.5631 }
costs { name: "loop_dynamic_update_slice_fusion.9.double_buffer_clone" cost_us: 1.5042 }
costs { name: "loop_add_fusion.10" cost_us: 100.7897 }
costs { name: "loop_add_fusion.11" cost_us: 174.177 }
costs { name: "loop_add_fusion.3" cost_us: 783.3735 }
costs { name: "loop_add_fusion.3.double_buffer_clone" cost_us: 784.8029 }
costs { name: "loop_add_fusion.4" cost_us: 100.8594 }
costs { name: "loop_add_fusion.4.double_buffer_clone" cost_us: 101.3533 }
costs { name: "loop_add_fusion.8" cost_us: 780.3777 }
costs { name: "loop_add_fusion.9" cost_us: 807.0513000000001 }
costs { name: "loop_add_multiply_fusion" cost_us: 2853.8104 }
costs { name: "loop_add_multiply_fusion.1" cost_us: 2839.002 }
costs { name: "loop_add_multiply_fusion.2" cost_us: 2893.477 }
costs { name: "loop_add_multiply_fusion.double_buffer_clone" cost_us: 2871.3866000000003 }
costs { name: "loop_compare_fusion.1" cost_us: 1.5568 }
costs { name: "loop_compare_fusion.1.double_buffer_clone" cost_us: 1.3557000000000001 }
costs { name: "loop_compare_fusion.3" cost_us: 2.2815 }
costs { name: "loop_compare_fusion.3.double_buffer_clone" cost_us: 1.4042000000000001 }
costs { name: "loop_multiply_fusion.3" cost_us: 2.2506 }
costs { name: "loop_multiply_fusion.3.double_buffer_clone" cost_us: 2.2679 }
costs { name: "loop_multiply_fusion.4" cost_us: 2.4473000000000003 }
costs { name: "loop_multiply_fusion.4.double_buffer_clone" cost_us: 2.4024 }
costs { name: "custom-call.159.0" cost_us: 25697.733 }
costs { name: "custom-call.179.0" cost_us: 23307.772 }
costs { name: "custom-call.83.0" cost_us: 23421.675600000002 }
costs { name: "custom-call.83.0.double_buffer_clone" cost_us: 23707.9734 }
costs { name: "custom-call.166.0" cost_us: 20550.998 }
costs { name: "custom-call.176.0" cost_us: 22649.0363 }
costs { name: "custom-call.90.0" cost_us: 22838.3085 }
costs { name: "custom-call.90.0.double_buffer_clone" cost_us: 22951.995600000002 }
costs { name: "cublas-gemm.20.0" cost_us: 23076.455 }
costs { name: "cublas-gemm.22.0" cost_us: 23347.275 }
costs { name: "cublas-gemm.7.0" cost_us: 22858.3676 }
costs { name: "cublas-gemm.7.0.double_buffer_clone" cost_us: 22836.477199999998 }
costs { name: "custom-call.167.0" cost_us: 19586.2827 }
costs { name: "custom-call.177.0" cost_us: 20819.988 }
costs { name: "custom-call.91.0" cost_us: 22604.0347 }
costs { name: "custom-call.91.0.double_buffer_clone" cost_us: 22610.111800000002 }
costs { name: "custom-call.157.0" cost_us: 24966.042699999998 }
costs { name: "custom-call.174.0" cost_us: 22828.1333 }
costs { name: "custom-call.81.0" cost_us: 22782.0118 }
costs { name: "custom-call.81.0.double_buffer_clone" cost_us: 23123.187 }
costs { name: "custom-call.168.0" cost_us: 22367.610699999997 }
costs { name: "custom-call.178.0" cost_us: 23168.8657 }
costs { name: "custom-call.92.0" cost_us: 19320.1175 }
costs { name: "custom-call.92.0.double_buffer_clone" cost_us: 19688.385 }
costs { name: "all-reduce-start.1" cost_us: 14105.149300000001 }
costs { name: "all-reduce-start.3" cost_us: 2766.3466000000003 }
costs { name: "wrapped_slice.12" cost_us: 1.7737 }
costs { name: "wrapped_slice.42" cost_us: 1.7283 }
costs { name: "wrapped_slice.43" cost_us: 1.8023 }
costs { name: "wrapped_slice.5" cost_us: 1.8382 }
costs { name: "all-reduce-start.8" cost_us: 1137.9813000000001 }
costs { name: "wrapped_slice.13" cost_us: 1.9345 }
costs { name: "wrapped_slice.4" cost_us: 1.9667000000000001 }
costs { name: "wrapped_slice.40" cost_us: 1.664 }
costs { name: "wrapped_slice.41" cost_us: 1.664 }
costs { name: "custom-call.39.0" cost_us: 26793.2863 }
costs { name: "custom-call.45.0" cost_us: 26651.9659 }
costs { name: "custom-call.45.0.double_buffer_clone" cost_us: 26556.8973 }
costs { name: "custom-call.47.0" cost_us: 27381.3063 }
costs { name: "custom-call.164.0" cost_us: 839.3727 }
costs { name: "custom-call.169.0" cost_us: 812.0203 }
costs { name: "custom-call.184.0" cost_us: 989.782 }
costs { name: "custom-call.186.0" cost_us: 828.3103000000001 }
costs { name: "custom-call.88.0" cost_us: 833.7192 }
costs { name: "custom-call.88.0.double_buffer_clone" cost_us: 831.7774000000001 }
costs { name: "custom-call.93.0" cost_us: 712.8782 }
costs { name: "custom-call.93.0.double_buffer_clone" cost_us: 696.8704 }
costs { name: "cublas-gemm.21.0" cost_us: 849.5797 }
costs { name: "cublas-gemm.23.0" cost_us: 1172.29 }
costs { name: "cublas-gemm.8.0" cost_us: 861.7334000000001 }
costs { name: "cublas-gemm.8.0.double_buffer_clone" cost_us: 859.7796 }
costs { name: "custom-call.172.0" cost_us: 795.071 }
costs { name: "custom-call.189.0" cost_us: 1088.012 }
costs { name: "custom-call.96.0" cost_us: 707.1936 }
costs { name: "custom-call.96.0.double_buffer_clone" cost_us: 818.9845 }
costs { name: "custom-call.163.0" cost_us: 6736.5467 }
costs { name: "custom-call.170.0" cost_us: 6608.0777 }
costs { name: "custom-call.183.0" cost_us: 6653.5693 }
costs { name: "custom-call.187.0" cost_us: 6766.391 }
costs { name: "custom-call.87.0" cost_us: 6711.7973 }
costs { name: "custom-call.87.0.double_buffer_clone" cost_us: 6691.514 }
costs { name: "custom-call.94.0" cost_us: 6185.134099999999 }
costs { name: "custom-call.94.0.double_buffer_clone" cost_us: 5908.531400000001 }
costs { name: "custom-call.165.0" cost_us: 5785.675 }
costs { name: "custom-call.171.0" cost_us: 6467.938700000001 }
costs { name: "custom-call.185.0" cost_us: 7905.0047 }
costs { name: "custom-call.188.0" cost_us: 6671.078 }
costs { name: "custom-call.89.0" cost_us: 5832.7942 }
costs { name: "custom-call.89.0.double_buffer_clone" cost_us: 5809.5829 }
costs { name: "custom-call.95.0" cost_us: 5753.7884 }
costs { name: "custom-call.95.0.double_buffer_clone" cost_us: 5599.7014 }
costs { name: "custom-call.156.0" cost_us: 28211.439300000002 }
costs { name: "custom-call.173.0" cost_us: 21563.15 }
costs { name: "custom-call.80.0" cost_us: 21645.2572 }
costs { name: "custom-call.80.0.double_buffer_clone" cost_us: 20079.6485 }
costs { name: "custom-call.158.0" cost_us: 23929.3647 }
costs { name: "custom-call.175.0" cost_us: 21438.168 }
costs { name: "custom-call.82.0" cost_us: 21340.3833 }
costs { name: "custom-call.82.0.double_buffer_clone" cost_us: 21085.2275 }
costs { name: "loop_multiply_fusion.1" cost_us: 364.9776 }
costs { name: "loop_multiply_fusion.1.double_buffer_clone" cost_us: 327.91409999999996 }
costs { name: "loop_multiply_fusion.6" cost_us: 414.8383 }
costs { name: "loop_multiply_fusion.8" cost_us: 330.561 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.4044 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 2.1330999999999998 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.1227 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.763 }
costs { name: "loop_rsqrt_fusion" cost_us: 2.2192 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.1973000000000003 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.4533 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 2.2211 }
costs { name: "custom-call.38.0" cost_us: 9361.999300000001 }
costs { name: "custom-call.44.0" cost_us: 9230.3794 }
costs { name: "custom-call.44.0.double_buffer_clone" cost_us: 9165.9476 }
costs { name: "custom-call.46.0" cost_us: 9223.454 }
costs { name: "loop_broadcast_fusion.2" cost_us: 1.4361 }
costs { name: "loop_broadcast_fusion.2.double_buffer_clone" cost_us: 1.5442 }
costs { name: "loop_broadcast_fusion.3" cost_us: 1.5511 }
costs { name: "loop_broadcast_fusion.3.double_buffer_clone" cost_us: 1.4673 }
costs { name: "loop_convert_fusion.13" cost_us: 53.4403 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 53.543 }
costs { name: "loop_convert_fusion.28" cost_us: 53.7813 }
costs { name: "loop_convert_fusion.29" cost_us: 53.045300000000005 }
costs { name: "loop_compare_fusion.2" cost_us: 1.4493 }
costs { name: "loop_compare_fusion.2.double_buffer_clone" cost_us: 1.5357 }
costs { name: "loop_convert_fusion.11" cost_us: 2.0122 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 1.6872 }
costs { name: "loop_convert_fusion.12" cost_us: 403.7073 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 402.841 }
costs { name: "loop_convert_fusion.26" cost_us: 408.01 }
costs { name: "loop_convert_fusion.27" cost_us: 405.3557 }
costs { name: "loop_cosine_sine_fusion" cost_us: 15.2017 }
costs { name: "loop_cosine_sine_fusion.double_buffer_clone" cost_us: 15.3188 }
costs { name: "loop_divide_fusion" cost_us: 1.6977 }
costs { name: "loop_divide_fusion.double_buffer_clone" cost_us: 1.7869000000000002 }
costs { name: "custom-call.161.0" cost_us: 838.1453 }
costs { name: "custom-call.181.0" cost_us: 841.78 }
costs { name: "custom-call.85.0" cost_us: 833.0066999999999 }
costs { name: "custom-call.85.0.double_buffer_clone" cost_us: 830.1999000000001 }
costs { name: "custom-call.162.0" cost_us: 840.3426999999999 }
costs { name: "custom-call.182.0" cost_us: 827.839 }
costs { name: "custom-call.86.0" cost_us: 833.1123 }
costs { name: "custom-call.86.0.double_buffer_clone" cost_us: 831.2364 }
costs { name: "custom-call.160.0" cost_us: 6737.0993 }
costs { name: "custom-call.180.0" cost_us: 6759.9267 }
costs { name: "custom-call.84.0" cost_us: 6679.0602 }
costs { name: "custom-call.84.0.double_buffer_clone" cost_us: 6665.0346 }
costs { name: "loop_slice_fusion.1" cost_us: 2.5493 }
costs { name: "loop_slice_fusion.2" cost_us: 2.6346999999999996 }
costs { name: "wrapped_transpose.2" cost_us: 281.963 }
costs { name: "wrapped_transpose.3" cost_us: 280.994 }
costs { name: "input_transpose_fusion.14" cost_us: 320.235 }
costs { name: "wrapped_transpose" cost_us: 3.8186999999999998 }
costs { name: "wrapped_transpose.1" cost_us: 3.5416999999999996 }
costs { name: "loop_transpose_fusion.2" cost_us: 13.0347 }
costs { name: "wrapped_transpose.4" cost_us: 93.92 }
costs { name: "loop_transpose_fusion.1" cost_us: 84.3953 }
costs { name: "loop_transpose_fusion" cost_us: 12.299 }
