apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: xpk-test-workload
  labels:
    kueue.x-k8s.io/queue-name: multislice-queue  # Name of the LocalQueue
    xpk.google.com/workload: xpk-test-workload
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: cloud.google.com/gke-nodepool # 1:1 job replica to node pool assignment
spec:
  failurePolicy:
    maxRestarts: 0
  replicatedJobs:
    - name: slice-job
      replicas: 1
      template:
        spec:
          parallelism: 1024    # Equal to the number of VMs per slice
          completions: 1024    # Same as the above.
          backoffLimit: 0   # When any pod fails, the job is failed
          template:
            metadata:
              labels:
                xpk.google.com/workload: xpk-test-workload
              annotations: # required for GCSFuse
                gke-gcsfuse/volumes: "true"
                gke-gcsfuse/cpu-limit: "0"
                gke-gcsfuse/memory-limit: "0"
                gke-gcsfuse/ephemeral-storage-limit: "0"
            
            spec:
              schedulerName: default-scheduler
              restartPolicy: Never
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: cloud.google.com/gke-nodepool
                        operator: NotIn
                        values:
                        - default-pool

              nodeSelector:
                cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
              
              # Needed for GCSFuse.
              initContainers:
              - name: gke-gcsfuse-sidecar
                image: gcr.io/gcs-tess/ayushsethi-custom-csi/gcs-fuse-csi-driver-sidecar-mounter:v1.4.0-36-gb83e1b73-dirty
                restartPolicy: Always
                env:
                - name: NATIVE_SIDECAR
                  value: "TRUE"
                # resources:
                #   requests:
                #     cpu: 250m
                #     memory: 256Mi
                #     ephemeral-storage: 1Ti
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
                  runAsGroup: 65534
                  runAsNonRoot: true
                  runAsUser: 65534
                  seccompProfile:
                    type: RuntimeDefault
                volumeMounts:
                - mountPath: /gcsfuse-tmp
                  name: gke-gcsfuse-tmp
                - mountPath: /gcsfuse-buffer
                  name: gke-gcsfuse-buffer
                - mountPath: /gcsfuse-cache
                  name: gke-gcsfuse-cache
                
              priorityClassName: medium
              hostNetwork: true
              dnsPolicy: ClusterFirstWithHostNet
              terminationGracePeriodSeconds: 30
              serviceAccountName: bernardhan-benchmark
              containers:
              - name: jax-cpu
                image: gcr.io/gcs-tess/bernardhan_runner_test
                
                env: 
                - name: REPLICATED_JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['jobset.sigs.k8s.io/replicatedjob-name']
                - name: JOB_INDEX
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['jobset.sigs.k8s.io/job-index']
                - name: JOB_COMPLETION_INDEX
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['batch.kubernetes.io/job-completion-index']
                - name: PROCESSES_IN_JOB
                  value: "1024"
                - name: JAX_PROCESS_COUNT
                  value: "1024"
                
                - name: JOBSET_NAME
                  value: "xpk-test-workload"
                - name: JAX_COORDINATOR_ADDRESS
                  value: "$(JOBSET_NAME)-$(REPLICATED_JOB_NAME)-0-0.$(JOBSET_NAME)"
  
                ports:
                - containerPort: 8471
                - containerPort: 8080
                - containerPort: 1234
                securityContext:
                  privileged: true
                command:
                - bash
                - -c
                - |
                  # Temporary fix to solve the slow pod initialization errors by specifically asking for all pods to be ready.
                  while true; do
                    kubectl wait --for=jsonpath='{.status.replicatedJobsStatus[0].ready}'=1 jobset/xpk-test-workload
                    if [ $? -eq 0 ]; then
                      echo "Pods are ready!"
                      break
                    else
                      echo "Pods are not ready! Sleeping for 5s before checking again"
                      sleep 5
                    fi
                  done
     
                  export COMMON_RUN_FLAGS="enable_checkpointing=False ici_data_parallelism=8 ici_fsdp_parallelism=128";
                  export BENCHMARK_RUN_FLAGS="hardware=cpu epochs=2 local_batch_size=32 prefetch_factor=2 data_loader_num_workers=2 per_step_computation_time=0";
                  echo XPK Start: $(date) ; _sigterm() ( kill -SIGTERM $! 2>/dev/null;); trap _sigterm SIGTERM;(JAX_PLATFORMS=cpu python3 MaxText/standalone_dataloader.py MaxText/configs/base.yml ${BENCHMARK_RUN_FLAGS} ${COMMON_RUN_FLAGS}) & PID=$!; while kill -0 $PID 2>/dev/null; do sleep 5; done; wait $PID; EXIT_CODE=$? ;  echo XPK End: $(date); echo EXIT_CODE=$EXIT_CODE;

                volumeMounts:
                - mountPath: /mnt/gcsfuse
                  name: gcs-fuse-csi-ephemeral
                  readOnly: true
  
              volumes:
              - name: gcs-fuse-csi-ephemeral
                csi:
                  driver: gcsfuse.csi.storage.gke.io
                  readOnly: true
                  volumeAttributes:
                    skipCSIBucketAccessCheck: "true"
                    bucketName: "xai-hf-dataset-parquet"
                    # mountOptions: "debug_fuse,uid=1001,gid=3003"
                    # mountOptions: "debug_fuse,uid=1001,gid=3003,file-cache:enable-parallel-downloads:false"
                    mountOptions: "debug_fuse,max-conns-per-host=0,uid=1001,gid=3003,file-cache:enable-parallel-downloads:true,file-cache:parallel-downloads-per-file:10,file-cache:download-chunk-size-mb:200"
                    metadataCacheTtlSeconds: "-1"
                    metadataStatCacheCapacity: "-1"
                    metadataTypeCacheCapacity: "-1"
                    fileCacheCapacity: "-1"
                    fileCacheForRangeRead: "true"
              - name: gke-gcsfuse-tmp
                emptyDir: { }
              - name: gke-gcsfuse-buffer
                emptyDir: { }
              - name: gke-gcsfuse-cache
                emptyDir: { }
