"""Check if the logits generated by a model's MaxText implementation matches hf logits for the same inputs"""

import numpy as np
import orbax.checkpoint as ocp
import jax
from absl import app


def main(argv):
  jax.config.update("jax_default_prng_impl", "unsafe_rbg")
  ckpt_path = "gs://ranran-multipod-dev/deepseek3/small/1/deepseek3-test1/checkpoints/"
  checkpointer = ocp.Checkpointer(ocp.CompositeCheckpointHandler())
  restored = checkpointer.restore(ckpt_path)
  restored.state
  breakpoint()


if __name__ == "__main__":
  app.run(main)
