mesh_axes: ['data', 'expert']
data_sharding: [['data', 'expert']]
# currently only EP support, will add data + EP
logical_axis_rules: [
                       ['activation_batch', ['data']],
                       ['activation_batch_moe', ['data']],
                       ['activation_batch_no_exp', ['data']],
                       ['activation_batch_no_exp_moe', ['data']],
                       ['activation_embed_and_logits_batch', ['data','expert']],
                       ['activation_embed_and_logits_batch_sequence', ['data', 'expert']],
                       ['activation_heads', ['expert']],
                       ['activation_kv_heads', ['expert']],
                       ['activation_attn_length', ['expert']],
                       ['activation_attn_length_no_exp', []],
                       ['activation_length', ['expert']],
                       ['activation_length_moe', ['expert']],
                       ['activation_length_no_exp', []],
                       ['activation_length_no_exp_moe', []],
                       ['activation_q_length', ['expert']],
                       ['activation_attn_embed', []],
                       ['activation_embed', ['expert']], # this says that the expert physical axes should act like TP for attention (and shared expert) activations
                       ['activation_embed_moe', ['expert']], # this is bad, it should be none, but we currently use this as an out_spec of wrapper when we should use activation_embed instead
                       ['activation_mlp', []],
                       ['activation_kv', []],
                       ['activation_prefill_kv_batch', ['data', 'expert']],
                       ['activation_kv_batch', ['data', 'expert']],
                       ['activation_kv_batch_no_exp', []],
                       ['activation_kv_head_dim', []],
                       ['activation_vocab', []],
                       ['activation_norm_length', []],
                       ['activation_norm_length_moe', []],
                       ['activation_exp', ['expert']],
                       ['decode_batch', ['data', 'expert']],
                       ['decode_length', []],
                       ['mlp', []],
                       ['mlp_no_fsdp', []],
                       ['moe_mlp', []],
                       ['vocab', []],
                       ['heads', []],
                       ['q_heads', ['expert']],
                       ['kv_heads', ['expert']],
                       ['kv_head_dim', []],
                       ['kv', []],
                       ['embed', ['expert']],
                       ['embed', []],
                       ['embed_moe', ['expert']],
                       ['embed_moe', []],
                       ['embed_tensor_transpose', []],
                       ['embed_no_exp', []],
                       ['embed_no_exp_moe', []],
                       ['q_lora', ['expert']],
                       ['kv_lora', ['expert']],
                       ['norm', []],
                       ['cache_heads', []],
                       ['exp', ['expert']],
                       ['paged_kv_heads', []],
                    ]
