# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This logical rule is designed to optimize pipeline parallelism for large-scale jobs. 
# Key changes include removing expert weight sharding on the `q_lora` dimension, which 
# is relatively small (e.g., 512 for DeepSeek), and limiting sharding strategies when 
# EP x FSDP > 512. 
#
# The `data` axis is preserved for two reasons: first, the pipeline stage acts as a 
# data parallel (DP) domain externally, making the `data` axis a necessary reference; 
# second, it may be required for DCN communication. 
# 
# The `context` axis is used for supporting fractional per device batch size
#
# Finally, the `tensor` axis is used to shard weights when `pipeline_fsdp_ag_once` or 
# `pipeline_fsdp_ag_per_repeat` is enabled, ensuring we have sufficient memory to 
# store prefetched weights.
mesh_axes: ['data', 'stage', 'fsdp', 'context', 'tensor', 'expert']
data_sharding: [['data', 'stage', 'fsdp', 'context', 'tensor', 'expert']]
logical_axis_rules: [
                      ['activation_batch', ['data', 'fsdp', 'expert']],
                      ['activation_batch_moe', ['data', 'fsdp', 'expert']],
                      ['activation_batch_no_exp', ['data', 'fsdp']],
                      ['activation_batch_no_exp_moe', ['data', 'fsdp']],
                      ['activation_embed_and_logits_batch', ['data', 'stage', 'fsdp', 'expert']],
                      ['activation_embed_and_logits_batch_sequence', ['data', 'stage', 'fsdp', 'context', 'expert']],
                      ['activation_heads', ['tensor']],
                      ['activation_kv_heads', ['tensor']],
                      ['activation_length', ['context', 'expert']],
                      ['activation_attn_length', ['context', 'expert']],
                      ['activation_q_length', ['context', 'expert']],
                      ['activation_attn_embed', ['tensor']],
                      ['activation_norm_length', ['context']],
                      ['activation_norm_length_moe', ['context']],
                      ['activation_embed', ['tensor']],
                      ['activation_embed_moe', ['tensor']],
                      ['activation_mlp', ['tensor']],
                      ['activation_kv', ['tensor']],
                      ['activation_kv_batch', ['data', 'fsdp', 'expert']],
                      ['activation_kv_batch_no_exp', ['data', 'fsdp']],
                      ['activation_kv_head_dim', ['tensor']],
                      ['activation_vocab', ['tensor']],
                      ['activation_stage', 'stage'],
                      ['activation_exp', ['expert']],
                      ['mlp', ['tensor']],
                      ['mlp_no_fsdp', ['tensor']],
                      ['vocab', ['tensor']],
                      ['heads', ['tensor']],
                      ['q_heads', ['tensor']],
                      ['kv_heads', ['tensor']],
                      ['embed', ['fsdp', 'expert']], # remove context from embed sharding
                      ['embed_moe', ['fsdp', 'expert']],
                      ['embed_no_exp', ['fsdp']],
                      ['embed_no_exp_moe', ['fsdp']],
                      ['q_lora', ['fsdp']],
                      ['kv_lora', ['fsdp']],
                      ['norm', ['tensor']],
                      ['layers', 'stage'],
                      ['cache_heads', ['tensor']],
                      ['exp', 'expert'],
                      ['exp_with_fsdp', 'fsdp'],
                      ['paged_kv_heads', ['tensor']],
                      ['engram_dim', ['tensor']],
                    ]
