mesh_axes: ['data', 'attn_dp', 'model', 'expert', 'attn_dp_expert']
logical_axis_rules: [
                      ['activation_batch', []],
                      ['activation_batch_moe', ['data']],
                      ['activation_embed_and_logits_batch', ['data']],
                      ['activation_embed_and_logits_batch_sequence', ['data']],
                      ['activation_heads', ['model', 'expert']],
                      ['activation_kv_heads', ['model', 'expert']],
                      ['activation_attn_length', []],
                      ['activation_length', []],
                      ['activation_length_moe', []],
                      ['activation_q_length', ['expert']],
                      ['activation_attn_embed', 'model'],
                      # Expert is missing explicitly from activation_embed despite using TP.
                      # We are going for a replicate-AR style of TP as opposed to our typical AG-RS style of TP
                      # due to the output sharding of the fused_moe_gmm kernel in tpu-inference.
                      ['activation_embed', ['model', 'attn_dp', 'attn_dp_expert']],
                      ['activation_embed_moe', ['model', 'attn_dp', 'attn_dp_expert']],
                      ['activation_mlp', ['model']],
                      ['activation_mlp_moe', ['model']],
                      ['activation_kv', ['model']],
                      ['activation_prefill_kv_batch', ['expert']],
                      ['activation_kv_batch', ['data', 'attn_dp_expert']],
                      ['activation_kv_head_dim', ['model']],
                      ['activation_vocab', ['model', 'attn_dp']],
                      ['activation_norm_length', []],
                      ['activation_norm_length_moe', []],
                      ['activation_exp', ['expert', 'attn_dp_expert']],
                      ['decode_batch', ['data', 'attn_dp_expert']],
                      ['decode_batch_moe', ['data', 'attn_dp_expert']],
                      ['decode_length', []],
                      ['mlp', ['model', 'attn_dp']],
                      ['mlp_moe', ['model', 'attn_dp']],
                      ['mlp_no_fsdp', ['model', 'attn_dp']],
                      ['vocab', ['model', 'attn_dp']],
                      # Expert is intended to act like TP for attention.
                      # We target two all-reduces, one at the end of attention out projection and one at the end of the feedforward.
                      ['heads', ['model', 'expert']],
                      ['q_heads', ['model', 'expert']],
                      ['kv_heads', ['model', 'expert']],
                      ['kv_head_dim', []],
                      ['kv', []],
                      ['embed', []],
                      ['embed_moe', []],
                      ['embed_tensor_transpose', ['attn_dp', 'model']],
                      ['q_lora', ['expert']],
                      ['kv_lora', ['expert']],
                      ['norm', []],
                      ['cache_heads', ['model']],
                      ['exp', ['expert', 'attn_dp_expert']],
                      ['paged_kv_heads', ['model']],
                    ]
data_sharding: [['data', 'attn_dp', 'model', 'expert', 'attn_dp_expert']]