#!/bin/bash

# This file is documentation for how to get started with GLM-5.1.

# This file runs Step 1 on CPU.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16): 
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check, pre-training, fine-tuning, and decoding.

set -ex

export MODEL_NAME='glm5.1-744b'
export TOKENIZER_PATH='THUDM/glm-5.1-744b'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# Step 1: Checkpoint conversion
# You can use the HuggingFace checkpoint at https://huggingface.co/THUDM/glm-5.1-744b
# Non-Googlers please remember to point `BF16_HF_PATH` to GCS buckets that you own
# Copying the HF checkpoint into a local directory `/tmp` -- you are free to use a different directory
BF16_HF_PATH=gs://maxtext-glm5-europe-west4/hf-bf16
if [ -z "${CKPT_DISK_LOCATION}" ]; then
  export BF16_HF_BUCKET=gs://maxtext-glm5-europe-west4/hf-bf16
  gcloud storage cp -r ${CKPT_BUCKET} /tmp || true
  export BF16_LOCAL_PATH=/tmp/hf-bf16
fi

# scanned
python3 -m maxtext.checkpoint_conversion.to_maxtext src/maxtext/configs/base.yml \
model_name=${MODEL_NAME} scan_layers=true attention=dot_product \
base_output_directory=${BASE_OUTPUT_PATH}/scanned hf_access_token=$HF_TOKEN \
hardware=cpu skip_jax_distributed_system=True \
--hf_model_path=$BF16_LOCAL_PATH \
--eager_load_method=safetensors \
--save_dtype=bfloat16

# unscanned
python3 -m maxtext.checkpoint_conversion.to_maxtext src/maxtext/configs/base.yml \
model_name=${MODEL_NAME} scan_layers=false attention=dot_product \
base_output_directory=${BASE_OUTPUT_PATH}/unscanned hf_access_token=$HF_TOKEN \
hardware=cpu skip_jax_distributed_system=True \
--hf_model_path=$BF16_LOCAL_PATH \
--eager_load_method=safetensors \
--save_dtype=bfloat16
