#!/bin/bash

# This file is documentation for how to get started with GLM-5.1.

# This file runs Step 2 on v5p-64.
# 1. Convert the HuggingFace checkpoint (bf16) to MaxText-compatible checkpoint (bf16):
#    Scanned format is better for training; unscanned format is better for decoding.
# 2. Run logit check, pre-training, fine-tuning, and decoding.

set -ex

export MODEL_NAME='glm5.1-744b'
export TOKENIZER_PATH='THUDM/glm-5.1-744b'

# Installing torch for checkpoint conversion and forward_pass_logit_checker.py
python3 -m pip install torch --index-url https://download.pytorch.org/whl/cpu

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

# Step 2:
SCANNED_CKPT_PATH=gs://maxtext-glm5-europe-west4/checkpoints/scanned/0/items
UNSCANNED_CKPT_PATH=gs://maxtext-glm5-europe-west4/checkpoints/unscanned/0/items
export DATASET_PATH=gs://maxtext-dataset

# Test whether the forward pass logits match the golden logits
GOLDEN_LOGITS_DISK_LOCATION="/deps/tests/assets/golden_logits/golden_data_${MODEL_NAME}.jsonl"
if [ ! -f "${GOLDEN_LOGITS_DISK_LOCATION}" ]; then
  GOLDEN_LOGITS_PATH="gs://maxtext-glm5-europe-west4/golden_glm5.1_bf16_4l.jsonl"
  GOLDEN_LOGITS_DISK_LOCATION=/tmp/golden_data.jsonl
  gcloud storage cp ${GOLDEN_LOGITS_PATH} ${GOLDEN_LOGITS_DISK_LOCATION} || true
fi

python3 -m tests.utils.forward_pass_logit_checker ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml base_output_directory=${BASE_OUTPUT_PATH} run_name=forward_logits_check load_parameters_path=${SCANNED_CKPT_PATH} scan_layers=true attention=dot_product per_device_batch_size=1 model_name=${MODEL_NAME} max_prefill_predict_length=4 max_target_length=4 async_checkpointing=false sparse_matmul=false ici_fsdp_parallelism=1 ici_expert_parallelism=-1 checkpoint_storage_concurrent_gb=1024 weight_dtype=bfloat16 dtype=bfloat16 activations_in_float32=true matmul_precision=highest float32_logits=true float32_qk_product=true override_model_config=true use_indexer=false --golden_logits_path=${GOLDEN_LOGITS_DISK_LOCATION} --max_kl_div=0.3

# Run pre-training - megablox ragged MoE implementation with optimal 4x4x4 mesh sharding (TP=1, EP=4, FSDP=16)
# sa_block_* = 512 prevents TPU v5p 16MB VMEM SRAM OOM for GLM-5.1 Latent Attention (v_head_dim=256)
export EXTRA_FLAGS="sa_block_q=512 sa_block_kv=512 sa_block_kv_compute=512 sa_block_q_dkv=512 sa_block_kv_dkv=512 sa_block_kv_dkv_compute=512 sa_block_q_dq=512 sa_block_kv_dq=512 remat_policy=custom decoder_layer_input=offload float32_weight_sum=False use_tokamax_splash=True use_random_routing=True use_custom_sort_vjp=True attention=flash use_tokamax_gmm=False prefuse_moe_weights=True"

python3 -m maxtext.trainers.pre_train.train ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml base_output_directory=${BASE_OUTPUT_PATH} run_name=megablox_pre_training model_name=${MODEL_NAME} override_model_config=true use_indexer=false indexer_sparse_training=false tokenizer_type=huggingface tokenizer_path=${TOKENIZER_PATH} dataset_type=synthetic enable_checkpointing=false attention=flash use_tokamax_splash=True sparse_matmul=True megablox=True dtype=bfloat16 weight_dtype=bfloat16 per_device_batch_size=1 steps=10 max_target_length=4096 ici_expert_parallelism=4 ici_fsdp_parallelism=-1 opt_type=sgd enable_tpu_profiling_options=True profiler=xplane skip_first_n_steps_for_profiler=5 profiler_steps=1 ${EXTRA_FLAGS}

# Run decoding - megablox implementation
python3 -m maxtext.inference.decode ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml base_output_directory=${BASE_OUTPUT_PATH} run_name=decode model_name=${MODEL_NAME} tokenizer_type=huggingface tokenizer_path=${TOKENIZER_PATH} hf_access_token=${HF_TOKEN} load_parameters_path=${UNSCANNED_CKPT_PATH} scan_layers=False attention=dot_product sparse_matmul=True megablox=True dtype=bfloat16 weight_dtype=bfloat16 per_device_batch_size=1 max_prefill_predict_length=3072 max_target_length=4096 ici_fsdp_parallelism=1 ici_tensor_parallelism=-1 ici_expert_parallelism=1 checkpoint_storage_concurrent_gb=1024 mla_naive_kvcache=false prompt="An attention function can be described as mapping a query and a set of key-value pairs to an output, where the query, keys, values, and outputs are all vectors. The output is "
