costs { name: "all-gather-start" cost_us: 14956.017 }
costs { name: "all-gather-start.1" cost_us: 14999.143 }
costs { name: "all-gather-start.2" cost_us: 15850.758 }
costs { name: "all-gather-start.3" cost_us: 15947.716 }
costs { name: "all-gather-start.4" cost_us: 15612.934 }
costs { name: "all-gather-start.5" cost_us: 15539.632 }
costs { name: "all-gather-start.6" cost_us: 16809.927 }
costs { name: "all-gather-start.7" cost_us: 10529.07 }
costs { name: "all-gather-start.8" cost_us: 15173.354 }
costs { name: "all-reduce-start" cost_us: 1692.605 }
costs { name: "all-reduce-start.2" cost_us: 1813.98 }
costs { name: "all-reduce-start.6" cost_us: 4121.496 }
costs { name: "input_transpose_fusion" cost_us: 4.384 }
costs { name: "input_transpose_fusion.1" cost_us: 416.736 }
costs { name: "input_transpose_fusion.2" cost_us: 9.568 }
costs { name: "input_transpose_fusion.3" cost_us: 14.016 }
costs { name: "loop_add_fusion.1" cost_us: 1.472 }
costs { name: "loop_add_fusion.1.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_add_fusion.5" cost_us: 1.408 }
costs { name: "loop_add_fusion.5.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_broadcast_fusion" cost_us: 1.6 }
costs { name: "loop_broadcast_fusion.10" cost_us: 56.704 }
costs { name: "loop_broadcast_fusion.2" cost_us: 843.871 }
costs { name: "loop_broadcast_fusion.3" cost_us: 6741.433 }
costs { name: "loop_broadcast_fusion.4" cost_us: 6753.497 }
costs { name: "loop_broadcast_fusion.5" cost_us: 397.119 }
costs { name: "loop_broadcast_fusion.6" cost_us: 194.624 }
costs { name: "loop_broadcast_fusion.7" cost_us: 2.88 }
costs { name: "loop_broadcast_fusion.8" cost_us: 14.849 }
costs { name: "loop_broadcast_fusion.9" cost_us: 55.68 }
costs { name: "loop_transpose_fusion" cost_us: 121.888 }
costs { name: "reduce-scatter.37.double_buffer_clone.1" cost_us: 15774.022 }
costs { name: "reduce-scatter.40" cost_us: 15669.352 }
costs { name: "reduce-scatter.41" cost_us: 16837.415 }
costs { name: "reduce-scatter.42" cost_us: 24670.039 }
costs { name: "wrapped_concatenate" cost_us: 20.768 }
costs { name: "wrapped_concatenate.1" cost_us: 1.76 }
costs { name: "wrapped_concatenate.2" cost_us: 20.544 }
costs { name: "wrapped_concatenate.3" cost_us: 1.888 }
costs { name: "wrapped_concatenate.4" cost_us: 84.16 }
costs { name: "wrapped_concatenate.5" cost_us: 1.92 }
costs { name: "wrapped_concatenate.6" cost_us: 1.984 }
costs { name: "wrapped_concatenate.7" cost_us: 2.912 }
costs { name: "wrapped_slice.10" cost_us: 3.584 }
costs { name: "wrapped_slice.11" cost_us: 4.127 }
costs { name: "wrapped_slice.12" cost_us: 4.544 }
costs { name: "wrapped_slice.13" cost_us: 4.031 }
costs { name: "wrapped_slice.14" cost_us: 4.608 }
costs { name: "wrapped_slice.15" cost_us: 3.52 }
costs { name: "wrapped_slice.18" cost_us: 2.08 }
costs { name: "wrapped_slice.19" cost_us: 2.496 }
costs { name: "wrapped_slice.20" cost_us: 2.688 }
costs { name: "wrapped_slice.21" cost_us: 2.08 }
costs { name: "wrapped_slice.22" cost_us: 4.192 }
costs { name: "wrapped_slice.23" cost_us: 4.096 }
costs { name: "wrapped_slice.24" cost_us: 1.952 }
costs { name: "wrapped_slice.25" cost_us: 1.952 }
costs { name: "wrapped_slice.26" cost_us: 2.337 }
costs { name: "wrapped_slice.27" cost_us: 2.335 }
costs { name: "wrapped_slice.28" cost_us: 2.368 }
costs { name: "wrapped_slice.29" cost_us: 2.336 }
costs { name: "wrapped_slice.30" cost_us: 1.952 }
costs { name: "wrapped_slice.31" cost_us: 1.984 }
costs { name: "wrapped_slice.32" cost_us: 3.904 }
costs { name: "wrapped_slice.33" cost_us: 3.872 }
costs { name: "wrapped_slice.34" cost_us: 3.936 }
costs { name: "wrapped_slice.35" cost_us: 3.872 }
costs { name: "wrapped_slice.36" cost_us: 3.712 }
costs { name: "wrapped_slice.37" cost_us: 4.544 }
costs { name: "wrapped_slice.38" cost_us: 1.504 }
costs { name: "wrapped_slice.39" cost_us: 1.312 }
costs { name: "wrapped_slice.4" cost_us: 2.048 }
costs { name: "wrapped_slice.40" cost_us: 1.312 }
costs { name: "wrapped_slice.41" cost_us: 1.344 }
costs { name: "wrapped_slice.42" cost_us: 1.28 }
costs { name: "wrapped_slice.43" cost_us: 1.28 }
costs { name: "wrapped_slice.48" cost_us: 1.344 }
costs { name: "wrapped_slice.49" cost_us: 1.313 }
costs { name: "wrapped_slice.5" cost_us: 2.656 }
costs { name: "wrapped_slice.51" cost_us: 1.312 }
costs { name: "wrapped_slice.52" cost_us: 1.503 }
costs { name: "wrapped_slice.53" cost_us: 1.472 }
costs { name: "wrapped_slice.54" cost_us: 1.312 }
costs { name: "wrapped_slice.55" cost_us: 1.344 }
costs { name: "wrapped_slice.56" cost_us: 1.28 }
costs { name: "wrapped_slice.57" cost_us: 1.28 }
costs { name: "wrapped_slice.58" cost_us: 1.312 }
costs { name: "wrapped_slice.59" cost_us: 1.344 }
costs { name: "wrapped_slice.6" cost_us: 2.496 }
costs { name: "wrapped_slice.60" cost_us: 1.312 }
costs { name: "wrapped_slice.61" cost_us: 1.312 }
costs { name: "wrapped_slice.62" cost_us: 1.344 }
costs { name: "wrapped_slice.63" cost_us: 1.344 }
costs { name: "wrapped_slice.64" cost_us: 1.312 }
costs { name: "wrapped_slice.65" cost_us: 1.28 }
costs { name: "wrapped_slice.66" cost_us: 1.312 }
costs { name: "wrapped_slice.67" cost_us: 1.376 }
costs { name: "wrapped_slice.68" cost_us: 1.312 }
costs { name: "wrapped_slice.69" cost_us: 1.311 }
costs { name: "wrapped_slice.7" cost_us: 2.048 }
costs { name: "wrapped_slice.70" cost_us: 1.344 }
costs { name: "wrapped_slice.71" cost_us: 1.344 }
costs { name: "wrapped_slice.72" cost_us: 1.312 }
costs { name: "wrapped_slice.73" cost_us: 1.28 }
costs { name: "wrapped_slice.74" cost_us: 1.312 }
costs { name: "wrapped_slice.75" cost_us: 1.344 }
costs { name: "wrapped_slice.76" cost_us: 1.28 }
costs { name: "wrapped_slice.77" cost_us: 1.312 }
costs { name: "wrapped_slice.78" cost_us: 1.313 }
costs { name: "wrapped_transpose.10" cost_us: 3.84 }
costs { name: "wrapped_transpose.11" cost_us: 3.904 }
costs { name: "wrapped_transpose.12" cost_us: 6.56 }
costs { name: "wrapped_transpose.13" cost_us: 7.456 }
costs { name: "wrapped_transpose.14" cost_us: 7.296 }
costs { name: "wrapped_transpose.9" cost_us: 2.496 }
costs { name: "wrapped_select" cost_us: 1.472 }
costs { name: "loop_add_fusion" cost_us: 1.344 }
costs { name: "wrapped_add" cost_us: 1.472 }
costs { name: "loop_minimum_fusion" cost_us: 1.631 }
costs { name: "wrapped_cosine" cost_us: 1.344 }
costs { name: "input_reduce_fusion" cost_us: 1.632 }
costs { name: "loop_xor_fusion" cost_us: 2.016 }
costs { name: "wrapped_multiply" cost_us: 1.28 }
costs { name: "loop_subtract_fusion" cost_us: 1.248 }
costs { name: "input_add_reduce_fusion.1" cost_us: 39.968 }
costs { name: "input_add_reduce_fusion.10" cost_us: 1528.893 }
costs { name: "input_add_reduce_fusion.13" cost_us: 48.896 }
costs { name: "input_add_reduce_fusion.14" cost_us: 50.464 }
costs { name: "input_add_reduce_fusion.15" cost_us: 6.335 }
costs { name: "input_add_reduce_fusion.2" cost_us: 32.639 }
costs { name: "input_add_reduce_fusion.3" cost_us: 398.368 }
costs { name: "input_add_reduce_fusion.4" cost_us: 395.199 }
costs { name: "input_add_reduce_fusion.5" cost_us: 32.48 }
costs { name: "input_add_reduce_fusion.6" cost_us: 14.272 }
costs { name: "input_add_reduce_fusion.7" cost_us: 14.208 }
costs { name: "input_add_reduce_fusion.8" cost_us: 1374.078 }
costs { name: "input_add_reduce_fusion.9" cost_us: 1528.67 }
costs { name: "input_compare_reduce_fusion" cost_us: 2.592 }
costs { name: "input_convert_reduce_fusion" cost_us: 2142.717 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 437.695 }
costs { name: "input_dynamic_slice_reduce_fusion" cost_us: 177.983 }
costs { name: "input_dynamic_slice_reduce_fusion.1" cost_us: 174.944 }
costs { name: "input_dynamic_slice_reduce_fusion.double_buffer_clone" cost_us: 178.048 }
costs { name: "input_reduce_fusion.10" cost_us: 13.824 }
costs { name: "input_reduce_fusion.11" cost_us: 80.864 }
costs { name: "input_reduce_fusion.12" cost_us: 85.569 }
costs { name: "input_reduce_fusion.13" cost_us: 14.08 }
costs { name: "input_reduce_fusion.14" cost_us: 5.695 }
costs { name: "input_reduce_fusion.15" cost_us: 5.792 }
costs { name: "input_reduce_fusion.16" cost_us: 234.912 }
costs { name: "input_reduce_fusion.17" cost_us: 248.608 }
costs { name: "input_reduce_fusion.18" cost_us: 255.808 }
costs { name: "input_reduce_fusion.19" cost_us: 2.112 }
costs { name: "input_reduce_fusion.2" cost_us: 251.968 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 256.032 }
costs { name: "input_reduce_fusion.20" cost_us: 2.08 }
costs { name: "input_reduce_fusion.21" cost_us: 1.952 }
costs { name: "input_reduce_fusion.22" cost_us: 2.272 }
costs { name: "input_reduce_fusion.23" cost_us: 2.176 }
costs { name: "input_reduce_fusion.24" cost_us: 2.272 }
costs { name: "input_reduce_fusion.25" cost_us: 2.08 }
costs { name: "input_reduce_fusion.26" cost_us: 2.016 }
costs { name: "input_reduce_fusion.27" cost_us: 2.143 }
costs { name: "input_reduce_fusion.28" cost_us: 491.071 }
costs { name: "input_reduce_fusion.29" cost_us: 2.208 }
costs { name: "input_reduce_fusion.3" cost_us: 85.056 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 85.152 }
costs { name: "input_reduce_fusion.30" cost_us: 363.52 }
costs { name: "input_reduce_fusion.33" cost_us: 257.568 }
costs { name: "input_reduce_fusion.34" cost_us: 85.376 }
costs { name: "input_reduce_fusion.35" cost_us: 169.088 }
costs { name: "input_reduce_fusion.36" cost_us: 257.28 }
costs { name: "input_reduce_fusion.37" cost_us: 85.504 }
costs { name: "input_reduce_fusion.38" cost_us: 169.344 }
costs { name: "input_reduce_fusion.4" cost_us: 168.255 }
costs { name: "input_reduce_fusion.4.double_buffer_clone" cost_us: 168.128 }
costs { name: "input_reduce_fusion.40" cost_us: 170.144 }
costs { name: "input_reduce_fusion.41" cost_us: 1.792 }
costs { name: "input_reduce_fusion.42" cost_us: 1.696 }
costs { name: "input_reduce_fusion.43" cost_us: 5.92 }
costs { name: "input_reduce_fusion.48" cost_us: 2.368 }
costs { name: "input_reduce_fusion.49" cost_us: 1.856 }
costs { name: "input_reduce_fusion.50" cost_us: 1.792 }
costs { name: "input_reduce_fusion.51" cost_us: 1.6 }
costs { name: "input_reduce_fusion.52" cost_us: 1.568 }
costs { name: "input_reduce_fusion.53" cost_us: 1.92 }
costs { name: "input_reduce_fusion.54" cost_us: 2.016 }
costs { name: "input_reduce_fusion.55" cost_us: 2.176 }
costs { name: "input_reduce_fusion.56" cost_us: 5.024 }
costs { name: "input_reduce_fusion.57" cost_us: 1.984 }
costs { name: "input_reduce_fusion.58" cost_us: 2.208 }
costs { name: "input_reduce_fusion.59" cost_us: 2.016 }
costs { name: "input_reduce_fusion.6" cost_us: 3.296 }
costs { name: "input_reduce_fusion.60" cost_us: 1.632 }
costs { name: "input_reduce_fusion.61" cost_us: 1.824 }
costs { name: "input_reduce_fusion.62" cost_us: 1.696 }
costs { name: "input_reduce_fusion.63" cost_us: 1.632 }
costs { name: "input_reduce_fusion.64" cost_us: 1.696 }
costs { name: "input_reduce_fusion.65" cost_us: 1.696 }
costs { name: "input_reduce_fusion.66" cost_us: 1.663 }
costs { name: "input_reduce_fusion.67" cost_us: 1.824 }
costs { name: "input_reduce_fusion.68" cost_us: 2.336 }
costs { name: "input_reduce_fusion.69" cost_us: 2.176 }
costs { name: "input_reduce_fusion.7" cost_us: 3.936 }
costs { name: "input_reduce_fusion.70" cost_us: 1.792 }
costs { name: "input_reduce_fusion.71" cost_us: 1.6 }
costs { name: "input_reduce_fusion.72" cost_us: 1.792 }
costs { name: "input_reduce_fusion.73" cost_us: 1.728 }
costs { name: "input_reduce_fusion.74" cost_us: 1.664 }
costs { name: "input_reduce_fusion.75" cost_us: 1.76 }
costs { name: "input_reduce_fusion.76" cost_us: 1.664 }
costs { name: "input_reduce_fusion.77" cost_us: 2.175 }
costs { name: "input_reduce_fusion.78" cost_us: 2.24 }
costs { name: "input_reduce_fusion.8" cost_us: 3.296 }
costs { name: "input_reduce_fusion.9" cost_us: 3.296 }
costs { name: "loop_add_fusion.10" cost_us: 7.008 }
costs { name: "loop_add_fusion.11" cost_us: 6.976 }
costs { name: "loop_add_log_fusion" cost_us: 2.08 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.728 }
costs { name: "loop_convert_fusion.26" cost_us: 7.007 }
costs { name: "loop_divide_fusion" cost_us: 1.856 }
costs { name: "loop_multiply_fusion.13" cost_us: 2.208 }
costs { name: "loop_multiply_fusion.16" cost_us: 1.536 }
costs { name: "loop_multiply_fusion.17" cost_us: 1.536 }
costs { name: "loop_select_fusion.1" cost_us: 817.215 }
costs { name: "loop_select_fusion.2" cost_us: 815.135 }
costs { name: "loop_select_fusion.3" cost_us: 801.054 }
costs { name: "loop_select_fusion.4" cost_us: 235.488 }
costs { name: "loop_select_fusion.5" cost_us: 231.583 }
costs { name: "loop_select_fusion.6" cost_us: 2.112 }
costs { name: "loop_select_fusion.7" cost_us: 1.312 }
costs { name: "loop_select_fusion.8" cost_us: 1.631 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.536 }
costs { name: "loop_sqrt_fusion" cost_us: 2.336 }
costs { name: "loop_subtract_fusion" cost_us: 1.376 }
costs { name: "while.6.0" cost_us: 331.04 }
costs { name: "while.6.0" cost_us: 10421.554 }
costs { name: "while.6.0" cost_us: 9969.649 }
costs { name: "while.6.0" cost_us: 15669.352 }
costs { name: "while.6.0" cost_us: 15850.758 }
costs { name: "while.6.0" cost_us: 5728.311 }
costs { name: "while.6.0" cost_us: 2823.803 }
costs { name: "while.6.0" cost_us: 3011.964 }
costs { name: "while.6.0" cost_us: 1692.605 }
costs { name: "while.6.0" cost_us: 1907.613 }
costs { name: "while.6.0" cost_us: 1864.093 }
costs { name: "while.6.0" cost_us: 130.304 }
costs { name: "while.6.0" cost_us: 996.223 }
costs { name: "while.6.0" cost_us: 353.791 }
costs { name: "while.6.0" cost_us: 508.672 }
costs { name: "while.6.0" cost_us: 568.351 }
costs { name: "while.6.0" cost_us: 396.095 }
costs { name: "while.6.0" cost_us: 275.84 }
costs { name: "while.6.0" cost_us: 251.968 }
costs { name: "while.6.0" cost_us: 100.543 }
costs { name: "while.6.0" cost_us: 193.6 }
costs { name: "while.6.0" cost_us: 191.552 }
costs { name: "while.6.0" cost_us: 182.783 }
costs { name: "while.6.0" cost_us: 177.983 }
costs { name: "while.6.0" cost_us: 168.128 }
costs { name: "while.6.0" cost_us: 114.752 }
costs { name: "while.6.0" cost_us: 85.056 }
costs { name: "while.6.0" cost_us: 65.6 }
costs { name: "while.6.0" cost_us: 25.024 }
costs { name: "while.6.0" cost_us: 20.544 }
costs { name: "while.6.0" cost_us: 10.048 }
costs { name: "while.6.0" cost_us: 5.248 }
costs { name: "while.6.0" cost_us: 8.064 }
costs { name: "while.6.0" cost_us: 6.752 }
costs { name: "while.6.0" cost_us: 5.184 }
costs { name: "while.6.0" cost_us: 2.24 }
costs { name: "while.6.0" cost_us: 2.015 }
costs { name: "while.6.0" cost_us: 4.127 }
costs { name: "while.6.0" cost_us: 4.031 }
costs { name: "while.6.0" cost_us: 3.937 }
costs { name: "while.6.0" cost_us: 3.52 }
costs { name: "while.6.0" cost_us: 1.727 }
costs { name: "while.6.0" cost_us: 3.392 }
costs { name: "while.6.0" cost_us: 3.2 }
costs { name: "while.6.0" cost_us: 1.407 }
costs { name: "while.6.0" cost_us: 2.656 }
costs { name: "while.6.0" cost_us: 2.496 }
costs { name: "while.6.0" cost_us: 2.144 }
costs { name: "while.6.0" cost_us: 2.048 }
costs { name: "while.6.0" cost_us: 2.048 }
costs { name: "while.6.0" cost_us: 2.048 }
costs { name: "while.6.0" cost_us: 1.984 }
costs { name: "while.6.0" cost_us: 1.76 }
costs { name: "while.6.0" cost_us: 1.728 }
costs { name: "while.6.0" cost_us: 1.6 }
costs { name: "while.6.0" cost_us: 1.536 }
costs { name: "while.6.0" cost_us: 1.248 }
costs { name: "while.6.0" cost_us: 1.472 }
costs { name: "while.6.0" cost_us: 1.408 }
costs { name: "while.6.0" cost_us: 1.44 }
costs { name: "while.6.0" cost_us: 1.28 }
costs { name: "while.6.0" cost_us: 1.056 }
costs { name: "loop_add_fusion.12" cost_us: 1.632 }
costs { name: "input_reduce_fusion" cost_us: 91.52 }
costs { name: "input_reduce_fusion.1" cost_us: 85.216 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 85.344 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 86.272 }
costs { name: "input_reduce_fusion.31" cost_us: 93.92 }
costs { name: "input_reduce_fusion.32" cost_us: 86.368 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 90.4 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 85.344 }
costs { name: "while.5.0" cost_us: 376.415 }
costs { name: "while.5.0" cost_us: 14956.017 }
costs { name: "while.5.0" cost_us: 9984.5 }
costs { name: "while.5.0" cost_us: 2965.053 }
costs { name: "while.5.0" cost_us: 3077.981 }
costs { name: "while.5.0" cost_us: 1959.39 }
costs { name: "while.5.0" cost_us: 902.11 }
costs { name: "while.5.0" cost_us: 632.319 }
costs { name: "while.5.0" cost_us: 632.735 }
costs { name: "while.5.0" cost_us: 318.432 }
costs { name: "while.5.0" cost_us: 191.904 }
costs { name: "while.5.0" cost_us: 191.999 }
costs { name: "while.5.0" cost_us: 90.4 }
costs { name: "while.5.0" cost_us: 85.216 }
costs { name: "while.5.0" cost_us: 80.608 }
costs { name: "while.5.0" cost_us: 80.64 }
costs { name: "while.5.0" cost_us: 41.344 }
costs { name: "while.5.0" cost_us: 4.768 }
costs { name: "while.5.0" cost_us: 4.737 }
costs { name: "while.5.0" cost_us: 2.112 }
costs { name: "while.5.0" cost_us: 2.048 }
costs { name: "while.5.0" cost_us: 1.984 }
costs { name: "while.5.0" cost_us: 2.944 }
costs { name: "while.5.0" cost_us: 2.88 }
costs { name: "while.5.0" cost_us: 1.728 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.28 }
costs { name: "while.5.0" cost_us: 1.792 }
costs { name: "while.5.0" cost_us: 1.472 }
costs { name: "input_reduce_fusion.39" cost_us: 86.848 }
costs { name: "loop_multiply_fusion.10" cost_us: 193.439 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.048 }
costs { name: "wrapped_convert.1" cost_us: 1.824 }
costs { name: "wrapped_convert" cost_us: 6.368 }
costs { name: "custom-call.141.0" cost_us: 11642.22 }
costs { name: "loop_convert_fusion.19" cost_us: 618.623 }
costs { name: "input_transpose_fusion.5" cost_us: 5.568 }
costs { name: "custom-call.135.0" cost_us: 9213.75 }
costs { name: "input_transpose_fusion.10" cost_us: 4.0 }
costs { name: "input_transpose_fusion.6" cost_us: 6.495 }
costs { name: "loop_convert_fusion" cost_us: 4.737 }
costs { name: "loop_convert_fusion.1" cost_us: 4.768 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 5.856 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 6.496 }
costs { name: "loop_convert_fusion.2" cost_us: 4.8 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 5.856 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 6.56 }
costs { name: "loop_convert_fusion.24" cost_us: 6.912 }
costs { name: "loop_convert_fusion.25" cost_us: 6.304 }
costs { name: "loop_convert_fusion.3" cost_us: 2.88 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 3.263 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 3.456 }
costs { name: "loop_convert_fusion.30" cost_us: 3.584 }
costs { name: "loop_convert_fusion.35" cost_us: 2.175 }
costs { name: "loop_convert_fusion.36" cost_us: 2.176 }
costs { name: "loop_convert_fusion.4" cost_us: 2.944 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 3.2 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 3.776 }
costs { name: "loop_convert_fusion.41" cost_us: 2.144 }
costs { name: "loop_convert_fusion.42" cost_us: 2.016 }
costs { name: "loop_convert_fusion.5" cost_us: 2.208 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 2.112 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 2.4 }
costs { name: "loop_convert_fusion.6" cost_us: 2.272 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 2.24 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 2.144 }
costs { name: "loop_convert_fusion.7" cost_us: 2.08 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 1.824 }
costs { name: "loop_convert_fusion.8" cost_us: 2.048 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 2.08 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 6.08 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 6.912 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 632.735 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 80.64 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 80.8 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 633.695 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 80.608 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 80.96 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 633.055 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 80.608 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 80.512 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 632.766 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 632.319 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 632.831 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 632.927 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 632.831 }
costs { name: "copy_fusion.1" cost_us: 1.76 }
costs { name: "loop_add_fusion" cost_us: 1.632 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_multiply_fusion" cost_us: 902.11 }
costs { name: "loop_multiply_fusion.7" cost_us: 903.103 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 902.335 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 902.783 }
costs { name: "custom-call.139.0" cost_us: 10495.693 }
costs { name: "custom-call.56.0" cost_us: 10372.117 }
costs { name: "custom-call.56.0.double_buffer_clone" cost_us: 10411.221 }
costs { name: "custom-call.56.0.peeled_double_buffer" cost_us: 10423.573 }
costs { name: "custom-call.140.0" cost_us: 10514.35 }
costs { name: "custom-call.57.0" cost_us: 10377.877 }
costs { name: "custom-call.57.0.double_buffer_clone" cost_us: 10431.413 }
costs { name: "custom-call.57.0.peeled_double_buffer" cost_us: 10442.229 }
costs { name: "cublas-gemm.32.0" cost_us: 10023.891 }
costs { name: "cublas-gemm.5.0" cost_us: 9984.5 }
costs { name: "cublas-gemm.5.0.double_buffer_clone" cost_us: 9987.153 }
costs { name: "cublas-gemm.5.0.peeled_double_buffer" cost_us: 10283.505 }
costs { name: "loop_multiply_fusion.1" cost_us: 192.64 }
costs { name: "loop_multiply_fusion.1.double_buffer_clone" cost_us: 191.999 }
costs { name: "loop_multiply_fusion.1.peeled_double_buffer" cost_us: 193.696 }
costs { name: "loop_multiply_fusion.11" cost_us: 193.792 }
costs { name: "loop_rsqrt_fusion" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.176 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 2.048 }
costs { name: "loop_multiply_fusion.12" cost_us: 194.399 }
costs { name: "loop_multiply_fusion.2" cost_us: 192.0 }
costs { name: "loop_multiply_fusion.2.double_buffer_clone" cost_us: 191.904 }
costs { name: "loop_multiply_fusion.2.peeled_double_buffer" cost_us: 192.159 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.24 }
costs { name: "custom-call.38.0" cost_us: 1959.39 }
costs { name: "custom-call.38.0" cost_us: 1.728 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 2084.99 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1.791 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1881.31 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1.76 }
costs { name: "custom-call.39.0" cost_us: 2143.229 }
costs { name: "custom-call.39.0" cost_us: 1.824 }
costs { name: "loop_broadcast_fusion" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.11" cost_us: 1.472 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.311 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.3" cost_us: 1.44 }
costs { name: "loop_multiply_fusion.3.double_buffer_clone" cost_us: 1.503 }
costs { name: "loop_multiply_fusion.3.peeled_double_buffer" cost_us: 1.472 }
costs { name: "input_concatenate_fusion" cost_us: 318.432 }
costs { name: "input_concatenate_fusion.2" cost_us: 319.231 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 318.719 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 318.208 }
costs { name: "input_concatenate_fusion.1" cost_us: 41.344 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 41.408 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 41.407 }
costs { name: "input_concatenate_fusion.3" cost_us: 41.696 }
costs { name: "custom-call.137.0" cost_us: 397.472 }
costs { name: "custom-call.53.0" cost_us: 377.12 }
costs { name: "custom-call.53.0.double_buffer_clone" cost_us: 383.36 }
costs { name: "custom-call.53.0.peeled_double_buffer" cost_us: 376.319 }
costs { name: "custom-call.138.0" cost_us: 400.575 }
costs { name: "custom-call.55.0" cost_us: 376.415 }
costs { name: "custom-call.55.0.double_buffer_clone" cost_us: 383.167 }
costs { name: "custom-call.55.0.peeled_double_buffer" cost_us: 376.544 }
costs { name: "cublas-gemm.31.0" cost_us: 3140.539 }
costs { name: "cublas-gemm.4.0" cost_us: 3077.981 }
costs { name: "cublas-gemm.4.0.double_buffer_clone" cost_us: 3081.661 }
costs { name: "cublas-gemm.4.0.peeled_double_buffer" cost_us: 3079.452 }
costs { name: "custom-call.136.0" cost_us: 3190.746 }
costs { name: "custom-call.52.0" cost_us: 2965.053 }
costs { name: "custom-call.52.0.double_buffer_clone" cost_us: 2991.837 }
costs { name: "custom-call.52.0.peeled_double_buffer" cost_us: 2979.739 }
costs { name: "loop_convert_fusion.27" cost_us: 6.784 }
costs { name: "loop_power_fusion.1" cost_us: 1.536 }
costs { name: "all-reduce-start.4" cost_us: 1958.653 }
costs { name: "all-reduce-start.5" cost_us: 3959.226 }
costs { name: "all-reduce-start.7" cost_us: 1109.182 }
costs { name: "all-reduce-start.9" cost_us: 473.567 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 996.223 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 1009.502 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 1003.678 }
costs { name: "input_add_multiply_reduce_fusion.double_buffer_clone" cost_us: 1003.423 }
costs { name: "input_add_reduce_fusion" cost_us: 568.351 }
costs { name: "input_add_reduce_fusion.11" cost_us: 573.631 }
costs { name: "input_add_reduce_fusion.12" cost_us: 570.783 }
costs { name: "input_add_reduce_fusion.double_buffer_clone" cost_us: 569.983 }
costs { name: "input_reduce_fusion.44" cost_us: 4.608 }
costs { name: "input_reduce_fusion.45" cost_us: 4.608 }
costs { name: "input_reduce_fusion.46" cost_us: 8.096 }
costs { name: "input_reduce_fusion.5" cost_us: 8.096 }
costs { name: "input_reduce_fusion.5.double_buffer_clone" cost_us: 8.064 }
costs { name: "loop_multiply_fusion.14" cost_us: 2.336 }
costs { name: "loop_multiply_fusion.15" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.176 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.08 }
costs { name: "input_reduce_fusion.47" cost_us: 4.576 }
costs { name: "wrapped_slice.50" cost_us: 1.6 }
costs { name: "custom-call.142.0" cost_us: 11310.828 }
costs { name: "custom-call.171.0" cost_us: 12181.644 }
costs { name: "custom-call.172.0" cost_us: 12265.035 }
costs { name: "input_transpose_fusion.11" cost_us: 3.808 }
costs { name: "input_transpose_fusion.12" cost_us: 3.808 }
costs { name: "input_transpose_fusion.7" cost_us: 6.272 }
costs { name: "input_transpose_fusion.8" cost_us: 6.08 }
costs { name: "loop_convert_fusion.10" cost_us: 5.248 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 5.984 }
costs { name: "loop_convert_fusion.11" cost_us: 5.248 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 5.984 }
costs { name: "loop_convert_fusion.13" cost_us: 3.2 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 3.232 }
costs { name: "loop_convert_fusion.14" cost_us: 3.392 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 3.392 }
costs { name: "loop_convert_fusion.15" cost_us: 2.303 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 2.24 }
costs { name: "loop_convert_fusion.16" cost_us: 2.336 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 2.336 }
costs { name: "loop_convert_fusion.17" cost_us: 2.272 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_convert_fusion.18" cost_us: 2.015 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 2.015 }
costs { name: "loop_convert_fusion.20" cost_us: 5.888 }
costs { name: "loop_convert_fusion.21" cost_us: 6.08 }
costs { name: "loop_convert_fusion.22" cost_us: 6.368 }
costs { name: "loop_convert_fusion.23" cost_us: 6.049 }
costs { name: "loop_convert_fusion.28" cost_us: 3.072 }
costs { name: "loop_convert_fusion.29" cost_us: 3.232 }
costs { name: "loop_convert_fusion.31" cost_us: 2.176 }
costs { name: "loop_convert_fusion.32" cost_us: 2.144 }
costs { name: "loop_convert_fusion.33" cost_us: 2.272 }
costs { name: "loop_convert_fusion.34" cost_us: 2.176 }
costs { name: "loop_convert_fusion.37" cost_us: 2.336 }
costs { name: "loop_convert_fusion.38" cost_us: 2.24 }
costs { name: "loop_convert_fusion.39" cost_us: 2.368 }
costs { name: "loop_convert_fusion.40" cost_us: 2.048 }
costs { name: "loop_convert_fusion.9" cost_us: 5.184 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 6.208 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 185.952 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 25.568 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 26.048 }
costs { name: "loop_select_fusion" cost_us: 1.6 }
costs { name: "loop_select_fusion.double_buffer_clone" cost_us: 1.728 }
costs { name: "loop_add_fusion.4" cost_us: 1.248 }
costs { name: "loop_add_fusion.4.double_buffer_clone" cost_us: 1.76 }
costs { name: "input_transpose_fusion.4" cost_us: 4.224 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 396.095 }
costs { name: "loop_dynamic_update_slice_fusion.5.double_buffer_clone" cost_us: 398.047 }
costs { name: "input_transpose_fusion.9" cost_us: 2.496 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 114.752 }
costs { name: "loop_dynamic_update_slice_fusion.4.double_buffer_clone" cost_us: 115.968 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 1.471 }
costs { name: "loop_dynamic_update_slice_fusion.11.double_buffer_clone" cost_us: 1.535 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 1.407 }
costs { name: "loop_dynamic_update_slice_fusion.12.double_buffer_clone" cost_us: 1.632 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 10.111 }
costs { name: "loop_dynamic_update_slice_fusion.6.double_buffer_clone" cost_us: 10.112 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 10.048 }
costs { name: "loop_dynamic_update_slice_fusion.7.double_buffer_clone" cost_us: 10.112 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 3.937 }
costs { name: "loop_dynamic_update_slice_fusion.8.double_buffer_clone" cost_us: 4.0 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.729 }
costs { name: "loop_dynamic_update_slice_fusion.10.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 1.727 }
costs { name: "loop_dynamic_update_slice_fusion.9.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_multiply_fusion" cost_us: 1864.093 }
costs { name: "loop_add_multiply_fusion.1" cost_us: 1847.868 }
costs { name: "loop_add_multiply_fusion.2" cost_us: 1865.437 }
costs { name: "loop_add_multiply_fusion.double_buffer_clone" cost_us: 1864.605 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.048 }
costs { name: "loop_multiply_fusion.5.double_buffer_clone" cost_us: 2.111 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.176 }
costs { name: "loop_multiply_rsqrt_fusion.double_buffer_clone" cost_us: 2.144 }
costs { name: "custom-call.146.0" cost_us: 10244.464 }
costs { name: "custom-call.163.0" cost_us: 10405.677 }
costs { name: "custom-call.78.0" cost_us: 9969.649 }
costs { name: "custom-call.78.0.double_buffer_clone" cost_us: 9975.183 }
costs { name: "custom-call.150.0" cost_us: 10194.163 }
costs { name: "custom-call.160.0" cost_us: 10061.869 }
costs { name: "custom-call.82.0" cost_us: 9855.379 }
costs { name: "custom-call.82.0.double_buffer_clone" cost_us: 9854.543 }
costs { name: "cublas-gemm.13.0" cost_us: 9976.723 }
costs { name: "cublas-gemm.13.0.double_buffer_clone" cost_us: 10002.739 }
costs { name: "cublas-gemm.34.0" cost_us: 10188.657 }
costs { name: "cublas-gemm.37.0" cost_us: 10338.893 }
costs { name: "custom-call.151.0" cost_us: 9547.348 }
costs { name: "custom-call.161.0" cost_us: 10043.405 }
costs { name: "custom-call.83.0" cost_us: 9631.665 }
costs { name: "custom-call.83.0.double_buffer_clone" cost_us: 9574.641 }
costs { name: "custom-call.144.0" cost_us: 10486.99 }
costs { name: "custom-call.158.0" cost_us: 10651.727 }
costs { name: "custom-call.76.0" cost_us: 10563.187 }
costs { name: "custom-call.76.0.double_buffer_clone" cost_us: 10519.795 }
costs { name: "custom-call.152.0" cost_us: 9939.06 }
costs { name: "custom-call.162.0" cost_us: 9753.358 }
costs { name: "custom-call.84.0" cost_us: 9558.801 }
costs { name: "custom-call.84.0.double_buffer_clone" cost_us: 9480.144 }
costs { name: "all-reduce-start.1" cost_us: 130.304 }
costs { name: "all-reduce-start.3" cost_us: 584.639 }
costs { name: "wrapped_slice.16" cost_us: 1.536 }
costs { name: "wrapped_slice.46" cost_us: 1.376 }
costs { name: "wrapped_slice.47" cost_us: 1.6 }
costs { name: "wrapped_slice.9" cost_us: 1.056 }
costs { name: "all-reduce-start.8" cost_us: 2018.652 }
costs { name: "wrapped_slice.17" cost_us: 1.504 }
costs { name: "wrapped_slice.44" cost_us: 1.6 }
costs { name: "wrapped_slice.45" cost_us: 1.6 }
costs { name: "wrapped_slice.8" cost_us: 1.472 }
costs { name: "custom-call.35.0" cost_us: 5911.158 }
costs { name: "custom-call.35.0" cost_us: 276.608 }
costs { name: "custom-call.35.0" cost_us: 101.056 }
costs { name: "custom-call.35.0" cost_us: 206.112 }
costs { name: "custom-call.41.0" cost_us: 5728.311 }
costs { name: "custom-call.41.0" cost_us: 275.84 }
costs { name: "custom-call.41.0" cost_us: 100.544 }
costs { name: "custom-call.41.0" cost_us: 198.303 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 5912.183 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 276.0 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 100.543 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 193.6 }
costs { name: "custom-call.43.0" cost_us: 5855.35 }
costs { name: "custom-call.43.0" cost_us: 275.456 }
costs { name: "custom-call.43.0" cost_us: 100.896 }
costs { name: "custom-call.43.0" cost_us: 200.799 }
costs { name: "loop_add_fusion.2" cost_us: 508.672 }
costs { name: "loop_add_fusion.2.double_buffer_clone" cost_us: 521.888 }
costs { name: "loop_add_fusion.6" cost_us: 513.631 }
costs { name: "loop_add_fusion.7" cost_us: 541.279 }
costs { name: "loop_add_fusion.3" cost_us: 65.6 }
costs { name: "loop_add_fusion.3.double_buffer_clone" cost_us: 67.264 }
costs { name: "loop_add_fusion.8" cost_us: 66.496 }
costs { name: "loop_add_fusion.9" cost_us: 69.76 }
costs { name: "custom-call.153.0" cost_us: 369.247 }
costs { name: "custom-call.167.0" cost_us: 358.496 }
costs { name: "custom-call.85.0" cost_us: 356.832 }
costs { name: "custom-call.85.0.double_buffer_clone" cost_us: 331.04 }
costs { name: "custom-call.148.0" cost_us: 369.151 }
costs { name: "custom-call.165.0" cost_us: 359.519 }
costs { name: "custom-call.80.0" cost_us: 353.791 }
costs { name: "custom-call.80.0.double_buffer_clone" cost_us: 359.36 }
costs { name: "custom-call.156.0" cost_us: 352.672 }
costs { name: "custom-call.170.0" cost_us: 412.639 }
costs { name: "custom-call.88.0" cost_us: 362.56 }
costs { name: "custom-call.88.0.double_buffer_clone" cost_us: 346.559 }
costs { name: "cublas-gemm.14.0" cost_us: 417.663 }
costs { name: "cublas-gemm.14.0.double_buffer_clone" cost_us: 418.752 }
costs { name: "cublas-gemm.35.0" cost_us: 421.663 }
costs { name: "cublas-gemm.38.0" cost_us: 417.568 }
costs { name: "custom-call.154.0" cost_us: 2875.931 }
costs { name: "custom-call.168.0" cost_us: 2831.324 }
costs { name: "custom-call.86.0" cost_us: 2789.531 }
costs { name: "custom-call.86.0.double_buffer_clone" cost_us: 2921.852 }
costs { name: "custom-call.147.0" cost_us: 2994.651 }
costs { name: "custom-call.164.0" cost_us: 3024.474 }
costs { name: "custom-call.79.0" cost_us: 3016.635 }
costs { name: "custom-call.79.0.double_buffer_clone" cost_us: 3011.964 }
costs { name: "custom-call.155.0" cost_us: 2672.988 }
costs { name: "custom-call.169.0" cost_us: 3090.81 }
costs { name: "custom-call.87.0" cost_us: 2787.675 }
costs { name: "custom-call.87.0.double_buffer_clone" cost_us: 2571.292 }
costs { name: "custom-call.149.0" cost_us: 3048.795 }
costs { name: "custom-call.166.0" cost_us: 2895.61 }
costs { name: "custom-call.81.0" cost_us: 2823.803 }
costs { name: "custom-call.81.0.double_buffer_clone" cost_us: 2926.811 }
costs { name: "custom-call.143.0" cost_us: 10471.79 }
costs { name: "custom-call.157.0" cost_us: 10480.076 }
costs { name: "custom-call.75.0" cost_us: 10421.554 }
costs { name: "custom-call.75.0.double_buffer_clone" cost_us: 10435.795 }
costs { name: "custom-call.145.0" cost_us: 10500.974 }
costs { name: "custom-call.159.0" cost_us: 10490.221 }
costs { name: "custom-call.77.0" cost_us: 10422.45 }
costs { name: "custom-call.77.0.double_buffer_clone" cost_us: 10453.138 }
costs { name: "loop_multiply_fusion.4" cost_us: 191.744 }
costs { name: "loop_multiply_fusion.4.double_buffer_clone" cost_us: 191.552 }
costs { name: "loop_multiply_fusion.8" cost_us: 191.487 }
costs { name: "loop_multiply_fusion.9" cost_us: 191.2 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.2.double_buffer_clone" cost_us: 1.984 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.176 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.24 }
costs { name: "custom-call.34.0" cost_us: 1928.636 }
costs { name: "custom-call.34.0" cost_us: 2.08 }
costs { name: "custom-call.40.0" cost_us: 1946.813 }
costs { name: "custom-call.40.0" cost_us: 1.728 }
costs { name: "custom-call.40.0.double_buffer_clone" cost_us: 1907.613 }
costs { name: "custom-call.40.0.double_buffer_clone" cost_us: 1.728 }
costs { name: "custom-call.42.0" cost_us: 2002.94 }
costs { name: "custom-call.42.0" cost_us: 2.304 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.311 }
costs { name: "loop_broadcast_fusion.1.double_buffer_clone" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.6" cost_us: 1.503 }
costs { name: "loop_multiply_fusion.6.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_convert_fusion.12" cost_us: 6.752 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 6.783 }
costs { name: "loop_power_fusion" cost_us: 1.536 }
costs { name: "loop_power_fusion.double_buffer_clone" cost_us: 1.6 }
costs { name: "cublas-gemm.12.0" cost_us: 3066.107 }
costs { name: "cublas-gemm.12.0.double_buffer_clone" cost_us: 3073.245 }
costs { name: "cublas-gemm.33.0" cost_us: 3084.316 }
costs { name: "cublas-gemm.36.0" cost_us: 3090.49 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 187.552 }
costs { name: "loop_dynamic_slice_fusion.2.double_buffer_clone" cost_us: 182.783 }
costs { name: "wrapped_slice" cost_us: 185.471 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 25.248 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 25.215 }
costs { name: "loop_dynamic_slice_fusion.1.double_buffer_clone" cost_us: 25.024 }
costs { name: "loop_dynamic_slice_fusion.double_buffer_clone" cost_us: 25.152 }
costs { name: "wrapped_slice.1" cost_us: 24.32 }
costs { name: "wrapped_slice.2" cost_us: 24.192 }
costs { name: "wrapped_slice.3" cost_us: 185.568 }
costs { name: "loop_divide_fusion" cost_us: 1.76 }
costs { name: "wrapped_transpose.2" cost_us: 394.015 }
costs { name: "wrapped_transpose.3" cost_us: 393.888 }
costs { name: "wrapped_transpose.4" cost_us: 412.927 }
costs { name: "wrapped_transpose.1" cost_us: 3.296 }
costs { name: "wrapped_transpose" cost_us: 3.264 }
costs { name: "wrapped_transpose.5" cost_us: 15.84 }
costs { name: "wrapped_transpose.6" cost_us: 418.112 }
costs { name: "wrapped_transpose.7" cost_us: 115.456 }
costs { name: "wrapped_transpose.8" cost_us: 16.032 }
