costs { name: "all-gather-start" cost_us: 15102.15 }
costs { name: "all-gather-start.1" cost_us: 15140.454 }
costs { name: "all-gather-start.2" cost_us: 15887.748 }
costs { name: "all-gather-start.3" cost_us: 16112.61 }
costs { name: "all-gather-start.4" cost_us: 15968.644 }
costs { name: "all-gather-start.5" cost_us: 15818.15 }
costs { name: "all-gather-start.6" cost_us: 17475.519 }
costs { name: "all-gather-start.7" cost_us: 10247.291 }
costs { name: "all-gather-start.8" cost_us: 15475.462 }
costs { name: "all-reduce-start" cost_us: 2822.614 }
costs { name: "all-reduce-start.2" cost_us: 2909.205 }
costs { name: "all-reduce-start.6" cost_us: 5610.412 }
costs { name: "input_transpose_fusion" cost_us: 4.288 }
costs { name: "input_transpose_fusion.1" cost_us: 417.406 }
costs { name: "input_transpose_fusion.2" cost_us: 9.376 }
costs { name: "input_transpose_fusion.3" cost_us: 14.112 }
costs { name: "loop_add_fusion.1" cost_us: 1.471 }
costs { name: "loop_add_fusion.1.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_fusion.5" cost_us: 1.504 }
costs { name: "loop_add_fusion.5.double_buffer_clone" cost_us: 1.439 }
costs { name: "loop_broadcast_fusion" cost_us: 1.568 }
costs { name: "loop_broadcast_fusion.10" cost_us: 56.0 }
costs { name: "loop_broadcast_fusion.2" cost_us: 840.062 }
costs { name: "loop_broadcast_fusion.3" cost_us: 6732.326 }
costs { name: "loop_broadcast_fusion.4" cost_us: 6747.111 }
costs { name: "loop_broadcast_fusion.5" cost_us: 400.158 }
costs { name: "loop_broadcast_fusion.6" cost_us: 195.871 }
costs { name: "loop_broadcast_fusion.7" cost_us: 2.944 }
costs { name: "loop_broadcast_fusion.8" cost_us: 15.36 }
costs { name: "loop_broadcast_fusion.9" cost_us: 55.552 }
costs { name: "loop_transpose_fusion" cost_us: 122.176 }
costs { name: "reduce-scatter.37.double_buffer_clone.1" cost_us: 16682.561 }
costs { name: "reduce-scatter.40" cost_us: 15898.181 }
costs { name: "reduce-scatter.41" cost_us: 18076.603 }
costs { name: "reduce-scatter.42" cost_us: 24936.288 }
costs { name: "wrapped_concatenate" cost_us: 20.896 }
costs { name: "wrapped_concatenate.1" cost_us: 1.824 }
costs { name: "wrapped_concatenate.2" cost_us: 20.512 }
costs { name: "wrapped_concatenate.3" cost_us: 1.952 }
costs { name: "wrapped_concatenate.4" cost_us: 83.647 }
costs { name: "wrapped_concatenate.5" cost_us: 1.951 }
costs { name: "wrapped_concatenate.6" cost_us: 2.016 }
costs { name: "wrapped_concatenate.7" cost_us: 2.527 }
costs { name: "wrapped_slice.10" cost_us: 3.648 }
costs { name: "wrapped_slice.11" cost_us: 4.128 }
costs { name: "wrapped_slice.12" cost_us: 4.512 }
costs { name: "wrapped_slice.13" cost_us: 4.064 }
costs { name: "wrapped_slice.14" cost_us: 4.608 }
costs { name: "wrapped_slice.15" cost_us: 3.583 }
costs { name: "wrapped_slice.18" cost_us: 2.112 }
costs { name: "wrapped_slice.19" cost_us: 2.464 }
costs { name: "wrapped_slice.20" cost_us: 2.72 }
costs { name: "wrapped_slice.21" cost_us: 2.048 }
costs { name: "wrapped_slice.22" cost_us: 4.256 }
costs { name: "wrapped_slice.23" cost_us: 4.064 }
costs { name: "wrapped_slice.24" cost_us: 2.08 }
costs { name: "wrapped_slice.25" cost_us: 2.112 }
costs { name: "wrapped_slice.26" cost_us: 2.4 }
costs { name: "wrapped_slice.27" cost_us: 2.4 }
costs { name: "wrapped_slice.28" cost_us: 2.432 }
costs { name: "wrapped_slice.29" cost_us: 2.4 }
costs { name: "wrapped_slice.30" cost_us: 2.08 }
costs { name: "wrapped_slice.31" cost_us: 2.112 }
costs { name: "wrapped_slice.32" cost_us: 4.0 }
costs { name: "wrapped_slice.33" cost_us: 3.905 }
costs { name: "wrapped_slice.34" cost_us: 3.968 }
costs { name: "wrapped_slice.35" cost_us: 3.936 }
costs { name: "wrapped_slice.36" cost_us: 3.968 }
costs { name: "wrapped_slice.37" cost_us: 4.736 }
costs { name: "wrapped_slice.38" cost_us: 1.504 }
costs { name: "wrapped_slice.39" cost_us: 1.312 }
costs { name: "wrapped_slice.4" cost_us: 2.016 }
costs { name: "wrapped_slice.40" cost_us: 1.344 }
costs { name: "wrapped_slice.41" cost_us: 1.376 }
costs { name: "wrapped_slice.42" cost_us: 1.376 }
costs { name: "wrapped_slice.43" cost_us: 1.312 }
costs { name: "wrapped_slice.48" cost_us: 1.344 }
costs { name: "wrapped_slice.49" cost_us: 1.376 }
costs { name: "wrapped_slice.5" cost_us: 2.688 }
costs { name: "wrapped_slice.51" cost_us: 1.343 }
costs { name: "wrapped_slice.52" cost_us: 1.568 }
costs { name: "wrapped_slice.53" cost_us: 1.44 }
costs { name: "wrapped_slice.54" cost_us: 1.28 }
costs { name: "wrapped_slice.55" cost_us: 1.312 }
costs { name: "wrapped_slice.56" cost_us: 1.376 }
costs { name: "wrapped_slice.57" cost_us: 1.28 }
costs { name: "wrapped_slice.58" cost_us: 1.312 }
costs { name: "wrapped_slice.59" cost_us: 1.312 }
costs { name: "wrapped_slice.6" cost_us: 2.368 }
costs { name: "wrapped_slice.60" cost_us: 1.376 }
costs { name: "wrapped_slice.61" cost_us: 1.311 }
costs { name: "wrapped_slice.62" cost_us: 1.28 }
costs { name: "wrapped_slice.63" cost_us: 1.312 }
costs { name: "wrapped_slice.64" cost_us: 1.344 }
costs { name: "wrapped_slice.65" cost_us: 1.311 }
costs { name: "wrapped_slice.66" cost_us: 1.311 }
costs { name: "wrapped_slice.67" cost_us: 1.344 }
costs { name: "wrapped_slice.68" cost_us: 1.408 }
costs { name: "wrapped_slice.69" cost_us: 1.28 }
costs { name: "wrapped_slice.7" cost_us: 2.08 }
costs { name: "wrapped_slice.70" cost_us: 1.28 }
costs { name: "wrapped_slice.71" cost_us: 1.28 }
costs { name: "wrapped_slice.72" cost_us: 1.376 }
costs { name: "wrapped_slice.73" cost_us: 1.311 }
costs { name: "wrapped_slice.74" cost_us: 1.28 }
costs { name: "wrapped_slice.75" cost_us: 1.312 }
costs { name: "wrapped_slice.76" cost_us: 1.408 }
costs { name: "wrapped_slice.77" cost_us: 1.28 }
costs { name: "wrapped_slice.78" cost_us: 1.28 }
costs { name: "wrapped_transpose.10" cost_us: 3.808 }
costs { name: "wrapped_transpose.11" cost_us: 4.128 }
costs { name: "wrapped_transpose.12" cost_us: 6.912 }
costs { name: "wrapped_transpose.13" cost_us: 7.2 }
costs { name: "wrapped_transpose.14" cost_us: 7.424 }
costs { name: "wrapped_transpose.9" cost_us: 2.496 }
costs { name: "wrapped_select" cost_us: 1.632 }
costs { name: "loop_add_fusion" cost_us: 1.408 }
costs { name: "wrapped_add" cost_us: 1.536 }
costs { name: "loop_minimum_fusion" cost_us: 1.728 }
costs { name: "wrapped_cosine" cost_us: 1.472 }
costs { name: "input_reduce_fusion" cost_us: 1.664 }
costs { name: "loop_xor_fusion" cost_us: 2.08 }
costs { name: "wrapped_multiply" cost_us: 1.376 }
costs { name: "loop_subtract_fusion" cost_us: 1.408 }
costs { name: "input_add_reduce_fusion.1" cost_us: 39.712 }
costs { name: "input_add_reduce_fusion.10" cost_us: 1527.13 }
costs { name: "input_add_reduce_fusion.13" cost_us: 50.463 }
costs { name: "input_add_reduce_fusion.14" cost_us: 50.527 }
costs { name: "input_add_reduce_fusion.15" cost_us: 6.369 }
costs { name: "input_add_reduce_fusion.2" cost_us: 32.8 }
costs { name: "input_add_reduce_fusion.3" cost_us: 398.111 }
costs { name: "input_add_reduce_fusion.4" cost_us: 394.943 }
costs { name: "input_add_reduce_fusion.5" cost_us: 32.576 }
costs { name: "input_add_reduce_fusion.6" cost_us: 14.528 }
costs { name: "input_add_reduce_fusion.7" cost_us: 14.432 }
costs { name: "input_add_reduce_fusion.8" cost_us: 1374.011 }
costs { name: "input_add_reduce_fusion.9" cost_us: 1528.346 }
costs { name: "input_compare_reduce_fusion" cost_us: 3.072 }
costs { name: "input_convert_reduce_fusion" cost_us: 2199.416 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 430.782 }
costs { name: "input_dynamic_slice_reduce_fusion" cost_us: 176.447 }
costs { name: "input_dynamic_slice_reduce_fusion.1" cost_us: 173.984 }
costs { name: "input_dynamic_slice_reduce_fusion.double_buffer_clone" cost_us: 176.671 }
costs { name: "input_reduce_fusion.10" cost_us: 14.24 }
costs { name: "input_reduce_fusion.11" cost_us: 80.608 }
costs { name: "input_reduce_fusion.12" cost_us: 86.112 }
costs { name: "input_reduce_fusion.13" cost_us: 13.984 }
costs { name: "input_reduce_fusion.14" cost_us: 5.856 }
costs { name: "input_reduce_fusion.15" cost_us: 5.92 }
costs { name: "input_reduce_fusion.16" cost_us: 237.215 }
costs { name: "input_reduce_fusion.17" cost_us: 250.655 }
costs { name: "input_reduce_fusion.18" cost_us: 256.063 }
costs { name: "input_reduce_fusion.19" cost_us: 2.144 }
costs { name: "input_reduce_fusion.2" cost_us: 251.967 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 255.998 }
costs { name: "input_reduce_fusion.20" cost_us: 1.984 }
costs { name: "input_reduce_fusion.21" cost_us: 2.08 }
costs { name: "input_reduce_fusion.22" cost_us: 2.272 }
costs { name: "input_reduce_fusion.23" cost_us: 2.304 }
costs { name: "input_reduce_fusion.24" cost_us: 2.144 }
costs { name: "input_reduce_fusion.25" cost_us: 2.144 }
costs { name: "input_reduce_fusion.26" cost_us: 2.209 }
costs { name: "input_reduce_fusion.27" cost_us: 2.144 }
costs { name: "input_reduce_fusion.28" cost_us: 529.278 }
costs { name: "input_reduce_fusion.29" cost_us: 2.048 }
costs { name: "input_reduce_fusion.3" cost_us: 85.12 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 85.184 }
costs { name: "input_reduce_fusion.30" cost_us: 380.223 }
costs { name: "input_reduce_fusion.33" cost_us: 257.471 }
costs { name: "input_reduce_fusion.34" cost_us: 86.655 }
costs { name: "input_reduce_fusion.35" cost_us: 168.799 }
costs { name: "input_reduce_fusion.36" cost_us: 257.311 }
costs { name: "input_reduce_fusion.37" cost_us: 86.239 }
costs { name: "input_reduce_fusion.38" cost_us: 169.055 }
costs { name: "input_reduce_fusion.4" cost_us: 167.903 }
costs { name: "input_reduce_fusion.4.double_buffer_clone" cost_us: 167.903 }
costs { name: "input_reduce_fusion.40" cost_us: 168.864 }
costs { name: "input_reduce_fusion.41" cost_us: 2.049 }
costs { name: "input_reduce_fusion.42" cost_us: 1.856 }
costs { name: "input_reduce_fusion.43" cost_us: 6.176 }
costs { name: "input_reduce_fusion.48" cost_us: 2.336 }
costs { name: "input_reduce_fusion.49" cost_us: 1.888 }
costs { name: "input_reduce_fusion.50" cost_us: 1.76 }
costs { name: "input_reduce_fusion.51" cost_us: 1.664 }
costs { name: "input_reduce_fusion.52" cost_us: 1.728 }
costs { name: "input_reduce_fusion.53" cost_us: 1.76 }
costs { name: "input_reduce_fusion.54" cost_us: 2.08 }
costs { name: "input_reduce_fusion.55" cost_us: 2.112 }
costs { name: "input_reduce_fusion.56" cost_us: 5.152 }
costs { name: "input_reduce_fusion.57" cost_us: 2.016 }
costs { name: "input_reduce_fusion.58" cost_us: 2.08 }
costs { name: "input_reduce_fusion.59" cost_us: 2.016 }
costs { name: "input_reduce_fusion.6" cost_us: 3.264 }
costs { name: "input_reduce_fusion.60" cost_us: 1.664 }
costs { name: "input_reduce_fusion.61" cost_us: 1.695 }
costs { name: "input_reduce_fusion.62" cost_us: 1.729 }
costs { name: "input_reduce_fusion.63" cost_us: 1.665 }
costs { name: "input_reduce_fusion.64" cost_us: 1.728 }
costs { name: "input_reduce_fusion.65" cost_us: 1.664 }
costs { name: "input_reduce_fusion.66" cost_us: 1.728 }
costs { name: "input_reduce_fusion.67" cost_us: 1.824 }
costs { name: "input_reduce_fusion.68" cost_us: 2.496 }
costs { name: "input_reduce_fusion.69" cost_us: 2.24 }
costs { name: "input_reduce_fusion.7" cost_us: 4.128 }
costs { name: "input_reduce_fusion.70" cost_us: 1.951 }
costs { name: "input_reduce_fusion.71" cost_us: 1.793 }
costs { name: "input_reduce_fusion.72" cost_us: 1.793 }
costs { name: "input_reduce_fusion.73" cost_us: 1.632 }
costs { name: "input_reduce_fusion.74" cost_us: 1.6 }
costs { name: "input_reduce_fusion.75" cost_us: 1.664 }
costs { name: "input_reduce_fusion.76" cost_us: 1.6 }
costs { name: "input_reduce_fusion.77" cost_us: 2.048 }
costs { name: "input_reduce_fusion.78" cost_us: 2.24 }
costs { name: "input_reduce_fusion.8" cost_us: 3.328 }
costs { name: "input_reduce_fusion.9" cost_us: 3.327 }
costs { name: "loop_add_fusion.10" cost_us: 6.88 }
costs { name: "loop_add_fusion.11" cost_us: 7.296 }
costs { name: "loop_add_log_fusion" cost_us: 2.176 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.631 }
costs { name: "loop_convert_fusion.26" cost_us: 7.104 }
costs { name: "loop_divide_fusion" cost_us: 1.728 }
costs { name: "loop_multiply_fusion.13" cost_us: 2.208 }
costs { name: "loop_multiply_fusion.16" cost_us: 1.632 }
costs { name: "loop_multiply_fusion.17" cost_us: 1.632 }
costs { name: "loop_select_fusion.1" cost_us: 815.197 }
costs { name: "loop_select_fusion.2" cost_us: 813.725 }
costs { name: "loop_select_fusion.3" cost_us: 799.901 }
costs { name: "loop_select_fusion.4" cost_us: 234.687 }
costs { name: "loop_select_fusion.5" cost_us: 231.231 }
costs { name: "loop_select_fusion.6" cost_us: 2.144 }
costs { name: "loop_select_fusion.7" cost_us: 1.312 }
costs { name: "loop_select_fusion.8" cost_us: 1.696 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.728 }
costs { name: "loop_sqrt_fusion" cost_us: 2.304 }
costs { name: "loop_subtract_fusion" cost_us: 1.471 }
costs { name: "while.6.0" cost_us: 318.111 }
costs { name: "while.6.0" cost_us: 10333.721 }
costs { name: "while.6.0" cost_us: 9871.452 }
costs { name: "while.6.0" cost_us: 15898.181 }
costs { name: "while.6.0" cost_us: 15887.748 }
costs { name: "while.6.0" cost_us: 5380.172 }
costs { name: "while.6.0" cost_us: 2692.79 }
costs { name: "while.6.0" cost_us: 2822.614 }
costs { name: "while.6.0" cost_us: 2955.413 }
costs { name: "while.6.0" cost_us: 1867.449 }
costs { name: "while.6.0" cost_us: 256.447 }
costs { name: "while.6.0" cost_us: 1864.857 }
costs { name: "while.6.0" cost_us: 985.533 }
costs { name: "while.6.0" cost_us: 339.711 }
costs { name: "while.6.0" cost_us: 554.622 }
costs { name: "while.6.0" cost_us: 485.694 }
costs { name: "while.6.0" cost_us: 395.135 }
costs { name: "while.6.0" cost_us: 275.775 }
costs { name: "while.6.0" cost_us: 251.967 }
costs { name: "while.6.0" cost_us: 100.576 }
costs { name: "while.6.0" cost_us: 193.183 }
costs { name: "while.6.0" cost_us: 191.296 }
costs { name: "while.6.0" cost_us: 182.72 }
costs { name: "while.6.0" cost_us: 176.447 }
costs { name: "while.6.0" cost_us: 167.903 }
costs { name: "while.6.0" cost_us: 114.688 }
costs { name: "while.6.0" cost_us: 85.12 }
costs { name: "while.6.0" cost_us: 62.304 }
costs { name: "while.6.0" cost_us: 24.992 }
costs { name: "while.6.0" cost_us: 20.512 }
costs { name: "while.6.0" cost_us: 10.08 }
costs { name: "while.6.0" cost_us: 4.992 }
costs { name: "while.6.0" cost_us: 7.84 }
costs { name: "while.6.0" cost_us: 6.816 }
costs { name: "while.6.0" cost_us: 5.248 }
costs { name: "while.6.0" cost_us: 2.176 }
costs { name: "while.6.0" cost_us: 1.984 }
costs { name: "while.6.0" cost_us: 4.128 }
costs { name: "while.6.0" cost_us: 4.064 }
costs { name: "while.6.0" cost_us: 3.936 }
costs { name: "while.6.0" cost_us: 3.583 }
costs { name: "while.6.0" cost_us: 1.728 }
costs { name: "while.6.0" cost_us: 3.104 }
costs { name: "while.6.0" cost_us: 3.073 }
costs { name: "while.6.0" cost_us: 1.471 }
costs { name: "while.6.0" cost_us: 2.688 }
costs { name: "while.6.0" cost_us: 2.368 }
costs { name: "while.6.0" cost_us: 2.144 }
costs { name: "while.6.0" cost_us: 2.143 }
costs { name: "while.6.0" cost_us: 2.048 }
costs { name: "while.6.0" cost_us: 2.016 }
costs { name: "while.6.0" cost_us: 2.08 }
costs { name: "while.6.0" cost_us: 1.824 }
costs { name: "while.6.0" cost_us: 1.792 }
costs { name: "while.6.0" cost_us: 1.664 }
costs { name: "while.6.0" cost_us: 1.568 }
costs { name: "while.6.0" cost_us: 1.248 }
costs { name: "while.6.0" cost_us: 1.439 }
costs { name: "while.6.0" cost_us: 1.504 }
costs { name: "while.6.0" cost_us: 1.44 }
costs { name: "while.6.0" cost_us: 1.279 }
costs { name: "while.6.0" cost_us: 1.056 }
costs { name: "loop_add_fusion.12" cost_us: 1.856 }
costs { name: "input_reduce_fusion" cost_us: 92.127 }
costs { name: "input_reduce_fusion.1" cost_us: 85.216 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 85.28 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 85.311 }
costs { name: "input_reduce_fusion.31" cost_us: 94.655 }
costs { name: "input_reduce_fusion.32" cost_us: 86.335 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 90.367 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 85.664 }
costs { name: "while.5.0" cost_us: 375.775 }
costs { name: "while.5.0" cost_us: 15102.15 }
costs { name: "while.5.0" cost_us: 9859.164 }
costs { name: "while.5.0" cost_us: 2947.669 }
costs { name: "while.5.0" cost_us: 3045.301 }
costs { name: "while.5.0" cost_us: 1879.32 }
costs { name: "while.5.0" cost_us: 901.852 }
costs { name: "while.5.0" cost_us: 632.254 }
costs { name: "while.5.0" cost_us: 632.606 }
costs { name: "while.5.0" cost_us: 318.175 }
costs { name: "while.5.0" cost_us: 191.455 }
costs { name: "while.5.0" cost_us: 192.159 }
costs { name: "while.5.0" cost_us: 90.367 }
costs { name: "while.5.0" cost_us: 85.216 }
costs { name: "while.5.0" cost_us: 80.671 }
costs { name: "while.5.0" cost_us: 80.704 }
costs { name: "while.5.0" cost_us: 41.439 }
costs { name: "while.5.0" cost_us: 4.8 }
costs { name: "while.5.0" cost_us: 4.864 }
costs { name: "while.5.0" cost_us: 2.207 }
costs { name: "while.5.0" cost_us: 2.08 }
costs { name: "while.5.0" cost_us: 2.017 }
costs { name: "while.5.0" cost_us: 2.912 }
costs { name: "while.5.0" cost_us: 2.912 }
costs { name: "while.5.0" cost_us: 1.728 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.503 }
costs { name: "while.5.0" cost_us: 1.28 }
costs { name: "while.5.0" cost_us: 1.76 }
costs { name: "while.5.0" cost_us: 1.471 }
costs { name: "input_reduce_fusion.39" cost_us: 85.952 }
costs { name: "loop_multiply_fusion.10" cost_us: 194.559 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.336 }
costs { name: "wrapped_convert.1" cost_us: 1.952 }
costs { name: "wrapped_convert" cost_us: 6.399 }
costs { name: "custom-call.141.0" cost_us: 12870.352 }
costs { name: "loop_convert_fusion.19" cost_us: 618.718 }
costs { name: "input_transpose_fusion.5" cost_us: 5.568 }
costs { name: "custom-call.135.0" cost_us: 9107.678 }
costs { name: "input_transpose_fusion.10" cost_us: 4.0 }
costs { name: "input_transpose_fusion.6" cost_us: 6.496 }
costs { name: "loop_convert_fusion" cost_us: 4.864 }
costs { name: "loop_convert_fusion.1" cost_us: 4.8 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 5.888 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 6.592 }
costs { name: "loop_convert_fusion.2" cost_us: 4.832 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 5.952 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 6.56 }
costs { name: "loop_convert_fusion.24" cost_us: 6.976 }
costs { name: "loop_convert_fusion.25" cost_us: 6.496 }
costs { name: "loop_convert_fusion.3" cost_us: 2.912 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 3.265 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 3.455 }
costs { name: "loop_convert_fusion.30" cost_us: 3.553 }
costs { name: "loop_convert_fusion.35" cost_us: 2.207 }
costs { name: "loop_convert_fusion.36" cost_us: 2.177 }
costs { name: "loop_convert_fusion.4" cost_us: 2.912 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 3.2 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 3.776 }
costs { name: "loop_convert_fusion.41" cost_us: 2.176 }
costs { name: "loop_convert_fusion.42" cost_us: 2.016 }
costs { name: "loop_convert_fusion.5" cost_us: 2.208 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 2.207 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 2.304 }
costs { name: "loop_convert_fusion.6" cost_us: 2.24 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 2.304 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 2.176 }
costs { name: "loop_convert_fusion.7" cost_us: 2.112 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 2.08 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.8" cost_us: 2.08 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 2.112 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 1.824 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 6.113 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 6.592 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 632.606 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 80.735 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 80.832 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 632.957 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 80.608 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 80.704 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 632.958 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 80.736 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 80.671 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 80.639 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 632.989 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 632.254 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 632.766 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 632.766 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 632.798 }
costs { name: "copy_fusion.1" cost_us: 1.6 }
costs { name: "loop_add_fusion" cost_us: 1.631 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_multiply_fusion" cost_us: 901.852 }
costs { name: "loop_multiply_fusion.7" cost_us: 903.389 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 901.885 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 898.045 }
costs { name: "custom-call.139.0" cost_us: 10374.522 }
costs { name: "custom-call.56.0" cost_us: 10338.746 }
costs { name: "custom-call.56.0.double_buffer_clone" cost_us: 10330.361 }
costs { name: "custom-call.56.0.peeled_double_buffer" cost_us: 10356.665 }
costs { name: "custom-call.140.0" cost_us: 10456.504 }
costs { name: "custom-call.57.0" cost_us: 10343.194 }
costs { name: "custom-call.57.0.double_buffer_clone" cost_us: 10323.034 }
costs { name: "custom-call.57.0.peeled_double_buffer" cost_us: 10382.937 }
costs { name: "cublas-gemm.32.0" cost_us: 9893.05 }
costs { name: "cublas-gemm.5.0" cost_us: 9886.876 }
costs { name: "cublas-gemm.5.0.double_buffer_clone" cost_us: 9859.164 }
costs { name: "cublas-gemm.5.0.peeled_double_buffer" cost_us: 10059.61 }
costs { name: "loop_multiply_fusion.1" cost_us: 192.351 }
costs { name: "loop_multiply_fusion.1.double_buffer_clone" cost_us: 192.159 }
costs { name: "loop_multiply_fusion.1.peeled_double_buffer" cost_us: 190.976 }
costs { name: "loop_multiply_fusion.11" cost_us: 193.503 }
costs { name: "loop_rsqrt_fusion" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.112 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 2.017 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 1.984 }
costs { name: "loop_multiply_fusion.12" cost_us: 193.695 }
costs { name: "loop_multiply_fusion.2" cost_us: 192.095 }
costs { name: "loop_multiply_fusion.2.double_buffer_clone" cost_us: 191.455 }
costs { name: "loop_multiply_fusion.2.peeled_double_buffer" cost_us: 193.151 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.08 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 2.112 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.208 }
costs { name: "custom-call.38.0" cost_us: 1879.32 }
costs { name: "custom-call.38.0" cost_us: 1.76 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1964.057 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1.728 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1886.969 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1.728 }
costs { name: "custom-call.39.0" cost_us: 2126.488 }
costs { name: "custom-call.39.0" cost_us: 1.92 }
costs { name: "loop_broadcast_fusion" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.11" cost_us: 1.344 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.312 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.3" cost_us: 1.503 }
costs { name: "loop_multiply_fusion.3.double_buffer_clone" cost_us: 1.504 }
costs { name: "loop_multiply_fusion.3.peeled_double_buffer" cost_us: 1.536 }
costs { name: "input_concatenate_fusion" cost_us: 318.494 }
costs { name: "input_concatenate_fusion.2" cost_us: 318.943 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 318.175 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 318.367 }
costs { name: "input_concatenate_fusion.1" cost_us: 41.44 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 41.439 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 41.44 }
costs { name: "input_concatenate_fusion.3" cost_us: 41.6 }
costs { name: "custom-call.137.0" cost_us: 383.903 }
costs { name: "custom-call.53.0" cost_us: 376.958 }
costs { name: "custom-call.53.0.double_buffer_clone" cost_us: 378.687 }
costs { name: "custom-call.53.0.peeled_double_buffer" cost_us: 377.119 }
costs { name: "custom-call.138.0" cost_us: 386.782 }
costs { name: "custom-call.55.0" cost_us: 375.775 }
costs { name: "custom-call.55.0.double_buffer_clone" cost_us: 377.31 }
costs { name: "custom-call.55.0.peeled_double_buffer" cost_us: 374.782 }
costs { name: "cublas-gemm.31.0" cost_us: 3115.637 }
costs { name: "cublas-gemm.4.0" cost_us: 3054.581 }
costs { name: "cublas-gemm.4.0.double_buffer_clone" cost_us: 3045.301 }
costs { name: "cublas-gemm.4.0.peeled_double_buffer" cost_us: 3059.285 }
costs { name: "custom-call.136.0" cost_us: 3064.693 }
costs { name: "custom-call.52.0" cost_us: 2947.669 }
costs { name: "custom-call.52.0.double_buffer_clone" cost_us: 2962.261 }
costs { name: "custom-call.52.0.peeled_double_buffer" cost_us: 2956.885 }
costs { name: "loop_convert_fusion.27" cost_us: 6.816 }
costs { name: "loop_power_fusion.1" cost_us: 1.504 }
costs { name: "all-reduce-start.4" cost_us: 6229.193 }
costs { name: "all-reduce-start.5" cost_us: 4784.079 }
costs { name: "all-reduce-start.7" cost_us: 1355.291 }
costs { name: "all-reduce-start.9" cost_us: 463.966 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 985.533 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 1035.357 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 1004.828 }
costs { name: "input_add_multiply_reduce_fusion.double_buffer_clone" cost_us: 1005.692 }
costs { name: "input_add_reduce_fusion" cost_us: 554.622 }
costs { name: "input_add_reduce_fusion.11" cost_us: 609.086 }
costs { name: "input_add_reduce_fusion.12" cost_us: 571.006 }
costs { name: "input_add_reduce_fusion.double_buffer_clone" cost_us: 558.366 }
costs { name: "input_reduce_fusion.44" cost_us: 4.832 }
costs { name: "input_reduce_fusion.45" cost_us: 4.512 }
costs { name: "input_reduce_fusion.46" cost_us: 8.192 }
costs { name: "input_reduce_fusion.5" cost_us: 7.84 }
costs { name: "input_reduce_fusion.5.double_buffer_clone" cost_us: 7.968 }
costs { name: "loop_multiply_fusion.14" cost_us: 2.304 }
costs { name: "loop_multiply_fusion.15" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.336 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.463 }
costs { name: "input_reduce_fusion.47" cost_us: 4.544 }
costs { name: "wrapped_slice.50" cost_us: 1.696 }
costs { name: "custom-call.142.0" cost_us: 10909.689 }
costs { name: "custom-call.171.0" cost_us: 11630.132 }
costs { name: "custom-call.172.0" cost_us: 11873.172 }
costs { name: "input_transpose_fusion.11" cost_us: 3.936 }
costs { name: "input_transpose_fusion.12" cost_us: 3.616 }
costs { name: "input_transpose_fusion.7" cost_us: 6.208 }
costs { name: "input_transpose_fusion.8" cost_us: 5.952 }
costs { name: "loop_convert_fusion.10" cost_us: 4.992 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 5.984 }
costs { name: "loop_convert_fusion.11" cost_us: 5.024 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 5.952 }
costs { name: "loop_convert_fusion.13" cost_us: 3.073 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 3.2 }
costs { name: "loop_convert_fusion.14" cost_us: 3.104 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 3.328 }
costs { name: "loop_convert_fusion.15" cost_us: 2.24 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 2.176 }
costs { name: "loop_convert_fusion.16" cost_us: 2.368 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 2.24 }
costs { name: "loop_convert_fusion.17" cost_us: 2.271 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_convert_fusion.18" cost_us: 1.984 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 2.016 }
costs { name: "loop_convert_fusion.20" cost_us: 6.176 }
costs { name: "loop_convert_fusion.21" cost_us: 5.856 }
costs { name: "loop_convert_fusion.22" cost_us: 6.432 }
costs { name: "loop_convert_fusion.23" cost_us: 6.048 }
costs { name: "loop_convert_fusion.28" cost_us: 3.136 }
costs { name: "loop_convert_fusion.29" cost_us: 3.136 }
costs { name: "loop_convert_fusion.31" cost_us: 2.144 }
costs { name: "loop_convert_fusion.32" cost_us: 2.24 }
costs { name: "loop_convert_fusion.33" cost_us: 2.24 }
costs { name: "loop_convert_fusion.34" cost_us: 2.272 }
costs { name: "loop_convert_fusion.37" cost_us: 2.336 }
costs { name: "loop_convert_fusion.38" cost_us: 2.368 }
costs { name: "loop_convert_fusion.39" cost_us: 2.432 }
costs { name: "loop_convert_fusion.40" cost_us: 2.08 }
costs { name: "loop_convert_fusion.9" cost_us: 5.248 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 6.176 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 184.96 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 25.599 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 26.048 }
costs { name: "loop_select_fusion" cost_us: 1.664 }
costs { name: "loop_select_fusion.double_buffer_clone" cost_us: 1.728 }
costs { name: "loop_add_fusion.4" cost_us: 1.248 }
costs { name: "loop_add_fusion.4.double_buffer_clone" cost_us: 1.728 }
costs { name: "input_transpose_fusion.4" cost_us: 4.225 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 395.135 }
costs { name: "loop_dynamic_update_slice_fusion.5.double_buffer_clone" cost_us: 400.254 }
costs { name: "input_transpose_fusion.9" cost_us: 2.528 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 114.688 }
costs { name: "loop_dynamic_update_slice_fusion.4.double_buffer_clone" cost_us: 116.224 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 1.504 }
costs { name: "loop_dynamic_update_slice_fusion.11.double_buffer_clone" cost_us: 1.536 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 1.471 }
costs { name: "loop_dynamic_update_slice_fusion.12.double_buffer_clone" cost_us: 1.663 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 10.143 }
costs { name: "loop_dynamic_update_slice_fusion.6.double_buffer_clone" cost_us: 10.144 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 10.08 }
costs { name: "loop_dynamic_update_slice_fusion.7.double_buffer_clone" cost_us: 10.208 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 3.936 }
costs { name: "loop_dynamic_update_slice_fusion.8.double_buffer_clone" cost_us: 4.032 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.791 }
costs { name: "loop_dynamic_update_slice_fusion.10.double_buffer_clone" cost_us: 1.792 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 1.728 }
costs { name: "loop_dynamic_update_slice_fusion.9.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_multiply_fusion" cost_us: 1865.657 }
costs { name: "loop_add_multiply_fusion.1" cost_us: 1846.904 }
costs { name: "loop_add_multiply_fusion.2" cost_us: 1867.193 }
costs { name: "loop_add_multiply_fusion.double_buffer_clone" cost_us: 1864.857 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.176 }
costs { name: "loop_multiply_fusion.5.double_buffer_clone" cost_us: 2.143 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.double_buffer_clone" cost_us: 2.144 }
costs { name: "custom-call.146.0" cost_us: 9780.059 }
costs { name: "custom-call.163.0" cost_us: 9970.009 }
costs { name: "custom-call.78.0" cost_us: 9872.764 }
costs { name: "custom-call.78.0.double_buffer_clone" cost_us: 9871.452 }
costs { name: "custom-call.150.0" cost_us: 10047.066 }
costs { name: "custom-call.160.0" cost_us: 9797.115 }
costs { name: "custom-call.82.0" cost_us: 9384.125 }
costs { name: "custom-call.82.0.double_buffer_clone" cost_us: 9457.468 }
costs { name: "cublas-gemm.13.0" cost_us: 9892.38 }
costs { name: "cublas-gemm.13.0.double_buffer_clone" cost_us: 9891.898 }
costs { name: "cublas-gemm.34.0" cost_us: 10296.122 }
costs { name: "cublas-gemm.37.0" cost_us: 10122.809 }
costs { name: "custom-call.151.0" cost_us: 9961.051 }
costs { name: "custom-call.161.0" cost_us: 9644.539 }
costs { name: "custom-call.83.0" cost_us: 9590.844 }
costs { name: "custom-call.83.0.double_buffer_clone" cost_us: 9431.998 }
costs { name: "custom-call.144.0" cost_us: 10347.066 }
costs { name: "custom-call.158.0" cost_us: 10504.345 }
costs { name: "custom-call.76.0" cost_us: 10434.65 }
costs { name: "custom-call.76.0.double_buffer_clone" cost_us: 10427.386 }
costs { name: "custom-call.152.0" cost_us: 10039.418 }
costs { name: "custom-call.162.0" cost_us: 9559.9 }
costs { name: "custom-call.84.0" cost_us: 9373.597 }
costs { name: "custom-call.84.0.double_buffer_clone" cost_us: 9482.364 }
costs { name: "all-reduce-start.1" cost_us: 256.447 }
costs { name: "all-reduce-start.3" cost_us: 737.181 }
costs { name: "wrapped_slice.16" cost_us: 1.536 }
costs { name: "wrapped_slice.46" cost_us: 1.248 }
costs { name: "wrapped_slice.47" cost_us: 1.76 }
costs { name: "wrapped_slice.9" cost_us: 1.056 }
costs { name: "all-reduce-start.8" cost_us: 3115.605 }
costs { name: "wrapped_slice.17" cost_us: 1.536 }
costs { name: "wrapped_slice.44" cost_us: 1.728 }
costs { name: "wrapped_slice.45" cost_us: 1.696 }
costs { name: "wrapped_slice.8" cost_us: 1.44 }
costs { name: "custom-call.35.0" cost_us: 6758.694 }
costs { name: "custom-call.35.0" cost_us: 277.087 }
costs { name: "custom-call.35.0" cost_us: 101.152 }
costs { name: "custom-call.35.0" cost_us: 205.951 }
costs { name: "custom-call.41.0" cost_us: 5380.172 }
costs { name: "custom-call.41.0" cost_us: 275.967 }
costs { name: "custom-call.41.0" cost_us: 100.768 }
costs { name: "custom-call.41.0" cost_us: 198.207 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 5909.098 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 275.775 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 100.576 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 193.183 }
costs { name: "custom-call.43.0" cost_us: 5856.362 }
costs { name: "custom-call.43.0" cost_us: 276.927 }
costs { name: "custom-call.43.0" cost_us: 101.056 }
costs { name: "custom-call.43.0" cost_us: 201.023 }
costs { name: "loop_add_fusion.2" cost_us: 485.694 }
costs { name: "loop_add_fusion.2.double_buffer_clone" cost_us: 521.822 }
costs { name: "loop_add_fusion.6" cost_us: 514.11 }
costs { name: "loop_add_fusion.7" cost_us: 589.31 }
costs { name: "loop_add_fusion.3" cost_us: 62.304 }
costs { name: "loop_add_fusion.3.double_buffer_clone" cost_us: 67.264 }
costs { name: "loop_add_fusion.8" cost_us: 66.496 }
costs { name: "loop_add_fusion.9" cost_us: 75.743 }
costs { name: "custom-call.153.0" cost_us: 372.415 }
costs { name: "custom-call.167.0" cost_us: 354.206 }
costs { name: "custom-call.85.0" cost_us: 318.111 }
costs { name: "custom-call.85.0.double_buffer_clone" cost_us: 328.638 }
costs { name: "custom-call.148.0" cost_us: 403.006 }
costs { name: "custom-call.165.0" cost_us: 356.799 }
costs { name: "custom-call.80.0" cost_us: 339.711 }
costs { name: "custom-call.80.0.double_buffer_clone" cost_us: 358.142 }
costs { name: "custom-call.156.0" cost_us: 378.047 }
costs { name: "custom-call.170.0" cost_us: 360.959 }
costs { name: "custom-call.88.0" cost_us: 337.119 }
costs { name: "custom-call.88.0.double_buffer_clone" cost_us: 344.127 }
costs { name: "cublas-gemm.14.0" cost_us: 411.454 }
costs { name: "cublas-gemm.14.0.double_buffer_clone" cost_us: 415.519 }
costs { name: "cublas-gemm.35.0" cost_us: 436.862 }
costs { name: "cublas-gemm.38.0" cost_us: 419.742 }
costs { name: "custom-call.154.0" cost_us: 2933.269 }
costs { name: "custom-call.168.0" cost_us: 2777.237 }
costs { name: "custom-call.86.0" cost_us: 2675.222 }
costs { name: "custom-call.86.0.double_buffer_clone" cost_us: 2737.974 }
costs { name: "custom-call.147.0" cost_us: 3336.852 }
costs { name: "custom-call.164.0" cost_us: 2984.821 }
costs { name: "custom-call.79.0" cost_us: 2962.261 }
costs { name: "custom-call.79.0.double_buffer_clone" cost_us: 2955.413 }
costs { name: "custom-call.155.0" cost_us: 2930.709 }
costs { name: "custom-call.169.0" cost_us: 2787.35 }
costs { name: "custom-call.87.0" cost_us: 2458.103 }
costs { name: "custom-call.87.0.double_buffer_clone" cost_us: 2564.822 }
costs { name: "custom-call.149.0" cost_us: 3338.644 }
costs { name: "custom-call.166.0" cost_us: 2897.237 }
costs { name: "custom-call.81.0" cost_us: 2692.79 }
costs { name: "custom-call.81.0.double_buffer_clone" cost_us: 2928.213 }
costs { name: "custom-call.143.0" cost_us: 10390.201 }
costs { name: "custom-call.157.0" cost_us: 10403.929 }
costs { name: "custom-call.75.0" cost_us: 10333.721 }
costs { name: "custom-call.75.0.double_buffer_clone" cost_us: 10358.234 }
costs { name: "custom-call.145.0" cost_us: 10406.969 }
costs { name: "custom-call.159.0" cost_us: 10410.681 }
costs { name: "custom-call.77.0" cost_us: 10346.394 }
costs { name: "custom-call.77.0.double_buffer_clone" cost_us: 10377.37 }
costs { name: "loop_multiply_fusion.4" cost_us: 191.807 }
costs { name: "loop_multiply_fusion.4.double_buffer_clone" cost_us: 191.296 }
costs { name: "loop_multiply_fusion.8" cost_us: 193.44 }
costs { name: "loop_multiply_fusion.9" cost_us: 191.807 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.08 }
costs { name: "loop_rsqrt_fusion.2.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.144 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.112 }
costs { name: "custom-call.34.0" cost_us: 1997.016 }
costs { name: "custom-call.34.0" cost_us: 2.208 }
costs { name: "custom-call.40.0" cost_us: 1916.504 }
costs { name: "custom-call.40.0" cost_us: 1.792 }
costs { name: "custom-call.40.0.double_buffer_clone" cost_us: 1867.449 }
costs { name: "custom-call.40.0.double_buffer_clone" cost_us: 1.792 }
costs { name: "custom-call.42.0" cost_us: 1928.76 }
costs { name: "custom-call.42.0" cost_us: 2.208 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.279 }
costs { name: "loop_broadcast_fusion.1.double_buffer_clone" cost_us: 1.279 }
costs { name: "loop_multiply_fusion.6" cost_us: 1.505 }
costs { name: "loop_multiply_fusion.6.double_buffer_clone" cost_us: 1.504 }
costs { name: "loop_convert_fusion.12" cost_us: 6.816 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 6.847 }
costs { name: "loop_power_fusion" cost_us: 1.631 }
costs { name: "loop_power_fusion.double_buffer_clone" cost_us: 1.568 }
costs { name: "cublas-gemm.12.0" cost_us: 3039.605 }
costs { name: "cublas-gemm.12.0.double_buffer_clone" cost_us: 3046.037 }
costs { name: "cublas-gemm.33.0" cost_us: 3066.996 }
costs { name: "cublas-gemm.36.0" cost_us: 3079.605 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 187.296 }
costs { name: "loop_dynamic_slice_fusion.2.double_buffer_clone" cost_us: 182.72 }
costs { name: "wrapped_slice" cost_us: 185.919 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 25.248 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 25.152 }
costs { name: "loop_dynamic_slice_fusion.1.double_buffer_clone" cost_us: 24.992 }
costs { name: "loop_dynamic_slice_fusion.double_buffer_clone" cost_us: 25.056 }
costs { name: "wrapped_slice.1" cost_us: 24.32 }
costs { name: "wrapped_slice.2" cost_us: 24.383 }
costs { name: "wrapped_slice.3" cost_us: 185.983 }
costs { name: "loop_divide_fusion" cost_us: 1.728 }
costs { name: "wrapped_transpose.2" cost_us: 393.503 }
costs { name: "wrapped_transpose.3" cost_us: 393.343 }
costs { name: "wrapped_transpose.4" cost_us: 413.951 }
costs { name: "wrapped_transpose.1" cost_us: 3.327 }
costs { name: "wrapped_transpose" cost_us: 3.296 }
costs { name: "wrapped_transpose.5" cost_us: 16.0 }
costs { name: "wrapped_transpose.6" cost_us: 417.182 }
costs { name: "wrapped_transpose.7" cost_us: 112.735 }
costs { name: "wrapped_transpose.8" cost_us: 16.0 }
