costs { name: "all-gather-start" cost_us: 15658.484 }
costs { name: "all-gather-start.1" cost_us: 15107.735 }
costs { name: "all-gather-start.2" cost_us: 15661.589 }
costs { name: "all-gather-start.3" cost_us: 16074.613 }
costs { name: "all-gather-start.4" cost_us: 15158.551 }
costs { name: "all-gather-start.5" cost_us: 16014.421 }
costs { name: "all-gather-start.6" cost_us: 17489.006 }
costs { name: "all-gather-start.7" cost_us: 10926.178 }
costs { name: "all-gather-start.8" cost_us: 14872.12 }
costs { name: "all-reduce-start" cost_us: 1131.452 }
costs { name: "all-reduce-start.2" cost_us: 1400.508 }
costs { name: "all-reduce-start.6" cost_us: 3012.952 }
costs { name: "input_transpose_fusion" cost_us: 4.352 }
costs { name: "input_transpose_fusion.1" cost_us: 417.439 }
costs { name: "input_transpose_fusion.2" cost_us: 9.504 }
costs { name: "input_transpose_fusion.3" cost_us: 14.176 }
costs { name: "loop_add_fusion.1" cost_us: 1.44 }
costs { name: "loop_add_fusion.1.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_fusion.5" cost_us: 1.504 }
costs { name: "loop_add_fusion.5.double_buffer_clone" cost_us: 1.408 }
costs { name: "loop_broadcast_fusion" cost_us: 1.536 }
costs { name: "loop_broadcast_fusion.10" cost_us: 56.128 }
costs { name: "loop_broadcast_fusion.2" cost_us: 839.358 }
costs { name: "loop_broadcast_fusion.3" cost_us: 6733.454 }
costs { name: "loop_broadcast_fusion.4" cost_us: 6731.918 }
costs { name: "loop_broadcast_fusion.5" cost_us: 400.48 }
costs { name: "loop_broadcast_fusion.6" cost_us: 195.615 }
costs { name: "loop_broadcast_fusion.7" cost_us: 2.912 }
costs { name: "loop_broadcast_fusion.8" cost_us: 15.776 }
costs { name: "loop_broadcast_fusion.9" cost_us: 56.383 }
costs { name: "loop_transpose_fusion" cost_us: 121.984 }
costs { name: "reduce-scatter.37.double_buffer_clone.1" cost_us: 16569.425 }
costs { name: "reduce-scatter.40" cost_us: 16204.277 }
costs { name: "reduce-scatter.41" cost_us: 21400.196 }
costs { name: "reduce-scatter.42" cost_us: 26381.686 }
costs { name: "wrapped_concatenate" cost_us: 20.864 }
costs { name: "wrapped_concatenate.1" cost_us: 1.825 }
costs { name: "wrapped_concatenate.2" cost_us: 20.512 }
costs { name: "wrapped_concatenate.3" cost_us: 2.016 }
costs { name: "wrapped_concatenate.4" cost_us: 83.935 }
costs { name: "wrapped_concatenate.5" cost_us: 1.856 }
costs { name: "wrapped_concatenate.6" cost_us: 2.08 }
costs { name: "wrapped_concatenate.7" cost_us: 2.624 }
costs { name: "wrapped_slice.10" cost_us: 3.712 }
costs { name: "wrapped_slice.11" cost_us: 4.128 }
costs { name: "wrapped_slice.12" cost_us: 4.576 }
costs { name: "wrapped_slice.13" cost_us: 4.064 }
costs { name: "wrapped_slice.14" cost_us: 4.608 }
costs { name: "wrapped_slice.15" cost_us: 3.647 }
costs { name: "wrapped_slice.18" cost_us: 2.111 }
costs { name: "wrapped_slice.19" cost_us: 2.496 }
costs { name: "wrapped_slice.20" cost_us: 2.72 }
costs { name: "wrapped_slice.21" cost_us: 2.08 }
costs { name: "wrapped_slice.22" cost_us: 4.224 }
costs { name: "wrapped_slice.23" cost_us: 4.064 }
costs { name: "wrapped_slice.24" cost_us: 2.111 }
costs { name: "wrapped_slice.25" cost_us: 2.016 }
costs { name: "wrapped_slice.26" cost_us: 2.369 }
costs { name: "wrapped_slice.27" cost_us: 2.336 }
costs { name: "wrapped_slice.28" cost_us: 2.368 }
costs { name: "wrapped_slice.29" cost_us: 2.336 }
costs { name: "wrapped_slice.30" cost_us: 2.112 }
costs { name: "wrapped_slice.31" cost_us: 1.952 }
costs { name: "wrapped_slice.32" cost_us: 3.904 }
costs { name: "wrapped_slice.33" cost_us: 3.904 }
costs { name: "wrapped_slice.34" cost_us: 3.904 }
costs { name: "wrapped_slice.35" cost_us: 3.936 }
costs { name: "wrapped_slice.36" cost_us: 4.16 }
costs { name: "wrapped_slice.37" cost_us: 4.32 }
costs { name: "wrapped_slice.38" cost_us: 1.76 }
costs { name: "wrapped_slice.39" cost_us: 1.28 }
costs { name: "wrapped_slice.4" cost_us: 2.08 }
costs { name: "wrapped_slice.40" cost_us: 1.28 }
costs { name: "wrapped_slice.41" cost_us: 1.312 }
costs { name: "wrapped_slice.42" cost_us: 1.472 }
costs { name: "wrapped_slice.43" cost_us: 1.312 }
costs { name: "wrapped_slice.48" cost_us: 1.312 }
costs { name: "wrapped_slice.49" cost_us: 1.312 }
costs { name: "wrapped_slice.5" cost_us: 2.688 }
costs { name: "wrapped_slice.51" cost_us: 1.44 }
costs { name: "wrapped_slice.52" cost_us: 1.504 }
costs { name: "wrapped_slice.53" cost_us: 1.6 }
costs { name: "wrapped_slice.54" cost_us: 1.248 }
costs { name: "wrapped_slice.55" cost_us: 1.249 }
costs { name: "wrapped_slice.56" cost_us: 1.28 }
costs { name: "wrapped_slice.57" cost_us: 1.472 }
costs { name: "wrapped_slice.58" cost_us: 1.28 }
costs { name: "wrapped_slice.59" cost_us: 1.249 }
costs { name: "wrapped_slice.6" cost_us: 2.464 }
costs { name: "wrapped_slice.60" cost_us: 1.344 }
costs { name: "wrapped_slice.61" cost_us: 1.44 }
costs { name: "wrapped_slice.62" cost_us: 1.28 }
costs { name: "wrapped_slice.63" cost_us: 1.249 }
costs { name: "wrapped_slice.64" cost_us: 1.312 }
costs { name: "wrapped_slice.65" cost_us: 1.439 }
costs { name: "wrapped_slice.66" cost_us: 1.28 }
costs { name: "wrapped_slice.67" cost_us: 1.249 }
costs { name: "wrapped_slice.68" cost_us: 1.312 }
costs { name: "wrapped_slice.69" cost_us: 1.44 }
costs { name: "wrapped_slice.7" cost_us: 2.048 }
costs { name: "wrapped_slice.70" cost_us: 1.249 }
costs { name: "wrapped_slice.71" cost_us: 1.247 }
costs { name: "wrapped_slice.72" cost_us: 1.312 }
costs { name: "wrapped_slice.73" cost_us: 1.44 }
costs { name: "wrapped_slice.74" cost_us: 1.247 }
costs { name: "wrapped_slice.75" cost_us: 1.247 }
costs { name: "wrapped_slice.76" cost_us: 1.344 }
costs { name: "wrapped_slice.77" cost_us: 1.408 }
costs { name: "wrapped_slice.78" cost_us: 1.247 }
costs { name: "wrapped_transpose.10" cost_us: 3.648 }
costs { name: "wrapped_transpose.11" cost_us: 3.776 }
costs { name: "wrapped_transpose.12" cost_us: 6.656 }
costs { name: "wrapped_transpose.13" cost_us: 7.104 }
costs { name: "wrapped_transpose.14" cost_us: 7.264 }
costs { name: "wrapped_transpose.9" cost_us: 2.656 }
costs { name: "wrapped_select" cost_us: 1.536 }
costs { name: "loop_add_fusion" cost_us: 1.344 }
costs { name: "wrapped_add" cost_us: 1.44 }
costs { name: "loop_minimum_fusion" cost_us: 1.952 }
costs { name: "wrapped_cosine" cost_us: 1.632 }
costs { name: "input_reduce_fusion" cost_us: 1.568 }
costs { name: "loop_xor_fusion" cost_us: 1.984 }
costs { name: "wrapped_multiply" cost_us: 1.344 }
costs { name: "loop_subtract_fusion" cost_us: 1.536 }
costs { name: "input_add_reduce_fusion.1" cost_us: 39.936 }
costs { name: "input_add_reduce_fusion.10" cost_us: 1525.564 }
costs { name: "input_add_reduce_fusion.13" cost_us: 50.848 }
costs { name: "input_add_reduce_fusion.14" cost_us: 50.207 }
costs { name: "input_add_reduce_fusion.15" cost_us: 6.272 }
costs { name: "input_add_reduce_fusion.2" cost_us: 32.896 }
costs { name: "input_add_reduce_fusion.3" cost_us: 398.079 }
costs { name: "input_add_reduce_fusion.4" cost_us: 395.263 }
costs { name: "input_add_reduce_fusion.5" cost_us: 32.896 }
costs { name: "input_add_reduce_fusion.6" cost_us: 13.792 }
costs { name: "input_add_reduce_fusion.7" cost_us: 13.984 }
costs { name: "input_add_reduce_fusion.8" cost_us: 1373.052 }
costs { name: "input_add_reduce_fusion.9" cost_us: 1526.876 }
costs { name: "input_compare_reduce_fusion" cost_us: 2.847 }
costs { name: "input_convert_reduce_fusion" cost_us: 2217.625 }
costs { name: "input_convert_reduce_fusion.1" cost_us: 441.471 }
costs { name: "input_dynamic_slice_reduce_fusion" cost_us: 176.799 }
costs { name: "input_dynamic_slice_reduce_fusion.1" cost_us: 175.584 }
costs { name: "input_dynamic_slice_reduce_fusion.double_buffer_clone" cost_us: 176.96 }
costs { name: "input_reduce_fusion.10" cost_us: 13.824 }
costs { name: "input_reduce_fusion.11" cost_us: 79.327 }
costs { name: "input_reduce_fusion.12" cost_us: 84.32 }
costs { name: "input_reduce_fusion.13" cost_us: 13.6 }
costs { name: "input_reduce_fusion.14" cost_us: 5.504 }
costs { name: "input_reduce_fusion.15" cost_us: 5.664 }
costs { name: "input_reduce_fusion.16" cost_us: 233.215 }
costs { name: "input_reduce_fusion.17" cost_us: 245.439 }
costs { name: "input_reduce_fusion.18" cost_us: 251.552 }
costs { name: "input_reduce_fusion.19" cost_us: 2.208 }
costs { name: "input_reduce_fusion.2" cost_us: 252.031 }
costs { name: "input_reduce_fusion.2.double_buffer_clone" cost_us: 255.583 }
costs { name: "input_reduce_fusion.20" cost_us: 1.952 }
costs { name: "input_reduce_fusion.21" cost_us: 2.016 }
costs { name: "input_reduce_fusion.22" cost_us: 2.336 }
costs { name: "input_reduce_fusion.23" cost_us: 2.208 }
costs { name: "input_reduce_fusion.24" cost_us: 2.112 }
costs { name: "input_reduce_fusion.25" cost_us: 2.144 }
costs { name: "input_reduce_fusion.26" cost_us: 2.144 }
costs { name: "input_reduce_fusion.27" cost_us: 2.144 }
costs { name: "input_reduce_fusion.28" cost_us: 523.646 }
costs { name: "input_reduce_fusion.29" cost_us: 2.08 }
costs { name: "input_reduce_fusion.3" cost_us: 85.088 }
costs { name: "input_reduce_fusion.3.double_buffer_clone" cost_us: 85.44 }
costs { name: "input_reduce_fusion.30" cost_us: 376.447 }
costs { name: "input_reduce_fusion.33" cost_us: 256.735 }
costs { name: "input_reduce_fusion.34" cost_us: 85.631 }
costs { name: "input_reduce_fusion.35" cost_us: 170.879 }
costs { name: "input_reduce_fusion.36" cost_us: 258.175 }
costs { name: "input_reduce_fusion.37" cost_us: 85.695 }
costs { name: "input_reduce_fusion.38" cost_us: 170.879 }
costs { name: "input_reduce_fusion.4" cost_us: 168.095 }
costs { name: "input_reduce_fusion.4.double_buffer_clone" cost_us: 168.415 }
costs { name: "input_reduce_fusion.40" cost_us: 169.92 }
costs { name: "input_reduce_fusion.41" cost_us: 1.824 }
costs { name: "input_reduce_fusion.42" cost_us: 1.728 }
costs { name: "input_reduce_fusion.43" cost_us: 6.047 }
costs { name: "input_reduce_fusion.48" cost_us: 2.303 }
costs { name: "input_reduce_fusion.49" cost_us: 1.824 }
costs { name: "input_reduce_fusion.50" cost_us: 1.728 }
costs { name: "input_reduce_fusion.51" cost_us: 1.856 }
costs { name: "input_reduce_fusion.52" cost_us: 1.632 }
costs { name: "input_reduce_fusion.53" cost_us: 1.76 }
costs { name: "input_reduce_fusion.54" cost_us: 1.984 }
costs { name: "input_reduce_fusion.55" cost_us: 2.049 }
costs { name: "input_reduce_fusion.56" cost_us: 5.216 }
costs { name: "input_reduce_fusion.57" cost_us: 1.984 }
costs { name: "input_reduce_fusion.58" cost_us: 1.983 }
costs { name: "input_reduce_fusion.59" cost_us: 2.08 }
costs { name: "input_reduce_fusion.6" cost_us: 3.295 }
costs { name: "input_reduce_fusion.60" cost_us: 1.824 }
costs { name: "input_reduce_fusion.61" cost_us: 1.664 }
costs { name: "input_reduce_fusion.62" cost_us: 1.664 }
costs { name: "input_reduce_fusion.63" cost_us: 1.664 }
costs { name: "input_reduce_fusion.64" cost_us: 1.664 }
costs { name: "input_reduce_fusion.65" cost_us: 1.6 }
costs { name: "input_reduce_fusion.66" cost_us: 1.728 }
costs { name: "input_reduce_fusion.67" cost_us: 1.792 }
costs { name: "input_reduce_fusion.68" cost_us: 2.4 }
costs { name: "input_reduce_fusion.69" cost_us: 2.177 }
costs { name: "input_reduce_fusion.7" cost_us: 4.096 }
costs { name: "input_reduce_fusion.70" cost_us: 1.856 }
costs { name: "input_reduce_fusion.71" cost_us: 1.6 }
costs { name: "input_reduce_fusion.72" cost_us: 1.76 }
costs { name: "input_reduce_fusion.73" cost_us: 1.536 }
costs { name: "input_reduce_fusion.74" cost_us: 1.76 }
costs { name: "input_reduce_fusion.75" cost_us: 1.6 }
costs { name: "input_reduce_fusion.76" cost_us: 1.6 }
costs { name: "input_reduce_fusion.77" cost_us: 1.952 }
costs { name: "input_reduce_fusion.78" cost_us: 2.336 }
costs { name: "input_reduce_fusion.8" cost_us: 3.264 }
costs { name: "input_reduce_fusion.9" cost_us: 3.168 }
costs { name: "loop_add_fusion.10" cost_us: 6.944 }
costs { name: "loop_add_fusion.11" cost_us: 7.232 }
costs { name: "loop_add_log_fusion" cost_us: 2.08 }
costs { name: "loop_compare_sqrt_fusion" cost_us: 1.696 }
costs { name: "loop_convert_fusion.26" cost_us: 7.168 }
costs { name: "loop_divide_fusion" cost_us: 1.728 }
costs { name: "loop_multiply_fusion.13" cost_us: 2.304 }
costs { name: "loop_multiply_fusion.16" cost_us: 1.536 }
costs { name: "loop_multiply_fusion.17" cost_us: 1.6 }
costs { name: "loop_select_fusion.1" cost_us: 816.061 }
costs { name: "loop_select_fusion.2" cost_us: 816.542 }
costs { name: "loop_select_fusion.3" cost_us: 801.182 }
costs { name: "loop_select_fusion.4" cost_us: 235.711 }
costs { name: "loop_select_fusion.5" cost_us: 231.743 }
costs { name: "loop_select_fusion.6" cost_us: 2.08 }
costs { name: "loop_select_fusion.7" cost_us: 1.312 }
costs { name: "loop_select_fusion.8" cost_us: 1.632 }
costs { name: "loop_select_subtract_fusion" cost_us: 1.792 }
costs { name: "loop_sqrt_fusion" cost_us: 2.432 }
costs { name: "loop_subtract_fusion" cost_us: 1.6 }
costs { name: "while.6.0" cost_us: 319.904 }
costs { name: "while.6.0" cost_us: 10301.956 }
costs { name: "while.6.0" cost_us: 16204.277 }
costs { name: "while.6.0" cost_us: 9799.493 }
costs { name: "while.6.0" cost_us: 15661.589 }
costs { name: "while.6.0" cost_us: 5431.633 }
costs { name: "while.6.0" cost_us: 2733.369 }
costs { name: "while.6.0" cost_us: 2965.689 }
costs { name: "while.6.0" cost_us: 1906.842 }
costs { name: "while.6.0" cost_us: 1131.452 }
costs { name: "while.6.0" cost_us: 1865.466 }
costs { name: "while.6.0" cost_us: 162.527 }
costs { name: "while.6.0" cost_us: 988.573 }
costs { name: "while.6.0" cost_us: 351.135 }
costs { name: "while.6.0" cost_us: 556.799 }
costs { name: "while.6.0" cost_us: 490.014 }
costs { name: "while.6.0" cost_us: 396.351 }
costs { name: "while.6.0" cost_us: 275.871 }
costs { name: "while.6.0" cost_us: 252.031 }
costs { name: "while.6.0" cost_us: 100.831 }
costs { name: "while.6.0" cost_us: 193.119 }
costs { name: "while.6.0" cost_us: 191.36 }
costs { name: "while.6.0" cost_us: 182.88 }
costs { name: "while.6.0" cost_us: 176.799 }
costs { name: "while.6.0" cost_us: 168.095 }
costs { name: "while.6.0" cost_us: 114.752 }
costs { name: "while.6.0" cost_us: 85.088 }
costs { name: "while.6.0" cost_us: 62.848 }
costs { name: "while.6.0" cost_us: 25.055 }
costs { name: "while.6.0" cost_us: 20.512 }
costs { name: "while.6.0" cost_us: 10.111 }
costs { name: "while.6.0" cost_us: 4.929 }
costs { name: "while.6.0" cost_us: 7.84 }
costs { name: "while.6.0" cost_us: 6.816 }
costs { name: "while.6.0" cost_us: 5.216 }
costs { name: "while.6.0" cost_us: 2.24 }
costs { name: "while.6.0" cost_us: 2.048 }
costs { name: "while.6.0" cost_us: 4.128 }
costs { name: "while.6.0" cost_us: 4.064 }
costs { name: "while.6.0" cost_us: 3.968 }
costs { name: "while.6.0" cost_us: 3.647 }
costs { name: "while.6.0" cost_us: 1.727 }
costs { name: "while.6.0" cost_us: 3.072 }
costs { name: "while.6.0" cost_us: 3.009 }
costs { name: "while.6.0" cost_us: 1.472 }
costs { name: "while.6.0" cost_us: 2.688 }
costs { name: "while.6.0" cost_us: 2.464 }
costs { name: "while.6.0" cost_us: 2.144 }
costs { name: "while.6.0" cost_us: 2.144 }
costs { name: "while.6.0" cost_us: 2.047 }
costs { name: "while.6.0" cost_us: 2.08 }
costs { name: "while.6.0" cost_us: 2.048 }
costs { name: "while.6.0" cost_us: 1.825 }
costs { name: "while.6.0" cost_us: 1.792 }
costs { name: "while.6.0" cost_us: 1.664 }
costs { name: "while.6.0" cost_us: 1.567 }
costs { name: "while.6.0" cost_us: 1.248 }
costs { name: "while.6.0" cost_us: 1.408 }
costs { name: "while.6.0" cost_us: 1.472 }
costs { name: "while.6.0" cost_us: 1.472 }
costs { name: "while.6.0" cost_us: 1.024 }
costs { name: "while.6.0" cost_us: 1.28 }
costs { name: "loop_add_fusion.12" cost_us: 1.792 }
costs { name: "input_reduce_fusion" cost_us: 91.84 }
costs { name: "input_reduce_fusion.1" cost_us: 85.12 }
costs { name: "input_reduce_fusion.1.double_buffer_clone" cost_us: 85.28 }
costs { name: "input_reduce_fusion.1.peeled_double_buffer" cost_us: 85.567 }
costs { name: "input_reduce_fusion.31" cost_us: 94.272 }
costs { name: "input_reduce_fusion.32" cost_us: 86.016 }
costs { name: "input_reduce_fusion.double_buffer_clone" cost_us: 90.336 }
costs { name: "input_reduce_fusion.peeled_double_buffer" cost_us: 86.24 }
costs { name: "while.5.0" cost_us: 376.383 }
costs { name: "while.5.0" cost_us: 15107.735 }
costs { name: "while.5.0" cost_us: 9783.494 }
costs { name: "while.5.0" cost_us: 2948.728 }
costs { name: "while.5.0" cost_us: 3044.984 }
costs { name: "while.5.0" cost_us: 1944.475 }
costs { name: "while.5.0" cost_us: 901.854 }
costs { name: "while.5.0" cost_us: 632.67 }
costs { name: "while.5.0" cost_us: 632.255 }
costs { name: "while.5.0" cost_us: 318.303 }
costs { name: "while.5.0" cost_us: 191.584 }
costs { name: "while.5.0" cost_us: 192.224 }
costs { name: "while.5.0" cost_us: 90.336 }
costs { name: "while.5.0" cost_us: 85.12 }
costs { name: "while.5.0" cost_us: 80.64 }
costs { name: "while.5.0" cost_us: 80.64 }
costs { name: "while.5.0" cost_us: 41.408 }
costs { name: "while.5.0" cost_us: 4.831 }
costs { name: "while.5.0" cost_us: 4.832 }
costs { name: "while.5.0" cost_us: 2.113 }
costs { name: "while.5.0" cost_us: 2.016 }
costs { name: "while.5.0" cost_us: 2.016 }
costs { name: "while.5.0" cost_us: 2.944 }
costs { name: "while.5.0" cost_us: 2.88 }
costs { name: "while.5.0" cost_us: 1.728 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "while.5.0" cost_us: 1.472 }
costs { name: "while.5.0" cost_us: 1.28 }
costs { name: "while.5.0" cost_us: 1.76 }
costs { name: "while.5.0" cost_us: 1.44 }
costs { name: "input_reduce_fusion.39" cost_us: 87.232 }
costs { name: "loop_multiply_fusion.10" cost_us: 194.464 }
costs { name: "loop_rsqrt_fusion.5" cost_us: 2.272 }
costs { name: "wrapped_convert.1" cost_us: 2.016 }
costs { name: "wrapped_convert" cost_us: 6.4 }
costs { name: "custom-call.141.0" cost_us: 12574.75 }
costs { name: "loop_convert_fusion.19" cost_us: 619.039 }
costs { name: "input_transpose_fusion.5" cost_us: 5.568 }
costs { name: "custom-call.135.0" cost_us: 9083.016 }
costs { name: "input_transpose_fusion.10" cost_us: 3.872 }
costs { name: "input_transpose_fusion.6" cost_us: 6.656 }
costs { name: "loop_convert_fusion" cost_us: 4.832 }
costs { name: "loop_convert_fusion.1" cost_us: 4.831 }
costs { name: "loop_convert_fusion.1.double_buffer_clone" cost_us: 5.856 }
costs { name: "loop_convert_fusion.1.peeled_double_buffer" cost_us: 6.624 }
costs { name: "loop_convert_fusion.2" cost_us: 4.927 }
costs { name: "loop_convert_fusion.2.double_buffer_clone" cost_us: 5.92 }
costs { name: "loop_convert_fusion.2.peeled_double_buffer" cost_us: 6.593 }
costs { name: "loop_convert_fusion.24" cost_us: 6.784 }
costs { name: "loop_convert_fusion.25" cost_us: 6.528 }
costs { name: "loop_convert_fusion.3" cost_us: 2.88 }
costs { name: "loop_convert_fusion.3.double_buffer_clone" cost_us: 3.2 }
costs { name: "loop_convert_fusion.3.peeled_double_buffer" cost_us: 3.392 }
costs { name: "loop_convert_fusion.30" cost_us: 3.488 }
costs { name: "loop_convert_fusion.35" cost_us: 2.176 }
costs { name: "loop_convert_fusion.36" cost_us: 2.24 }
costs { name: "loop_convert_fusion.4" cost_us: 2.944 }
costs { name: "loop_convert_fusion.4.double_buffer_clone" cost_us: 3.136 }
costs { name: "loop_convert_fusion.4.peeled_double_buffer" cost_us: 3.872 }
costs { name: "loop_convert_fusion.41" cost_us: 2.176 }
costs { name: "loop_convert_fusion.42" cost_us: 2.016 }
costs { name: "loop_convert_fusion.5" cost_us: 2.144 }
costs { name: "loop_convert_fusion.5.double_buffer_clone" cost_us: 2.113 }
costs { name: "loop_convert_fusion.5.peeled_double_buffer" cost_us: 2.272 }
costs { name: "loop_convert_fusion.6" cost_us: 2.24 }
costs { name: "loop_convert_fusion.6.double_buffer_clone" cost_us: 2.208 }
costs { name: "loop_convert_fusion.6.peeled_double_buffer" cost_us: 2.464 }
costs { name: "loop_convert_fusion.7" cost_us: 2.016 }
costs { name: "loop_convert_fusion.7.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_convert_fusion.7.peeled_double_buffer" cost_us: 1.888 }
costs { name: "loop_convert_fusion.8" cost_us: 2.048 }
costs { name: "loop_convert_fusion.8.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_convert_fusion.8.peeled_double_buffer" cost_us: 1.856 }
costs { name: "loop_convert_fusion.double_buffer_clone" cost_us: 6.048 }
costs { name: "loop_convert_fusion.peeled_double_buffer" cost_us: 6.688 }
costs { name: "loop_dynamic_update_slice_fusion" cost_us: 632.671 }
costs { name: "loop_dynamic_update_slice_fusion.1" cost_us: 80.703 }
costs { name: "loop_dynamic_update_slice_fusion.1.double_buffer_clone" cost_us: 80.64 }
costs { name: "loop_dynamic_update_slice_fusion.1.peeled_double_buffer" cost_us: 81.088 }
costs { name: "loop_dynamic_update_slice_fusion.13" cost_us: 633.087 }
costs { name: "loop_dynamic_update_slice_fusion.14" cost_us: 80.736 }
costs { name: "loop_dynamic_update_slice_fusion.15" cost_us: 80.992 }
costs { name: "loop_dynamic_update_slice_fusion.16" cost_us: 633.182 }
costs { name: "loop_dynamic_update_slice_fusion.2" cost_us: 80.703 }
costs { name: "loop_dynamic_update_slice_fusion.2.double_buffer_clone" cost_us: 80.64 }
costs { name: "loop_dynamic_update_slice_fusion.2.peeled_double_buffer" cost_us: 80.512 }
costs { name: "loop_dynamic_update_slice_fusion.3" cost_us: 632.958 }
costs { name: "loop_dynamic_update_slice_fusion.3.double_buffer_clone" cost_us: 632.255 }
costs { name: "loop_dynamic_update_slice_fusion.3.peeled_double_buffer" cost_us: 632.862 }
costs { name: "loop_dynamic_update_slice_fusion.double_buffer_clone" cost_us: 632.67 }
costs { name: "loop_dynamic_update_slice_fusion.peeled_double_buffer" cost_us: 632.702 }
costs { name: "copy_fusion.1" cost_us: 1.6 }
costs { name: "loop_add_fusion" cost_us: 1.632 }
costs { name: "loop_add_fusion.double_buffer_clone" cost_us: 1.44 }
costs { name: "loop_multiply_fusion" cost_us: 901.854 }
costs { name: "loop_multiply_fusion.7" cost_us: 902.91 }
costs { name: "loop_multiply_fusion.double_buffer_clone" cost_us: 902.078 }
costs { name: "loop_multiply_fusion.peeled_double_buffer" cost_us: 900.894 }
costs { name: "custom-call.139.0" cost_us: 10404.131 }
costs { name: "custom-call.56.0" cost_us: 10284.292 }
costs { name: "custom-call.56.0.double_buffer_clone" cost_us: 10306.756 }
costs { name: "custom-call.56.0.peeled_double_buffer" cost_us: 10298.053 }
costs { name: "custom-call.140.0" cost_us: 10361.253 }
costs { name: "custom-call.57.0" cost_us: 10287.62 }
costs { name: "custom-call.57.0.double_buffer_clone" cost_us: 10303.268 }
costs { name: "custom-call.57.0.peeled_double_buffer" cost_us: 10329.38 }
costs { name: "cublas-gemm.32.0" cost_us: 9958.468 }
costs { name: "cublas-gemm.5.0" cost_us: 9783.494 }
costs { name: "cublas-gemm.5.0.double_buffer_clone" cost_us: 9788.997 }
costs { name: "cublas-gemm.5.0.peeled_double_buffer" cost_us: 9869.413 }
costs { name: "loop_multiply_fusion.1" cost_us: 192.288 }
costs { name: "loop_multiply_fusion.1.double_buffer_clone" cost_us: 192.224 }
costs { name: "loop_multiply_fusion.1.peeled_double_buffer" cost_us: 192.576 }
costs { name: "loop_multiply_fusion.11" cost_us: 192.832 }
costs { name: "loop_rsqrt_fusion" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.6" cost_us: 2.272 }
costs { name: "loop_rsqrt_fusion.double_buffer_clone" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.peeled_double_buffer" cost_us: 2.144 }
costs { name: "loop_multiply_fusion.12" cost_us: 194.272 }
costs { name: "loop_multiply_fusion.2" cost_us: 191.679 }
costs { name: "loop_multiply_fusion.2.double_buffer_clone" cost_us: 191.584 }
costs { name: "loop_multiply_fusion.2.peeled_double_buffer" cost_us: 192.383 }
costs { name: "loop_rsqrt_fusion.1" cost_us: 2.111 }
costs { name: "loop_rsqrt_fusion.1.double_buffer_clone" cost_us: 2.016 }
costs { name: "loop_rsqrt_fusion.1.peeled_double_buffer" cost_us: 2.08 }
costs { name: "loop_rsqrt_fusion.7" cost_us: 2.112 }
costs { name: "custom-call.38.0" cost_us: 1944.475 }
costs { name: "custom-call.38.0" cost_us: 1.76 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1977.306 }
costs { name: "custom-call.38.0.double_buffer_clone" cost_us: 1.728 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1866.011 }
costs { name: "custom-call.38.0.peeled_double_buffer" cost_us: 1.728 }
costs { name: "custom-call.39.0" cost_us: 2122.811 }
costs { name: "custom-call.39.0" cost_us: 1.888 }
costs { name: "loop_broadcast_fusion" cost_us: 1.312 }
costs { name: "loop_broadcast_fusion.11" cost_us: 1.344 }
costs { name: "loop_broadcast_fusion.double_buffer_clone" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.peeled_double_buffer" cost_us: 1.312 }
costs { name: "loop_multiply_fusion.3" cost_us: 1.472 }
costs { name: "loop_multiply_fusion.3.double_buffer_clone" cost_us: 1.472 }
costs { name: "loop_multiply_fusion.3.peeled_double_buffer" cost_us: 1.504 }
costs { name: "input_concatenate_fusion" cost_us: 318.335 }
costs { name: "input_concatenate_fusion.2" cost_us: 318.943 }
costs { name: "input_concatenate_fusion.double_buffer_clone" cost_us: 318.303 }
costs { name: "input_concatenate_fusion.peeled_double_buffer" cost_us: 318.431 }
costs { name: "input_concatenate_fusion.1" cost_us: 41.471 }
costs { name: "input_concatenate_fusion.1.double_buffer_clone" cost_us: 41.408 }
costs { name: "input_concatenate_fusion.1.peeled_double_buffer" cost_us: 41.472 }
costs { name: "input_concatenate_fusion.3" cost_us: 41.6 }
costs { name: "custom-call.137.0" cost_us: 393.663 }
costs { name: "custom-call.53.0" cost_us: 376.383 }
costs { name: "custom-call.53.0.double_buffer_clone" cost_us: 380.575 }
costs { name: "custom-call.53.0.peeled_double_buffer" cost_us: 373.663 }
costs { name: "custom-call.138.0" cost_us: 397.086 }
costs { name: "custom-call.55.0" cost_us: 376.799 }
costs { name: "custom-call.55.0.double_buffer_clone" cost_us: 378.495 }
costs { name: "custom-call.55.0.peeled_double_buffer" cost_us: 373.183 }
costs { name: "cublas-gemm.31.0" cost_us: 3119.415 }
costs { name: "cublas-gemm.4.0" cost_us: 3044.984 }
costs { name: "cublas-gemm.4.0.double_buffer_clone" cost_us: 3055.607 }
costs { name: "cublas-gemm.4.0.peeled_double_buffer" cost_us: 3032.344 }
costs { name: "custom-call.136.0" cost_us: 3045.207 }
costs { name: "custom-call.52.0" cost_us: 2948.728 }
costs { name: "custom-call.52.0.double_buffer_clone" cost_us: 2949.305 }
costs { name: "custom-call.52.0.peeled_double_buffer" cost_us: 2938.04 }
costs { name: "loop_convert_fusion.27" cost_us: 6.784 }
costs { name: "loop_power_fusion.1" cost_us: 1.535 }
costs { name: "all-reduce-start.4" cost_us: 5815.92 }
costs { name: "all-reduce-start.5" cost_us: 3788.374 }
costs { name: "all-reduce-start.7" cost_us: 711.422 }
costs { name: "all-reduce-start.9" cost_us: 384.67 }
costs { name: "input_add_multiply_reduce_fusion" cost_us: 988.573 }
costs { name: "input_add_multiply_reduce_fusion.1" cost_us: 1015.229 }
costs { name: "input_add_multiply_reduce_fusion.2" cost_us: 1035.933 }
costs { name: "input_add_multiply_reduce_fusion.double_buffer_clone" cost_us: 998.782 }
costs { name: "input_add_reduce_fusion" cost_us: 556.799 }
costs { name: "input_add_reduce_fusion.11" cost_us: 587.807 }
costs { name: "input_add_reduce_fusion.12" cost_us: 602.622 }
costs { name: "input_add_reduce_fusion.double_buffer_clone" cost_us: 568.863 }
costs { name: "input_reduce_fusion.44" cost_us: 4.96 }
costs { name: "input_reduce_fusion.45" cost_us: 4.8 }
costs { name: "input_reduce_fusion.46" cost_us: 7.936 }
costs { name: "input_reduce_fusion.5" cost_us: 7.84 }
costs { name: "input_reduce_fusion.5.double_buffer_clone" cost_us: 8.095 }
costs { name: "loop_multiply_fusion.14" cost_us: 2.368 }
costs { name: "loop_multiply_fusion.15" cost_us: 2.24 }
costs { name: "loop_multiply_rsqrt_fusion.1" cost_us: 2.272 }
costs { name: "loop_multiply_rsqrt_fusion.2" cost_us: 2.368 }
costs { name: "input_reduce_fusion.47" cost_us: 4.704 }
costs { name: "wrapped_slice.50" cost_us: 1.632 }
costs { name: "custom-call.142.0" cost_us: 10823.905 }
costs { name: "custom-call.171.0" cost_us: 11256.418 }
costs { name: "custom-call.172.0" cost_us: 11255.169 }
costs { name: "input_transpose_fusion.11" cost_us: 3.807 }
costs { name: "input_transpose_fusion.12" cost_us: 3.648 }
costs { name: "input_transpose_fusion.7" cost_us: 6.337 }
costs { name: "input_transpose_fusion.8" cost_us: 5.856 }
costs { name: "loop_convert_fusion.10" cost_us: 4.929 }
costs { name: "loop_convert_fusion.10.double_buffer_clone" cost_us: 5.952 }
costs { name: "loop_convert_fusion.11" cost_us: 4.96 }
costs { name: "loop_convert_fusion.11.double_buffer_clone" cost_us: 6.016 }
costs { name: "loop_convert_fusion.13" cost_us: 3.009 }
costs { name: "loop_convert_fusion.13.double_buffer_clone" cost_us: 3.296 }
costs { name: "loop_convert_fusion.14" cost_us: 3.072 }
costs { name: "loop_convert_fusion.14.double_buffer_clone" cost_us: 3.296 }
costs { name: "loop_convert_fusion.15" cost_us: 2.24 }
costs { name: "loop_convert_fusion.15.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_convert_fusion.16" cost_us: 2.304 }
costs { name: "loop_convert_fusion.16.double_buffer_clone" cost_us: 2.304 }
costs { name: "loop_convert_fusion.17" cost_us: 2.176 }
costs { name: "loop_convert_fusion.17.double_buffer_clone" cost_us: 2.272 }
costs { name: "loop_convert_fusion.18" cost_us: 2.048 }
costs { name: "loop_convert_fusion.18.double_buffer_clone" cost_us: 2.048 }
costs { name: "loop_convert_fusion.20" cost_us: 6.209 }
costs { name: "loop_convert_fusion.21" cost_us: 5.888 }
costs { name: "loop_convert_fusion.22" cost_us: 6.4 }
costs { name: "loop_convert_fusion.23" cost_us: 6.176 }
costs { name: "loop_convert_fusion.28" cost_us: 3.167 }
costs { name: "loop_convert_fusion.29" cost_us: 3.168 }
costs { name: "loop_convert_fusion.31" cost_us: 2.209 }
costs { name: "loop_convert_fusion.32" cost_us: 2.176 }
costs { name: "loop_convert_fusion.33" cost_us: 2.24 }
costs { name: "loop_convert_fusion.34" cost_us: 2.176 }
costs { name: "loop_convert_fusion.37" cost_us: 2.4 }
costs { name: "loop_convert_fusion.38" cost_us: 2.272 }
costs { name: "loop_convert_fusion.39" cost_us: 2.368 }
costs { name: "loop_convert_fusion.40" cost_us: 2.08 }
costs { name: "loop_convert_fusion.9" cost_us: 5.216 }
costs { name: "loop_convert_fusion.9.double_buffer_clone" cost_us: 6.207 }
costs { name: "loop_dynamic_slice_fusion.3" cost_us: 186.848 }
costs { name: "loop_dynamic_slice_fusion.4" cost_us: 25.6 }
costs { name: "loop_dynamic_slice_fusion.5" cost_us: 26.24 }
costs { name: "loop_select_fusion" cost_us: 1.664 }
costs { name: "loop_select_fusion.double_buffer_clone" cost_us: 1.76 }
costs { name: "loop_add_fusion.4" cost_us: 1.248 }
costs { name: "loop_add_fusion.4.double_buffer_clone" cost_us: 1.76 }
costs { name: "input_transpose_fusion.4" cost_us: 4.192 }
costs { name: "loop_dynamic_update_slice_fusion.5" cost_us: 396.351 }
costs { name: "loop_dynamic_update_slice_fusion.5.double_buffer_clone" cost_us: 398.271 }
costs { name: "input_transpose_fusion.9" cost_us: 2.464 }
costs { name: "loop_dynamic_update_slice_fusion.4" cost_us: 114.752 }
costs { name: "loop_dynamic_update_slice_fusion.4.double_buffer_clone" cost_us: 115.52 }
costs { name: "loop_dynamic_update_slice_fusion.11" cost_us: 1.504 }
costs { name: "loop_dynamic_update_slice_fusion.11.double_buffer_clone" cost_us: 1.536 }
costs { name: "loop_dynamic_update_slice_fusion.12" cost_us: 1.472 }
costs { name: "loop_dynamic_update_slice_fusion.12.double_buffer_clone" cost_us: 1.663 }
costs { name: "loop_dynamic_update_slice_fusion.6" cost_us: 10.144 }
costs { name: "loop_dynamic_update_slice_fusion.6.double_buffer_clone" cost_us: 10.144 }
costs { name: "loop_dynamic_update_slice_fusion.7" cost_us: 10.111 }
costs { name: "loop_dynamic_update_slice_fusion.7.double_buffer_clone" cost_us: 10.208 }
costs { name: "loop_dynamic_update_slice_fusion.8" cost_us: 3.968 }
costs { name: "loop_dynamic_update_slice_fusion.8.double_buffer_clone" cost_us: 4.0 }
costs { name: "loop_dynamic_update_slice_fusion.10" cost_us: 1.76 }
costs { name: "loop_dynamic_update_slice_fusion.10.double_buffer_clone" cost_us: 1.823 }
costs { name: "loop_dynamic_update_slice_fusion.9" cost_us: 1.727 }
costs { name: "loop_dynamic_update_slice_fusion.9.double_buffer_clone" cost_us: 1.791 }
costs { name: "loop_add_multiply_fusion" cost_us: 1865.466 }
costs { name: "loop_add_multiply_fusion.1" cost_us: 1847.93 }
costs { name: "loop_add_multiply_fusion.2" cost_us: 1867.195 }
costs { name: "loop_add_multiply_fusion.double_buffer_clone" cost_us: 1865.755 }
costs { name: "loop_multiply_fusion.5" cost_us: 2.144 }
costs { name: "loop_multiply_fusion.5.double_buffer_clone" cost_us: 2.176 }
costs { name: "loop_multiply_rsqrt_fusion" cost_us: 2.176 }
costs { name: "loop_multiply_rsqrt_fusion.double_buffer_clone" cost_us: 2.144 }
costs { name: "custom-call.146.0" cost_us: 9933.509 }
costs { name: "custom-call.163.0" cost_us: 9965.669 }
costs { name: "custom-call.78.0" cost_us: 9869.126 }
costs { name: "custom-call.78.0.double_buffer_clone" cost_us: 9869.99 }
costs { name: "custom-call.150.0" cost_us: 9840.901 }
costs { name: "custom-call.160.0" cost_us: 9756.677 }
costs { name: "custom-call.82.0" cost_us: 9387.301 }
costs { name: "custom-call.82.0.double_buffer_clone" cost_us: 9510.759 }
costs { name: "cublas-gemm.13.0" cost_us: 9799.493 }
costs { name: "cublas-gemm.13.0.double_buffer_clone" cost_us: 9835.27 }
costs { name: "cublas-gemm.34.0" cost_us: 9870.885 }
costs { name: "cublas-gemm.37.0" cost_us: 9991.621 }
costs { name: "custom-call.151.0" cost_us: 9647.941 }
costs { name: "custom-call.161.0" cost_us: 10136.901 }
costs { name: "custom-call.83.0" cost_us: 9462.789 }
costs { name: "custom-call.83.0.double_buffer_clone" cost_us: 9383.943 }
costs { name: "custom-call.144.0" cost_us: 10401.282 }
costs { name: "custom-call.158.0" cost_us: 10445.282 }
costs { name: "custom-call.76.0" cost_us: 10462.372 }
costs { name: "custom-call.76.0.double_buffer_clone" cost_us: 10416.677 }
costs { name: "custom-call.152.0" cost_us: 9836.166 }
costs { name: "custom-call.162.0" cost_us: 10140.389 }
costs { name: "custom-call.84.0" cost_us: 9376.711 }
costs { name: "custom-call.84.0.double_buffer_clone" cost_us: 9320.902 }
costs { name: "all-reduce-start.1" cost_us: 162.527 }
costs { name: "all-reduce-start.3" cost_us: 421.343 }
costs { name: "wrapped_slice.16" cost_us: 1.6 }
costs { name: "wrapped_slice.46" cost_us: 1.216 }
costs { name: "wrapped_slice.47" cost_us: 1.632 }
costs { name: "wrapped_slice.9" cost_us: 1.024 }
costs { name: "all-reduce-start.8" cost_us: 1030.557 }
costs { name: "wrapped_slice.17" cost_us: 1.535 }
costs { name: "wrapped_slice.44" cost_us: 1.536 }
costs { name: "wrapped_slice.45" cost_us: 1.664 }
costs { name: "wrapped_slice.8" cost_us: 1.472 }
costs { name: "custom-call.35.0" cost_us: 6244.463 }
costs { name: "custom-call.35.0" cost_us: 276.191 }
costs { name: "custom-call.35.0" cost_us: 100.991 }
costs { name: "custom-call.35.0" cost_us: 206.271 }
costs { name: "custom-call.41.0" cost_us: 5431.633 }
costs { name: "custom-call.41.0" cost_us: 275.871 }
costs { name: "custom-call.41.0" cost_us: 100.831 }
costs { name: "custom-call.41.0" cost_us: 198.399 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 5754.033 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 275.999 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 100.863 }
costs { name: "custom-call.41.0.double_buffer_clone" cost_us: 193.119 }
costs { name: "custom-call.43.0" cost_us: 6557.358 }
costs { name: "custom-call.43.0" cost_us: 275.968 }
costs { name: "custom-call.43.0" cost_us: 101.248 }
costs { name: "custom-call.43.0" cost_us: 201.215 }
costs { name: "loop_add_fusion.2" cost_us: 490.014 }
costs { name: "loop_add_fusion.2.double_buffer_clone" cost_us: 510.047 }
costs { name: "loop_add_fusion.6" cost_us: 573.247 }
costs { name: "loop_add_fusion.7" cost_us: 549.022 }
costs { name: "loop_add_fusion.3" cost_us: 62.848 }
costs { name: "loop_add_fusion.3.double_buffer_clone" cost_us: 65.664 }
costs { name: "loop_add_fusion.8" cost_us: 73.855 }
costs { name: "loop_add_fusion.9" cost_us: 70.816 }
costs { name: "custom-call.153.0" cost_us: 365.279 }
costs { name: "custom-call.167.0" cost_us: 379.775 }
costs { name: "custom-call.85.0" cost_us: 319.904 }
costs { name: "custom-call.85.0.double_buffer_clone" cost_us: 330.751 }
costs { name: "custom-call.148.0" cost_us: 374.943 }
costs { name: "custom-call.165.0" cost_us: 396.798 }
costs { name: "custom-call.80.0" cost_us: 351.135 }
costs { name: "custom-call.80.0.double_buffer_clone" cost_us: 360.703 }
costs { name: "custom-call.156.0" cost_us: 352.447 }
costs { name: "custom-call.170.0" cost_us: 381.727 }
costs { name: "custom-call.88.0" cost_us: 336.383 }
costs { name: "custom-call.88.0.double_buffer_clone" cost_us: 340.544 }
costs { name: "cublas-gemm.14.0" cost_us: 413.375 }
costs { name: "cublas-gemm.14.0.double_buffer_clone" cost_us: 411.999 }
costs { name: "cublas-gemm.35.0" cost_us: 418.111 }
costs { name: "cublas-gemm.38.0" cost_us: 437.215 }
costs { name: "custom-call.154.0" cost_us: 2870.68 }
costs { name: "custom-call.168.0" cost_us: 2957.688 }
costs { name: "custom-call.86.0" cost_us: 2688.729 }
costs { name: "custom-call.86.0.double_buffer_clone" cost_us: 2870.552 }
costs { name: "custom-call.147.0" cost_us: 3101.528 }
costs { name: "custom-call.164.0" cost_us: 3245.687 }
costs { name: "custom-call.79.0" cost_us: 2966.68 }
costs { name: "custom-call.79.0.double_buffer_clone" cost_us: 2965.689 }
costs { name: "custom-call.155.0" cost_us: 2903.672 }
costs { name: "custom-call.169.0" cost_us: 2961.144 }
costs { name: "custom-call.87.0" cost_us: 2373.113 }
costs { name: "custom-call.87.0.double_buffer_clone" cost_us: 2497.401 }
costs { name: "custom-call.149.0" cost_us: 3087.095 }
costs { name: "custom-call.166.0" cost_us: 3240.984 }
costs { name: "custom-call.81.0" cost_us: 2733.369 }
costs { name: "custom-call.81.0.double_buffer_clone" cost_us: 2850.68 }
costs { name: "custom-call.143.0" cost_us: 10317.285 }
costs { name: "custom-call.157.0" cost_us: 10368.61 }
costs { name: "custom-call.75.0" cost_us: 10301.956 }
costs { name: "custom-call.75.0.double_buffer_clone" cost_us: 10315.685 }
costs { name: "custom-call.145.0" cost_us: 10333.252 }
costs { name: "custom-call.159.0" cost_us: 10382.915 }
costs { name: "custom-call.77.0" cost_us: 10313.668 }
costs { name: "custom-call.77.0.double_buffer_clone" cost_us: 10326.725 }
costs { name: "loop_multiply_fusion.4" cost_us: 191.36 }
costs { name: "loop_multiply_fusion.4.double_buffer_clone" cost_us: 191.871 }
costs { name: "loop_multiply_fusion.8" cost_us: 192.575 }
costs { name: "loop_multiply_fusion.9" cost_us: 192.128 }
costs { name: "loop_rsqrt_fusion.2" cost_us: 2.111 }
costs { name: "loop_rsqrt_fusion.2.double_buffer_clone" cost_us: 2.047 }
costs { name: "loop_rsqrt_fusion.3" cost_us: 2.304 }
costs { name: "loop_rsqrt_fusion.4" cost_us: 2.208 }
costs { name: "custom-call.34.0" cost_us: 1943.387 }
costs { name: "custom-call.34.0" cost_us: 2.368 }
costs { name: "custom-call.40.0" cost_us: 1944.091 }
costs { name: "custom-call.40.0" cost_us: 1.792 }
costs { name: "custom-call.40.0.double_buffer_clone" cost_us: 1906.842 }
costs { name: "custom-call.40.0.double_buffer_clone" cost_us: 1.824 }
costs { name: "custom-call.42.0" cost_us: 1975.994 }
costs { name: "custom-call.42.0" cost_us: 2.4 }
costs { name: "loop_broadcast_fusion.1" cost_us: 1.28 }
costs { name: "loop_broadcast_fusion.1.double_buffer_clone" cost_us: 1.28 }
costs { name: "loop_multiply_fusion.6" cost_us: 1.473 }
costs { name: "loop_multiply_fusion.6.double_buffer_clone" cost_us: 1.472 }
costs { name: "loop_convert_fusion.12" cost_us: 6.816 }
costs { name: "loop_convert_fusion.12.double_buffer_clone" cost_us: 6.816 }
costs { name: "loop_power_fusion" cost_us: 1.6 }
costs { name: "loop_power_fusion.double_buffer_clone" cost_us: 1.567 }
costs { name: "cublas-gemm.12.0" cost_us: 3038.903 }
costs { name: "cublas-gemm.12.0.double_buffer_clone" cost_us: 3036.088 }
costs { name: "cublas-gemm.33.0" cost_us: 3046.392 }
costs { name: "cublas-gemm.36.0" cost_us: 3076.503 }
costs { name: "loop_dynamic_slice_fusion.2" cost_us: 187.199 }
costs { name: "loop_dynamic_slice_fusion.2.double_buffer_clone" cost_us: 182.88 }
costs { name: "wrapped_slice" cost_us: 185.728 }
costs { name: "loop_dynamic_slice_fusion" cost_us: 25.248 }
costs { name: "loop_dynamic_slice_fusion.1" cost_us: 25.247 }
costs { name: "loop_dynamic_slice_fusion.1.double_buffer_clone" cost_us: 25.055 }
costs { name: "loop_dynamic_slice_fusion.double_buffer_clone" cost_us: 25.12 }
costs { name: "wrapped_slice.1" cost_us: 24.289 }
costs { name: "wrapped_slice.2" cost_us: 24.224 }
costs { name: "wrapped_slice.3" cost_us: 185.888 }
costs { name: "loop_divide_fusion" cost_us: 1.631 }
costs { name: "wrapped_transpose.2" cost_us: 393.631 }
costs { name: "wrapped_transpose.3" cost_us: 393.503 }
costs { name: "wrapped_transpose.4" cost_us: 413.791 }
costs { name: "wrapped_transpose.1" cost_us: 3.296 }
costs { name: "wrapped_transpose" cost_us: 3.424 }
costs { name: "wrapped_transpose.5" cost_us: 17.088 }
costs { name: "wrapped_transpose.6" cost_us: 417.087 }
costs { name: "wrapped_transpose.7" cost_us: 112.607 }
costs { name: "wrapped_transpose.8" cost_us: 16.032 }
