#!/bin/bash

# This file is documentation for how to get started with Qwen3-Omni-30B-A3B.

# This file runs Step 2 on a v5p-8 TPU VM.
# 2. Run multimodal decoding: text+image, and text+video+audio.
# ---
# Example Usage:
#
# export HF_TOKEN=<your_hf_token>
# export BASE_OUTPUT_PATH=gs://your-gcs-bucket/qwen3-omni-30b-a3b_maxtext_ckpt
# bash tests/end_to_end/tpu/qwen/moe/qwen3-omni-30b-a3b/2_test_qwen3_omni_30b_a3b.sh
# ---

set -ex

export MODEL_NAME="${MODEL_NAME:-qwen3-omni-30b-a3b}"
export TOKENIZER_PATH="${TOKENIZER_PATH:-Qwen/Qwen3-Omni-30B-A3B-Instruct}"

if [ -z "${BASE_OUTPUT_PATH}" ]; then
  # Non-Googlers please remember to point `BASE_OUTPUT_PATH` to GCS buckets that you own, this script uses internal buckets for testing.
  # this bucket will store all the files generated by MaxText during a run
  export BASE_OUTPUT_PATH=gs://runner-maxtext-logs/$(date +%Y-%m-%d-%H-%M)
  echo "BASE_OUTPUT_PATH is not set"
fi
BASE_OUTPUT_PATH=${BASE_OUTPUT_PATH%/}
echo using BASE_OUTPUT_PATH = ${BASE_OUTPUT_PATH}

if [ -z "${HF_TOKEN}" ]; then
  echo "Error: HF_TOKEN environment variable is not set. Please export your Hugging Face token."
  echo "Example: export HF_TOKEN=hf_..."
  exit 1
fi

UNSCANNED_CKPT_PATH=gs://maxtext-model-checkpoints/qwen3-omni-30b-a3b/unscanned/0/items

# ---
# Step 2a: Multimodal Decode — text + image
# Uses a test image from the repo assets.
# max_prefill_predict_length accounts for image tokens (~256) + text prompt tokens.
# ---
python3 -m maxtext.inference.decode ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml \
    model_name=${MODEL_NAME} \
    tokenizer_path=${TOKENIZER_PATH} \
    tokenizer_type=huggingface \
    load_parameters_path=${UNSCANNED_CKPT_PATH} \
    hf_access_token=${HF_TOKEN} \
    per_device_batch_size=1 \
    run_name=qwen3_omni_decode_image \
    steps=1 \
    async_checkpointing=false \
    scan_layers=false \
    use_multimodal=true \
    prompt='Describe this image in one sentence.' \
    image_path='tests/assets/test_image.jpg' \
    max_prefill_predict_length=512 \
    max_target_length=542 \
    add_bos=false \
    attention=dot_product

# ---
# Step 2b: Multimodal Decode — text + video + audio
# Passes a video file and enables audio processing from the video track.
# max_prefill_predict_length is set higher to accommodate video frame tokens (~1126)
# plus audio tokens (~77) plus text prompt tokens.
# ---
python3 -m maxtext.inference.decode ${MAXTEXT_CONFIGS_DIR:-${MAXTEXT_REPO_ROOT:-$PWD}/src/maxtext/configs}/base.yml \
    model_name=${MODEL_NAME} \
    tokenizer_path=${TOKENIZER_PATH} \
    tokenizer_type=huggingface \
    load_parameters_path=${UNSCANNED_CKPT_PATH} \
    hf_access_token=${HF_TOKEN} \
    per_device_batch_size=1 \
    run_name=qwen3_omni_decode_video \
    steps=1 \
    async_checkpointing=false \
    scan_layers=false \
    use_multimodal=true \
    use_audio_in_video=true \
    prompt='What can you see and hear? Answer in one short sentence.' \
    video_path='tests/assets/test_video.mp4' \
    max_prefill_predict_length=1240 \
    max_target_length=1280 \
    add_bos=false \
    attention=dot_product 
