# SPDX-License-Identifier: Apache-2.0

# model config for gemma3-27b

base_num_decoder_layers: 62
base_emb_dim: 5376
base_num_query_heads: 32
base_num_kv_heads: 16
base_mlp_dim: 21504
head_dim: 128
mlp_activations: ["gelu","linear"]
vocab_size: 262_144
decoder_block: "gemma3"
normalization_layer_epsilon: 1e-6
logits_via_embedding: True
sliding_window_size: 1024
use_post_attn_norm: true
use_post_ffw_norm: true
local_rope_max_timescale: 10_000
rope_max_timescale: 1_000_000
