# SPDX-License-Identifier: Apache-2.0

# model config for gemma-2b

base_emb_dim: 2048
base_num_query_heads: 8
base_num_kv_heads: 1
base_mlp_dim: 16384
base_num_decoder_layers: 18
head_dim: 256
mlp_activations: ["gelu","linear"]
vocab_size: 256128
decoder_block: "gemma"
normalization_layer_epsilon: 1.e-06
logits_via_embedding: True