# SPDX-License-Identifier: Apache-2.0

# model config for gemma-7b

base_emb_dim: 3072
base_num_query_heads: 16
base_num_kv_heads: 16
base_mlp_dim: 24576
base_num_decoder_layers: 28
head_dim: 256
mlp_activations: ["gelu","linear"]
vocab_size: 256128
decoder_block: "gemma"
normalization_layer_epsilon: 1.e-06
logits_via_embedding: True