base_emb_dim: 2880
base_num_query_heads: 64
base_num_kv_heads: 8
base_mlp_dim: 2880
base_num_decoder_layers: 24
head_dim: 64
mlp_activations: ["silu","linear"]
vocab_size: 201088
enable_dropout: False
logits_via_embedding: False
normalization_layer_epsilon: 1.0e-5
num_experts: 32
num_experts_per_tok: 4
rope_max_timescale: 1_000_000
decoder_block: "mixtral"