# Copyright 2023 Google LLC
#
# Licensed under the Apache License Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing software
# distributed under the License is distributed on an "AS IS" BASIS
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# model config for gpt3-175b

base_emb_dim: 12288
base_num_heads: 96
base_mlp_dim: 49152
base_num_decoder_layers: 96
head_dim: 128
use_positional_embedding: True
trainable_position_size: 16384
mlp_activations: ["gelu"]
vocab_size: 50304
enable_dropout: False
norm_logits_via_embedding: False
logits_via_embedding: True
logits_dot_in_fp32: False
norm_epsilon: 1.e-05
use_iota_embed: True
fused_qkv: True
add_bos: False
add_eos: False
opt_type: "adam_pax"
stable_cross_entropy_loss: False
gradient_clipping_threshold: 1.
adam_b1: 0.9
adam_b2: 0.95
adam_eps: 1.e-8
adam_weight_decay: 0.1
checkpoint_period: 10_000
target_eval_loss: 2.69
