# SPDX-License-Identifier: Apache-2.0

# model config for llama3-70b

base_emb_dim: 8192
base_num_query_heads: 64
base_num_kv_heads: 8
base_num_decoder_layers: 80
base_mlp_dim: 28672
head_dim: 128
mlp_activations: ["silu","linear"]
vocab_size: 128256
enable_dropout: False
logits_via_embedding: False
normalization_layer_epsilon: 1.0e-5
rope_max_timescale: 500_000
decoder_block: "llama2" # Uses the same decoder block as llama2
