base_emb_dim: 4
base_num_query_heads: 16
base_num_kv_heads: 8
base_mlp_dim: 64
head_dim: 128
mlp_activations: ["silu","linear"]
vocab_size: 32000
enable_dropout: False
logits_via_embedding: False
normalization_layer_epsilon: 1.0e-5
num_experts: 8
num_experts_per_tok: 2
decoder_block: "mistral"