# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Derives the decoupled-mode requirements from a generated requirements lock.

Decoupled mode (``DECOUPLE_GCLOUD=TRUE``) is only meaningful when the optional Google Cloud
dependencies are genuinely not installed, so the decoupled requirements are a hardware lock with
those distributions removed. Deriving the file instead of maintaining it by hand keeps the decoupled
environment on the same package versions the tests it shadows use, and makes the transform a pure
text operation that a pre-commit hook can check offline. The default source is the GPU pre-training
lock; ``--source`` picks another one, which yields that hardware's versions instead.

Decoupling is independent of the accelerator, so the accelerator entries are left out as well and the
result installs anywhere: CI runs the decoupled suite on CPU, and a decoupled run on an accelerator
installs those entries back on top (see docs/run_maxtext/decoupled_mode.md).

Usage:
  python3 src/dependencies/scripts/generate_decoupled_requirements.py           # write the file
  python3 src/dependencies/scripts/generate_decoupled_requirements.py --check   # verify it is current
  python3 src/dependencies/scripts/generate_decoupled_requirements.py --print-accelerator-requirements
"""

import argparse
import pathlib
import re
import sys

GENERATED_DIR = pathlib.Path(__file__).resolve().parents[1] / "requirements" / "generated_requirements"
SOURCE_FILE = GENERATED_DIR / "cuda12-requirements.txt"
OUTPUT_FILE = GENERATED_DIR / "decoupled-requirements.txt"

# The Google Cloud clients that maxtext.common.gcloud_stub stubs out, together with the plumbing that
# exists only to serve them: every google-* distribution goes, so the google.cloud, google.api_core
# and google.auth namespaces stay empty and a module-scope import of any of them fails the way it
# does for an offline user. googleapis-common-protos is not matched by the prefix and stays, because
# tensorflow-metadata requires it and an offline install therefore has it as well.
EXCLUDED_GCLOUD_PREFIXES = ("google-",)
EXCLUDED_GCLOUD_PACKAGES = (
    "cloud-accelerator-diagnostics",
    "cloud-tpu-diagnostics",
    "gcsfs",
    "grpc-google-iam-v1",
    "grpcio-status",
    "ml-goodput-measurement",
    "proto-plus",
    "xprof",
)
# google-pasta is a tensorflow dependency that only provides `pasta`; it has no Cloud surface.
KEPT_GCLOUD_PACKAGES = ("google-pasta",)

# Decoupled mode says nothing about the accelerator, so the backend plugins, the CUDA libraries they
# load and Transformer Engine are dropped, and a run on GPU installs them back on top
# (--print-accelerator-requirements). libtpu is listed so a TPU backend never appears implicitly.
# nvidia-ml-py is deliberately not matched here: it is pure Python, pynvml requires it, and dropping
# it would leave the decoupled environment resolving a different version than the GPU tests use.
EXCLUDED_ACCELERATOR_PREFIXES = (
    "jax-cuda",
    "libtpu",
    "nvidia-cuda-",
    "nvidia-cudnn-",
    "transformer-engine",
)
EXCLUDED_ACCELERATOR_SUFFIXES = ("-cu12",)

HEADER = (
    "# Generated by generate_decoupled_requirements.py from {source_name}. Do not edit manually.\n"
    "#    See https://maxtext.readthedocs.io/en/latest/development/update_dependencies.html for details.\n"
    "#\n"
    "# The Google Cloud clients are intentionally absent: this environment is what\n"
    "# DECOUPLE_GCLOUD=TRUE has to work in. The accelerator wheels are left out so the file installs\n"
    "# on any hardware; add the backend plugin for the accelerator under test on top of it.\n"
    "\n"
)

_REQUIREMENT_NAME = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)")
_VERSION_SPECIFIER = re.compile(r"[=<>!~]")


def _distribution_name(line: str) -> str | None:
  """Returns the normalized distribution name of a requirement line, or None for non-requirements."""
  stripped = line.strip()
  if not stripped or stripped.startswith("#"):
    return None
  match = _REQUIREMENT_NAME.match(stripped)
  return match.group(1).lower().replace("_", "-") if match else None


def _display(path: pathlib.Path) -> str:
  """Returns the path relative to the working directory when it is inside it, for readable output."""
  try:
    return str(path.relative_to(pathlib.Path.cwd()))
  except ValueError:
    return str(path)


def _is_accelerator(name: str) -> bool:
  return name.startswith(EXCLUDED_ACCELERATOR_PREFIXES) or name.endswith(EXCLUDED_ACCELERATOR_SUFFIXES)


def _is_gcloud(name: str) -> bool:
  if name in KEPT_GCLOUD_PACKAGES:
    return False
  return name in EXCLUDED_GCLOUD_PACKAGES or name.startswith(EXCLUDED_GCLOUD_PREFIXES)


def validate_lock(source: str, source_name: str) -> None:
  """Exits when the source is not a flat pinned lock, which would otherwise yield a partial file.

  Base requirements carry `-r` includes and unpinned names; filtering those would silently drop
  whole includes and produce a decoupled file with no versions in it.
  """
  for line in source.splitlines():
    stripped = line.strip()
    if not stripped or stripped.startswith("#"):
      continue
    if not _distribution_name(stripped) or not _VERSION_SPECIFIER.search(stripped):
      sys.exit(
          f"{source_name} is not a flat pinned lock ({stripped!r}); "
          "point --source at a file under generated_requirements/."
      )


def render_decoupled_requirements(source: str, source_name: str) -> str:
  """Returns the decoupled requirements text derived from a hardware requirements text."""
  kept = [
      line
      for line in source.splitlines()
      if (name := _distribution_name(line)) and not _is_gcloud(name) and not _is_accelerator(name)
  ]
  return HEADER.format(source_name=source_name) + "\n".join(kept) + "\n"


def render_accelerator_requirements(source: str) -> str:
  """Returns the accelerator entries left out of the decoupled requirements, pinned as the source pins them."""
  dropped = [line for line in source.splitlines() if (name := _distribution_name(line)) and _is_accelerator(name)]
  return "\n".join(dropped) + "\n"


def main() -> int:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument(
      "--source",
      type=pathlib.Path,
      default=SOURCE_FILE,
      help="requirements to derive from; another lock yields that hardware's versions "
      "(default: generated_requirements/cuda12-requirements.txt)",
  )
  parser.add_argument(
      "--output",
      type=pathlib.Path,
      default=OUTPUT_FILE,
      help="decoupled requirements file to write or check (default: generated_requirements/decoupled-requirements.txt)",
  )
  parser.add_argument(
      "--check",
      action="store_true",
      help="exit non-zero if the decoupled requirements are not what this script would write",
  )
  parser.add_argument(
      "--print-accelerator-requirements",
      action="store_true",
      help="print the accelerator entries this script leaves out, to install on top of a decoupled environment",
  )
  args = parser.parse_args()

  if not args.source.is_file():
    sys.exit(f"source requirements not found: {_display(args.source)}")
  source = args.source.read_text(encoding="utf-8")
  validate_lock(source, args.source.name)
  if args.print_accelerator_requirements:
    print(render_accelerator_requirements(source), end="")
    return 0

  expected = render_decoupled_requirements(source, args.source.name)
  if not args.check:
    args.output.write_text(expected, encoding="utf-8")
    print(f"Wrote {_display(args.output)}")
    return 0

  current = args.output.read_text(encoding="utf-8") if args.output.is_file() else None
  if current != expected:
    command = f"python3 {_display(pathlib.Path(__file__).resolve())}"
    if args.source != SOURCE_FILE:
      command += f" --source {_display(args.source)}"
    if args.output != OUTPUT_FILE:
      command += f" --output {_display(args.output)}"
    state = "missing" if current is None else f"out of date with {args.source.name}"
    print(f"{args.output.name} is {state}.\nRun: {command}", file=sys.stderr)
    return 1
  return 0


if __name__ == "__main__":
  sys.exit(main())
