base_config: "base.yml"

use_grpo: True
train_data_columns: ['prompt', 'completion']

per_device_batch_size: 1.0
learning_rate: 1.e-6 # from TRL

dataset_type: hf # we currently only support Huggingface input pipeline with GRPO.

#TRL
max_prefill_predict_length: 512
max_target_length: 1024

adam_b2: 0.999

# Group Relative Policy Optimization (GRPO)
num_generations: 4 # TRL is 8
temperature: 0.9
grpo_beta: 0.04
inference_rollouts: 8

decode_sampling_strategy: "weighted"
async_checkpointing: false
