# SPDX-License-Identifier: Apache-2.0

base_config: "base.yml"
# The model_name guarantees we will use the correct model from
# configs/models/mixtral-8x7b.yml, see update_model_vars in pyconfig.py for details.
model_name: "mixtral-8x7b"

run_name: "gpu_train_test"
hardware: "gpu"
steps: 30
per_device_batch_size: 12
max_target_length: 4096
attention: "cudnn_flash_te"
remat_policy: "minimal_flash"
use_iota_embed: True
dataset_type: "synthetic"
reuse_example_batch: 1
enable_checkpointing: False
megablox: False
scan_layers: False
tokenizer_path: "/deps/assets/tokenizer.mistral-v1"
profiler: "nsys"
capacity_factor: 1.0
