# SPDX-License-Identifier: Apache-2.0

base_config: "base.yml"
# The model_name guarantees we use the correct model params from
# configs/models/mixtral-8x7b. mixtral-8x1b is mixtral-8x7b but
# with different base_num_decoder_layers.
model_name: "mixtral-8x7b"
base_num_decoder_layers: 5

run_name: "gpu_train_test"
hardware: "gpu"
steps: 30

per_device_batch_size: 8
max_target_length: 4096
attention: "cudnn_flash_te"
remat_policy: "full"
use_iota_embed: True
dataset_type: "synthetic"
reuse_example_batch: 1
enable_checkpointing: False
megablox: False
sparse_matmul: False
