# Copyright 2023–2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Soft Distillation Configuration

# Inherit MaxText defaults
base_config: "post_train/distillation.yml"

use_sft: True
sft_train_on_completion_only: True

# --- Dataset & Tokenizer ---
hf_path: "HuggingFaceH4/ultrachat_200k"
dataset_type: "hf"

# chat_template is required for sft mode & HF pipeline. Many tokenizers already provide it.
# Some non-instruct versions of hf tokenizers have no chat template defined so one has to specify it here
chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n' + message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = '<|begin_of_text|>' + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
train_split: "train_sft"
eval_split: "test_sft"
train_data_columns: ["messages"]
eval_data_columns: ["messages"]