# Soft Distillation Configuration

# Inherit MaxText defaults
base_config: "base.yml"

enable_nnx: True

# --- Student Specifics ---
# These are passed as kwargs to the Student config initialization
student_overrides:
  model_name: "gpt-oss-20b"
  base_num_query_heads: 32
  head_dim: 128
  base_num_kv_heads: 4
  load_parameters_path: "gs://jfacevedo-maxdiffusion/distillation/student_orbax_188_grad_lora16_kl_50ep/0/items"
  override_model_config: True 
  gradient_accumulation_steps: 3

# --- Teacher Specifics ---
# These are passed as kwargs to the Teacher config initialization
teacher_overrides:
  model_name: "gpt-oss-20b"
  load_parameters_path: "gs://jfacevedo-maxdiffusion/distillation/teacher_orbax_188_grad_lora16_kl_50ep/0/items"
  # override_model_config: False
  gradient_accumulation_steps: 3

# --- Distillation Loss ---
distill_alpha: 0.5
distill_temperature: 1.0
distill_beta: 0.0
distill_layer_indices: [0, 1, 2, 3, 4, 5, 6, 7]

# --- Dataset & Tokenizer ---
hf_path: "Alibaba-Apsara/Superior-Reasoning-SFT-gpt-oss-120b"
dataset_type: "hf"
tokenizer_type: "huggingface"
tokenizer_path: "openai/gpt-oss-20b"

max_target_length: 2048
packing: True

# --- Training Loop ---
steps: 1986
checkpoint_period: 200
log_period: 10
save_checkpoint_on_completion: True

# --- Batch Size Strategy ---
# Global Batch Size = per_device_batch_size * num_devices * gradient_accumulation_steps
per_device_batch_size: 1
gradient_accumulation_steps: 3

# --- Learning Rate Schedule ---
learning_rate_schedule_steps: 1986

# --- Learning Rate Schedule ---
learning_rate: 1e-4
warmup_steps_fraction: 0.0302
learning_rate_final_fraction: 0.1