# Copyright 2026 Google LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     https://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow will test and promote a MaxText Docker image.

name: Promote MaxText Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      device:
        required: true
        type: string
      workflow:
        required: true
        type: string
permissions:
  contents: read

jobs:
  check_image:
    runs-on: linux-x86-n2-16-buildkit
    container: google/cloud-sdk:524.0.0
    outputs:
      image_exists: ${{ steps.check.outputs.exists }}
    steps:
      - name: Check if image exists
        id: check
        shell: bash
        run: |
          if gcloud container images describe "gcr.io/${{ vars.PROJECT_NAME }}/${{ inputs.image_name }}:${{ inputs.image_tag }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  test:
    needs: check_image
    if: needs.check_image.outputs.image_exists == 'true'
    strategy:
      fail-fast: false
      matrix:
        flavor: >-
            ${{ fromJSON('{
              "gpu-pre-training": ["gpu-unit", "gpu-integration"],
              "tpu-post-training": ["tpu-post-training-unit", "tpu-post-training-integration", "cpu-post-training-unit"],
              "tpu-pre-training": ["tpu-unit", "tpu-integration", "cpu-unit"]
            }')[format('{0}-{1}', inputs.device, inputs.workflow)] }}
    uses: ./.github/workflows/run_tests_coordinator.yml
    with:
      flavor: ${{ matrix.flavor }}
      base_image: ${{ inputs.image_name }}:${{ inputs.image_tag }}
      is_scheduled_run: true
      maxtext_installed: true
      additional_pytest_args: ${{ contains(inputs.image_name, 'maxtext_jax_nightly') && '--ignore=tests/integration/hlo_diff_test.py' || '' }}

  tagging:
    needs: [test]
    if: needs.test.result == 'success'
    runs-on: linux-x86-n2-16-buildkit
    container: google/cloud-sdk:524.0.0
    steps:
      - name: Configure Docker
        run: gcloud auth configure-docker us-docker.pkg.dev,gcr.io -q

      - name: Add tags to Docker image
        shell: bash
        run: |
          # Add Latest Tag
          SOURCE_IMAGE="gcr.io/${{ vars.PROJECT_NAME }}/${{ inputs.image_name }}"
          gcloud container images add-tag "${SOURCE_IMAGE}:${{ inputs.image_tag }}" "${SOURCE_IMAGE}:latest" --quiet
