# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This workflow will build and test the MaxText package, and build Docker images
# for a Release Candidate when a new release tag is created.

name: MaxText Release Pipeline

# Triggers when a new "release" is published in the GitHub UI
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  id-token: write

jobs:
  release_approval:
    name: Approve Release Candidate
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    # "release" environment is configured in MaxText repository settings.
    # This environment requires manual approval before proceeding to the next job.
    environment: release
    steps:
      - name: Acknowledge Approval
        run: echo "Release candidate approved, proceeding to build and test MaxText package."

  build_and_test_maxtext_package:
    name: Build and Test MaxText Package
    needs: [release_approval]
    if: |
      always() &&
      (needs.release_approval.result == 'success' || needs.release_approval.result == 'skipped')
    uses: ./.github/workflows/build_and_test_maxtext.yml
    secrets: inherit

  build_release_candidate_images:
    name: ${{ matrix.image_name }}
    needs: [build_and_test_maxtext_package]
    if: |
      always() &&
      (needs.build_and_test_maxtext_package.result == 'success' || needs.build_and_test_maxtext_package.result == 'skipped')
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: tpu
            build_mode: stable
            image_name: maxtext_jax_stable
            workflow: pre-training
            dockerfile: maxtext_tpu_dependencies.Dockerfile
          - device: tpu
            build_mode: stable
            image_name: maxtext_post_training_stable
            workflow: post-training
            dockerfile: maxtext_tpu_dependencies.Dockerfile
    uses: ./.github/workflows/build_and_push_docker_image.yml
    with:
      image_name: ${{ matrix.image_name }}
      device: ${{ matrix.device }}
      build_mode: ${{ matrix.build_mode }}
      workflow: ${{ matrix.workflow }}
      dockerfile: ${{ matrix.dockerfile }}
      maxtext_sha: ${{ github.sha }}
      include_test_assets: true
    secrets:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
