# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file runs unit tests with Pathways backend.

name: Run Pathways Tests

on:
  workflow_call:
    inputs:
      device_type:
        required: true
        type: string
      device_name:
        required: true
        type: string
      image_type:
        required: false
        type: string
      pytest_marker:
        required: true
        type: string
      pytest_addopts:
        required: false
        type: string
        default: ''
      is_scheduled_run:
        required: true
        type: string
      xla_python_client_mem_fraction:
        required: true
        type: string
      tf_force_gpu_allow_growth:
        required: true
        type: string
      container_resource_option:
        required: true
        type: string
      cloud_runner:
        required: false
        type: string

jobs:
  run:
    runs-on: ${{ inputs.cloud_runner != '' && inputs.cloud_runner || fromJson(format('["self-hosted", "{0}", "{1}"]', inputs.device_type, inputs.device_name)) }}
    container:
      image: gcr.io/tpu-prod-env-multipod/maxtext_${{ github.run_id }}:${{ inputs.image_type != '' && inputs.image_type || inputs.device_type }}
      volumes:
        - ${{ github.workspace }}:/tmp
      env:
        XLA_PYTHON_CLIENT_MEM_FRACTION: ${{ inputs.xla_python_client_mem_fraction }}
        TF_FORCE_GPU_ALLOW_GROWTH: ${{ inputs.tf_force_gpu_allow_growth }}
        IFRT_PROXY_USE_INSECURE_GRPC_CREDENTIALS: true
        JAX_PLATFORMS: "proxy"
        JAX_BACKEND_TARGET: "grpc://localhost:29000"
      options: ${{ inputs.container_resource_option }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          if [ "${{ inputs.is_scheduled_run }}" = "true" ]; then
            FINAL_PYTEST_MARKER="${{ inputs.pytest_marker }}"
          else
            FINAL_PYTEST_MARKER="${{ inputs.pytest_marker }} and not scheduled_only"
          fi
          python3 -m pip install -e . --no-dependencies &&
          python3 -m pip uninstall -y libtpu &&
          # TODO(b/454659463): Enable test_default_hlo_match after volume mount is supported.
          python3 -m pytest ${{ inputs.pytest_addopts }} -v -m "${FINAL_PYTEST_MARKER}" -k "not test_default_hlo_match" --durations=0
    
    services:
      resource_manager:
        image: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/server:latest
        ports:
          - "29001:29001"
          - "29002:29002"
        options:
          --entrypoint=[/usr/pathways/run/cloud_pathways_server_sanitized, --server_port=29001, --node_type=resource_manager, --instance_count=1, --instance_type=tpuv4:2x2x1, --gcs_scratch_location=gs://cloud-pathways-staging/tmp]
        env:
          TPU_SKIP_MDS_QUERY: true

      worker:
        image: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/server:latest
        ports:
          - "29005:29005"
          - "29006:29006"
          - "8471:8471"
          - "8080:8080"
        options:
          --entrypoint=[/usr/pathways/run/cloud_pathways_server_sanitized, --server_port=29005, --resource_manager_address=localhost:29001, --gcs_scratch_location=gs://cloud-pathways-staging/tmp]
          --tpu=4

      proxy:
        image: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/proxy_server:latest
        volumes:
          - ${{ github.workspace }}:/tmp
        ports:
          - "29000:29000"
        env:
          IFRT_PROXY_USE_INSECURE_GRPC_CREDENTIALS: true
          XLA_FLAGS: "--xla_dump_to=/tmp/aot_test_dump --xla_dump_hlo_as_text --xla_dump_hlo_module_re=jit_train_step"
        options:
          --entrypoint=[/usr/pathways/run/cloud_proxy_server_sanitized, --server_port=29000, --resource_manager_address=localhost:29001, --gcs_scratch_location=gs://cloud-pathways-staging/tmp, --xla_tpu_scoped_vmem_limit_kib=65536, --xla_tpu_spmd_rng_bit_generator_unsafe=true]
